kubevela/kubevela

pkg/addon/addon.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/webservice/addon.go
pkg/controller/utils/capability.go
pkg/controller/utils/capability_test.go

1. Now get addon detail will use memory cache
2. fix uiSchama not work
Fixes #
I have:

Fix: add detail cache, fix uiSchema

---

pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/utils/bcode/application.go
pkg/apiserver/rest/webservice/application.go
test/e2e-apiserver-test/application_test.go

ApiServer logic for CRUD trait
I have:

Feat: manage trait

---

cmd/apiserver/main.go
go.mod
pkg/apiserver/model/application.go
pkg/apiserver/rest/rest_server.go
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go
pkg/workflow/workflow.go

Feat: add record status sync

---

charts/vela-core/templates/addons/terraform.yaml
docs/examples/terraform/cloud-resource-provision-and-consume/application-sls-project.yaml
docs/examples/terraform/cloud-resource-provision-and-consume/application-sls-store.yaml
vela-templates/addons/auto-gen/terraform.yaml
vela-templates/addons/terraform/definitions/terraform-alibaba-sls-project.yaml
vela-templates/addons/terraform/definitions/terraform-alibaba-sls-store.yaml

Docs: add alicloud sls cloud resources

---

pkg/apiserver/model/application.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go

Feat: add triat alias description time

---

docs/apidoc/swagger.json
pkg/apiserver/model/application.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go
pkg/apiserver/rest/webservice/application.go
pkg/apiserver/rest/webservice/workflow.go

Feat: add app revision list and detail api

---

pkg/addon/addon.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/utils/bcode/addon.go
pkg/apiserver/rest/webservice/addon.go

Now support query enabled addon's argument
Fixes #
I have:

Feat: add addon arguments API

---

pkg/addon/addon.go
pkg/apiserver/rest/usecase/addon.go

If use runtime cluster mode, the definitions will be applied to control plane k8s directly, not included in the Application object.

Feat: EnableAddon supports runtime cluster

---

apis/types/capability.go

Fix: small issue
Fixes #
I have:

Fix: addon spell issue

---

e2e/application/application_test.go
e2e/application/vela.yaml
e2e/commonContext.go
references/appfile/api/appfile.go
references/appfile/api/appfile_test.go
references/cli/common.go
references/cli/def.go
references/cli/delete.go
references/cli/dryrun.go
references/cli/exec.go
references/cli/export.go
references/cli/init.go
references/cli/livediff.go
references/cli/ls.go
references/cli/show.go
references/cli/status.go
references/cli/up.go
references/cli/up_test.go
references/cli/workflow.go
references/cli/workloads.go
references/common/application.go
references/common/common.go
references/common/workload.go

Align commands to use `-n` means namespace
Fixes #
I have:

Fix: Align -n command argument

---

pkg/addon/addon.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/webservice/addon.go

1. Add definitions to addon detail API, each definition contains `name`,`type`,`description` fields.
2. optimize addon cache usage
3. download the addon's files parallelly
Fixes #
I have:

Feat: add definitions to addon detail API, fix addon cache, async download files

---

e2e/application/application_test.go
e2e/application/vela.yaml
e2e/commonContext.go
references/appfile/api/appfile.go
references/appfile/api/appfile_test.go
references/cli/common.go
references/cli/def.go
references/cli/delete.go
references/cli/dryrun.go
references/cli/exec.go
references/cli/export.go
references/cli/init.go
references/cli/livediff.go
references/cli/ls.go
references/cli/print.go
references/cli/show.go
references/cli/status.go
references/cli/up.go
references/cli/up_test.go
references/cli/workflow.go
references/cli/workloads.go
references/common/application.go
references/common/common.go
references/common/workload.go

* add namespace flag
fix
fix test
fix tests
* try test
* try test
* fix tests
(cherry picked from commit b38aa1cdf06729d5b3469d851a0d5d2b59006beb)
Fixes #
I have:

Fix: Align -n command argument (backport #2719)

---

charts/vela-core/templates/velaql-views/component-pod-view.yaml
docs/examples/velaql-views/usage.md
pkg/stdlib/pkgs/query.cue
pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/handler.go
test/e2e-apiserver-test/testdata/component-pod-view.yaml
test/e2e-apiserver-test/velaql_test.go

component-pod-view support filter resource by cluster name and cluster namespace
Fixes #
I have:

Feat: component-pod-view support filter resource by cluster name and cluster namespace

---

pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/envbinding.go
pkg/apiserver/rest/usecase/envbinding_test.go
pkg/apiserver/rest/utils/bcode/envbinding.go

fix envbinding related workflow logic，add unit test
Fixes # 
I have:

Fix: fix envbinding related workflow logic，add unit test

---

pkg/addon/addon.go
pkg/addon/error.go
pkg/apiserver/rest/usecase/addon.go
test/e2e-apiserver-test/addon_test.go

1. fix github rate limit error judge panic
2. fix multicluster enable addon workflow nil panic
3. lint code
4. fix list API lack of parameter
Fixes #
I have:

Fix: lint apiserver code, fix panic

---

pkg/workflow/recorder/recorder.go

Fix: controllerrevision can not be updated

---

pkg/addon/addon.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/utils/bcode/addon.go

Feat: check addon dependencies when enable

---

pkg/apiserver/rest/usecase/addon.go

Fix: get addon omit uiSchema

---

vela-templates/gen_addons.go

Fix: merge branch import fail

---

pkg/apiserver/datastore/kubeapi/kubeapi.go
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go

Fixes #
I have:
/cc @hongchaodeng

Fix: fix sync controller revision

---

charts/vela-core/templates/velaql-views/component-pod-view.yaml
charts/vela-core/templates/velaql-views/pod-view.yaml
docs/examples/velaql-views/usage.md
go.mod
go.sum
pkg/stdlib/pkgs/time.cue
pkg/velaql/providers/query/handler.go
pkg/workflow/providers/time/date.go
pkg/workflow/providers/time/date_test.go

this PR  tidy up the view api expose to dashboard, more details please see [doc](https://github.com/yangsoon/kubevela/blob/6611b6ab09d7a3c8335fccf62033127d2365e09f/docs/examples/velaql-views/usage.md).
Fixes #
I have:

Fix: tidy up the view api

---

pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/workflow.go

Feat: add workflow name for frontend

---

references/cli/addon.go

Feat: optimize addon enable experience

---

pkg/apiserver/rest/usecase/workflow.go

add more logs in workflow sync
I have:

Feat: add more logs in workflow sync

---

pkg/apiserver/model/workflow.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go

Add alias in workflow step status for FE.
Fixes #
I have:

Feat: add alias in workflow step status

---

pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/definition.go
pkg/apiserver/rest/usecase/envbinding.go
pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
pkg/apiserver/rest/webservice/webservice.go

Automatically create a workflow for a cloud service application. 
Fixes #
I have:

Feat: support auto creating workflow step for cloud app

---

apis/types/capability.go
pkg/addon/addon.go

Install addon UI schema feature, read schema files from addon  catalog and generate a configmap an install them to cluster

Feat: install helm addon  schema

---

pkg/stdlib/pkgs/query.cue
test/e2e-apiserver-test/testdata/component-pod-view.yaml
test/e2e-apiserver-test/velaql_test.go

Fix: fix flaky e2e-test of apiserver

---

README.md

Fix: add CII Best Practices badge

---

pkg/apiserver/model/workflow.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/workflow.go

Add alias in list record api for FE.
I have:

Feat: add alias in list record api

---

pkg/addon/addon.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/webservice/addon.go
pkg/apiserver/rest/webservice/webservice.go

1. apiserver interface to list enabled addon from cluster 
2. apiserver interface to update addon
Fixes #
I have:

Feat: list enabled addon from cluster interface and update addon

---

apis/types/capability.go
go.mod
go.sum
pkg/addon/addon.go
pkg/addon/addon_suite_test.go
pkg/addon/addon_test.go
pkg/addon/error.go
pkg/addon/source.go
pkg/addon/testdata/example/definitions/helm.yaml
pkg/addon/testdata/example/metadata.yaml
pkg/addon/testdata/example/readme.md
pkg/addon/testdata/example/resources/configmap.cue
pkg/addon/testdata/example/resources/parameter.cue
pkg/addon/testdata/example/resources/service/source-controller.yaml
pkg/addon/testdata/example/template.yaml
pkg/apiserver/model/addon.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/addon.go
pkg/utils/parse.go

Now our addons can be retrieved only from GitHub. This PR add support for OSS bucket. 
Note: This PR suppurted only aliyun OSS and bucket with `public read` authorization.
This helps to fix three problem:
1. add default addon registry for apiserver. 
2. merge addon use experience between CLI and apiserver.
3. get faster addon pull spped and avoid GitHub rete llimit 
I have:
- Unit test added
- Test snapshot
test bucket: https://yiling-addons.oss-cn-beijing.aliyuncs.com/  There are three addons in this bucket.
snapshots:

Feat: oss suppurt for addon

---

pkg/apiserver/rest/usecase/application.go

vela-core will running some gc process when delete application,may take some time, but this status will not wirte to cr, apiserver application model should identify it and response correct status
I'm not sure whether to write this status as a constant in the common package

Feat: add deleting phase for apiserver application status model

---

pkg/apiserver/model/application.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go

fix workflow apiserver sort and rollback status
I have:

Fix: fix workflow apserver sort and rollback status

---

pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/envbinding.go
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go

fix sync from status version instead of anno and sort
I have:

Fix: fix sync from status version instead of anno

---

.github/workflows/registry.yml

Add vela-apiserver release workflow
Fixes #
I have:

Feat: add vela apiserver release into github workflow

---

references/cli/logs.go

Refined the logic to display logs for Terraform typed applications,
and upated the namespace of the pod running Terraform jobs
Fix https://github.com/oam-dev/kubevela/issues/2670
Fixes #
I have:

Fix: support displaying logs for Terraform typed applications

---

charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-core/templates/defwithtemplate/worker.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/worker.yaml
vela-templates/definitions/internal/component/webservice.cue
vela-templates/definitions/internal/component/worker.cue

fix webservice and worker def
I have:
/cc @barnettZQG @zzxwill

Fix: fix webservice and worker def

---

.github/workflows/timed-task.yml
Makefile

Chore: add more frequency on CI image clean job

---

charts/vela-core/templates/addon_registry.yaml
e2e/addon/addon_test.go
e2e/addon/testdata/test-addon/metadata.yaml
e2e/addon/testdata/test-addon/template.yaml
go.mod
go.sum
pkg/addon/addon.go
pkg/addon/helper.go
pkg/addon/registry.go
pkg/addon/source.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/webservice/addon_registry.go
references/cli/addon.go
test/e2e-addon-test/addon_test.go

I have reimplement vela  addon  cli
- vela addon list (list addons from rgistry)
- vela addon enable (enable an addon)
- vela addon disable (disable an addon)
- vela addon status (check addon status)

Feat: algin addon cli with apiserver

---

go.mod
go.sum
pkg/controller/utils/capability.go
pkg/controller/utils/capability_test.go

support generate definition schema from terraform remote
I have:
/cc @zzxwill

Feat: support generate definition schema from terraform remote

---

pkg/apiserver/rest/usecase/cluster.go

Fixes [Security Problem](https://github.com/oam-dev/kubevela/security/code-scanning/37)

Fix: kubeconfig tmp file security

---

pkg/multicluster/cluster_management.go

Fix: create vela namespace in apiserver

---

pkg/builtin/http/http.go

Fix: enable InsecureSkipVerify in http client

---

charts/vela-core/templates/cluster-gateway.yaml

> Signed-off-by: yue9944882 <291271447@qq.com>

Feat: Honor existing cluster-gateway installation if exists

---

charts/vela-core/templates/addons/ocm-cluster-manager.yaml
vela-templates/addons/auto-gen/ocm-cluster-manager.yaml
vela-templates/addons/ocm-cluster-manager/resource/manager/hub.yaml
vela-templates/addons/ocm-cluster-manager/resource/operator/operator.yaml

> Signed-off-by: yue9944882 <291271447@qq.com>

Chore: OCM addon image version

---

hack/apis/sync.sh

Signed-off-by: yangsoon <yangsoonlx@gmail.com>
Fixes #
I have:

Fix: fix sync-api CI

---

pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/cluster.go
pkg/apiserver/rest/usecase/delivery_target.go
pkg/apiserver/rest/usecase/delivery_target_test.go

Fixes #267
Now `GET /targets` returns
```json
{
"targets": [
{
"name": "runtime-dt-cluster",
"project": {
"name": "default",
"alias": "default-project",
"description": "project description",
"namespace": "project-default",
"createTime": "2021-12-15T11:04:54.27296+08:00",
"updateTime": "2021-12-15T11:04:54.272961+08:00"
},
"alias": "runtime-dt-alias-cluster",
"description": "description",
"cluster": {
"clusterName": "runtime-cluster",
"namespace": "runtime-namespace"
},
"clusterAlias": "runtime-cluster-alias",
"createTime": "2021-12-15T11:09:10.827176+08:00",
"updateTime": "2021-12-15T11:09:10.827176+08:00"
}
],
"total": 1
}
```
I have:

Feat: add cluster alias to dt

---

pkg/addon/addon.go
pkg/apiserver/rest/usecase/addon.go
references/cli/addon.go
references/cli/status.go

`vela cli status` less of some capability of get more error info of application, generally the application error info will be contained in workflow status. So print out the workflowStatus of app.
Before:
After 
When running workflow error
I have:

Feat(cli): app status more info

---

docs/examples/helm-module/webapp-chart-cd.yaml
e2e/plugin/plugin_test.go
pkg/appfile/appfile_test.go
pkg/appfile/helm/schema_test.go
pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
test/e2e-test/helm_app_test.go

Fix: change catlog helm repo path to https://charts.kubevela.net/example

---

go.mod
go.sum
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/cluster.go
pkg/apiserver/rest/usecase/envbinding.go
pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/utils/bcode/bcode.go
pkg/utils/sanitize.go
pkg/utils/sanitize_test.go

1. Sanitize log parameters with user inputs.
2. Upgrade dependencies for security.
I have:

Fix: security alert

---

charts/vela-core/templates/cluster-gateway.yaml
charts/vela-core/values.yaml
charts/vela-minimal/values.yaml

1. upgrade cluster-gateway to v1.1.7
2. [sync](https://github.com/oam-dev/cluster-gateway/pull/38) rolling update strategy with cluster-gateway repo 
I have:

Feat: upgrade cluster-gateway

---

contribute/coding-conventions.md
docs/apidoc/swagger.json
pkg/apiserver/rest/webservice/cluster.go
pkg/apiserver/rest/webservice/oam_application.go
pkg/apiserver/rest/webservice/policy_definition.go

Fix: fix apiserver snake case

---

pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/handler_test.go

Fix: velaql compatible with v1.2.0-beta version

---

pkg/cloudprovider/aliyun.go

Add DashboardURL for connected ACK Cloud Cluster. Previous url returned by ACK API is not valid now. This PR fixes it.
I have:

Fix: ack dashboard url

---

charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
vela-templates/definitions/internal/workflowstep/notification.cue

fix notification definition to show better
I have:

Fix: fix notification definition to show better

---

pkg/cloudprovider/aliyun.go

Aliyun ListCloudCluster return *string which could be nil. This PR fixes it.

Fix: nil pointer aliyun sdk

---

design/vela-core/workflow_policy.md

add workflow stability mechanism doc
I have:
/cc @leejanee @wonderflow @hongchaodeng

Feat: add workflow stability mechanism doc

---

pkg/apiserver/rest/usecase/workflow.go

Fix: amend fix for log sanitize

---

docs/examples/workflow/inti-secret-with-http/app.yaml
docs/examples/workflow/notification/app.yaml

add init secret demo
I have:
/cc @wonderflow @barnettZQG

Feat: add init secret demo

---

charts/vela-core/templates/defwithtemplate/export2config.yaml
charts/vela-core/templates/defwithtemplate/export2secret.yaml
charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/export2config.yaml
charts/vela-minimal/templates/defwithtemplate/export2secret.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
docs/examples/workflow/export2config/app.yaml
docs/examples/workflow/export2secret/app.yaml
pkg/appfile/parser.go
vela-templates/definitions/internal/workflowstep/export2config.cue
vela-templates/definitions/internal/workflowstep/export2secret.cue
vela-templates/definitions/internal/workflowstep/notification.cue

Fixes #
I have:
/cc @barnettZQG @zzxwill

Fix: nit fix for workflow

---

design/vela-core/workflow_policy.md

Docs: update some outdated content in workflow doc

---

pkg/resourcekeeper/gc.go
pkg/resourcekeeper/gc_suite_test.go

1. Managed clusters may not have ResourceTracker CRD. Upgrade should ignore this error.
2. For developing, the VelaVersion is "UNKNOWN" or "master" or other. Previously we skip the "UNKNOWN" application upgrade. Now we force one upgrade check and update the app version so that the upgrade only trigger once.

Fix: optimize ResourceTracker upgrade

---

docs/apidoc/swagger.json
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/envbinding.go

Fixes: oam-dev/velaux#265
I have:

Fix: can not find target name in pod list

---

test/e2e-test/resource_policy_test.go

Resource Policy Test is a bit flaky due to update conflict (update resource when controller is also modifying it).
This PR fixes it (partially).

Fix: resource policy test flaky

---

pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/webservice/addon.go

Fix: list addon will always return non-nil err

---

pkg/addon/helper.go

Lowercase the key name in the API response for Addon Observability
status
Fixes #
I have:

Fix: lowercase the key name in API response

---

e2e/addon/addon_test.go
references/cli/addon-registry.go
references/cli/addon.go

1. vela cli addon registry support oss path
2. vela cli addon support upgrade addon
Fixes #
I have:

Feat: vela cli support oss path and cli upgrade an addon

---

pkg/workflow/workflow.go

change update cm to commit context
I have:
@leejanee

Fix: change update cm to commit context

---

e2e/addon/addon_test.go
references/cli/addon-registry.go

several small style issue fix
Fixes #
I have:

Fix: cli addon registry style small fix

---

charts/vela-core/templates/cluster-gateway.yaml

> Signed-off-by: yue9944882 <291271447@qq.com>

Fix: Idempotent conditional apiservice deletion

---

references/cli/addon.go

print Addon related app status when addon status
Fixes #
I have:

Fix: more app info in addon status

---

pkg/apiserver/model/env.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/env.go
pkg/apiserver/rest/usecase/env_model.go
pkg/apiserver/rest/usecase/env_test.go
pkg/apiserver/rest/usecase/envbinding.go
pkg/apiserver/rest/usecase/envbinding_test.go
pkg/apiserver/rest/usecase/project.go
pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
pkg/apiserver/rest/utils/bcode/011_env.go

-  Check whether the target exists.
-  Check whether the target conflict.
I have:

Feat: check target where create and update env

---

charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
pkg/utils/env/env.go
references/cli/env.go
vela-templates/definitions/internal/workflowstep/notification.cue

fix notfication properties for schema
I have:

Fix: fix notfication properties for schema

---

.github/workflows/registry.yml
Dockerfile

Feat: set GOPROXY build arg

---

charts/vela-core/templates/defwithtemplate/webhook.yaml
charts/vela-minimal/templates/defwithtemplate/webhook.yaml
vela-templates/definitions/internal/workflowstep/webhook.cue

Fix: fix webhook definition
I have:

Fix: fix webhook definition

---

pkg/apiserver/model/application.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
pkg/apiserver/rest/usecase/webhook.go
pkg/apiserver/rest/usecase/webhook_test.go
pkg/apiserver/rest/utils/bcode/001_application.go
pkg/apiserver/rest/webservice/application.go
pkg/apiserver/rest/webservice/webhook.go

Fix: trigger webbook bug

---

charts/vela-core/templates/defwithtemplate/task.yaml
charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/task.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
references/plugins/references.go
vela-templates/definitions/internal/component/task.cue
vela-templates/definitions/internal/component/webservice.cue

Fix website can't be displayed as elements can not be parsed
I have:

Fix: fix vela show --web that can not show elems

---

pkg/addon/addon.go
pkg/addon/addon_suite_test.go
references/cli/addon.go
references/cli/portforward.go

This pr does such things:
1.  vela port-forward not support helm component
2. vela addon enable restart a have running phase workflow
3. vela addon enable velaux print requestWay in cli 
default service:
nodePort service
domain way
loadbalance way

Fix: helm addon demo issues

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go

Filter Application and ResourceTracker update event by ignoring managedFields changes.
For old k8s version like 1.18.5, the managedField could always update and cause infinite loop, this function helps filter those events and prevent infinite loop.
I have:

Fix: filter managedfields update events

---

pkg/addon/addon_test.go
pkg/addon/source.go
pkg/utils/parse.go

Fix: addon panic bug

---

pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/utils/bcode/001_application.go
pkg/apiserver/rest/webservice/application.go

Feat: support application trigger deletion

---

pkg/apiserver/rest/usecase/workflow.go
pkg/apiserver/rest/usecase/workflow_test.go

Fixes oam-dev/velaux#318
I have:

Fix: reset step status to stopped if the workflow is terminated

---

docs/apidoc/swagger.json
pkg/apiserver/model/application.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/webhook.go
pkg/apiserver/rest/usecase/webhook_test.go
pkg/apiserver/rest/webservice/application.go
pkg/apiserver/rest/webservice/payload_types.go
pkg/apiserver/rest/webservice/webhook.go
pkg/apiserver/rest/webservice/webservice.go

add ACR webhook trigger
I have:
/cc @barnettZQG @wonderflow

Feat: add ACR webhook trigger

---

charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-core/templates/defwithtemplate/worker.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/worker.yaml
vela-templates/definitions/internal/component/webservice.cue
vela-templates/definitions/internal/component/worker.cue

Fix: fix component definition status message
I have:

Fix: fix component definition status message

---

pkg/apiserver/rest/rest_server.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/envbinding.go

https://github.com/oam-dev/kubevela/security/code-scanning
I have:

Fix: security alerts

---

pkg/addon/suite_test.go
pkg/appfile/suit_test.go
references/appfile/addon_suit_test.go
references/appfile/dryrun/suit_test.go
references/plugins/suit_test.go

Fix: migrate test from crd v1beta1 to v1

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go

Signed-off-by: songminglong <1247768069@qq.com>
Fixes #3055
I have:

Fix: Do not fiter event triggered by resync for application controller

---

charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
docs/examples/workflow/notification/app.yaml
pkg/stdlib/op.cue
pkg/stdlib/pkgs/lark.cue
vela-templates/definitions/internal/workflowstep/notification.cue

Signed-off-by: Shuai Tian <tians1@xiaopeng.com>
Feat: Add Lark support for notification (#3053)
I have:
@FogDong

Feat: Add Lark support for notification (#3053)

---

charts/vela-core/templates/velaql/endpoints.yaml

Fix: change namespace for the service-endpoints-view velaQL

---

pkg/addon/addon.go
pkg/addon/helper.go
pkg/addon/reader_local.go
pkg/addon/reader_local_test.go
pkg/addon/testdata/local/metadata.yaml
pkg/addon/testdata/local/resources/parameter.cue
pkg/oam/labels.go
references/cli/addon.go

support install an addon by local dir
Fixes #
I have:

Feat: addon enable support local dir for install offline

---

references/appfile/api/appfile.go
references/appfile/api/appfile_test.go
references/cli/up.go
references/cli/up_test.go
references/common/application.go
references/common/common.go

Feat: support vela up from remote url  && remove health scope in appfile

---

references/cli/def.go

Address the comments to change the command line name
Fixes #
I have:

Fix: change `vela def gen-doc` to `vela def doc-gen`

---

charts/vela-core/templates/velaql/endpoints.yaml
pkg/stdlib/pkgs/query.cue
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/types/type.go
references/cli/addon.go
references/cli/cli_suite_test.go
references/cli/status.go
references/cli/uischema_test.go
references/cli/velaql.go
references/cli/velaql_test.go

Feat: add cluster name in service endpoint

---

e2e/addon/addon_test.go
pkg/addon/addon.go
references/cli/addon-registry.go
references/cli/addon.go
references/cli/cli.go
references/cli/cluster.go
references/cli/components.go
references/cli/cue_packages.go
references/cli/def.go
references/cli/env.go
references/cli/help.go
references/cli/init.go
references/cli/logs.go
references/cli/portforward.go
references/cli/show.go
references/cli/status.go
references/cli/system.go
references/cli/traits.go
references/cli/workflow.go
references/common/application.go
test/e2e-addon-test/addon_test.go

Feat: vela up support read from stdin && refine CLI output && fix vela addon command

---

references/cli/logs.go
references/cli/status.go

Fix: vela logs for namespace get from CLI and add container name args

---

pkg/apiserver/datastore/datastore.go
pkg/apiserver/datastore/mongodb/mongodb.go
pkg/apiserver/datastore/mongodb/mongodb_test.go

Fix: can't query data from the MongoDB

---

pkg/apiserver/datastore/mongodb/mongodb_test.go

Fix: clear old data in mongodb unit test case

---

apis/core.oam.dev/v1alpha1/envbinding_types.go
pkg/policy/envbinding/patch.go
pkg/policy/envbinding/patch_test.go
pkg/stdlib/pkgs/multicluster.cue

Support external revision specify in EnvBinding patch.
Fixes #
I have:

Feat: support external revision in patch component

---

references/cli/components.go
references/cli/traits.go

Fix: trait/comp command output without a new line

---

references/plugins/i18n.go
references/plugins/reference_test.go
references/plugins/references.go

Added application samples for all Terraform typed ComponentDefinition,
and also localize the title for AWS and AZure
Fixes #
I have:

Fix: add app samples for Terraform definition

---

charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
docs/examples/core-definitions/component/webservice.yaml
vela-templates/definitions/internal/component/webservice.cue

Feat: add port name in webservice

---

apis/core.oam.dev/v1beta1/application_types.go
cmd/core/main.go
pkg/controller/core.oam.dev/oamruntime_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/revision.go
pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go

Fix: workflow skip executing all steps occasionally

---

apis/core.oam.dev/common/types.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/velaql/context.go
pkg/workflow/context/context.go
pkg/workflow/context/context_test.go
pkg/workflow/context/interface.go
pkg/workflow/interface.go
pkg/workflow/tasks/custom/task.go
pkg/workflow/tasks/custom/task_test.go
pkg/workflow/workflow.go
pkg/workflow/workflow_test.go

Ref #3085
I have:
/cc @leejanee @wonderflow

Fix: handle workflow cache reconcile

---

pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/usecase/addon_test.go
pkg/apiserver/rest/usecase/testdata/addon-uischema-test.yaml

Addon parameter support UI-schema
Fixes #
I have:

Feat: addon parameter support ui-shcema

---

pkg/cue/convert.go
pkg/cue/convert_test.go
pkg/utils/common/common.go
pkg/utils/common/common_test.go
references/cli/registry.go
references/cli/show.go
references/cli/show_test.go
references/plugins/cluster.go
references/plugins/cluster_test.go
references/plugins/reference_test.go
references/plugins/references.go

support vela show for workflow step definition
I have:

Feat: support vela show for workflow step definition

---

.krew.yaml

Fix: krew install template of kubectl-vela.exe

---

CHANGELOG/CHANGELOG-1.2.md

add change log of v1.2.x
I have:

Chore: add changelog of v1.2.x

---

pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler.go

Previous error message for application in webhook is too complicated for user to read. This PR simplify it by removing the concrete value but only keep the basic information like field and detail message.
Error message in webhook is too complicated to read. This PR simplifies it by removing the concrete value print.
Now the error message is like
```bash
Error from server: error when creating "./testapp.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "spec": Invalid value error encountered, fetch component
/policy type of express-server2: LoadTemplate from workloadDefinition [webservice2] : WorkloadDefinition.core.oam.dev "webservice2" not found.
```
I have:
This PR currently only affect application controller.

Fix: error msg in webhook too complicated to read

---

charts/oam-runtime/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/oam-runtime/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/oam-runtime/values.yaml
charts/vela-core/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/vela-core/values.yaml
charts/vela-minimal/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/vela-minimal/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/vela-minimal/values.yaml

Fixes #2810 
I have:
Need to update the e2e tests to cover `nodeSelector` and labels.
New to Kubernetes and KubeVela, so please be gentle! ;)

Fix: Add nodeselector to jobs in kubevela helm chart

---

pkg/appfile/appfile.go
pkg/appfile/appfile_test.go
pkg/cue/model/keyword.go
pkg/cue/packages/package.go

Fixes #3199
discussed in https://github.com/oam-dev/kubevela/discussions/3172
I have:

Feat: add componentType in context for traitDefinition

---

Makefile
references/cli/def.go

Fix: fix flag conflict

---

design/vela-core/resourcetracker_design.md

Fix: ControllerRevision typo

---

pkg/utils/apply/apply.go
pkg/utils/apply/apply_resource_test.go
pkg/utils/apply/apply_test.go
pkg/utils/apply/patch.go
references/cli/install.go

Fix: apply crd error that the annotations too long

---

pkg/apiserver/rest/webservice/application.go

Fix: remove duplicative route in application webservice.

---

community.md

Feat: update community.md

---

charts/vela-core/Chart.yaml

Feat: update logo to .svg

---

OWNERS_ALIASES

Feat: update owners_aliases

---

references/cli/addon.go
references/cli/addon_test.go

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>
Fixes #3183 
I have:

Fix: Optimize error msg of addon enable/upgrade local path

---

pkg/addon/addon.go

add DisableUpdateAnnotation for addon
I have:

Fix: add DisableUpdateAnnotation for addon

---

OWNERS_ALIASES

https://github.com/oam-dev/kubevela/issues/3261. /cc @wangwang
Fixes #
I have:

Feat: add @wangwang as one Reviewer

---

Dockerfile
Dockerfile.apiserver
Dockerfile.e2e
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
pkg/apiserver/rest/webservice/application.go
references/appfile/dryrun/diff.go

Signed-off-by: zxbyoyoyo <596908030@qq.com>
Fixes #
I have:

Feat: add api for app compare、reset、dryrun 

---

charts/vela-core/templates/kubevela-controller.yaml
charts/vela-core/values.yaml
cmd/core/main.go

Chore: remove use less controller args to avoid confusion

---

cmd/core/main.go
pkg/controller/core.oam.dev/oamruntime_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/oam/labels.go

* application controller version control
* modify command arg name
Backport
Fixes #
I have:

Feat: application support controller requirement (#3192)

---

e2e/plugin/plugin_test.go

Fix: make e2e CI more stable in vela show case

---

apis/types/types.go
charts/vela-core/templates/addon/fluxcd-def.yaml
charts/vela-core/templates/addon/fluxcd.yaml
charts/vela-core/templates/addon_registry.yaml
charts/vela-core/values.yaml
e2e/addon/addon_test.go
e2e/addon/mock/utils/utils.go
e2e/cli.go
pkg/addon/addon.go
pkg/addon/addon_test.go
references/cmd/cli/main.go

cherry pick 3280 to release 1.2 
Fixes #
I have:

Fix: cherry pick #3280 to release 1.2 

---

apis/types/types.go
pkg/addon/addon.go
pkg/addon/addon_suite_test.go
pkg/addon/addon_test.go
pkg/addon/error.go
pkg/addon/helper.go
pkg/addon/suite_test.go
pkg/addon/type.go
pkg/apiserver/clients/kubeclient.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/utils/bcode/005_addon.go
pkg/utils/common/args.go
references/cli/addon.go

check-pick #3304 to release 1.2 
Fixes #
I have:

Feat(addon): support version check and dependency by cherry-pick #3304 

---

.github/workflows/registry.yml
Makefile
charts/vela-core/README.md
charts/vela-core/values.yaml
charts/vela-minimal/values.yaml
makefiles/dependency.mk

add helm chart doc and make command
I have:

Feat: add helm chart doc and make command

---

pkg/addon/addon.go
pkg/addon/addon_test.go

Signed-off-by: cezhang <c1zhang.dev@gmail.com>
Feature #3352
I have:
Create dummy.txt file in example addon "definitions" and "resources" folder for testing other format case

Feat: Addon yaml files discovery logic improvement

---

pkg/apiserver/rest/webservice/application.go

fix apiserver deploy application return type error
I have:

Fix: deploy application api return value

---

pkg/oam/util/helper_test.go

Fix: remove unused variable

---

hack/utils/installdefinition.sh

fix error bash script in `make def-install`
Fixes https://github.com/oam-dev/kubevela/issues/3369
I have:
By run `make def-install`

Fix: install definition script

---

docs/apidoc/swagger.json
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/webservice/addon.go
pkg/apiserver/rest/webservice/addon_registry.go
pkg/apiserver/rest/webservice/application.go
pkg/apiserver/rest/webservice/cluster.go
pkg/apiserver/rest/webservice/definition.go
pkg/apiserver/rest/webservice/env.go
pkg/apiserver/rest/webservice/oam_application.go
pkg/apiserver/rest/webservice/payload_types.go
pkg/apiserver/rest/webservice/policy_definition.go
pkg/apiserver/rest/webservice/project.go
pkg/apiserver/rest/webservice/system_info.go
pkg/apiserver/rest/webservice/target.go
pkg/apiserver/rest/webservice/velaql.go
pkg/apiserver/rest/webservice/webhook.go
pkg/apiserver/rest/webservice/webservice.go

Fix: swagger error

---

references/cli/common.go
references/cli/def.go
references/plugins/reference_test.go
references/plugins/references.go
references/plugins/testdata/terraform-alibaba-ask.yaml
references/plugins/testdata/terraform-aws-elb.yaml
references/plugins/testdata/terraform-azure-database-mariadb.yaml
references/plugins/testdata/terraform-baidu-vpc.yaml
references/plugins/testdata/terraform-gcp-gcs.yaml
references/plugins/testdata/terraform-tencent-subnet.yaml

Signed-off-by: Nicola115 <2225992901@qq.com>
support `vela def doc-gen <localFile.yaml>`
Fixes #
I have:

Feat: support def doc-gen <LocalFile.yaml> and corresponding functions

---

docs/apidoc/swagger.json
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go

This PR adds some params(Inputs, Outputs) in the create component API. 
I have:

Feat: make the component list is in reverse order

---

charts/vela-core/README.md
charts/vela-core/templates/kubevela-controller.yaml
charts/vela-core/values.yaml
charts/vela-minimal/README.md
charts/vela-minimal/templates/kubevela-controller.yaml
charts/vela-minimal/values.yaml

Helm Chart values.yaml typo
Fixes #
I have:

Fix: Helm Chart values.yaml typo

---

OWNERS_ALIASES

Feat: add @evanli18 as one Reviewer

---

references/cli/registry_test.go

Fix: pend registry test

---

Makefile
charts/vela-core/README.md
charts/vela-core/templates/NOTES.txt
charts/vela-core/templates/addon/fluxcd-def.yaml
charts/vela-core/templates/addon/fluxcd.yaml
references/cli/uninstall.go
references/cli/uninstall_test.go

Don't delete fluxcd addon when uninstall the vela helm chart.
Fixes #3353 
I have:

Feat: helm chart keep fluxcd addon while delete

---

pkg/addon/addon_test.go

Test: add more test for complicated semver check

---

references/common/application.go

Signed-off-by: zhangshukun [zshirley518@gmail.com](url)
Fixes #3416
1. remove the Service status line.
2. add vela status <app-name> --endpoint as it's very useful.
I have:

Feat: add vela status --endpoint into the tips for vela up

---

OWNERS_ALIASES

@devholic has contribute several PRs https://github.com/oam-dev/kubevela/pulls?q=is%3Apr+author%3Adevholic+is%3Aclosed 
Including some core features like https://github.com/oam-dev/kubevela/pull/3434 
As talked with @devholic , he's also going to contribute more to the community, so I nominate him as a review member.
Ping @barnettZQG @leejanee and other maintainers, please LGTM or approve if you agree!

Chore: Nominate @devholic as as a Review member

---

pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/cluster.go
pkg/apiserver/rest/usecase/definition.go
pkg/apiserver/rest/usecase/definition_test.go
pkg/apiserver/rest/usecase/envbinding_test.go
pkg/apiserver/rest/utils/cache.go
pkg/apiserver/rest/utils/cache_test.go
pkg/apiserver/rest/utils/http_test.go
pkg/apiserver/rest/utils/params_test.go
pkg/apiserver/rest/utils/ui_schema_test.go

Auto clears the data after the timeout. 
I have:
/cc @wonderflow 
```
goos: darwin
goarch: amd64
pkg: github.com/oam-dev/kubevela/pkg/apiserver/rest/utils
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkWrite-12        1000000              1199 ns/op
BenchmarkRead-12         4630959               258.4 ns/op
BenchmarkRW-12           1536162              1110 ns/op
PASS
ok      github.com/oam-dev/kubevela/pkg/apiserver/rest/utils    13.102s
```

Feat: add auto clear data function for the memory cache

---

Makefile
cmd/apiserver/main.go
go.mod
go.sum
pkg/apiserver/model/system_info.go
pkg/apiserver/model/user.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/usecase/authentication_test.go
pkg/apiserver/rest/usecase/system_info.go
pkg/apiserver/rest/utils/bcode/012_authentication.go
pkg/apiserver/rest/webservice/authentication.go
pkg/apiserver/rest/webservice/webservice.go

Feat: add dex login in apiserver

---

pkg/controller/core.oam.dev/v1alpha2/application/apply.go
pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go

Closes: #3355
Signed-off-by: Evan Li <evan.li97@outlook.com>
Fixes #3355
I have:

Fix(workflow): correct terraform component health check

---

Makefile
docs/apidoc/swagger.json
go.mod
pkg/apiserver/model/user.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
pkg/apiserver/rest/usecase/user.go
pkg/apiserver/rest/usecase/user_test.go
pkg/apiserver/rest/utils/bcode/013_user.go
pkg/apiserver/rest/utils/bcode/014_user.go
pkg/apiserver/rest/webservice/authentication.go
pkg/apiserver/rest/webservice/user.go
pkg/apiserver/rest/webservice/validate.go
pkg/apiserver/rest/webservice/validate_test.go
pkg/apiserver/rest/webservice/webservice.go
test/e2e-apiserver-test/user_test.go

Add user management apis
I have:

Feat: add user management apis

---

OWNERS_ALIASES

Chore: Nominate fourierr as a Reviewer member

---

docs/apidoc/swagger.json
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/env.go
pkg/apiserver/rest/usecase/project.go
pkg/apiserver/rest/usecase/project_test.go
pkg/apiserver/rest/usecase/target_model.go
pkg/apiserver/rest/utils/bcode/008_target.go
pkg/apiserver/rest/webservice/env.go
pkg/apiserver/rest/webservice/project.go
pkg/apiserver/rest/webservice/webservice_suite_test.go

Fixes #3480
Fixes #3477
I have:

Feat: add page index for env list API

---

pkg/apiserver/rest/webservice/addon.go
pkg/apiserver/sync/cache.go
pkg/apiserver/sync/cache_test.go
pkg/apiserver/sync/cr2ux_test.go
pkg/apiserver/sync/store.go

Fix: delete app won't be synced in UI

---

docs/apidoc/swagger.json
pkg/apiserver/model/application.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/webservice/addon.go

Feat: support delete the readonly application

---

docs/examples/custom-trait/README.md
docs/examples/custom-trait/app.yaml
docs/examples/custom-trait/stateful.cue
docs/examples/custom-trait/volume-trait.cue
pkg/apiserver/rest/usecase/application.go
pkg/cue/definition/template.go
references/appfile/dryrun/diff.go
references/appfile/dryrun/dryrun.go
references/appfile/dryrun/suit_test.go
references/appfile/dryrun/testdata/invalid-app-format.yaml
references/cli/dryrun.go
references/cli/livediff.go

Fix: add severside dry run for vela dry-run

---

references/cli/workflow.go
references/cli/workflow_test.go

fixes https://github.com/oam-dev/kubevela/issues/3431
Fix: fix workflow cli must have workflow in spec
I have:
/cc @zzxwill

Fix: fix workflow cli must have workflow in spec

---

references/common/application.go

Fix: vela status --endpoint format

---

OWNERS_ALIASES

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>
Resolves #3481

Chore: Nominate JooKS-me as a Reviewer member

---

pkg/apiserver/rest/usecase/authentication.go

fix parse token error validate
I have:

Fix: fix parse token error validate

---

pkg/resourcekeeper/componentrevision.go

The parallel apply component will cause data race for the recording of component revision. This PR fixes it. 
I have:

Fix: concurrent write to controller revision

---

codecov.yml

Fix: ignore kubebuilder generated file in code coverage

---

charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
vela-templates/definitions/internal/workflowstep/notification.cue

Signed-off-by: huanggze <gzhuang2014@gmail.com>
Fixes #3518
I have:

Fix: fix undefined field error in email workflowstep

---

pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/usecase/user.go
pkg/apiserver/rest/utils/bcode/012_authentication.go
pkg/apiserver/rest/utils/bcode/014_user.go

optimize err for auth in apiserver
I have:

Fix: optimize err for auth in apiserver

---

pkg/addon/helper.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/usecase/rbac.go

Fix: change the default permission name

---

pkg/addon/addon.go
pkg/addon/addon_suite_test.go
pkg/addon/helper.go
pkg/addon/versioned_registry.go
pkg/apiserver/rest/usecase/addon.go
pkg/apiserver/rest/utils/bcode/005_addon.go
pkg/apiserver/rest/webservice/addon.go

Fix: addon API panic and override workflow step for addon installation

---

charts/vela-core/templates/addon_registry.yaml

Fix: fix addon registry unmashall bug

---

pkg/addon/addon.go

Support empty components in application for addon.

Fix: addon support empty components

---

charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
vela-templates/definitions/internal/component/webservice.cue

Fix: fix the componentDefinition webservice parameter error

---

pkg/utils/common/common.go
references/cli/logs.go

add `--name` param for vela logs
I have:

Feat: add name param in vela logs

---

apis/core.oam.dev/v1alpha1/register.go

Fixes minor bugs in live-diff display.
I have:

Fix: livediff minor bug

---

references/cli/install.go

Update constraint from <=1.21 to <=1.22
Fixes #
I have:

Chore: bump k8s version contraints

---

docs/apidoc/swagger.json
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/helm.go
pkg/apiserver/rest/usecase/helm_test.go
pkg/apiserver/rest/webservice/helm.go
pkg/oam/labels.go

add helm repo list interface
Fixes #
I have:

Feat: add helm repo list endpoint

---

charts/vela-core/README.md
charts/vela-core/templates/NOTES.txt
pkg/apiserver/rest/usecase/user.go
references/cli/addon.go

Chore: refine chart readme and notes

---

README.md

Chore: add video records in readme for chinese community call

---

apis/types/types.go
pkg/apiserver/model/system_info.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/usecase/authentication_test.go
pkg/apiserver/rest/usecase/system_info.go
pkg/apiserver/rest/usecase/testdata/dex-config-def.yaml
pkg/apiserver/rest/usecase/user.go
pkg/apiserver/rest/utils/bcode/014_user.go
pkg/apiserver/rest/utils/dex.go
pkg/apiserver/rest/utils/dex_test.go
pkg/apiserver/rest/webservice/webservice.go

add update dex config in apiserver
I have:
/cc @zzxwill

Feat: add update dex config in apiserver

---

.github/workflows/apiserver-test.yaml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
contribute/developer-guide.md

Bump test environment k8s version to v1.20
Fixes #1873
I have:

Chore: bump test k8s to 1.20

---

pkg/apiserver/model/system_info.go
pkg/apiserver/rest/usecase/system_info.go

Fix: fix dex config field

---

references/cli/addon.go

Fix: upgrade addon velaql info bug

---

pkg/apiserver/rest/usecase/helm.go
pkg/apiserver/rest/usecase/helm_test.go

Fix: align config secret label

---

pkg/addon/addon.go
pkg/addon/addon_suite_test.go

addon cannot update label
Fixes #3575
I have:

Fix: addon cannot update label bug

---

.github/workflows/go.yml

upgrade golangci-lint-action to v3 to fix ci
Related issue: https://github.com/golangci/golangci-lint-action/issues/434
I have:

Chore: upgrade golangci-lint-action to v3 to fix ci

---

pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/utils/bcode/012_authentication.go

Fixes # 
fix refresh code expired bcode
I have:

Fix: fix refresh code expired bcode

---

cmd/core/main.go

Fix: add feature-gates to command-line args

---

references/cli/def.go
references/cli/provider.go
references/cli/provider_test.go

Fix #3589 and refine prompts for cli
Fixes #
I have:

Fix: add terraform aws provider without AWS_SESSION_TOKEN

---

OWNERS_ALIASES

Resolves https://github.com/oam-dev/kubevela/issues/3588

Chore: Nominate s4rd1nh4 as a Reviewer member

---

pkg/utils/helm/helm_helper.go

the underlying helm util package didn't handle the case that values.yaml in the chart has new default values:
In this PR, I have merged the new values with the old.
Fixes #3611 
I have:
after this PR:

Fix: reuse chart values in vela install

---

references/cmd/cli/main.go

CLI needs to switch on feature flags by default.
I have:

Fix: cli default switch on feature flags

---

pkg/controller/flags.go

Fixes application controller flags bug after upgrading flags library.
I have:

Fix: flags for controller

---

pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/usecase/authentication_test.go
pkg/apiserver/rest/usecase/system_info.go
pkg/apiserver/rest/utils/bcode/012_authentication.go
pkg/apiserver/rest/utils/bcode/014_user.go

fix dex login with existed email
I have:

Fix: fix dex login with existed email

---

apis/core.oam.dev/v1alpha1/garbagecollect_types.go
apis/core.oam.dev/v1alpha1/garbagecollect_types_test.go
apis/core.oam.dev/v1alpha1/zz_generated.deepcopy.go
docs/examples/app-with-policy/gc-policy/persist-resources.md

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>
About #3395 
/cc @Somefive

Feat: allow select resource by resource type for gc policy

---

pkg/addon/cache.go
pkg/apiserver/rest/usecase/helm.go
pkg/apiserver/rest/usecase/user.go
pkg/apiserver/rest/utils/bcode/013_repository.go

cherry-pick 3641 to release 1.3
Fixes #
I have:

Chore: cherry-pick 3641 to release 1.3

---

pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/config.go
pkg/apiserver/rest/usecase/config_test.go
pkg/apiserver/rest/usecase/project.go
pkg/apiserver/rest/usecase/project_test.go

- Refine the config sync logic
Fixes #
I have:

Fix: refine the config sync logic

---

pkg/apiserver/sync/convert.go
pkg/oam/auxiliary.go
pkg/stdlib/pkgs/query.cue
pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/types/type.go

Instance list:
Resource list(show multiple version):
I have:

Fix: duplicately list pods in velaQL

---

pkg/apiserver/sync/cache.go
pkg/apiserver/sync/cache_test.go

Fix: add label from inner system in CR can prevent sync

---

e2e/plugin/plugin_test.go
pkg/apiserver/rest/usecase/authentication.go
pkg/apiserver/rest/usecase/system_info.go
test/e2e-apiserver-test/velaql_test.go

fix token invalid after the server restarted
I have:

Fix: fix token invalid after the server restarted

---

e2e/addon/mock/testdata/mock-addon/metadata.yaml
e2e/addon/mock/testdata/mock-addon/template.yaml
e2e/plugin/plugin_test.go
makefiles/e2e.mk
pkg/apiserver/rest/webservice/addon.go
test/e2e-apiserver-test/addon_test.go
test/e2e-apiserver-test/suite_test.go
test/e2e-apiserver-test/velaql_test.go

cherry-pick https://github.com/oam-dev/kubevela/pull/3607 https://github.com/oam-dev/kubevela/pull/3665 to release 1.3
Fixes #
I have:

Fix: cherrypick 3665 and 3607 to release 1.3

---

pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/handler_test.go

Fix: can not query the instance list for the app with apply once policy

---

pkg/features/controller_features.go
pkg/resourcekeeper/gc.go

Feat: support disable legacy gc upgrade operation

---

pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go

Fixes #3635 
How to fix it?
check if the depended component is exist in all components, if not, raises one error.
report the error message in logs as below
```
I0412 10:13:34.844870       1 apply.go:345] "[Finished]: i-wnvrzjvl.apply-policies(finish apply policies)" application="vela-system/first-vela-app" controller="application" resource_version="559295" generation=1 publish_version="undefined" duration="7.3µs" spanID="i-wnvrzjvl.apply-policies"
E0412 10:13:34.845402       1 application_controller.go:194] "[handle workflow]" err="convert step: convert [apply-component]: component express-server-0 not found, which is depended by express-server-3" application="vela-system/first-vela-app" controller="application" resource_version="559295" …
```

Fix: invalid component depends on check

---

.github/workflows/go.yml
makefiles/dependency.mk

fix error CI : https://github.com/oam-dev/kubevela/runs/6122831846?check_suite_focus=true
https://github.com/oam-dev/kubevela/runs/6122557941?check_suite_focus=true and so on.
Fixes #
I have:

Fix: specify staticcheck version

---

charts/vela-core/templates/defwithtemplate/init-container.yaml
charts/vela-core/templates/defwithtemplate/sidecar.yaml
charts/vela-minimal/templates/defwithtemplate/init-container.yaml
charts/vela-minimal/templates/defwithtemplate/sidecar.yaml
vela-templates/definitions/internal/trait/init-container.cue
vela-templates/definitions/internal/trait/sidecar.cue

Feat: add env for sidecar and init-container trait

---

apis/core.oam.dev/v1alpha1/garbagecollect_types.go
docs/examples/app-with-policy/gc-policy/reverse-dependency.md
pkg/controller/core.oam.dev/v1alpha2/application/gc_policy_test.go
pkg/resourcekeeper/gc.go
pkg/resourcekeeper/gc_test.go
pkg/resourcekeeper/options.go

Fixes #2449
add sequential in gc policy
I have:

Feat: add sequential in gc policy

---

README.md

Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>

Chore: enhance KubeVela slack url in readme

---

pkg/controller/core.oam.dev/v1alpha2/application/revision.go

cherry-pick https://github.com/oam-dev/kubevela/pull/3724
Fixes #
I have:

Fix: cherry-pick #3724 to delete apprev annotation. 

---

apis/types/types.go
docs/apidoc/swagger.json
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/definition.go
pkg/apiserver/rest/usecase/definition_test.go
pkg/apiserver/rest/usecase/testdata/applyapplication-sd.yaml
pkg/apiserver/rest/usecase/testdata/myingress-td.yaml
pkg/apiserver/rest/usecase/testdata/webserver-cd.yaml

We may want to see aliases on the velaux, such as Chinese
Fixes #
I have:

Feat: apiserver definition alias

---

pkg/apiserver/rest/usecase/helm.go
pkg/apiserver/rest/usecase/helm_test.go

Fix: use unify project filter func to list secret

---

charts/vela-core/templates/defwithtemplate/config-image-registry.yaml
charts/vela-minimal/templates/defwithtemplate/config-image-registry.yaml
vela-templates/definitions/internal/component/config-image-registry.cue

Fix: public image registry config could not be created

---

pkg/addon/addon.go
pkg/addon/addon_suite_test.go
pkg/addon/helper.go
pkg/addon/reader_local.go

fix several issue
Fixes #
I have:

Fix: fix the bug of  vela cli enable addon by localDir on  windows os  

---

charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
vela-templates/definitions/internal/component/webservice.cue

Fix: fix revision in webservice

---

references/cli/addon.go
references/cli/addon_test.go

Fix: addon  cli parse any type

---

charts/vela-core/templates/defwithtemplate/env.yaml
charts/vela-minimal/templates/defwithtemplate/env.yaml
vela-templates/definitions/internal/trait/env.cue

The original env trait has problems while patching object with env using valueFrom instead of value. This PR solves it.
I have:

Fix: env trait compatible with valueFrom

---

pkg/addon/cache.go

Fixes #3780 
How to fix it?
just pass right arguments
I have:

Fix: log message wraps wrong arguments

---

.github/workflows/release.yml

Fix: update latest version

---

pkg/addon/cache_test.go

Test: add some unittest to addon cache

---

README.md

add some links in readme
I have:

Feat: add some links in readme

---

docs/apidoc/swagger.json
pkg/apiserver/model/user.go
pkg/apiserver/rest/apis/v1/types.go
pkg/apiserver/rest/usecase/application.go
pkg/apiserver/rest/usecase/application_test.go
pkg/apiserver/rest/usecase/user.go
pkg/apiserver/rest/webservice/webservice.go

Feat: apiserver deploy user info for revision

---

references/cli/debug.go

add some message to make debug more clear
I have:

Fix: add some message to make debug more clear

---

pkg/appfile/parser.go
pkg/appfile/parser_test.go
pkg/appfile/testdata/backport-1-2/app.yaml
pkg/appfile/testdata/backport-1-2/apprev1.yaml
pkg/appfile/testdata/backport-1-2/apprev2.yaml
pkg/appfile/testdata/backport-1-2/apprev3.yaml
pkg/appfile/testdata/backport-1-2/wsd.yaml
pkg/controller/core.oam.dev/v1alpha2/application/revision.go
pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go

Signed-off-by: cezhang <c1zhang.dev@gmail.com>
handle publishversion case
Signed-off-by: cezhang <c1zhang.dev@gmail.com>
Fixes "1.2 upgrade 1.3 workflowstep XXX not found" issue
I have:
- vela install --version 1.2.0 in k3d
- create application through CLI(explicitly define workflow) and velaux
- vela install --version 1.3.3 in k3d
- watch application running from rendering to running
- check the apprev if workstepdefinitions are patched

Fix: update latest version Fix: 1.2 upgrade 1.3 workflowstep XXX not found

---

e2e/addon/mock/vela_addon_mock_server.go
references/cli/portforward.go

Signed-off-by: afzal442 <afzal442@gmail.com>
Fixes #
I have:

Fix: refactors http write resp to use 'html/template' instead

---

pkg/cue/model/value/value.go
pkg/cue/model/value/value_test.go

Fixes #3838
I have:
/cc @leejanee @wangyikewxgm

Fix: add parse comments in lookupScript to make patch work

---

pkg/addon/source.go
pkg/addon/source_test.go
pkg/apiserver/rest/usecase/addon.go

Merge PR #3837 to branch release-1.3
Fixes #3836 
I have:

Fix: sensitive field of addon registry is exposed, cherry-pick #3837

---

pkg/addon/cache.go
pkg/addon/cache_test.go
test/e2e-multicluster-test/suite_test.go

Merger PR #3835 to branch release-1.3 
Fixes #3795 
I have:

Fix: The new addon can not shown in the Addons page, cherry-pick #3835

---

pkg/resourcekeeper/cache.go

Fix: ignore no kind match error in gc

---

.github/workflows/codeql-analysis.yml
.github/workflows/trivy-scan.yml
go.mod
go.sum

Signed-off-by: huangminjie <minjie.huang@daocloud.io>
run image scan CI for every pull request and fix CVEs in time  ( #3834)
Fixes #
I have:

Feat: run image scan CI for every pull request and fix CVEs in time

---

pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/handler.go
references/cli/addon.go
references/cli/status.go
references/cli/velaql.go

Fix: the endpoints is repeated and can not query the ingress with v1 version

---

pkg/cue/definition/template.go
pkg/cue/definition/template_test.go

Fix: delete context when patch outputs in trait

---

charts/vela-core/templates/defwithtemplate/command.yaml
charts/vela-core/templates/defwithtemplate/container-image.yaml
charts/vela-core/templates/defwithtemplate/env.yaml
charts/vela-minimal/templates/defwithtemplate/command.yaml
charts/vela-minimal/templates/defwithtemplate/container-image.yaml
charts/vela-minimal/templates/defwithtemplate/env.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
references/cli/traits_test.go
vela-templates/definitions/internal/trait/command.cue
vela-templates/definitions/internal/trait/container-image.cue
vela-templates/definitions/internal/trait/env.cue

Signed-off-by: ZhongsJie <zhongsjie@cmbchina.com>
modify the cue template to solve the issue
Fixes #3841 
I have:
@wonderflow

Fix: modify the template definition to solve the trait cli error

---

entrypoint.sh
hack/apis/sync.sh

https://github.com/koalaman/shellcheck/wiki/SC3010
Fixes #
I have:

Refactor: Minor changes on shell script to support double quotes format and [ ] POSIX

---

docs/apidoc/swagger.json
pkg/apiserver/rest/webservice/addon.go

Fix: update API document

---

references/cli/uninstall.go

Signed-off-by: Kethavath Siva Naik <sivanaikk0903@gmail.com>
Fixed a minor change in code. Changed uintall to uninstall
Fixes #
I have:

Fix: corrected minor typo in code

---

docs/examples/velaql-views/usage.md

I have fixed a spelling error of velaQL usage document, the path of this problematic file is "docs/examples/velaql-views/usage.md".

Fix: fix a spelling error of velaQL usage document

---

charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
vela-templates/definitions/internal/component/webservice.cue

Signed-off-by: ivyilike <pww123@cmbchina.com>
webservice support healthProbe With https
Fixes  https://github.com/kubevela/kubevela/issues/3910
I have:
ping @wonderflow

Feat: webservice support healthProbe With https

---

references/plugins/reference_test.go
references/plugins/references.go

Fixes #2208. Try to get the mapValue type name from `Source`.
I have:
Ran the `vela show service-binding` locally, and the output is like this:
```
❯ ./bin/vela show service-binding                                                                                                                                                                                                                                        
+-------------+------------------------------------------------+------------+----------+---------+
|    NAME     |                  DESCRIPTION                   |    TYPE    | REQUIRED | DEFAULT |
+-------------+------------------------------------------------+------------+----------+---------+
| envMappings | The mapping of environment variables to secret | #KeySecret | true     | …
```

Fix(cli): try to get mapValue type name

---

charts/vela-core/crds/core.oam.dev_applications.yaml
charts/vela-core/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/vela-core/values.yaml
charts/vela-minimal/crds/core.oam.dev_applications.yaml
charts/vela-minimal/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/vela-minimal/values.yaml
config/crd/kustomization.yaml

Signed-off-by: huangminjie <minjie.huang@daocloud.io>
support chart value to disable conversion on application crd （#3808）
Fixes #
I have:

Feat: support chart value to disable conversion on application crd

---

charts/vela-core/templates/defwithtemplate/gateway.yaml
charts/vela-minimal/templates/defwithtemplate/gateway.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
vela-templates/definitions/internal/trait/gateway.cue

The gateway trait support https protocol (#3832)
Fixes #3832
I have:

Feat: gateway trait support https protocol (#3832)

---

pkg/apiserver/domain/service/cluster.go

Fix: listKubeCluster page=0

---

pkg/auth/privileges.go

Grant readonly privilege mis-bond the writer's Role. This PR fixes it.
I have:

Fix: grant privilege readonly incorrect binding

---

pkg/workflow/tasks/custom/task.go
pkg/workflow/tasks/discover.go
pkg/workflow/tasks/discover_test.go
pkg/workflow/types/types.go
pkg/workflow/workflow.go
pkg/workflow/workflow_test.go

refactor the step group in workflow
I have:
/cc @wonderflow @zq200618

Fix: refactor the step group in workflow

---

go.mod
go.sum

Bump kubectl package to v0.23.6 to address https://github.com/kubernetes/kubernetes/pull/107131
Fixes #3896
I have:

Chore: Bump kubectl sdk

---

cmd/apiserver/main.go
pkg/apiserver/config/config.go
pkg/apiserver/infrastructure/clients/clients_suite_test.go
pkg/apiserver/infrastructure/clients/kubeclient.go
pkg/apiserver/infrastructure/clients/kubeclient_test.go
pkg/apiserver/server.go

Feat: support to configure the qps and burst

---

pkg/utils/common/common.go

Fix: failed to create Provider by CLI

---

pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/types/type.go
test/e2e-apiserver-test/velaql_test.go

Fix: velaql appliedResource bug and add e2e-test
Fixes #
I have:

Fix: velaql appliedResource bug and add e2e-test

---

.github/workflows/registry.yml
Dockerfile
Dockerfile.apiserver
Dockerfile.cli
Dockerfile.e2e
makefiles/build.mk
makefiles/const.mk
references/cli/cli.go
references/cmd/cli/main.go
runtime/rollout/e2e/Dockerfile.e2e

fixes #1392
One of the use case could be https://github.com/kubevela/kubevela/discussions/3821
I have:

Feat: build docker image(oamdev/vela-cli) for vela-cli

---

.github/workflows/release.yml

When release contains "alpha" or "beta", don't update version pointer file in OSS.
Fixes #
I have:

Fix: don't update version file when publish alpha/beta version

---

pkg/apiserver/domain/service/project.go

Fix: add Target fail by fetch terraform-provider error

---

charts/vela-core/templates/rbac/x-definition.yaml
cmd/apiserver/main.go
pkg/apiserver/domain/service/rbac.go
pkg/apiserver/domain/service/target.go
pkg/apiserver/infrastructure/clients/kubeclient.go
pkg/apiserver/server.go
pkg/apiserver/utils/auth.go
pkg/apiserver/utils/context.go
pkg/auth/privileges.go
pkg/features/apiserver_features.go

Add support for impersonation for application mutating requests in apiserver.
I have:

Feat: support impersonation for application in apiserver

---

go.mod
go.sum
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/tree_test.go
pkg/velaql/providers/query/types/type.go

1. helmRelase and helmRepo heath check.
2. additional info for pod and service
3. deletionTime and createTime
4. one deleted appliedResource don't block whole resourceTree request.
Fixes #
I have:

Feat: optimize some logic of topology resource-tree

---

pkg/apiserver/infrastructure/datastore/mongodb/mongodb.go
pkg/apiserver/infrastructure/datastore/mongodb/mongodb_test.go

Fix: fail to query the count with MongoDB

---

docs/examples/workflow/step-group/README.md
docs/examples/workflow/step-group/example.yaml
pkg/workflow/workflow.go

Signed-off-by: Qiang Zheng <zhengq20018@cmbchina.com>
1. step group documentation update
2. bug fix of firstExecuteTime mission in step group execute status
I have:

Fix: step group documentation update and bug fix of firstExecuteTime mission

---

references/cli/portforward.go
references/cli/portforward_test.go

Fixes https://github.com/kubevela/kubevela/issues/3885
I have:

Fix: vela port-forward not working for webservice component

---

charts/vela-core/templates/defwithtemplate/env.yaml
charts/vela-minimal/templates/defwithtemplate/env.yaml
vela-templates/definitions/internal/trait/env.cue

Fixes #4037 and #3978.
I have:

Fix: env trait error when existing env exists

---

.github/workflows/release.yml

Fix: release script condition syntax

---

pkg/velaql/providers/query/handler.go

Fixes https://github.com/kubevela/kubevela/issues/4047
I have:

Fix: Fail to get the endpoints via the VelaQL

---

pkg/apiserver/domain/repository/application.go
pkg/apiserver/domain/service/application.go
pkg/apiserver/domain/service/envbinding.go
pkg/apiserver/domain/service/envbinding_test.go
pkg/apiserver/interfaces/api/application.go

Fixes #4048
I have:
/cc @yangsoon

Fix: the policies can not be deleted

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go

set workflow to finish before record in controller revision
I have:

Fix: set workflow to finish before record in controller revision

---

.github/workflows/registry.yml

Fix: CI workflow for rollout acr image build and push

---

README.md

Chore: change the key features in readme

---

pkg/utils/config/application.go

Fixes #4069
Investigation：
When the Application is got by https://github.com/kubevela/kubevela/blob/b13eb4adb5cf14e2b8165789cce4ec61581caeb3/pkg/utils/config/application.go#L116  successfully with `err2==nil`,  
the error is still reported by https://github.com/kubevela/kubevela/blob/b13eb4adb5cf14e2b8165789cce4ec61581caeb3/pkg/utils/config/application.go#L124
Before:
```
➜  ~ vela provider delete terraform-alibaba  --name default
Error: failed to delete Terraform Cloud Provider default: failed to delete Terraform Provider default
2022/05/31 00:22:37 failed to delete Terraform Cloud Provider default: failed to delete Terraform Provider default
➜  ~
```
After:
```
➜  bin git:(fix-delterra) ✗ ./vela provider delete terraform-alibaba  --name …
```

Fix: Can not delete terraform provider

---

charts/vela-core/templates/cluster-gateway/certmanager.yaml
charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
charts/vela-core/templates/cluster-gateway/job-patch.yaml

Fixes https://github.com/kubevela/kubevela/issues/4071
I have:

Fix: upgrade from v1.3+ to v1.4+ with new secret for cluster-gateway

---

e2e/application/application_test.go
e2e/application/component-pod-view.yaml
references/cli/cli.go
references/cli/velaql.go

Signed-off-by: Shukun Zhang <2236407598@qq.com>
I build the query capability of VelaQL into vela-cli, improving the experience of using VelaQL. we can use command like `vela ql`, and put the VelaQL.
Currently using json to display query results, the next step will refer to [kube-prompt](https://github.com/c-bata/kube-prompt) to provide friendly interaction, use [tablewriter](https://github.com/olekukonko/tablewriter) to improve the printing method, and change the json data to table printing to make the display more intuitive.
Fixes #3361
I have:
```shell
velq ql "component-pod-view{appNs=default,appName=demo,name=demo}"
```
```
{
"podList": [
{
"status": {
"phase": "Running",
"podIP": "10.244.0.17",
"hostIP": "172.18.0.2",
"nodeName": "kind-control-plane"
},
"cluster": "local", …
```

Feat:  build the query capability of VelaQL into vela-cli

---

pkg/apiserver/domain/repository/workflow.go

Refer to #3503 
Fixes #3900
I have:
/cc @zzxwill

Fix: change the region to customRegion

---

pkg/cmd/factory.go
references/cli/cli.go

Feat: use deferred config in CLI

---

pkg/apiserver/domain/service/user.go
references/cli/addon.go
references/cli/provider.go

Fix: show the default password after enabled the VelaUX addon

---

.github/workflows/registry.yml

Change the image name for ghcr:
"ghcr.io/kubevela/kubevela/vela-core:latest" => "ghcr.io/kubevela/oamdev/vela-core:latest"
I have:

Fix: change the image name in ghcr

---

references/cli/addon-registry.go

Signed-off-by: ZhongsJie <zhongsjie@gmail.com>
Fixes #4132
I have:

Fix: vela addon registry get panic

---

pkg/multicluster/cluster_management.go

Support joining cluster with `insecure-skip-tls-verify`.
Fixes #4134
I have:

Feat: support join an insecure cluster

---

pkg/controller/core.oam.dev/v1alpha2/application/apply.go
pkg/cue/process/handle.go

Fix trait customStatus error when controlPlanOnly=true
I have:

Fix: fix trait customStatus error when controlPlanOnly=true

---

CHANGELOG/CHANGELOG-1.0.md
CHANGELOG/CHANGELOG-1.2.md
docs/examples/velaql-views/usage.md

fix some type mistake for  docs

Fix: fix typo mistake in docs

---

references/cli/addon-registry.go

Feat: cli addon add registry add more git types

---

.github/workflows/registry.yml

Online self-built mirror registry. 
I have:

Chore: change the acr registry address

---

.github/workflows/registry.yml

Chore: change the acr registry address (#4214)

---

apis/core.oam.dev/common/types.go
cmd/core/main.go
pkg/apiserver/domain/service/workflow.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
pkg/cue/model/value/value.go
pkg/stdlib/op.cue
pkg/workflow/hooks/data_passing.go
pkg/workflow/hooks/data_passing_test.go
pkg/workflow/providers/mock/mock.go
pkg/workflow/providers/workspace/workspace.go
pkg/workflow/providers/workspace/workspace_test.go
pkg/workflow/tasks/custom/task.go
pkg/workflow/tasks/custom/task_test.go
pkg/workflow/tasks/discover.go
pkg/workflow/tasks/discover_test.go
pkg/workflow/types/types.go
pkg/workflow/workflow.go
pkg/workflow/workflow_test.go
references/cli/workflow_test.go

Fixes #4087 
Fixes #4088 
I have:

Feat: support more expressions in if and op.Fail

---

docs/examples/workflow/app-with-if/README.md
docs/examples/workflow/app-with-timeout/README.md
docs/examples/workflow/step-group/README.md

Fixes #
I have:
/cc @wonderflow @barnettZQG

Feat: add timeout and if examples

---

charts/vela-core/templates/defwithtemplate/affinity.yaml
charts/vela-minimal/templates/defwithtemplate/affinity.yaml
references/cli/show.go
references/cli/show_test.go
references/plugins/cluster.go
references/plugins/references.go
vela-templates/definitions/internal/trait/affinity.cue

Some ComponentDefinitions, TraitDefinitions, WorkflowDefinitions
failed to show the usage in web browser
Signed-off-by: Zheng Xi Zhou <zhengxi.zzx@alibaba-inc.com>
Fixes #
I have:

Fix: fixed the problems of display definition in web and support displaying WorkflowStep and Policy

---

references/cli/status.go

Feat: omit service output if there's nothing

---

pkg/apiserver/domain/service/cloudshell.go

A cloudshell instance can live for a maximum of 60 minutes. This rule is the same with the Aliyun Cloud shell.
I have:

Feat: set the cloudshell instance max live time

---

pkg/workflow/step/generator.go

When user uses override policy without topology policy, previously the deploy workflow step will not be used. Now it will be used as default which will leverage all the override policy.
Example:
```yaml
metadata:
name: policy-test
annotations: 
version: "v0.0.1"
description: "My override application"
spec:
components:
- name: nginx-with-override
properties:
image: nginx
policies:
- name: override-nginx-legacy-image
type: override
properties:
components:
- name: nginx-with-override
properties:
image: nginx:1.20
```
I have:

Feat: enhance deploy workflow step generator

---

references/cli/delete.go
references/common/application.go

Feat: don't ask user confirmation when delete with --force or --yes

---

pkg/cue/model/value/value.go

Feat: end logic not use

---

pkg/controller/core.oam.dev/v1alpha2/application/revision.go

Fix: disable apprev status update when apprev disabled

---

charts/vela-core/templates/defwithtemplate/init-container.yaml
charts/vela-core/templates/defwithtemplate/service-account.yaml
charts/vela-core/templates/defwithtemplate/sidecar.yaml
charts/vela-minimal/templates/defwithtemplate/init-container.yaml
charts/vela-minimal/templates/defwithtemplate/service-account.yaml
charts/vela-minimal/templates/defwithtemplate/sidecar.yaml
vela-templates/definitions/internal/trait/init-container.cue
vela-templates/definitions/internal/trait/service-account.cue
vela-templates/definitions/internal/trait/sidecar.cue

1. Enhance sidecar trait by adding adding fieldRef.
2. Enhance init-container trait by adding extra volumeMounts.
3. Fix service-account trait bug.
I have:

Fix: enhance sidecar & init traits

---

charts/vela-core/templates/defwithtemplate/init-container.yaml
charts/vela-minimal/templates/defwithtemplate/init-container.yaml
vela-templates/definitions/internal/trait/init-container.cue

Fixes init-container bug.
I have:

Fix: init container bug

---

pkg/cue/model/value/value_test.go
pkg/stdlib/packages.go
pkg/stdlib/packages_test.go
pkg/workflow/tasks/custom/task.go

optimize imports packages
Before:
After:
I have:

Feat: optimize imports packages to reduce 75% cpu with better performance

---

pkg/multicluster/cluster_management.go

Signed-off-by: huiwq1990 <huiwq1990@163.com>
Fixes #
I have:

Feat: cleanup cluster exist check

---

.github/workflows/chart.yaml
.github/workflows/registry.yml

Fix: add the job of independently publishing chart packages

---

.github/workflows/chart.yaml
.github/workflows/registry.yml

* Fix: add the job of independently publishing chart packages
* Fix: add the job of independently publishing chart packages
Fixes #
I have:

Fix: add the job of independently publishing chart packages (#4360)

---

pkg/oam/labels.go
pkg/stdlib/pkgs/query.cue
pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/endpoint_test.go
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/handler_test.go
pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/types/type.go
pkg/velaql/providers/query/utils.go
references/cli/velaql_test.go
test/e2e-apiserver-test/velaql_test.go

1. support resource topology for endpoints check
2. refactor the code to reduce duplicate
I have:

Feat: support resource topology for endpoints

---

pkg/addon/versioned_registry.go
pkg/definition/definition.go
references/cli/def.go

Fixes #4257 
I have:
I've tested locally:
For both create and update:
Create:
Updated:

Feat: support vela def apply for yaml definition

---

pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/resourcetracker/app.go
pkg/stdlib/pkgs/kube.cue
pkg/workflow/providers/kube/handle.go

1. Support using "vela/ql" in Workflow.
2. Add comments to ListApplicationResourceTrackers.
3. Fix op.#List namespace parameter bug.
4. Add application labels to resources dispatched by kube.#Apply, otherwise they cannot be recycled.
I have:

Fix: several minor bugs

---

references/cli/addon.go

Fix: fail directly when app terminated

---

charts/vela-core/templates/defwithtemplate/ref-objects.yaml
charts/vela-minimal/templates/defwithtemplate/ref-objects.yaml
vela-templates/definitions/internal/component/ref-objects.cue

Fix: add usage comment for ref-objects

---

pkg/apiserver/domain/model/application.go
pkg/apiserver/domain/service/application.go
pkg/apiserver/interfaces/api/dto/v1/types.go

Fix: addon env name and alias for policy

---

charts/vela-core/templates/defwithtemplate/storage.yaml
charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/storage.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
docs/examples/core-definitions/component/webservice.yaml
docs/examples/core-definitions/trait/storage.yaml
vela-templates/definitions/internal/component/webservice.cue
vela-templates/definitions/internal/trait/storage.cue

Fix: fix volumes duplicate in list

---

pkg/apiserver/domain/service/cloudshell.go
pkg/apiserver/domain/service/cloudshell_test.go

Fix: read the ca cert from the test env

---

docs/examples/terraform/cloud-resource-provision-and-consume/application-oss-deploy-website.yaml
docs/examples/terraform/cloud-resource-provision-and-consume/application-rds-data-outputs.yaml

Added RDS and OSS examples to show to use cloud resources
Fixes #
I have:

Fix: examples on how to use cloud resources

---

references/cli/addon.go

Fix: build failed as addon function converted

---

pkg/appfile/dryrun/dryrun.go
pkg/appfile/dryrun/dryrun_test.go

Signed-off-by: ZhongsJie <zhongsjie@cmbchina.com>
Fixes #4219 
I have:

Feat: provide defualt namespace for dry-run

---

references/cli/kube.go
references/plugins/cluster.go

Chore: trim debug info

---

pkg/apiserver/event/sync/convert.go

Fix: the sync env name is empty

---

Makefile

Feat: trim redundant makefile dependency

---

pkg/apiserver/event/sync/cache.go
pkg/apiserver/event/sync/cr2ux.go

Fix: the history applications are repeatedly synchronized

---

pkg/apiserver/domain/service/project.go
pkg/apiserver/domain/service/project_test.go
pkg/apiserver/interfaces/api/dto/v1/types.go
test/e2e-test/resource_policy_test.go

Feat: support to query the alias of the project member

---

pkg/addon/addon.go
pkg/addon/render.go
pkg/addon/render_test.go
pkg/cue/model/value/value.go

support vela addon enable app in cue Template and packages
I have:

Feat: support vela addon enable with package

---

references/cli/common.go
references/cli/delete.go

Signed-off-by: suxiang <704427617@qq.com>
Fixes #4442 
I have:
1. make
2. run `vela delete --help` and find no `--svc`

Feat: delete svc flag from vela delete cli cmd

---

Dockerfile.cli
references/docgen/def-doc/trait/service-account.eg.md

Fix: docker file fail to build for vela cli

---

pkg/appfile/parser.go
pkg/features/controller_features.go

[Backport release-1.5] Feat: add featuregates to disallow url in ref-objects

---

pkg/addon/addon.go
pkg/addon/addon_suite_test.go
pkg/addon/addon_test.go
pkg/addon/helper.go
pkg/addon/init.go
pkg/addon/render.go
pkg/addon/render_test.go
pkg/cue/model/value/value.go
pkg/oam/labels.go

CUE files in resources must specify packages to be used. The default package is:
```
package main
```
I have:

Chore: refactor addon enable with package

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go

Fix: fix logs to record the right publish version

---

.github/CODEOWNERS

Update code owner for new maintainers and approvers.
I have:

Chore: update code owner

---

pkg/apiserver/interfaces/api/authentication.go

Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>
Fixes #
I have:

Fix: missing return when token is null

---

cmd/apiserver/main.go

Fix: there is no color in the diff report

---

references/cli/portforward.go

Fix: can not find the resource when the resource namespace is different with application

---

e2e/addon/mock/utils/utils.go
makefiles/e2e.mk

Fix: fix e2e flaky tests

---

.github/workflows/chart.yaml
.github/workflows/registry.yml

Fix: align release image and charts with the master branch

---

pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/cue/model/sets/operation.go
pkg/cue/model/sets/operation_test.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-with-env-and-storage.yaml

Fixes storage patch env bug in #3300
P.S. This PR does not ensure all the possible cases in storage works. It only fixes the bug in #3300.
I have:

Fix: storage patch env

---

.github/workflows/chart.yaml

Chore: update chart-publishing, only push index and new charts

---

.github/workflows/chart.yaml

Fix: publish chart version

---

charts/vela-core/templates/defwithtemplate/sidecar.yaml
charts/vela-minimal/templates/defwithtemplate/sidecar.yaml
vela-templates/definitions/internal/trait/sidecar.cue

Fix: sidecar trait

---

references/cli/def.go
references/cli/dryrun.go
references/cli/velaql.go

Chore: fix cli description to remove html tag format

---

hack/load-test/README.md

Fix: typo in load-test readme

---

pkg/addon/utils.go
pkg/addon/utils_test.go
pkg/oam/labels.go

Fix: fix addon bond component annotaion 

---

cmd/core/main.go
pkg/controller/core.oam.dev/oamruntime_controller.go
pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_suit_test.go
pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go
pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/suite_test.go
pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
pkg/oam/labels.go

Feat: definition support controller requirement

---

apis/core.oam.dev/common/types.go
apis/core.oam.dev/v1alpha1/envbinding_types.go
charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-core/crds/core.oam.dev_applications.yaml
charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_applications.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
pkg/policy/envbinding/placement.go
pkg/policy/envbinding/utils.go
pkg/stdlib/pkgs/multicluster.cue
pkg/workflow/providers/multicluster/multicluster.go

Mark envbinding related functions and spec as deprecated. Proposed to remove it in v1.7/v1.8.
I have:

Feat: mark envbinding related code as deprecated

---

pkg/stdlib/pkgs/http.cue

Amend PR https://github.com/kubevela/kubevela/pull/4516 to fix bug.
I have:

Fix: add status code for cue struct

---

pkg/addon/addon.go

Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>
Fixes #
current code unable identify legacy addon, and will update it.
I have:

Fix: addon dependency 1.1 legacy support

---

cmd/core/main.go

fix writing logs to file
I have:

Fix: fix writing logs to file

---

e2e/addon/mock/utils/utils.go
e2e/addon/mock/vela_addon_mock_server.go
test/e2e-apiserver-test/addon_test.go

Fix: try to fix addon flaky test

---

pkg/features/controller_features.go
pkg/utils/apply/apply.go
pkg/utils/apply/apply_resource_test.go

Fixes #4469
I have:
Notice:
1. Resources like Service have separate controller to modify its spec. Therefore, for Service resource, this configuration will not take effect.
2. KubeVela legacy rollout will not work when this flag is enabled.

Feat: support use update instead of patch for apply

---

pkg/addon/addon_test.go

Test: add rc version addon check semVer test

---

apis/core.oam.dev/v1alpha1/applyonce_types.go
apis/core.oam.dev/v1alpha1/garbagecollect_types.go
pkg/resourcekeeper/statekeep_suite_test.go

Fixes #4594
I have:
/cc @fourierr

Feat: align resource selector across policies

---

references/cli/kube.go
references/cli/up.go

Fix: up command example

---

pkg/cue/model/sets/operation.go
pkg/cue/model/sets/utils.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-with-env-labels-storage.yaml

* Fix: open basic lit fails lookup path
* Fix: test
Same with #4625, except that this PR is for master branch (CUE 0.4).
I have:

Fix: open basic lit fails lookup path to KubeVela

---

hack/docgen/cli/gen.go
hack/docgen/def/mods/component.go
references/docgen/markdown.go
references/docgen/parser.go
references/docgen/vars.go

Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>### Description of your changes
Generated files is here: https://github.com/kubevela/kubevela.io/pull/928
I have:

Feat: add base resource section for component ref

---

references/cli/debug.go
references/cli/debug_test.go

Fix: optimize workflow debug cmd

---

references/cli/debug.go
references/cli/debug_test.go

[Backport release-1.5]Fix: optimize workflow debug cmd

---

references/cli/def.go

Fix: add supported but missing provider

---

pkg/apiserver/domain/model/system_info.go
pkg/apiserver/domain/service/authentication.go
pkg/apiserver/domain/service/system_info.go

[Backport release-1.5]Fix: fix signedKey using platform id

---

pkg/apiserver/domain/model/system_info.go
pkg/apiserver/domain/service/authentication.go
pkg/apiserver/domain/service/system_info.go

[Backport release-1.4]Fix: fix signedKey using platform id

---

references/cli/system.go

Feat https://github.com/kubevela/kubevela/issues/3924
- Add diagnose of  the link of hub APIServer to cluster-gateway
I have:
- run `system diagnose` to diagnose the link of hub APIServer to cluster-gateway

Feat: System diagnose

---

charts/vela-core/templates/velaql/application-revision.yaml
references/cli/revision.go
references/cli/revision_test.go
references/cli/utils.go
references/cli/utils_test.go

Feat: vela revision support read the apprevision details in yaml format

---

charts/vela-core/templates/defwithtemplate/topology.yaml
charts/vela-minimal/templates/defwithtemplate/topology.yaml
vela-templates/definitions/internal/policy/topology.cue

```
Workflow:
mode: StepByStep
finished: true
Suspend: false
Terminated: true
Steps
- id: pzgkymxcox
name: deploy-e2e
type: deploy
phase: failed 
message: step deploy: run step(provider=multicluster,do=deploy): failed to parse topology policy topology: json: unknown field "cluster"
```
I have:

Fix: unknown field cluster

---

.github/workflows/apiserver-test.yaml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
test/e2e-multicluster-test/multicluster_standalone_test.go

Chore: Add v1.23 to regular CI test (#4673)

---

cmd/core/main.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/features/controller_features.go

Chore: remove duplicated feature flags for workflowrun

---

references/cli/system.go

Signed-off-by: HanMengnan <1448189829@qq.com>
In the former code, `vela system` return the error massge when the metric server isn't installed.
Now I fix the bug to ensure other data can be displayed normally expect the metric data.
Fixes #4672 
I have:
@barnettZQG

Fix: fix the `vela system info` command can not work

---

pkg/velaql/view.go
test/e2e-apiserver-test/suite_test.go
test/e2e-apiserver-test/velaql_test.go

Fix: fix config parameter in ql for collect pod logs
I have:

Fix: fix config parameter in ql

---

hack/apis/sync.sh

Fix: fix the sync api script

---

go.mod
go.sum

https://avd.aquasec.com/nvd/cve-2022-27664
I have:

Fix: CVE-2022-27664

---

pkg/apiserver/domain/model/workflow.go
pkg/apiserver/domain/service/workflow.go
pkg/apiserver/domain/service/workflow_test.go

Fix: the workflow records do not delete if the driver is MongoDB

---

codecov.yml
version/version_test.go

Chore: update test coverage

---

pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/utils.go
references/cli/top/model/resource.go
test/e2e-apiserver-test/velaql_test.go

Fix: query the resource duplicately

---

references/docgen/markdown.go

Fix Backport error caused by #4726
Fixes #
I have:

Fix: show command caused by wrong backport

---

pkg/apiserver/domain/service/workflow.go

This change is part of https://github.com/kubevela/kubevela/pull/4631
I have:

Fix: nil pointer dereference

---

pkg/velaql/providers/query/collector.go
pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/utils.go
test/e2e-apiserver-test/velaql_test.go

Backport of https://github.com/kubevela/kubevela/pull/4714 to release-1.5.

[Backport release-1.5] Fix: query the resource duplicately (#4714)

---

pkg/addon/addon_suite_test.go
references/cli/show.go
references/docgen/markdown.go

Feat: support no browserver when using vela show without --web

---

apis/core.oam.dev/v1beta1/core_types.go
apis/core.oam.dev/v1beta1/policy_definition.go
apis/core.oam.dev/v1beta1/workflow_step_definition.go
charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
charts/vela-core/crds/core.oam.dev_policydefinitions.yaml
charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
charts/vela-core/crds/core.oam.dev_workflowstepdefinitions.yaml
charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_definitionrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_policydefinitions.yaml
charts/vela-minimal/crds/core.oam.dev_traitdefinitions.yaml
charts/vela-minimal/crds/core.oam.dev_workflowstepdefinitions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_policydefinitions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_workflowstepdefinitions.yaml
pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go
pkg/controller/core.oam.dev/v1alpha2/core/requirement.go
pkg/controller/core.oam.dev/v1alpha2/core/revison.go
pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
pkg/controller/utils/utils.go

1. Remove `RefreshPackageDiscover`, this is an unuseful code.
2. Merge similar code.
I have:

Feat: optimize the definition controllers

---

charts/vela-core/templates/defwithtemplate/container-image.yaml
charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/container-image.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
go.mod
go.sum
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
vela-templates/definitions/internal/trait/container-image.cue
vela-templates/definitions/internal/workflowstep/notification.cue

Update cue version to fix panic in def.
Ref: cue-lang/cue#1829
I have:

Chore: update cue version to fix panic in def

---

apis/core.oam.dev/v1beta1/core_types.go
charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_definitionrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_traitdefinitions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/controller/core.oam.dev/v1alpha2/application/revision.go
pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go

Remove SkipRevisionAffect in TraitDefinition.
I have:

Feat: remove skip revision affect

---

pkg/resourcekeeper/gc.go
pkg/resourcekeeper/gc_suite_test.go
pkg/resourcekeeper/utils.go
pkg/utils/k8s.go
pkg/utils/k8s_test.go

Backport #4769 to release-1.5.
I have:

[Backport 1.5] Fix: gc legacy rt with regularization

---

references/cli/top/model/cluster.go
references/cli/top/view/cluster_namespace_view.go
references/cli/top/view/cluster_view.go
references/cli/top/view/managed_resource_view.go

Signed-off-by: HanMengnan <1448189829@qq.com>
Fixes #4770
I have:

Fix: fix the bug that the empty row exists in cluster view in `vela  top`

---

charts/vela-core/templates/defwithtemplate/daemon.yaml
charts/vela-core/templates/defwithtemplate/deploy2runtime.yaml
charts/vela-core/templates/defwithtemplate/storage.yaml
charts/vela-core/templates/defwithtemplate/task.yaml
charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-core/templates/defwithtemplate/worker.yaml
charts/vela-minimal/templates/defwithtemplate/daemon.yaml
charts/vela-minimal/templates/defwithtemplate/deploy2runtime.yaml
charts/vela-minimal/templates/defwithtemplate/storage.yaml
charts/vela-minimal/templates/defwithtemplate/task.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/worker.yaml
vela-templates/definitions/internal/component/daemon.cue
vela-templates/definitions/internal/component/task.cue
vela-templates/definitions/internal/component/webservice.cue
vela-templates/definitions/internal/component/worker.cue
vela-templates/definitions/internal/trait/storage.cue
vela-templates/definitions/internal/workflowstep/deploy2runtime.cue

Revert the definitions after cue upgrade to make them compatible.
Ref: cue-lang/cue#1838
I have:

Chore: revert the definitions after cue upgrade

---

pkg/utils/common/common.go

Fix: add path clean for request

---

pkg/apiserver/interfaces/api/user.go

Fix: interface updateUser missing read body

---

pkg/stdlib/pkgs/query.cue
pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/endpoint_test.go
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/handler_test.go
pkg/velaql/providers/query/types/type.go

Feat: add port name to CollectServiceEndpoints

---

pkg/stdlib/pkgs/query.cue
pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/endpoint_test.go
pkg/velaql/providers/query/handler.go
pkg/velaql/providers/query/handler_test.go
pkg/velaql/providers/query/types/type.go

Cherry-pick #4801 to release-1.5.
I have:

[Backport release-1.5] Feat: add port name to CollectServiceEndpoints

---

charts/vela-core/templates/defwithtemplate/init-container.yaml
charts/vela-minimal/templates/defwithtemplate/init-container.yaml
vela-templates/definitions/internal/trait/init-container.cue

Feat: add image-pull-policy to init-container

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go

Fixes #
I have:
feature or configuration option, an update to the documentation is necessary.

Chore: simplify enqueueing app reconcile request for rt

---

charts/vela-core/templates/defwithtemplate/collect-service-endpoints.yaml
charts/vela-minimal/templates/defwithtemplate/collect-service-endpoints.yaml
vela-templates/definitions/internal/workflowstep/collect-service-endpoints.cue

Feat: enhance collect service endpoints

---

references/cli/debug.go

Fix: fix render fields in debug command
I have:

Fix: fix render fields in debug command

---

pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go
pkg/oam/util/helper_test.go

Signed-off-by: Diego Pinheiro <diego.milhomes@gmail.com>
Fixes #
I have:

Fix: test typo 

---

apis/core.oam.dev/common/types.go
apis/core.oam.dev/v1beta1/core_types.go
charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_definitionrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_traitdefinitions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/controller/core.oam.dev/v1alpha2/application/apply.go
pkg/controller/core.oam.dev/v1alpha2/application/dispatcher.go
pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/controller/core.oam.dev/v1alpha2/application/testdata/definitions/storage-pre-dispatch-unhealthy.yaml
pkg/controller/core.oam.dev/v1alpha2/application/testdata/definitions/storage-pre-dispatch.yaml
pkg/features/controller_features.go

Signed-off-by: ZhongsJie <zhongsjie@cmbchina.com>
Fixes #4143 
Fixes #3888 
I have:

Feat: provide Stage field for TraitDefinition

---

pkg/addon/render.go
pkg/addon/render_test.go

Fix issues of  a cue file reference a value of another cue file should announce the value in this file. 
Fixes #
I have:

Fix: fix addon render cue template cross-file reference bug

---

charts/vela-core/templates/defwithtemplate/gateway.yaml
charts/vela-minimal/templates/defwithtemplate/gateway.yaml
vela-templates/definitions/internal/trait/gateway.cue

Chore: add IP for gateway trait

---

.github/workflows/release.yml

Fixes #4822
I have:
Tested in my own repo: https://github.com/wonderflow/kubevela/releases/tag/v1.0.102

Fix: align sha256sums file with binary name

---

references/cli/status.go

Chore: omit empty message in workflow step status

---

references/cli/workflow.go

When application is running, we can't operate the workflow because it's finished. So we must prevent these action in cause unexpected behavior.
Only rollback is allowed.
I have:
I've tested it locally

Feat: prevent restart/resume/suspend/terminate workflow when application running

---

test/e2e-multicluster-test/multicluster_test.go

Chore: fix flaky multicluster test

---

pkg/velaql/providers/query/tree.go

Fixes https://github.com/kubevela/catalog/issues/487
I have:
I create a kustomize app from nginx directory in https://gitee.com/chengleqi/argocd-example-apps repo.
And the Resource Graph is below:

Feat: add Resource Relationships for kustomize

---

pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/tree_test.go

Fix: change LabelResourceRuleFormat from Annotations to Labels

---

pkg/apiserver/utils/ui_schema.go

The default action can be empty, but it reports error in this case.
I have:

Fix: support default value of ui schema

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go

In KubeVela v1.6, when workflow finished, it will fill the EndTime to the status of the application. Previously, this will be done every time we reached the end of workflow. It will let the application continuously update the end time of workflow even if workflow does not run anymore, for example, state-keeping or garbage-collecting. This PR fixes it.
I have:

Fix: workflow end time refill

---

pkg/controller/core.oam.dev/v1alpha2/application/revision.go
pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go

[Backport release-1.5] Fix: #4865 introduces future dependencies

---

charts/vela-core/templates/defwithtemplate/daemon.yaml
charts/vela-core/templates/defwithtemplate/webservice.yaml
charts/vela-core/templates/defwithtemplate/worker.yaml
charts/vela-minimal/templates/defwithtemplate/daemon.yaml
charts/vela-minimal/templates/defwithtemplate/webservice.yaml
charts/vela-minimal/templates/defwithtemplate/worker.yaml
vela-templates/definitions/internal/component/daemon.cue
vela-templates/definitions/internal/component/webservice.cue
vela-templates/definitions/internal/component/worker.cue

Fix: fix array in definition
I have:
/cc @Somefive

Fix: fix array in definition

---

pkg/stdlib/pkgs/util.cue
references/cli/cli.go
references/cli/logs.go

Support step logs in vela logs, you can use `vela logs example-app -s my-step` to see the logs of the workflow step.
I have:

Feat: support step logs in vela logs

---

go.mod
go.sum
pkg/cue/definition/template.go
pkg/cue/process/handle_test.go
pkg/velaql/context.go

Chore: upgrade workflow vendor version

---

docs/apidoc/swagger.json
pkg/apiserver/domain/model/context.go
pkg/apiserver/domain/service/pipeline.go
pkg/apiserver/domain/service/service.go
pkg/apiserver/interfaces/api/dto/v1/types.go
pkg/apiserver/interfaces/api/interfaces.go
pkg/apiserver/interfaces/api/interfaces_test.go
pkg/apiserver/interfaces/api/pipeline.go
pkg/apiserver/utils/bcode/017_pipeline.go

Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>### Description of your changes
Fixes #
I have:

Feat: pipeline API for apiserver

---

charts/vela-core/templates/defwithtemplate/delete-config.yaml
charts/vela-core/templates/defwithtemplate/read-config.yaml
charts/vela-minimal/templates/defwithtemplate/delete-config.yaml
charts/vela-minimal/templates/defwithtemplate/read-config.yaml
go.mod
go.sum
pkg/stdlib/pkgs/config.cue
test/e2e-test/config_workflow_test.go
vela-templates/definitions/internal/workflowstep/delete-config.cue
vela-templates/definitions/internal/workflowstep/read-config.cue

Fix: upgrade the workflow to support the provider about the config

---

pkg/appfile/appfile.go
pkg/cue/definition/template.go
pkg/cue/definition/template_test.go

Feat: support parameter in health check of definition

---

pkg/apiserver/domain/service/oam_application.go
pkg/apiserver/domain/service/oam_application_test.go
pkg/apiserver/domain/service/testdata/dryrun-app.yaml
pkg/apiserver/interfaces/api/oam_application.go
test/e2e-apiserver-test/oam_application_test.go
test/e2e-apiserver-test/testdata/dryrun-app.yaml

support dryrun operation when creating or updating applications in the specified namespace
Fixes #
I have:

Feat: support dryrun operation when creating or updating applications

---

pkg/utils/common/common.go
pkg/utils/common/common_test.go
references/cli/debug.go
references/cli/logs.go
references/cli/print.go
references/cli/workflow.go

Example:
```
vela workflow logs <name>
```
I have:

Feat: remove workflow step logs to vela workflow logs

---

references/cli/top/config/color.go
references/cli/top/model/application.go
references/cli/top/model/container.go
references/cli/top/model/container_test.go
references/cli/top/model/managed_resource.go
references/cli/top/model/type.go
references/cli/top/view/container_view.go
references/cli/top/view/container_view_test.go
references/cli/top/view/help_view_test.go
references/cli/top/view/managed_resource_view.go
references/cli/top/view/managed_resource_view_test.go
references/cli/top/view/pod_view.go
references/cli/top/view/pod_view_test.go
references/cli/top/view/resource_view.go

Feat: add the container view to `vela top`

---

makefiles/dependency.mk

Chore: change the package name of the readme-generator-for-helm

---

charts/vela-core/templates/defwithtemplate/gateway.yaml
charts/vela-minimal/templates/defwithtemplate/gateway.yaml
vela-templates/definitions/internal/trait/gateway.cue

Fix gateway compatibility for legacy networking API. 
Fixes #
I have:
Test on 1.21 K8s. (Test with `context.clusterVersion.minor < 22`)
ref [API change PR](https://github.com/kubernetes/kubernetes/pull/89778)

Fix: legacy API in gateway trait

---

pkg/apiserver/domain/service/addon.go

To support UI mark the experimental Addon.
I have:

Fix: assign the value for the registry of the addon

---

pkg/stdlib/op.cue
references/cli/status.go

Fix: support sub steps in vela status
I have:

Fix: support sub steps in vela status

---

charts/vela-core/README.md
charts/vela-core/templates/kubevela-controller.yaml
charts/vela-core/values.yaml
docs/examples/multi-stage-component-apply/README.md

Signed-off-by: ZhongsJie <zhongsjie@gmail.com>
Fixes #
I have:

Feat: add feature docs and controller parameters for multiStageComponentApply

---

references/cli/debug.go
references/cli/workflow.go

Fix: add sub step in vela workflow logs
I have:

Fix: add sub step in vela workflow logs

---

apis/core.oam.dev/v1alpha1/applyonce_types.go
charts/vela-core/templates/defwithtemplate/apply-once.yaml
charts/vela-minimal/templates/defwithtemplate/apply-once.yaml
docs/examples/app-with-policy/apply-once-policy/apply-once.md
pkg/controller/core.oam.dev/v1alpha2/application/apply_once_policy_test.go
pkg/resourcekeeper/dispatch.go
pkg/resourcekeeper/statekeep.go
vela-templates/definitions/internal/policy/apply-once.cue

Signed-off-by: 朱晓兵 <596908030@qq.com>
Fixes #4757 
I have:

Feat: enhance the apply-once capability

---

go.mod
go.sum
pkg/apiserver/domain/service/workflow.go
pkg/workflow/operation/operation.go
pkg/workflow/operation/operation_test.go
references/cli/workflow.go
references/cli/workflow_test.go

support operations for workflow run
I have:
cc @wangyikewxgm

Feat: support operations for workflow run

---

charts/vela-core/templates/defwithtemplate/cron-task.yaml
charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/tree_test.go
vela-templates/definitions/internal/component/cron-task.cue

Signed-off-by: HanMengnan <1448189829@qq.com>
Fixes #4914
I have:

Fix: can't get pods of CronTask component 

---

references/cli/utils.go
references/cli/utils_test.go

Fix: get Application status using jsonpath filter expression

---

references/docgen/cluster.go
references/docgen/fix/fix.go
references/docgen/parser.go

Ref cue-lang/cue#2047
I have:
cc @wonderflow

Fix: fix gen doc for container image

---

references/cli/addon-registry.go

Fix: fix use gitlab repo as addon registry

---

references/docgen/def-doc/workflowstep/export2config.eg.md
references/docgen/def-doc/workflowstep/export2secret.eg.md

https://github.com/kubevela/kubevela/discussions/4931
I have:

Fix: update export2config and export2secret example

---

pkg/apiserver/infrastructure/clients/kubeclient.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/multicluster/utils.go
pkg/utils/common/args.go
references/cli/cluster.go
references/cli/status.go
references/cli/velaql.go

Fix: apiserver & vela status use multi-cluster client

---

pkg/apiserver/domain/model/workflow.go
pkg/apiserver/domain/repository/workflow.go
pkg/apiserver/domain/repository/workflow_test.go
pkg/apiserver/domain/service/application_test.go
pkg/apiserver/domain/service/rbac.go
pkg/apiserver/domain/service/workflow.go
pkg/apiserver/domain/service/workflow_test.go
pkg/apiserver/event/sync/convert/convert.go
pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
pkg/apiserver/interfaces/api/assembler/v1/dto2do.go
pkg/apiserver/interfaces/api/dto/v1/types.go

Fixes #
I have:
cc @barnettZQG

Feat: sync the model of api workflow with core

---

pkg/apiserver/domain/service/addon.go

bocde error override origin error message
Fixes #
I have:

Fix: bocde error override origin error message

---

go.mod
go.sum
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/workflow/workflow.go

Chore: stable the version of cue and workflow
I have:

Chore: stable the version of cue and workflow

---

charts/vela-core/templates/kubevela-controller.yaml
pkg/apiserver/domain/service/cloudshell.go
pkg/apiserver/domain/service/cloudshell_test.go
pkg/apiserver/domain/service/project.go
pkg/apiserver/interfaces/api/dto/v1/types.go
pkg/apiserver/utils/auth.go
pkg/auth/privileges.go

Fix: grant the permission to read the ConfigMap in the vela-system namesapce

---

references/cli/workflow.go

Feat: allowing restart a completed workflow
I have:
@wonderflow

Feat: allowing restart a completed workflow

---

pkg/apiserver/domain/service/cloudshell_test.go
pkg/apiserver/domain/service/project.go
pkg/apiserver/domain/service/rbac.go
pkg/apiserver/domain/service/rbac_test.go

Fix: enhance the default permissions

---

.github/workflows/go.yml
go.mod
go.sum

Fix: fix filepath for windows

---

.github/workflows/core-api-test.yml
.github/workflows/sync-api.yml
hack/apis/clientgen.sh
hack/apis/sync.sh

Feat: add build check for generate kubevela-core-api

---

.github/workflows/go.yml

Fix: test ci windows

---

docs/apidoc/swagger.json
references/cli/config.go

Chore: update the API schema

---

references/cli/ls.go
references/cli/ls_test.go

support label selector filter for 'vela ls'
Fixes #
I have:

Feat:  support label selector filter for 'vela ls'

---

makefiles/e2e.mk

mock server duplicate
Fixes #
I have:

Fix: remove duplicate mock server in CI

---

pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/endpoint_test.go

`vela status` sometimes print internal IP even if there are external IP for nodes in cluster.
This also have an impact when deploy add-on VelaUX and influence the first-time installation experience.
Fix this by always printing the node's external IP if there are any.
Fixes #
I have:

Fix: vela status will always get external ip first

---

apis/types/types.go
charts/vela-core/templates/defwithtemplate/apply-application-in-parallel.yaml
charts/vela-core/templates/defwithtemplate/apply-application.yaml
charts/vela-core/templates/defwithtemplate/apply-remaining.yaml
charts/vela-core/templates/defwithtemplate/deploy-cloud-resource.yaml
charts/vela-core/templates/defwithtemplate/deploy.yaml
charts/vela-core/templates/defwithtemplate/deploy2env.yaml
charts/vela-core/templates/defwithtemplate/deploy2runtime.yaml
charts/vela-core/templates/defwithtemplate/share-cloud-resource.yaml
charts/vela-minimal/templates/defwithtemplate/apply-application-in-parallel.yaml
charts/vela-minimal/templates/defwithtemplate/apply-application.yaml
charts/vela-minimal/templates/defwithtemplate/apply-remaining.yaml
charts/vela-minimal/templates/defwithtemplate/deploy-cloud-resource.yaml
charts/vela-minimal/templates/defwithtemplate/deploy.yaml
charts/vela-minimal/templates/defwithtemplate/deploy2runtime.yaml
charts/vela-minimal/templates/defwithtemplate/share-cloud-resource.yaml
pkg/apiserver/domain/service/definition.go
pkg/apiserver/domain/service/definition_test.go
pkg/apiserver/domain/service/testdata/applyapplication-sd.yaml
pkg/apiserver/interfaces/api/definition.go
vela-templates/definitions/internal/workflowstep/apply-application-in-parallel.cue
vela-templates/definitions/internal/workflowstep/apply-application.cue
vela-templates/definitions/internal/workflowstep/apply-remaining.cue
vela-templates/definitions/internal/workflowstep/deploy-cloud-resource.cue
vela-templates/definitions/internal/workflowstep/deploy.cue
vela-templates/definitions/internal/workflowstep/deploy2env.cue
vela-templates/definitions/internal/workflowstep/deploy2runtime.cue
vela-templates/definitions/internal/workflowstep/share-cloud-resource.cue

add scope label in workflow step defs
I have:
cc @barnettZQG

Feat: add scope label in workflow step defs

---

go.mod
go.sum
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go

Fix: temporary fix comments in comprehesions for env trait

---

references/cli/install.go

Fix: higher version contraint(k8s 1.19-1.24) in install command

---

pkg/utils/k8s.go
pkg/utils/k8s_test.go
references/cli/ls.go
references/cli/ls_test.go

support field selector filter for 'vela ls'
Fixes #
I have:

Feat: support field selector filter for 'vela ls'

---

pkg/addon/addon.go
pkg/addon/addon_test.go
pkg/addon/helper.go

Chore: remove legacy o11y logic

---

references/docgen/def-doc/trait/cpuscaler.eg.md

Signed-off-by: yanru.lv <yanru.lv@daocloud.io>
/kind Docs
cpuscaler traits documentation example modify
Fixes #5060
I have:

Docs: cpuscaler traits documentation example

---

go.mod
go.sum
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
references/cli/status.go

Fix: fix fill array with array in inputs

---

pkg/utils/k8s.go

Fix: remove unnecessary case in field selector

---

pkg/resourcekeeper/statekeep_suite_test.go

Chore: update test case and remove unnecessary info

---

charts/vela-core/templates/defwithtemplate/print-message-in-status.yaml
charts/vela-minimal/templates/defwithtemplate/print-message-in-status.yaml
references/docgen/def-doc/workflowstep/print-message-in-status.eg.md
vela-templates/definitions/internal/workflowstep/print-message-in-status.cue

Feat: add print message example

---

pkg/apiserver/domain/model/application.go
pkg/apiserver/domain/service/application.go
pkg/apiserver/domain/service/webhook.go
pkg/apiserver/domain/service/webhook_test.go
pkg/apiserver/interfaces/api/dto/v1/types.go

Fixes #5089
I have:
@barnettZQG

Fix: fix acr webhook for enterprise registry

---

design/README.md
design/TEMPLATE.md

Docs: add KEPs introduction to the main repo

---

cmd/apiserver/app/options/options.go
cmd/apiserver/app/options/validation.go
cmd/apiserver/app/server.go
pkg/apiserver/config/config.go

refer to [kubesphere api server](https://github.com/kubesphere/kubesphere/blob/master/cmd/ks-apiserver/apiserver.go#L25-L32) and [kubevea plugin](https://github.com/kubevela/kubevela/blob/master/cmd/plugin/main.go#27-L35)
Use github.com/spf13/cobra to execute cmd.
Fixes #
I have:

Refactor: Use github.com/spf13/cobra to execute cmd for apiserver

---

.github/workflows/apiserver-test.yml
.github/workflows/back-port.yml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/issue-commands.yml
.github/workflows/registry.yml
.github/workflows/release.yml
.github/workflows/unit-test.yml

Signed-off-by: basefas <basefas@hotmail.com>
action: zeebe-io/backport-action released yesterday, so update it.
Also update some missed action.
zeebe-io/backport-action@v0.0.8 to zeebe-io/backport-action@v0.0.9
nolar/setup-k3d-k3s@v1.0.8 to nolar/setup-k3d-k3s@v1.0.9
supercharge/mongodb-github-action@1.7.0 to supercharge/mongodb-github-action@1.8.0
set continue-on-error: true to steps

Fix: update actions

---

pkg/component/ref_objects.go
pkg/component/ref_objects_suite_test.go

Fix: ref-objects should clear namespace field when referring cluster-scoped resource

---

.github/workflows/go.yml
Dockerfile.apiserver

Fixes https://github.com/kubevela/kubevela/actions/runs/3537032744/jobs/5936644544
I have:

Fix: apiserver image build and add CI check for it

---

.github/workflows/definition-lint.yml
hack/docgen/def/gen.go
hack/docgen/def/mods/component.go
hack/docgen/def/mods/policy.go
hack/docgen/def/mods/trait.go
hack/docgen/def/mods/types.go
hack/docgen/def/mods/workflow.go
references/docgen/def-doc/policy/health.eg.md
references/docgen/def-doc/trait/affinity.eg.md
references/docgen/def-doc/trait/json-merge-patch.eg.md
references/docgen/def-doc/trait/json-patch.eg.md
references/docgen/def-doc/trait/topologyspreadconstraints.eg.md
references/docgen/def-doc/workflowstep/create-config.eg.md
references/docgen/def-doc/workflowstep/delete-config.eg.md
references/docgen/def-doc/workflowstep/deploy-cloud-resource.eg.md
references/docgen/def-doc/workflowstep/generate-jdbc-connection.eg.md
references/docgen/def-doc/workflowstep/list-config.eg.md
references/docgen/def-doc/workflowstep/read-config.eg.md
references/docgen/def-doc/workflowstep/share-cloud-resource.eg.md
references/docgen/markdown.go

Add a force CI check for definition doc example.
I have:

Chore: add definition example doc CI check

---

.github/CODEOWNERS

Fix: add fogdong to codeowners of packages

---

charts/vela-core/templates/defwithtemplate/container-image.yaml
charts/vela-minimal/templates/defwithtemplate/container-image.yaml
vela-templates/definitions/internal/trait/container-image.cue

Align `container-image` with `env`, `command`.
I have:

Fix: container image cue

---

pkg/velaql/providers/query/endpoint.go
pkg/velaql/providers/query/endpoint_test.go
pkg/velaql/providers/query/handler_test.go
references/cli/status.go

Fix: vela status --endpoint show no IP when only one master node

---

references/docgen/def-doc/workflowstep/apply-object.eg.md

Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>

Fix: doc format error

---

go.mod
go.sum
pkg/apiserver/domain/service/pipeline.go

Fix: update the workflow vendor and delete mode in workflow spec

---

references/cli/def.go

Feat: support huawei cloud terraform generation

---

pkg/utils/k8s.go

Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>### Description of your changes
This is a hotfix of https://github.com/kubevela/kubevela/issues/5140.
Fixes https://github.com/kubevela/kubevela/issues/5140
I have:

Fix: fail to get logs from pod of remote clusters 

---

pkg/addon/helper.go
pkg/addon/helper_test.go
references/cli/addon.go
references/cli/addon_suite_test.go
references/cli/addon_test.go

In this pr, I've added the value options if the field is an enum string. This could be very helpful.
I have:

Feat: add options for addon parameter

---

pkg/utils/common/common.go
pkg/velaql/providers/query/collector.go
references/cli/velaql.go
test/e2e-multicluster-test/multicluster_cli_test.go
test/e2e-multicluster-test/testdata/view/component-pod-view.yaml

1. Added a test for `vela logs` in a multicluster scenario.
2. Modified the `--cluster` argument to work properly by making changes to the VelaQL parsing.
Fixes #5162 
I have:

Feat: add multicluster test for vela logs

---

pkg/controller/standard.oam.dev/v1alpha1/rollout/utils.go
runtime/rollout/charts/templates/vela-runtime-rollout.yaml

Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>
add some error logs
There is wrong with RBAC about statefulsets.
We need to modify the helm chart `vela-rollout`.
Fixes #5148 
I have:

Feat: rollout support statefulsets

---

pkg/apiserver/config/config.go
pkg/apiserver/domain/model/model.go
pkg/apiserver/domain/service/pipeline.go
pkg/apiserver/domain/service/service.go

Fix: add controller version for pipeline in velaux

---

.github/workflows/back-port.yml
.github/workflows/chart.yml
.github/workflows/codeql-analysis.yml
.github/workflows/commit-lint.yml
.github/workflows/core-api-test.yml
.github/workflows/definition-lint.yml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/issue-commands.yml
.github/workflows/license.yml
.github/workflows/registry.yml
.github/workflows/sync-api.yml
.github/workflows/timed-task.yml
.github/workflows/trivy-scan.yml
.github/workflows/unit-test.yml

Fix: limit github action permission

---

.github/workflows/registry.yml

Fix: registry permission failed for build-addon-image

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/cue/definition/template.go

Let health check first check the resource with the name of the context. If not found, fall back to label selection.
I have:

Feat: change health check resource fetch order

---

.github/workflows/apiserver-test.yml
.github/workflows/back-port.yml
.github/workflows/chart.yml
.github/workflows/codeql-analysis.yml
.github/workflows/core-api-test.yml
.github/workflows/definition-lint.yml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/issue-commands.yml
.github/workflows/license.yml
.github/workflows/registry.yml
.github/workflows/release.yml
.github/workflows/scorecards.yml
.github/workflows/sync-api.yml
.github/workflows/timed-task.yml
.github/workflows/trivy-scan.yml
.github/workflows/unit-test.yml

Chore: enhance workflow with specific git commit id

---

.github/workflows/apiserver-test.yml
.github/workflows/codeql-analysis.yml
.github/workflows/core-api-test.yml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/registry.yml
.github/workflows/release.yml
.github/workflows/scorecards.yml
.github/workflows/unit-test.yml
Dockerfile
Dockerfile.apiserver
Dockerfile.cli
Dockerfile.e2e
makefiles/dependency.mk
runtime/rollout/Dockerfile
runtime/rollout/e2e/Dockerfile.e2e

remove useless action and makefile steps
Fixes #
I have:

Fix: pin dependencies to hash

---

charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-core/crds/core.oam.dev_applications.yaml
charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_applications.yaml
go.mod
go.sum
legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
pkg/velaql/context.go
pkg/webhook/core.oam.dev/v1alpha2/application/mutating_handler.go
pkg/webhook/core.oam.dev/v1alpha2/application/mutating_handler_test.go
pkg/workflow/operation/operation.go
pkg/workflow/operation/operation_test.go
references/cli/workflow.go
test/e2e-multicluster-test/multicluster_test.go

Update workflow version to add restart from step and fix bugs.
This PR:
* Add step name-generator in mutating webhook.
* Add restart from a specified step in cli.
* Fixes #5178
Fixes
I have:

Chore: update workflow version to add restart from step and fix bugs

---

references/cli/top/component/crumbs.go
references/cli/top/model/pod.go
references/cli/top/model/pod_test.go
references/cli/top/view/app.go
references/cli/top/view/application_view.go
references/cli/top/view/help_view.go
references/cli/top/view/managed_resource_view.go
references/cli/top/view/pod_view.go
references/cli/top/view/pod_view_test.go

Fix: remove cluster field from pod view in vela top and optimize some ui

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-disconnection-test.yaml

Manually cherry-pick #5240 to release-1.6.

[Backport release-1.6] Fix: gc failure cause workflow restart not working properly

---

.github/workflows/release.yml

Fix: add permission for release ci

---

pkg/apiserver/interfaces/api/project.go

Correct update project user api's doc description
I have:
no tests needed

Docs: correct update project user api's doc description

---

test/e2e-test/definition_test.go

The E2E test `Test notification step definition` in `definition_test.go` fails when it is run on a cluster where it has already run.
The problem is that it creates resources in the `default` namespace instead of in the namespace created for the test case. The resources in `default` do not get cleaned up when the test finishes, so subsequent test executions fail.
I have:
I tested by:
1) Setting up the code without the fix
2) Running `make e2e-test` once
3) Observing the `noti` and `noti-secret` Applications and the `my-secret` Secret still present in the `default` namespace after the tests have finished.
4) Running `make e2e-test` again and seeing the test fail
5) Manually removing the Applications and Secret from the `default` namespace.
6) Applying the fix in this PR.
7) Ran `make …

Test: prevent notification step definition test from failing when re-run.

---

.github/workflows/apiserver-test.yaml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/timed-task.yml
Makefile
makefiles/e2e.mk
pkg/addon/helper_test.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
references/cli/addon_suite_test.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-disconnection-test.yaml

Manually cherry-pick #5240 to release-1.4.

[Backport release-1.4] Fix: gc failure cause workflow restart not working properly

---

go.mod
go.sum
pkg/apiserver/domain/service/pipeline.go

Fixes
* HTTP client optimization.
* Workflow status bug caused by invalid inputs.
I have:
cc @barnettZQG

Chore: update workflow vendor to fix certain bugs in 1.6

---

.github/workflows/apiserver-test.yaml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/timed-task.yml
pkg/addon/helper_test.go
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
references/cli/addon_suite_test.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-disconnection-test.yaml

Manually cherry-pick #5240 to release-1.5.

[Backport release-1.5] Fix: gc failure cause workflow restart not working properly

---

.github/bot.md

Signed-off-by: aimuz <mr.imuz@gmail.com>
Fixes #
I have:

Chore: update broken link of bot.md

---

pkg/addon/addon.go

Fix: move notes to the right to avoid package head to be invalid format

---

hack/utils/installdefinition.sh

Chore: update makefile with velaql in make def-install

---

references/cli/debug.go
references/cli/workflow.go

Fix: fix vela debug cli to find id for step

---

.github/workflows/issue-commands.yml

Fix: fix backport command action caused by upgrades

---

pkg/apiserver/domain/service/config.go
pkg/apiserver/utils/bcode/016_config.go
pkg/config/factory.go
pkg/config/factory_test.go
test/e2e-apiserver-test/config_test.go

Fix: create a config with the same name reported an incorrect error

---

references/cli/uninstall.go

Signed-off-by: bitliu <bitliu@tencent.com>

Fix: error msg when uninstall vela

---

.github/workflows/issue-commands.yml

Fix: fix permissions for backport in commands

---

pkg/apiserver/domain/service/application.go
pkg/apiserver/server.go
pkg/appfile/dryrun/dryrun.go
pkg/velaql/providers/query/handler.go

Fix: the developer user can't load the definition

---

pkg/apiserver/domain/service/workflow.go
pkg/apiserver/event/sync/convert.go

Fix: maintain compatibility with old project data

---

go.mod
go.sum

Please checkout the [Workflow v0.4.0 release note](https://github.com/kubevela/workflow/releases/tag/v0.4.0) for details.
I have:

Feat: upgrade the workflow version to v0.4.0

---

cmd/core/app/options/options.go
cmd/core/app/server.go
pkg/utils/system/system.go

Feat: remove useless storage driver

---

README.md

Docs: fix README.md ad-hoc

---

.github/workflows/definition-lint.yml
hack/docgen/def/gen.go
hack/docgen/def/mods/component.go
hack/docgen/def/mods/policy.go
hack/docgen/def/mods/trait.go
hack/docgen/def/mods/types.go
hack/docgen/def/mods/workflow.go
references/cli/show.go
references/docgen/cluster.go
references/docgen/console.go
references/docgen/i18n.go
references/docgen/markdown.go
references/docgen/markdown_test.go
references/docgen/parser.go
references/docgen/vars.go

Feat: add workflow step scope in doc gen

---

charts/vela-core/README.md
charts/vela-core/values.yaml
charts/vela-minimal/README.md
charts/vela-minimal/values.yaml

Feat: upgrade cluster gateway to 1.7.0

---

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/cue/definition/template.go
pkg/cue/definition/template_test.go
pkg/workflow/workflow.go

…form
Fix: fix panic if trait tries to patch an invalid workload like terraform
I have:
@wonderflow

Fix: fix panic if trait tries to patch an invalid workload like terraform

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml

This PR introduce goreleaser too KubeVela's CLI and kubectl plugin release process. Goreleaser will take care of these things which is done by script in GitHub Action.
1. Build artifacts
2. Archive the binary and other file needed.
3. Upload all archives and `sha256sums.txt` to GitHub release page.
Add windows/arm64 artifacts
Fixes #5347
I have:
The whole process may influence several things:
```shell
curl -fsSl https://static.kubevela.net/script/install.sh | bash -s 1.7.0-d1
```

Fix: replace homemade release script with goreleaser

---

pkg/apiserver/domain/service/application.go
pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/tree_test.go

Feat: add the func of additionalInfo for workload

---

.github/workflows/apiserver-test.yml

Fix: rework on apisrever e2e test covergae

---

cmd/core/app/options/options.go
pkg/config/factory.go
pkg/config/provider/provider.go
pkg/config/provider/provider_test.go
pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/utils/apply/apply.go
pkg/utils/apply/apply_test.go
references/cli/delete.go

This PR migrate the config provider package from workflow to kubevela.
I have:

Fix: aligin config create to be managed by apps with Dispatch function

---

docs/apidoc/swagger.json
pkg/apiserver/domain/service/application.go
pkg/apiserver/domain/service/application_test.go
pkg/apiserver/domain/service/webhook_test.go
pkg/apiserver/domain/service/workflow_test.go
pkg/apiserver/interfaces/api/application.go
pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
pkg/apiserver/interfaces/api/dto/v1/types.go
test/e2e-apiserver-test/application_test.go

Feat: add the updating the application trigger API

---

cmd/core/app/options/options.go
pkg/config/factory.go
pkg/config/provider/provider.go
pkg/config/provider/provider_test.go
pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/utils/apply/apply.go
pkg/utils/apply/apply_test.go
references/cli/delete.go

cherry-pick from (#5384)
Fixes #
I have:

Fix: aligin config create to be managed by apps with Dispatch function - cherry-pick from (#5384)

---

.github/workflows/release.yml

Fixes #
Avoid release timeout situation like https://github.com/kubevela/kubevela/actions/runs/4054293492/jobs/6975948757
I have:

Fix: longer releaser timeout

---

pkg/apiserver/event/sync/convert.go
pkg/apiserver/event/sync/cr2ux_test.go
pkg/apiserver/event/sync/testdata/test-app5.yaml

Specify the env of a project to take over the application, the app project should be the project to which env belongs.
Fixes #5352 
I have:

Fix: sync project from app crd to velaux

---

e2e/addon/addon_test.go
references/cli/addon.go

cherry pick 5404 to 1.6 
Fixes #
I have:

Fix: cherry pick 5404 to 1.6 

---

Dockerfile
Dockerfile.apiserver
Dockerfile.cli
Dockerfile.e2e
runtime/rollout/Dockerfile
runtime/rollout/e2e/Dockerfile.e2e

Signed-off-by: fengshunli <1171313930@qq.com>
Fixes #
I have:

Fix: update CVE-2022-3996 vuln

---

go.mod
go.sum

Chore: update cue to v0.5.0-beta.5
I have:

Chore: update cue to v0.5.0-beta.5

---

charts/vela-core/templates/defwithtemplate/deploy.yaml
charts/vela-minimal/templates/defwithtemplate/deploy.yaml
pkg/appfile/appfile.go
pkg/appfile/parser.go
pkg/appfile/template.go
pkg/appfile/unit_test.go
pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/stdlib/pkgs/multicluster.cue
pkg/workflow/providers/multicluster/deploy.go
pkg/workflow/providers/multicluster/multicluster.go
vela-templates/definitions/internal/workflowstep/deploy.cue

Add deploy inline policy and support loading definitions when lack in the revision.
I have:

Feat: add deploy inline policy

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file
I have:

Chore: Create dependabot.yml for security package management

---

go.mod
go.sum
references/docgen/def-doc/workflowstep/notification.eg.md

dingding-notification message.text.content
Fixes #
https://github.com/kubevela/kubevela.io/pull/1145
I have:
@wonderflow

Fix: dingding notification message.text.content

---

charts/vela-core/templates/defwithtemplate/notification.yaml
charts/vela-minimal/templates/defwithtemplate/notification.yaml
vela-templates/definitions/internal/workflowstep/notification.cue

1. Simplify patterns like 
```cue
foo?: *null | ...
```
2. Remove `close()` call to array object.
Fixes #
I have:

Fix: simplify notification parameters

---

README.md

Chore: refine readme with more featrues

---

references/cli/top.go

Fix: suppress klog logs output for vela top

---

.github/workflows/release.yml

stop sending update to brew and krew if alpha or beta version
Fixes #5449
I have:
Not contains alpha/beta:
https://github.com/chivalryq/kubevela/actions/runs/4121672740
contains alpha/beta:
https://github.com/chivalryq/kubevela/actions/runs/4121660237

Fix: stop sending update to brew and krew if alpha version

---

charts/vela-core/templates/defwithtemplate/expose.yaml
charts/vela-minimal/templates/defwithtemplate/expose.yaml
vela-templates/definitions/internal/trait/expose.cue

Fix: expose trait load balance cue check bug

---

charts/vela-core/templates/defwithtemplate/expose.yaml
charts/vela-minimal/templates/defwithtemplate/expose.yaml
references/cli/adopt.go
vela-templates/definitions/internal/trait/expose.cue

1. Fix cue template issue when expose LoadBalancer with empty ingress returned.
2. Enhance vela adopt and fix empty namespace issue when adopt template does not set correct app name & ns.
I have:

Feat: enhance expose trait and adopt

---

go.mod
go.sum

update cue version to v0.5.0-beta.5 to fix certain bugs in the old version like:
```
repoMessage: 2 errors in empty disjunction: (and 2 more errors)
```
I have:

Chore: update cue version to v0.5.0-beta.5 to fix certain bugs in the old version

---

charts/vela-core/templates/defwithtemplate/apply-terraform-provider.yaml
charts/vela-core/templates/defwithtemplate/container-image.yaml
charts/vela-minimal/templates/defwithtemplate/apply-terraform-provider.yaml
charts/vela-minimal/templates/defwithtemplate/container-image.yaml
vela-templates/definitions/internal/trait/container-image.cue
vela-templates/definitions/internal/workflowstep/apply-terraform-provider.cue

Fix definitions as preparation for SDK generating. https://github.com/kubevela/kubevela/pull/5431/files/96a08d1c9c84e07f64c955df1d2041c1723ec344#r1103927486
Fixes #
I have:

Fix: apply-terraform-provider and container-image definition

---

cmd/core/app/server.go

Fix: pprof addr checked before parsed

---

pkg/apiserver/domain/service/cluster.go
pkg/apiserver/domain/service/cluster_test.go

Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>
Fixes #5467 
I have:

Fix: delete the secret of the cluster

---

charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml

Feat: expose cluster gateway metrics

---

README.md

Signed-off-by: frank-zsy <syzhao1988@126.com>
Add contribution leaderboard badge to README.
I have:
No need

docs: add leaderboard badge

---

charts/vela-core/templates/defwithtemplate/suspend.yaml
charts/vela-minimal/templates/defwithtemplate/suspend.yaml
go.mod
go.sum
pkg/apiserver/domain/service/workflow_test.go
pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
pkg/workflow/operation/operation.go
pkg/workflow/template/static/suspend.cue
references/cli/workflow.go
references/cli/workflow_test.go
vela-templates/definitions/internal/workflowstep/suspend.cue

This PR upgrades the workflow version and adds op.#Suspend,  suspending phase in step.
I have:
cc @barnettZQG

Feat: add op.#Suspend and suspending phase in step

---

pkg/apiserver/domain/service/util_test.go

Fix: add test for InterfaceSlice

---

charts/vela-core/README.md
charts/vela-core/values.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
pkg/controller/core.oam.dev/v1alpha2/application/apply.go
pkg/controller/core.oam.dev/v1alpha2/application/generator.go
pkg/controller/core.oam.dev/v1alpha2/application/revision.go

1. Upgrade cluster-gateway to support metrics exposure.
2. Fix incorrect time metrics recording.
I have:

Feat: upgrade cluster-gateway to use v1.8.0-alpha.3

---

pkg/utils/apply/apply.go

Fix: make read-only object not found error more clear

---

hack/apis/sync.sh
hack/sdk/sync.sh

Fix: push tags anyway in new release while syncing api and sdk 

---

Dockerfile

Fixes https://avd.aquasec.com/nvd/2022/cve-2022-4203/
I have:

Fix: cve-2022-4203

---

pkg/velaql/providers/query/tree.go
pkg/velaql/providers/query/tree_test.go

Fix: The resource topology fails to display the pods under the cronjob (#5640)

---

hack/load-test/README.md
hack/load-test/app-templates/heavy.yaml
hack/load-test/app-templates/multicluster.yaml
hack/load-test/app-templates/region.yaml
hack/load-test/bootstrap.sh
hack/load-test/cleanup.sh
hack/load-test/deploy.sh

Add application templates and scripts for load test.
Run `SHARD=3 CLUSTER=2 bash bootstrap.sh`. This will create 3 namespaces `load-test-0`, `load-test-1`, `load-test-2` to local cluster and all managed clusters.
Run `BEGIN=0 SIZE=1000 SHARD=3 WORKER=6 bash deploy.sh` to deploy 1000 application (id from 0 to 1000) to 3 shard in 6 parallel threads.
By default, the deployed apps will use variable `VERSION=1`. You can set this variable to change the version of applications and test version upgrades.
Set `TEMPLATE=heavy` will use the `app-templates/heavy.yaml` as the application template to deploy.
Set `CLUSTER=3` will inject the `CLUSTER` variable to the app template. You can use `TEMPLATE=multicluster` or `TEMPLATE=region` to make multicluster application delivery.
> To make multicluster …

Feat: add load testing app template

---

go.mod
go.sum

Update the workflow in vendor to fix depends on skip: 
* [Fix: fix step depends on skip](https://github.com/kubevela/workflow/commit/59e7c1c967febd07c45e369d50917c2dca5a049f)
I have:

Chore: update workflow version to fix depends on skip

---

go.mod
go.sum

Update workflow version from v0.4.1 to v0.4.3:
Changes are listed below:
* [Backport release-0.4] Fix: fix step depends on skip by @github-actions in https://github.com/kubevela/workflow/pull/147
* Fix: remove patch in apply to make it standalone action and update cue version by @FogDong in https://github.com/kubevela/workflow/pull/135
* [Backport 0.4]Feat: watch event listener in controller for a faster reconcile by @FogDong in https://github.com/kubevela/workflow/pull/144
I have:

Chore: update workflow version in 1.7 to add op.#Patch and fix depends on skip

---

references/cli/adopt.go

Fix: use logs to show errs instead of returning in adopt all
I have:

Fix: use logs to show errs instead of returning in adopt all

---

pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/mutating_handler.go

Fix: Optimize the webhook log format

---

references/cli/adopt-templates/default.cue
references/cli/adopt.go
test/e2e-multicluster-test/multicluster_test.go

1. Use cuex.CompileString for adopt-rules.
2. Remove the appName in the component name. This is designed to avoid duplicated component name across applications. It is relaxed by https://github.com/kubevela/kubevela/pull/5727.
3. Refactor part of the ctx usage. Use cmd.Context to replace context.Background.
I have:

Feat: enhance vela adopt and refactor

---

hack/load-test/README.md
hack/load-test/deploy.sh

Feat: add qps for load test client

---

test/e2e-multicluster-test/multicluster_test.go

Feat: fix flaky multicluster test

---

references/cli/adopt-templates/default.cue
references/cli/adopt.go

Backport #5635 to release-1.8.
I have:

[Backport release-1.8] Feat: vela adopt support multi-cluster adoption #5635

---

references/cli/adopt-templates/default.cue

CUE: fix the adopt-templates/default.cue
closes #5771
Fixes #5771
I have:

 Fix: component name generated by vela adopt is not in lowercase

---

charts/vela-core/templates/defwithtemplate/expose.yaml
charts/vela-minimal/templates/defwithtemplate/expose.yaml
vela-templates/definitions/internal/trait/expose.cue

* update expose trait to support multiple traits and more fields.
* support matchLabels as an optional fields.
I have:

Feat: expose trait with new ports

---

charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-core/crds/core.oam.dev_applications.yaml
charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
charts/vela-minimal/crds/core.oam.dev_applications.yaml
go.mod
go.sum
legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go

Feat: add mode in steps for step group
I have:

Feat: add mode in steps for step group

---

pkg/utils/apply/patch.go
pkg/utils/apply/patch_test.go

Feat: compatible with k8s last-applied-configuration while perfer app.oam.dev/last-applied-configuration in annotations

---

.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-rollout-test.yml
.github/workflows/e2e-test.yml
e2e/application/application_test.go
pkg/velaql/providers/query/tree.go

Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>### Description of your changes
Fixes #5801
I have:

Chore: bump testing to Kubernetes v1.26

---

.github/CODEOWNERS

Chore: update codeowners

---

pkg/config/factory.go
pkg/config/writer/nacos.go
pkg/config/writer/writer.go
pkg/cue/cuex/providers/config/config.cue
pkg/cue/cuex/providers/config/config.go
pkg/cue/script/schema.go
pkg/cue/script/template.go
pkg/cue/script/template_test.go
pkg/utils/common/common.go
pkg/utils/common/common_test.go

Signed-off-by: wuzhongjian wuzhongjian_yewu@cmss.chinamobile.com
support parse template depends on cuex
Fixes #5088 
I have:

Feat: support parse template depends on CueX

---

.github/workflows/issue-commands.yml
.github/workflows/release.yml
charts/vela-core/README.md
charts/vela-core/values.yaml
pkg/cue/cuex/providers/config/config_test.go
pkg/utils/helm/helm_helper_test.go

- Fixes #5821 #5822 
- Bump cluster-gateway
- Refactor config test
I have:

Feat: upgrade deps

---

pkg/appfile/template.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-carrying-deploy-step-with-inline-policy.yaml
test/e2e-multicluster-test/testdata/def/inline-deploy.yaml

Fix: multi cluster inline policy load extra definitions

---

charts/vela-core/README.md
charts/vela-core/templates/defwithtemplate/check-metrics.yaml
charts/vela-minimal/README.md
charts/vela-minimal/templates/defwithtemplate/check-metrics.yaml
go.sum
pkg/appfile/template.go
test/e2e-multicluster-test/multicluster_test.go
test/e2e-multicluster-test/testdata/app/app-carrying-deploy-step-with-inline-policy.yaml
test/e2e-multicluster-test/testdata/def/inline-deploy.yaml
test/e2e-test/health_scope_test.go

[Backport release-1.8] Fix: multi cluster inline policy load extra definitions

---

.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-test.yml

Chore: add e2e ci env bootstrap & remove multlcluster legacy rollout ci 

---

go.mod
go.sum

Fixes security issue
- Docker Swarm encrypted overlay network may be unauthenticated
I have:

Chore: upgrade moby dependency to fix security issue

---

Makefile
pkg/addon/addon_suite_test.go
pkg/addon/init.go
pkg/addon/memory_reader_test.go
pkg/addon/utils.go

Signed-off-by: Xinwei Xiong <3293172751nss@gmail.com>### Description of your changes
Fixes #
I have:
```bash 
Usage:
make [comment]
Comments:
test                           Run tests
test-cli-gen                   Run the unit tests for cli gen
unit-test-core                 Run the unit tests for core
build                          Build vela cli binary
build-cli                      Clean build
vet                            Run go vet against code
staticcheck                    Run the staticcheck
lint                           Run the golangci-lint
build-swagger                  Build the swagger
image-cleanup                  Delete Docker images
image-load                     load docker image to the k3d cluster
image-load-runtime-cluster     Load the run-time cluster image …
```

Chore: Give the help information of Makefile to make it more clear

---

.github/workflows/chart.yml

Fix: cleanup ci for minimal chart

---

references/cli/adopt-templates/default.cue
references/cli/adopt.go
test/e2e-multicluster-test/multicluster_adopt_test.go

Refactor vela adopt multicluster and add e2e test for it.
Fixes #5970
I have:

Fix: multicluster adopt

---

.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-test.yml

Chore: auto prune ci network after test

---

.github/workflows/unit-test.yml
pkg/velaql/providers/query/handler_test.go
references/cli/velaql_test.go

Chore: upgrade kubebuilder installation in unit-test ci

---

.github/workflows/definition-lint.yml
.github/workflows/e2e-multicluster-test.yml
.github/workflows/e2e-test.yml
.github/workflows/go.yml
.github/workflows/unit-test.yml
Makefile
e2e/application/application_test.go
hack/e2e/end_e2e.sh
hack/e2e/end_e2e_core.sh
makefiles/e2e.mk
pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componetrevision_test.go
pkg/utils/common/common_test.go

Feat: revert ci to kind

---

cmd/core/app/options/options.go
cmd/core/app/server.go

Fix duplicate logs and parameter wrong hints.

Chore: Fix duplicate logs and parameter wrong hints.

---

pkg/utils/common/args.go

Cache the DiscoveryClient for cli command.

Chore: Cache the DiscoveryClient for cli command.

---

pkg/utils/common/common.go
pkg/utils/common/common_test.go
references/cli/addon-registry.go
references/cli/addon.go

Fix: remove forbid redirect for http get

---

go.mod
references/cli/top.go

Related issues:
- https://github.com/derailed/k9s/issues/448
- https://github.com/gdamore/tcell/issues/203
- https://github.com/rivo/tview/issues/118
But I'm not sure if this can solve #6076
I have:

Fix: top command abnormal render

---

charts/vela-core/templates/defwithtemplate/gateway.yaml
vela-templates/definitions/internal/trait/gateway.cue

add annotations and labels to gateway.cue and update gateway.yaml by "make reviewable"
fix this issue https://github.com/kubevela/kubevela/issues/6396

Feat: add annotations and labels to gateway.cue

---

pkg/utils/apply/apply.go

Fix a "comma-sytle" bug. I've checked other place to prevent similar bugs.
I have:

Fix: missing comma ok

---

references/cli/workflow_test.go

Unit test "TestWorkflowList" was failing consistently due to no workflow cleanup after the execution of a test case.
Made changes to cleanup the workflow which is being created by the test case.
Fixes #
I have:

Fix: TestWorkflowList unit-test

---

docs/examples/kube-module/kube-worker-cd.yaml
docs/examples/workflow/Li-Auto-Inc/common-definitions.yaml

Fixes #6436
This was tested by using the dry-run feature of vela cli as well as by deploying and checking the status of the apps in these examples to a k3d cluster

Fix(docs): documentation where schematic for component definition refers to kube

---

.github/workflows/chart.yml
.github/workflows/commit-lint.yml
.github/workflows/license.yml
.github/workflows/trivy-scan.yml

fixed the pinned dependencies issue reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/kubevela/kubevela).
Part of #6601 
I have:

Fix: fixed the pinned dependencies issue

---

README.md

Make it possible to deploy KubeVela on Alibaba Cloud in 3 minutes for experimental purposes
I have:
- [-] Added `backport release-x.y` labels to auto-backport this PR if necessary.

Chore: quick deploy button for kubevela

---

.github/workflows/go.yml
.github/workflows/unit-test.yml

Fix build failure due to deprecated actions/cache

Fix: build failure due to deprecated actions/cache

---

.github/workflows/scorecards.yml

Update score card action version from 2.3.1 to 2.4.1
Update score card action version from 2.3.1 to 2.4.1
Fixes #6758
I have:

Chore: Update score card action version

---

pkg/controller/core.oam.dev/v1beta1/application/generator.go
pkg/controller/core.oam.dev/v1beta1/application/generator_test.go

Enhance workflow context generation to include application labels and annotations
This pull request enhances the workflow context generation to include the labels and annotations of the application. This allows developers to access the application's metadata within their CUE actions, enabling more powerful and flexible workflows.
Fixes #6861
I have:
The changes have been tested by adding new unit tests in `pkg/controller/core.oam.dev/v1beta1/application/generator_test.go`. These tests ensure that the application's labels and annotations are correctly added to the workflow context.

Fix: Enhance workflow context generation 
