kubevela/kubevela

- .github/workflows/e2e-multicluster-test.yml
- codecov.yml
- pkg/oam/auxiliary.go
- pkg/oam/labels.go
- pkg/policy/topology.go
- pkg/resourcetracker/tree.go
- pkg/utils/apply/patch.go
- pkg/utils/strings.go
- pkg/workflow/providers/multicluster/multicluster.go
- references/cli/status.go
- test/e2e-multicluster-test/multicluster_cli_test.go
`vela status --tree` shows the hierarchical structure of applied resources.
- It will show all the resources the application currently holds, including outdated ones. (This is done by retrieving all the resources from ResourceTrackers.)
- With the `--detail` option, it will fetch the resources dynamically, and display the detail information of the resources.
- With the `--detail-format` option, it can display resources in several different ways.
Examples
- vela status --tree
- vela status --tree --detail 
- vela status --tree --detail --detail-format=wide
- vela status --tree --detail --detail-format=table
- vela status --tree --detail --detail-format=list
- vela status --tree --detail --detail-format=raw
A large example:
A example of …
> Feat: vela status --tree

- apis/types/multicluster.go
- pkg/multicluster/cluster_management.go
- pkg/multicluster/virtual_cluster.go
- references/cli/cluster.go
- test/e2e-multicluster-test/multicluster_test.go
Support vela cluster alias.
1. `vela cluster alias` add alias to cluster.
2. `vela cluster list` show cluster alias explicitly.
3. Other vela cluster commands show cluster alias implicitly.
The underlying annotation is `cluster.core.oam.dev/cluster-alias`.
NOTE:
1. Alias is only used for help user identify the cluster. There is no name conflict detection for cluster alias. Therefore, it is possible for two clusters to share the same alias.
2. Alias **CANNOT** be used to select clusters now.
I have:
> Feat: support alias in cluster

- pkg/apiserver/rest/usecase/user.go
`utils2.RandomString` may generate plain string without number
Fixes #3613
I have:
> Fix: verify password valid

- pkg/cmd/builder.go
- pkg/cmd/completion.go
- pkg/cmd/factory.go
- pkg/cmd/types.go
- pkg/cmd/utils.go
- pkg/controller/utils/actions.go
- pkg/oam/auxiliary.go
- references/cli/addon.go
- references/cli/cli.go
- references/cli/revision.go
- references/cli/up.go
- references/cli/up_test.go
- references/cli/workflow.go
- test/e2e-apiserver-test/velaql_test.go
- test/e2e-multicluster-test/multicluster_test.go
Support `vela up --revision` to update application with a previous existing revision.
The rework support auto-completion for vela up.
Demo:
I have:
> Feat: rework vela up to support specified revision

- pkg/addon/addon.go
- pkg/addon/addon_test.go
- pkg/addon/error.go
- pkg/apiserver/rest/usecase/addon.go
clear info when addon version cannot meet require
Fixes #
I have:
> Fix: clear info when addon version cannot meet require

- pkg/apiserver/rest/usecase/config.go
- pkg/apiserver/rest/usecase/config_test.go
When there are configs, but not in the project where the appliation
is about to deploy, the sync application will hit an issue. It will
lead to block the deploy of an application.
Fixes #
I have:
> Fix: failed to deploy application when no config is avaiable

- charts/vela-core/templates/defwithtemplate/storage.yaml
- charts/vela-minimal/templates/defwithtemplate/storage.yaml
- docs/examples/core-definitions/trait/storage.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- vela-templates/definitions/internal/trait/storage.cue
Signed-off-by: Shijie Zhong <zhongsjie@cmbchina.com>
Support the multi-mountToEnv parameter of storage trait in secret and configmap. By this feature, we can mount multi-env in container env, without creating multi-secret or multi-configmap resrouces
I have:
> Feat: enhance storage trait to support multi-mountToEnv config

- pkg/multicluster/virtual_cluster.go
- pkg/resourcetracker/tree.go
- references/cli/status.go
- test/e2e-multicluster-test/multicluster_cli_test.go
1. `vela status --tree` show cluster alias.
2. `vela status --tree --detail --detail-format raw` fix format.
I have:
> Fix: vela status tree show cluster alias & raw format

- e2e/addon/mock/testdata/mock-addon/metadata.yaml
- e2e/addon/mock/testdata/mock-addon/template.yaml
- e2e/plugin/plugin_test.go
- test/e2e-apiserver-test/addon_test.go
- test/e2e-apiserver-test/velaql_test.go
mock an addon in e2e-test env to fix flaky test
Fixes #
I have:
> Fix: mock an addon to fix flaky test

- apis/core.oam.dev/v1beta1/resourcetracker_types.go
- apis/types/multicluster.go
- pkg/multicluster/utils.go
When application is not using multi-cluster, the recorded resources will set cluster to "". But if using multi-cluster, the local cluster will be recorded as "local".
So if one application is upgrading from non-multi-cluster to multi-cluster, the recorded resources will mismatch, which will lead to some in-use resources being mis-recycled. This PR fixes it.
I have:
Related to #3667 .
> Fix: rt resource key compare mismatch local cluster

- apis/types/types.go
- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/config.go
- pkg/apiserver/rest/usecase/config_test.go
- pkg/apiserver/rest/usecase/project.go
- references/cli/provider.go
- For VelaUX, users don't need to manually set the provider name. Used
the application/component name (config name) to be the provider name.
- Store the description of a config to the annotation of the config application
Fixes #
I have:
> Fix: set provider name as the config name

- pkg/oam/util/helper.go
- pkg/oam/util/helper_test.go
- pkg/utils/system/system.go
- references/cmd/cli/main.go
CLI could use `KUBEVELA_SYSTEM_NAMESPACE` and `KUBEVELA_DEFINITION_NAMESPACE` environment variables for override default `vela-system` for use. 
I have:
> Fix: bind env to system namespace

- go.mod
- pkg/definition/go_gen.go
- pkg/definition/go_gen_test.go
- references/cli/def.go
Add `vela def gen-api` command to generate Go struct for X-definition, example: 
```shell
$ vela def go-gen vela-templates/definitions/internal/trait/resource.cue
package main
// Requests Specify the resources in requests
type Requests struct {
CPU    number `json:"cpu"`
Memory string `json:"memory"`
}
// Limits Specify the resources in limits
type Limits struct {
CPU    number `json:"cpu"`
Memory string `json:"memory"`
}
// Parameter -
type Parameter struct {
CPU      number   `json:"cpu"`
Memory   string   `json:"memory"`
Requests Requests `json:"requests"`
Limits   Limits   `json:"limits"`
}
```
Partially fixes #3606 
I have:
1. A lot tests with different types of parameter in go_gen_test.go
2. Test almost every X-definition in …
> Feat: vela def gen-api command

- pkg/workflow/tasks/template/load.go
Signed-off-by: clarechu [1062186165@qq.com](mailto:1062186165@qq.com)
Fixes #
In Windows 10， When running vela-core
```log
"msg"="Reconciler error" "error"="object level reconcile error, type: \"Workflow\", msg: \"open static\\\\builtin-apply-compon
ent.cue: file does not exist\"
```
I have:
> Fix: embed.FS filepath that follow the unix style file path when running on windows

- charts/vela-core/templates/defwithtemplate/config-image-registry.yaml
- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/config-image-registry.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- vela-templates/definitions/internal/component/config-image-registry.cue
- vela-templates/definitions/internal/component/webservice.cue
1. change the host alias field to not required.
2. change the config-image-registry definition to UI hidden.
I have:
> Feat: change the webservice and config-image-registry definitions

- .github/workflows/apiserver-test.yaml
- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/e2e-test.yml
- .github/workflows/go.yml
- .github/workflows/unit-test.yml
- makefiles/const.mk
- makefiles/e2e.mk
When push tags with "v*", all e2e test will be running on 1.18/1.20/1.22 Kubernetes (in Kind)
I have:
> Feat: run e2e test on several K8s version

- pkg/utils/config/project.go
- pkg/utils/config/project_test.go
If the config project is not nil, it's matched whether the project
matched the target project.
If the config project is nil, the target project matched the config.
Fixes #
I have:
> Feat: check whether a project matched a config's project

- .github/workflows/apiserver-test.yaml
- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/e2e-test.yml
This PR add missing triggers in #3714. With these triggers, GitHub will launch e2e-tests with multi-versions of Kubernetes. 
I have:
> Chore: fix missing trigger for e2e tests 

- .github/workflows/apiserver-test.yaml
- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/e2e-test.yml
Using simpler method to check if tag exist when releasing or push tags and set the test Kubernetes version matrix.
I have:
> Chore: fix e2e test check tag exist and set matrix

- references/cli/addon.go
There are some changes in `vela port-forward`, this PR fix the legacy prompt when enable velaux addon.
I have:
> Fix: velaux addon hint after enable

- pkg/apiserver/model/system_info.go
- pkg/apiserver/rest/usecase/authentication.go
- pkg/apiserver/rest/usecase/authentication_test.go
- pkg/apiserver/rest/usecase/system_info.go
- pkg/apiserver/rest/usecase/user.go
- pkg/apiserver/rest/usecase/user_test.go
- test/e2e-apiserver-test/suite_test.go
add default user in dex
I have:
> Feat: add default user in dex

- apis/core.oam.dev/v1beta1/core_types.go
- charts/oam-runtime/crds/core.oam.dev_traitdefinitions.yaml
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
- charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_traitdefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/multicluster/utils.go
Signed-off-by: Xiangbo Ma [maxiangboo@cmbchina.com](mailto:maxiangboo@cmbchina.com)
Description of your changes
Support trait with custom resource be dispatched to hubcluster
Fixes https://github.com/oam-dev/kubevela/issues/3754
I have:
> Feat: Support trait with custom resource be dispatched to hubcluster

- apis/core.oam.dev/v1beta1/resourcetracker_types.go
- charts/vela-core/templates/defwithtemplate/deploy.yaml
- charts/vela-minimal/templates/defwithtemplate/deploy.yaml
- pkg/appfile/appfile.go
- pkg/appfile/dryrun/testdata/wd-deploy.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/cue/model/value/value.go
- pkg/policy/envbinding/patch.go
- pkg/policy/topology.go
- pkg/policy/topology_test.go
- pkg/resourcekeeper/containsresources.go
- pkg/resourcekeeper/resourcekeeper.go
- pkg/stdlib/op.cue
- pkg/stdlib/pkgs/multicluster.cue
- pkg/stdlib/pkgs/oam.cue
- pkg/workflow/providers/multicluster/deploy.go
- pkg/workflow/providers/multicluster/deploy_test.go
- pkg/workflow/providers/multicluster/multicluster.go
- pkg/workflow/providers/multicluster/multicluster_test.go
- pkg/workflow/providers/oam/apply.go
- pkg/workflow/providers/oam/apply_test.go
- pkg/workflow/types/types.go
- pkg/workflow/workflow.go
- references/cli/status.go
- vela-templates/definitions/internal/workflowstep/deploy.cue
1. Rework the implementation of `deploy` workflowstep into GoLang in avoid of infinite loop explosion in CUELang. https://github.com/cue-lang/cue/issues/1660 This re-implementation does not affect any usage for `deploy` step.
2. `deploy` step supports `dependsOn` in components. This is done by (a) pre-check the health status of all components; (b) only apply components that have all dependents ready but are not healthy yet; (c) if not all components are healthy, wait for next reconcile loop. The backoff time will be reset when message changes.
3. If no topology policy specified in `deploy` step, previously no cluster will be deployed. In this PR, the default behavior is to deploy to the local cluster.
I have:
> Feat: support dependsOn in deploy workflowstep

- .github/workflows/release.yml
- references/cli/traits.go
The PR oam-dev/kubevela.io#627 changes the script to install the vela form OSS, so, we should sync the vela new versioned binaries to OSS.
I have:
> Chore: sync the cli binaries to OSS

- charts/vela-core/templates/defwithtemplate/cron-task.yaml
- charts/vela-core/templates/defwithtemplate/task.yaml
- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-core/templates/defwithtemplate/worker.yaml
- charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
- charts/vela-minimal/templates/defwithtemplate/task.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/worker.yaml
- vela-templates/definitions/internal/component/cron-task.cue
- vela-templates/definitions/internal/component/task.cue
- vela-templates/definitions/internal/component/webservice.cue
- vela-templates/definitions/internal/component/worker.cue
This PR adds the application name to the generated workloads metadata labels (e.g., deployments, jobs, etc) that are created using the standard component types: `webservice`, `worker`, `task`, and `cron-task`.
The motivation behind this change is to maintain the old behavior of the previous kubernetes runtime where generated entities such as deployments or their resulting pods carried the labels of the parent application and component. That enabled using label selectors to get all pods of an application:
```bash
$ k get pods -l=app.oam.dev/name=first-vela-app-as-webservice
NAME                                         READY   STATUS    RESTARTS   AGE
express-server-webservice-54dcccbf4b-qcskl   1/1     Running   0          2m21s
```
The ability of retrieving pods by application name and/or …
> Fix: Add application name to the generated workload entities

- pkg/apiserver/rest/usecase/user.go
Fixes #3790 
How to fix it?
Just remove "\n" in log message.
I have:
> Fix: useless \n is printed in log message

- apis/core.oam.dev/v1alpha2/application_types.go
- apis/core.oam.dev/v1beta1/application_types.go
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-minimal/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
Add short name velaapp for application CRD   (#3797)
I have:
@wonderflow
> Feat: Add short name velaapp for application CRD

- pkg/controller/utils/capability_linux_test.go
- pkg/controller/utils/capability_test.go
- pkg/utils/common/common_test.go
> Chore: seprate test into linux env which can't be execute in darwin

- pkg/resourcetracker/app.go
- pkg/resourcetracker/app_test.go
Support use ApplicationResourceTracker for list resource trackers when users do not have permissions to access cluster-scoped ResourceTracker.
This PR is a cherry-pick for #3768.
The server part is moved to [vela-prism](https://github.com/kubevela/prism).
Fixes #
I have:
> Feat: add support for ApplicationResourceTracker

- pkg/cue/model/sets/operation.go
- pkg/cue/model/sets/operation_test.go
support multi keys in patchKey
I have:
/cc @leejanee
> Feat: support multi keys in patchKey

- hack/crd/cleanup.sh
- hack/e2e/end_e2e.sh
- hack/e2e/end_e2e_core.sh
- hack/licence/header-check.sh
- hack/utils/installdefinition.sh
> Fix: Refactors shell to have double quotes format

- pkg/addon/cache.go
- pkg/addon/cache_test.go
- pkg/addon/versioned_registry_test.go
- test/e2e-multicluster-test/suite_test.go
1. load addon from different cache pool according to registry's type
2. refactor code to avoid duplicated code
Fixes #3795 
I have:
> Fix: The new addon can not shown in the Addons page

- pkg/addon/source.go
- pkg/addon/source_test.go
- pkg/apiserver/rest/usecase/addon.go
1. vela-apiserver only responses safe fields to caller
Fixes #3836 
I have:
> Fix: sensitive field of addon registry is exposed

- references/cli/addon.go
- references/cli/addon_suite_test.go
- references/cli/addon_test.go
- references/cli/uninstall_test.go
Addressed an issue where locally installed addons being displayed as the registry one if there is an addon with the same name is in the registry.
Notice the `dex` addon, which is installed from local sources, but displayed as the one in the registry.
It is now displayed properly as locally installed (the one in  KubeVela registry is not affected).
I have:
Changes that need to apply to existing unit tests have been added.
> Fix: resolve locally installed addons not being displayed

- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-minimal/crds/core.oam.dev_applications.yaml
- makefiles/dependency.mk
Update kustomize to the last version available.  The previous pinned version was not available for darwin-arm64. 
[Fixes #3807](https://github.com/kubevela/kubevela/issues/3807)
I have:
In a darwin-ar64 machine, execute:
```
make manifests
```
If there is another kustomize version installed in $HOME/go/bin, you will need to remove it before compiling with the new makefile
```
make manifests
installing kustomize-v4.5.4	 into ...go/bin
.../go/bin/kustomize exists. Remove it first.
make: *** [kustomize] Error 1
```
> Fix(makefile): update kustomize version to be available for darwin-arm64

- pkg/controller/core.oam.dev/v1alpha2/application/testdata/crds/terraform.core.oam.dev_configurations.yaml
Updated Terraform Configuration CRDS to v1beta2 to fix the UT
issue of https://github.com/kubevela/kubevela/pull/3851
Fixes #
I have:
> Fix: update Terraform Configuration CRDS test file

- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
when controlPlaneOnly=true, There are probability to report error "resource not found"
After applycomponent, when waiting for health, the trace still checks the CR of the corresponding trace from the managedcluster corresponding to comp. At this time, the status of the CR should be checked from local
I have:
> Fix: there are probability to report error when controlPlaneOnly=true

- pkg/apiserver/rest/usecase/application.go
- pkg/apiserver/rest/usecase/application_test.go
- pkg/apiserver/rest/usecase/testdata/terraform-alibaba-rds.yaml
- pkg/apiserver/rest/usecase/workflow_model.go
Can not query the environments by an empty name list.
I have:
This bug was introduced by #3878
> Fix: fail to create the cloud service application

- pkg/apiserver/model/application.go
- pkg/apiserver/rest/usecase/application.go
- pkg/apiserver/rest/usecase/application_test.go
- pkg/apiserver/rest/usecase/webhook.go
For the trigger, In addition to the custom payload type, we should support setting the component name, whose image address needs to be changed by the trigger.
Fixes #
I have:
> Feat: add the component name field for the trigger

- cmd/core/main.go
- pkg/features/controller_features.go
- pkg/utils/jwt.go
- pkg/utils/k8s.go
This PR includes two changes:
1. Support auto-detect identity in X509 kubeconfig and let controller to impersonate as itself in this case. (Previously only ServiceAccount based kubeconfig is supported.)
2. Add a feature flag to controller impersonation. By default enabled.
I have:
> Feat: controller auto-impersonation

- pkg/auth/kubeconfig.go
- pkg/cmd/builder.go
- pkg/cmd/completion.go
- pkg/cmd/factory.go
- pkg/utils/util/cmd.go
- references/cli/auth.go
- references/cli/cli.go
- references/cli/create.go
- references/cli/up_test.go
- test/e2e-multicluster-test/multicluster_auth_test.go
- test/e2e-multicluster-test/suite_test.go
`vela auth gen-kubeconfig` generate kubeconfig for users with given User/Groups or ServiceAccount.
For User/Groups, the command will generate a new private key, create a CertificateSigningRequest, approve itself and generate kubeconfig with the signed X.509 certificate.
For ServiceAccount, the command will find the serviceaccount secret and generate kubeconfig with the token inside the secret.
Example usage:
```                                                                                                                                                     
vela auth gen-kubeconfig --user new-user                                                                                                                    
vela auth gen-kubeconfig …
```
> Feat: vela auth gen-kubeconfig

- pkg/apiserver/rest/usecase/application.go
- pkg/stdlib/pkgs/query.cue
- pkg/velaql/providers/query/collector.go
- pkg/velaql/providers/query/handler.go
- pkg/velaql/providers/query/handler_test.go
There are two changes:
1. add kind or apiVersion as a filter option, this is useful for querying one kind resource of application.  for an example:
original:
```
apiVersion: "terraform.core.oam.dev/v1beta1"
kind:       "Configuration"
resources: ql.#ListResourcesInApp & {
app: {
name:      parameter.appName
namespace: parameter.appNs
}
}
status: {
if resources.err == _|_ {
"cloud-resources": [ for i, resource in resources.list if resource.object.apiVersion == apiVersion && resource.object.kind == kind {
resource.object
}]
}
if resources.err != _|_ {
error: resources.err
}
}
```
now:
```
resources: ql.#ListResourcesInApp & {
app: {
name:      parameter.appName
namespace: parameter.appNs
filter: {
"apiVersion": …
```
> Feat: support filter the resource by kind or apiVersion

- go.mod
- go.sum
- pkg/auth/identity.go
- pkg/auth/kubeconfig.go
- pkg/auth/privileges.go
- pkg/cmd/completion.go
- pkg/cmd/factory.go
- pkg/utils/k8s.go
- pkg/utils/parallel/parallel.go
- references/cli/auth.go
- references/cli/cli.go
- references/cli/up_test.go
- test/e2e-multicluster-test/multicluster_auth_test.go
Support `vela auth list-privileges`. This command can show the privileges of given User/Group/ServiceAccount across multiple clusters.
Detail usage:
```
vela auth list-privileges --user alice
vela auth list-privileges --group org:dev-team
example-cluster
vela auth list-privileges --user bob --group org:dev-team --group org:test-team --cluster local --cluster
example-cluster
vela auth list-privileges --serviceaccount example-sa -n demo --cluster cluster-1 --cluster cluster-2
vela auth list-privileges --kubeconfig ./example.kubeconfig --cluster local --cluster cluster-1
```
Example:
```
$ vela auth list-privileges --user somefive --cluster velad-002 --cluster velad-003                                                
User=somefive …
```
> Feat: vela auth list-privileges

- pkg/cmd/builder.go
- pkg/cmd/types.go
- pkg/cmd/utils.go
- pkg/utils/file.go
- references/cli/auth.go
- references/cli/cli.go
- references/cli/kube.go
- test/e2e-multicluster-test/multicluster_cli_test.go
- test/e2e-multicluster-test/testdata/kube/data/configmap.yaml
- test/e2e-multicluster-test/testdata/kube/service.yaml
Support run `vela kube apply --cluster` to apply native resources in multiple clusters. This command is not intended to be widely used. Only if user finds it is difficult to apply some native resources directly into managed clusters, such as Roles/ClusterRoles. The recommended way to delivery resources in multiple clusters should always be using KubeVela Application.
Usage:
```
vela kube apply -f my.yaml --cluster cluster-1
vela kube apply -f my-1.yaml -f my-2.yaml --cluster cluster-1 --cluster cluster-2
vela kube apply -f https://github.com/kubevela/kubevela/blob/master/docs/examples/app-with-probe/app-with-probe.yaml
vela kube apply -f ./resources -n demo --cluster cluster-1 --cluster cluster-2
```
I have:
This CLI command is design out …
> Feat: vela kube apply --cluster

- pkg/oam/labels.go
- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_test.go
This PR remove the last-applied-config annotation for configmap and secret, and allow users to disable it by fill `-` or `skip` into this annotation `app.oam.dev/last-applied-configuration`.
You can disable it by adding a annotation triat, or manuelly add this annotation on it.
```
metadata:
spec:
components:
- name: express-server
properties:
image: oamdev/hello-world
ports:
- port: 8000
expose: true
traits:
- type: annotations
properties:
app.oam.dev/last-applied-configuration: skip
```
Then the deployment won't have the `app.oam.dev/last-applied-configuration` filled:
Fixes #3938
I have:
> Fix: remove last-applied-config annotation for configmap and secret

- pkg/appfile/template.go
- pkg/utils/common/args.go
- references/cli/dryrun.go
Fixes #3865
I have:
Made a sample `definition.yaml` file and a `app.yaml` and run the `vela dry-run` command with the `-d` `-f` and `--offline` flags.
> Feat(cli): added the offline flag to the dry-run command

- charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
- pkg/auth/identity.go
- pkg/auth/privileges.go
- pkg/utils/jwt.go
- pkg/utils/k8s.go
- pkg/webhook/core.oam.dev/v1alpha2/application/mutating_handler.go
- references/cli/auth.go
- references/cli/kube.go
- test/e2e-multicluster-test/multicluster_auth_test.go
Support `vela auth grant-privileges` to grant privileges to users across clusters.
Usage:
```
vela auth grant-privileges --user alice --for-namespace demo
vela auth grant-privileges --user alice --for-namespace demo --for-cluster cluster-1 --create-namespace
vela auth grant-privileges --group org:dev-team
cluster example-cluster
vela auth grant-privileges --group org:dev-team --group org:test-team --for-namespace test --for-cluster local
--for-cluster example-cluster
vela auth grant-privileges --serviceaccount observer -n test --for-namespace test --readonly
vela auth grant-privileges --kubeconfig ./example.kubeconfig --for-cluster cluster-1
```
Solves #3933 partially. Only support internal pre-configured privilege sets now. More …
> Feat: vela auth grant-privileges

- makefiles/dependency.mk
Signed-off-by: huangminjie <minjie.huang@daocloud.io>
When I run `make kustomize`, I get the following err:
```
installing kustomize-v4.5.4      into /Users/jar/go/bin
/Users/jar/go/bin/kustomize exists. Remove it first.
make: *** [makefiles/dependency.mk:64: kustomize] Error 1
```
The reason is that I already have another version kustomize in my GOBIN.
So I think it is better to download the kustomize in project folder rather than GOBIN.
Fixes #
I have:
> Feat: support download kustomize in local folder

- charts/vela-core/templates/velaql/resourceTree.yaml
- pkg/stdlib/pkgs/query.cue
- pkg/stdlib/ql.cue
- pkg/velaql/providers/query/collector.go
- pkg/velaql/providers/query/handler.go
- pkg/velaql/providers/query/tree.go
- pkg/velaql/providers/query/tree_test.go
- pkg/velaql/providers/query/types/health_status.go
- pkg/velaql/providers/query/types/type.go
implementation for get application resourceTree with velaql
eg: When access the endpoint: http://127.0.0.1:8000/api/v1/query/?velaql=application-resource-tree-view{appName="addon-kruise-rollout",appNs="vela-system",}.status . The result is
```json
{
"resources": [
{
"apiVersion": "source.toolkit.fluxcd.io/v1beta1",
"cluster": "",
"component": "kruise-rollout",
"kind": "HelmRepository",
"latest": true,
"name": "kruise-rollout",
"namespace": "vela-system",
"resourceTree": {
"apiVersion": "source.toolkit.fluxcd.io/v1beta1",
"cluster": "",
"kind": "HelmRepository",
"name": "kruise-rollout",
"namespace": "vela-system",
"resourceHealthStatus": {
"message": "",
"reason": "",
"statusCode": "HealthStatusHealthy"
}
},
"revision": "addon-kruise-rollout-v1",
"trait": ""
},
{
"apiVersion": …
```
> Feat: velaql provider for get application resource-tree

- references/cli/kube.go
- test/e2e-multicluster-test/multicluster_cli_test.go
Support `vela kube delete <resourceType> <resourceName> --cluster <clusterName>` to delete resources in clusters.
Usage:
```
vela kube delete deployment nginx --cluster cluster-1
vela kube delete deployment nginx -n demo --cluster cluster-1 --cluster cluster-2
vela kube delete deployment --all -n demo --cluster cluster-1
```
I have:
> Feat: vela kube delete

- pkg/auth/privileges.go
- references/cli/auth.go
1. `auth grant-privileges` show cluster when displaying results.
```
$ vela auth grant-privileges --user bob --for-cluster=velad-002 --for-namespace=dev --readonly
RoleBinding dev/kubevela:reader:binding created in velad-002.
Privileges granted.
```
2. Fixes grant cluster-scoped privileges error. (Previously not correctly convert the input)
```
$ vela auth grant-privileges --user bob --for-cluster=velad-003           
ClusterRoleBinding kubevela:writer:binding created in velad-003.
Privileges granted.
```
3. Enhance the output of list-privileges. Converting "Binding" to "Scope" to be more clear.
```
$ vela auth list-privileges --user bob --cluster velad-002,velad-003                        
User=bob
├── [Cluster]  velad-002
│   └── …
```
> Fix: enhance auth CLI output

- makefiles/dependency.mk
Kustomize can not read environment variables
I have:
> Fix: kustomize can not read environment variables

- go.mod
- pkg/oam/labels.go
- pkg/velaql/providers/query/handler.go
- pkg/velaql/providers/query/handler_test.go
- pkg/velaql/providers/query/tree.go
- pkg/velaql/providers/query/tree_test.go
mechanism to  relation-rule between parent and children resource
You can apply this configmap to create the relationship between cronjob, job and pod
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: clone-set-relation
namespace: vela-system
labels:
"rules.oam.dev/resources": "true"
data:
rules: |-
- parentResourceType:
group: batch
kind: CronJob
childrenResourceType:
- apiVersion: batch/v1
kind: Job
- parentResourceType:
group: batch
kind: Job
childrenResourceType:
- apiVersion: v1
kind: Pod
```
then you request the application resource tree will get
```json
{
"resources": [
{
"apiVersion": "batch/v1beta1",
"cluster": "",
"component": "nacos",
"kind": "CronJob",
"latest": true,
"name": "nacos",
"namespace": "default",
"resourceTree": {
"apiVersion": "batch/v1beta1",
"cluster": "", …
```
> Feat:  mechanism to let user add relationship  mapping rule by configmap

- cmd/apiserver/main.go
- pkg/apiserver/domain/service/project.go
- pkg/apiserver/domain/service/project_test.go
- pkg/apiserver/domain/service/rbac.go
- pkg/apiserver/domain/service/velaql.go
- pkg/apiserver/infrastructure/clients/kubeclient.go
- pkg/apiserver/server.go
- pkg/velaql/providers/query/types/health_status.go
- test/e2e-apiserver-test/suite_test.go
Adjust the order in which the kube conf is created, there is must only one kube config instance. 
Others: Fixes #3967
I have:
> Fix: initialize kube config multiple times

- pkg/apiserver/domain/service/config.go
> Fix: delete Project fail

- pkg/apiserver/domain/service/rbac.go
- pkg/apiserver/domain/service/rbac_test.go
- pkg/apiserver/interfaces/api/config.go
- pkg/apiserver/interfaces/api/project.go
Fixes the issue that the project admin user can not get the configurations.
I have:
> Fix: add some default permissions about the configuration

- pkg/addon/addon.go
- pkg/addon/addon_test.go
```
Error: addon terraform-alibaba system requirement miss match: vela cli/ux version: v1.4.0-beta.1  require: >=v1.3.0
addon terraform-alibaba cannot enable 
```
If can not compare the version with beta or alpha, try to remove the suffix and make it as pass as possible.
Fixes #3950
I have:
/cc @wangyikewxgm
> Fix: optimized the version comparison

- pkg/cue/utils.go
- pkg/cue/utils_test.go
- pkg/velaql/providers/query/handler.go
- pkg/velaql/providers/query/utils.go
- pkg/velaql/providers/query/utils_test.go
- pkg/workflow/providers/kube/handle.go
- references/cli/velaql_test.go
- test/e2e-apiserver-test/testdata/component-pod-view.yaml
When we use VelaQL to query k8s object and convert to JSON,  the transformation route for query data is k8s-object -> cue-Value -> Json. k8s-object often contains nil value, those value will convert to **top** type in CUE, While CUE(v0.2.2) not support to marshal cue **Value** struct which contains **top** type to JSON, this will lead to VelaQL fail to parse query result to json format.
To fix this problem, we change the transformation route of data to k8s-object -> Json -> cue-Value -> Json, In this way will avoid generating **top** type CUE data.
Here's an example failed parse CUE data which contains **top** type
``` 
conditions: {
status:             "True"
lastProbeTime:      _  // top type
lastTransitionTime: …
```
> Fix: VelaQL fail to parse query result to json format

- pkg/workflow/step/types.go
```
"msg":"deploy app game2048 failure cannot patch object: admission webhook \"validating.core.oam.dev.v1beta1.applications\" denied the request: field \"spec\": Invalid value error encountered, failed to parsePolicies: invalid WorkflowStep default: json: unknown field \"ignoreTerraformComponent\"
```
New a field for the deploy workflow step must set both cue script and go struct.
I have:
/cc @Somefive
> Fix: unknown field ignoreTerraformComponent

- pkg/utils/env/env.go
- pkg/utils/env/env_test.go
- pkg/utils/k8s.go
Fixes #3947
Error message of `vela init env` is not clear
I have:
> Fix: error message of `vela init env` is not clear

- docs/apidoc/swagger.json
- pkg/apiserver/domain/repository/grpc.go
- pkg/apiserver/domain/service/rbac.go
- pkg/apiserver/domain/service/rbac_test.go
- pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
- pkg/apiserver/interfaces/api/dto/v1/types.go
- pkg/apiserver/interfaces/api/env.go
- pkg/apiserver/interfaces/api/project.go
- pkg/apiserver/interfaces/api/rbac.go
- pkg/apiserver/utils/bcode/015_rbac.go
Added the 4 APIs about the permission:
* the creating platform scope permission API.
* the deleting platform scope permission API.
* the creating project scope permission API.
* the deleting project scope permission API.
Fixed the permission check bug that the actions do not task effect.
I have:
> Feat: add the creating and deleting permission APIs

- pkg/velaql/providers/query/tree.go
- pkg/velaql/providers/query/tree_test.go
1. down-grade the endpointSlice to v1beta1 to compatible for kubernetes 1.20
2. since the service is not the owner of endpoint, add listOption for them.
Fixes #
I have:
> Fix: some optimize for resource-tree

- pkg/velaql/providers/query/handler_test.go
- pkg/velaql/providers/query/types/type.go
- references/cli/velaql_test.go
For the TCP protocol, remove the prefix in the endpoint string.
before:
```
tcp://10.101.2.1:8089
```
after:
```
10.101.2.1:8089
```
I have:
> Fix: remove the tcp protocol prefix in the endpoint string

- references/cli/provider.go
- references/cmd/cli/main.go
Print the detail error for provider add failure
Fixes #3936 
Before:
```
➜  bin git:(fix-terr) ✗ vela provider add terraform-alibaba --ALICLOUD_ACCESS_KEY xxxxx --ALICLOUD_SECRET_KEY xxxxx   --ALICLOUD_REGION cn-hangzhou
Error: failed to authenticate Terraform cloud provider terraform-alibaba
2022/05/30 14:41:29 failed to authenticate Terraform cloud provider terraform-alibaba
```
After:
```
➜  bin git:(fix-terr) ✗  ./vela provider add terraform-alibaba --ALICLOUD_ACCESS_KEY xxxxxx --ALICLOUD_SECRET_KEY xxxxx   --ALICLOUD_REGION cn-hangzhou
Error: failed to authenticate Terraform cloud provider terraform-alibaba err: terraform provider default for terraform-alibaba already exists
2022/05/30 14:46:37 failed to authenticate Terraform cloud …
```
> Fix: Improve vela provider add response

- charts/vela-core/templates/defwithtemplate/container-image.yaml
- charts/vela-core/templates/defwithtemplate/deploy2env.yaml
- charts/vela-core/templates/defwithtemplate/json-merge-patch.yaml
- charts/vela-core/templates/defwithtemplate/json-patch.yaml
- charts/vela-core/templates/defwithtemplate/ref-objects.yaml
- charts/vela-core/templates/defwithtemplate/step-group.yaml
- charts/vela-minimal/templates/defwithtemplate/container-image.yaml
- charts/vela-minimal/templates/defwithtemplate/json-merge-patch.yaml
- charts/vela-minimal/templates/defwithtemplate/json-patch.yaml
- charts/vela-minimal/templates/defwithtemplate/ref-objects.yaml
- charts/vela-minimal/templates/defwithtemplate/step-group.yaml
- vela-templates/definitions/internal/component/ref-objects.cue
- vela-templates/definitions/internal/trait/container-image.cue
- vela-templates/definitions/internal/trait/json-merge-patch.cue
- vela-templates/definitions/internal/trait/json-patch.cue
- vela-templates/definitions/internal/workflowstep/deploy2env.cue
- vela-templates/definitions/internal/workflowstep/step-group.cue
Some definitions did not generate the UI schema, we provisionally hid them. 
I have:
/cc @Somefive @wonderflow
> Chore: hide some definitions in VelaUX

- pkg/addon/versioned_registry.go
- pkg/addon/versioned_registry_test.go
- references/cli/addon.go
more  info when system requirement miss match  and filter prerelease version
Fixes #
I have:
> Fix(addon): more note info and filter prerelease addon version

- references/cli/provider.go
Fixes #4093 
Before:
```
Examples:
vela provider delete <provider-type> -name <provider-name>
```
After:
```
Examples:
vela provider delete <provider-type> --name <provider-name>
```
I have:
> Fix: vela provider delete command's example is wrong

- .github/CODEOWNERS
* This PR add @StevenLeiZhang as the approver of vela CLI. 
* @Somefive has contribute great in most of the areas of KubeVela, so we request him to own more areas of code review.
* For our heavily development, I ajust the owner file for more flexiblity.
> Chore: add @StevenLeiZhang into owners file and ajust for more flexible owners

- references/cli/uninstall.go
A bug generated when fluxcd addon has been enabled, then use `uninstall -f`
The uninstall process begin to remove the vela core controller and vela-system namespace while fluxcd addon is  been deleting. This will cause a dead clock to block whole uninstall and re-install process.
Fixes #
I have:
> Fix: hold the force uninstalling process untill the last addon been deleted

- .github/workflows/registry.yml
- charts/vela-core/values.yaml
- charts/vela-minimal/values.yaml
1. Fix: bump oamdev/kube-webhook-certgen to v2.4.1 to support arm64
2. Fix: split the image build process to make it faster
I have:
> Fix: bump oamdev/kube-webhook-certgen to v2.4.1 to support arm64 

- references/cli/components.go
- references/cli/traits.go
Using  the `description` field in the component and trait definition, show it now as an 3rd column in the vela cli command `vela components` and `vela traits`.
> Feat: Add description column to vela trait and component command

- e2e/addon/addon_test.go
- e2e/addon/mock/testdata/sample/metadata.yaml
- e2e/addon/mock/testdata/sample/resources/parameter.cue
- e2e/cli.go
- references/cli/addon.go
- references/cli/test-data/addon/sample/resources/parameter.cue
- test/e2e-addon-test/addon_test.go
When we use `.` to enable local addons, cli will use `.` as the addon name to print endpoints, which will cause errors.
Example: `vela addon enable .` or `vela addon enable ./some/path/.`
Notice the last three (or five) lines. (`.` is used as addon name, and `addon-.` invalid labels)
```console
$ vela addon enable .
enable addon by local dir: . 
I0607 22:14:37.470277  705624 apply.go:107] "creating object" name="canary-rollout" resource="core.oam.dev/v1beta1, Kind=WorkflowStepDefinition"
I0607 22:14:37.535854  705624 apply.go:107] "creating object" name="istio-gateway" resource="core.oam.dev/v1beta1, Kind=TraitDefinition"
I0607 22:14:37.597845  705624 apply.go:107] "creating object" name="canary-rollback" …
```
> Fix(cli): avoid incorrect addon name when using dot as local addon path

- references/cli/up.go
- references/common/application.go
Signed-off-by: huangminjie <minjie.huang@daocloud.io>
render color for outputs of vela up command (#3903 )
Fixes #3903 
I have:
> Feat: render color for outputs of vela up command

- pkg/velaql/providers/query/tree.go
- pkg/velaql/providers/query/tree_test.go
resourceTree more robust
Fixes #4128 
I have:
> Fix: api not exist don't break whole query process

- .github/workflows/issue-commands.yml
KubeVela bot sometimes will fail and the log shows that it is caused by an inconsistent lockfile.
However the lockfile itself is fine, and I suspect it is caused by node version changes (as it uses the version bundled with `ubuntu-latest`, which just updated recently with npm `v8.5.5` -> `v8.11.0` and causing this issue). 
Using `latest` tag does no good, which will often cause problems when software version changes. 
It is a good practice to fix node versions (also npm versions).
So I did the following:
- fixed node version to `v14` (instead of node `v16` + npm `v8.11.0` bundled with `ubuntu-latest`; that specific `v8.11.0` version doesn't work and will fail)
- fixed ubuntu version to 20.04, just for good measure
- (btw) added …
> Chore: fix potential bot failures

- pkg/apiserver/domain/model/user.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_test.go
- references/cli/components.go
- references/cli/traits.go
Signed-off-by: fengkang <fengkangb@digitalchina.com>
I change the user model index function ,and replace symbol timing.
In the kubeapi datastore , the list function can get include Special characters("@"," ")filed "name" and "email",i use verifyUserValue function to replace the Special characters to make sure that can be used by k8s label
In the mongoDB datastore , this list funciton keep intact,so that the program can special a email to list the model user
Fixes #4104 
I have:
@FogDong
> Fix: mongoDB datastore can't list special email user(#4104)

- pkg/apiserver/domain/service/application_test.go
- pkg/apiserver/domain/service/definition.go
- pkg/apiserver/domain/service/definition_test.go
- pkg/apiserver/domain/service/envbinding_test.go
* Disable the cache in the list definition API.
* Ignore the error of API schema not found in the query definition API.
Fixes #4098 
I have:
> Feat: optimize the API that list and detail definition 

- apis/core.oam.dev/common/types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-core/crds/core.oam.dev_workflows.yaml
- charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_workflows.yaml
- pkg/apiserver/domain/service/workflow.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler_test.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validation.go
- pkg/workflow/interface.go
- pkg/workflow/tasks/custom/task.go
- pkg/workflow/tasks/custom/task_test.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/tasks/discover_test.go
- pkg/workflow/types/types.go
- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
- references/cli/workflow.go
- references/cli/workflow_test.go
- test/e2e-multicluster-test/multicluster_standalone_test.go
Fixes #4020
This PR adds timeout in workflow step, you can use it like:
```yaml
workflow:
steps:
- name: suspend
type: suspend
timeout: 15s
```
After 15s, if the workflow is still not resumed, then the status will be like:
```yaml
steps:
- name: suspend
type: suspend
phase: failed
reason: Timeout
```
**Note**: In the past version, the `suspend` step succeeded when executed. After this PR is merged, the `suspend` step' status is `running` when it was executed, and become `succeeded` if it's resumed.
I have:
/cc @leejanee @wonderflow 
This PR also made some optimization to #3644 /cc @ArenaSu
> Feat: add timeout in workflow step

- pkg/addon/addon.go
handle of files of type ".yml" miss in the original function.
so I add handle of ".yml" type in readviewfile function
Signed-off-by: HanMengnan <1448189829@qq.com>
Fixes #4171
I have:
> Fix: add handle of ".yml" type in readviewfile function

- charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
Make the annatation for cert-manger be the same as the new version
secret
Signed-off-by: Zheng Xi Zhou <zhengxi.zzx@alibaba-inc.com>
Fixes #
I have:
> Fix: fix the annotation for APIService

- pkg/resourcekeeper/delete.go
- pkg/resourcekeeper/dispatch.go
- pkg/resourcekeeper/utils.go
- pkg/resourcekeeper/utils_test.go
ResourceTracker will record resources with metadata. The namespace for cluster scoped resource is incorrectly recorded. Although it does not affect the normal function, it will makes the resource view a bit weird.
Before:
After:
I have:
> Fix: clear namespace for cluster scoped resource for dispatching

- pkg/cue/model/keyword.go
- pkg/velaql/parse.go
- pkg/velaql/view.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/tasks/template/load.go
- references/cli/velaql.go
- references/cli/velaql_test.go
This PR changes the experience of vela ql, supports:
```
vela ql --query "<query>"
vela ql --file my-view.cue
```
I have:
> Feat: enhance velq ql and support cue file

- pkg/definition/definition.go
- references/cli/common.go
- references/cli/def.go
User can use alias metadata in cue.
Fixes #
I have:
go run cmd/plugin/main.go def render test.cue
go run cmd/plugin/main.go def get test-trait
```
test: {
type:  "trait"
alias: "可以加上中文别名"
}
```
The alias field can also be placed in the annotation, but I think it's better as a native field.
> Feat: cli def alias support

- e2e/addon/addon_test.go
- references/cli/addon.go
- references/cli/status.go
Please refer to #4163. Changes are exactly the same as what is described in that issue. Addons with no endpoints will skip the table, otherwise it is not affected.
Fixes #4163
I have:
> Fix: skip endpoint table if no endpoints are found in addons

- e2e/application/application_test.go
- e2e/commonContext.go
- pkg/apiserver/domain/model/application.go
- pkg/apiserver/domain/model/whole.go
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/workflow.go
- pkg/apiserver/domain/service/workflow_test.go
- pkg/apiserver/event/event.go
- pkg/apiserver/event/sync/cache.go
- pkg/apiserver/event/sync/cache_test.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/event/sync/convert/convert.go
- pkg/apiserver/event/sync/cr2ux.go
- pkg/apiserver/event/sync/cr2ux_test.go
- pkg/apiserver/event/sync/testdata/test-app1.yaml
- pkg/apiserver/event/sync/worker.go
- pkg/apiserver/event/sync/worker_test.go
- pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
- pkg/velaql/providers/query/collector.go
- pkg/velaql/providers/query/handler.go
- pkg/velaql/view.go
- references/cli/delete.go
This PR support automatically hosts CLI-created apps. 
1. Create the application by CLI
```bash
vela up -f https://kubevela.net/example/applications/first-app.yaml
```
2. Open the application page in VelaUX
The workflow status is workflowSuspending, and we could click the Deploy button and select the default env, then
Here, the application has been hosted and you can operate the workflow review action through the UI.
If the application has been hosted, change the application CR can not be synced to VelaUX. next, we should support viewing the Diff the application configuration with application CR in the cluster.
I have:
> Feat: support to manage the CLI-created apps in VelaUX

- pkg/cue/model/sets/operation.go
- pkg/cue/model/sets/utils.go
- pkg/cue/model/sets/walk_test.go
While dealing with multiple trait patch in one component, the temp variable used in previous trait patch will remain in the following patch, which will lead to two problems:
1. Recursive explosion. For example, one trait patch use a map [1] to record all containers, then the second trait also use a map [2] to record all containers, but since the map [1] is included in the container the first trait patch to, the map[2] will include map [1] and this will cause lots of useless render.
2. The temporary variable will cause name conflict across different traits.
Fixes #4203
I have:
> Fix: cue patch remove temp var

- pkg/cue/model/sets/operation.go
JsonPatch and JsonMergePatch will close the patched result which will cause following cue trait patch failed. So before this PR, traits like `annotations` that uses the JsonPatch or JsonMergePatch must be placed after other patch trait.
Partially fixes #4221.
I have:
> Fix: json-patch & json-merge-patch open result

- pkg/addon/create.go
- pkg/addon/create_test.go
- pkg/utils/file.go
- pkg/utils/file_test.go
- references/cli/addon.go
- references/cli/addon_suite_test.go
- references/cli/addon_test.go
As described in https://github.com/kubevela/kubevela/issues/4116#issuecomment-1148450959, this pr adds a `vela addon init` command.
- If the user provides all three Chart-related parameters, an addon scaffold, with a `helm` component inside, will be created.
- If the user does't provide all the necessary parameters to create a `helm` component, a basic addon scaffold is generated instead.
This pr does **not** close that issue, since more features are needed.
<details>
<summary>Command Help Text</summary>
```console
$ vela addon init -h
Create an addon scaffold for quick starting. A Helm Component is generated if you provide Chart-related parameters.
Usage:
vela addon init [flags]
Examples:
vela addon init mongodb --helm-repo-url=https://marketplace.azurecr.io/helm/v1/repo --chart=mongodb …
```
> Feat: implement addon init command

- pkg/resourcetracker/tree.go
- pkg/resourcetracker/tree_test.go
Fixes #4238 
Before:
```
➜  chart vela -n vela-system status addon-terraform -t
CLUSTER       NAMESPACE       RESOURCE                            STATUS       
local     ─┬─ vela-system ─┬─ HelmRelease/terraform-controller    updated      
│               └─ HelmRepository/terraform-controller updated      
└─ -           ─── -                                   not-deployed 
```
After:
```
➜  bin git:(master) ✗ ./vela -n vela-system status addon-terraform -t
CLUSTER       NAMESPACE       RESOURCE                            STATUS    
local     ─── vela-system ─┬─ HelmRelease/terraform-controller    updated   
└─ HelmRepository/terraform-controller updated   
```
I have:
> Fix: vela status print wrong STATUS

- charts/vela-core/templates/defwithtemplate/cron-task.yaml
- charts/vela-core/templates/defwithtemplate/task.yaml
- charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
- charts/vela-minimal/templates/defwithtemplate/task.yaml
- vela-templates/definitions/internal/component/cron-task.cue
- vela-templates/definitions/internal/component/task.cue
Update the param `env` in task and cron-task ComponentDefinitions. Previous version was:
```
// +usage=Define arguments by using environment variables
env?: [...{
// +usage=Environment variable name
name: string
// +usage=The value of the environment variable
value?: string
// +usage=Specifies a source the value of this var should come from
valueFrom?: {
// +usage=Selects a key of a secret in the pod's namespace
secretKeyRef: {
// +usage=The name of the secret in the pod's namespace to select from
name: string
// +usage=The key of the secret to select from. Must be a valid secret key
key: string
}
// +usage=Selects a key of a config map in the pod's namespace
configMapKeyRef: {
// +usage=The name of the config map in the pod's namespace to select from
name: string
// +usage=The key of the …
```
> Fix: env from secret or configmap in task and cron-task componentdefinition

- pkg/workflow/tasks/custom/task.go
- pkg/workflow/tasks/custom/task_test.go
> Fix: fix the dash case in if validate for inputs

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/utils/capability.go
- pkg/controller/utils/capability_config_test.go
- pkg/utils/config/application.go
- references/cli/provider.go
- references/plugins/reference_test.go
* Fixes the error:
```
vela provider add terraform-alibaba --ALICLOUD_ACCESS_KEY xxx --ALICLOUD_SECRET_KEY xxx --ALICLOUD_REGION cn-hangzhou
Error: failed to authenticate Terraform cloud provider terraform-alibaba err: failed to authenticate Terraform cloud provider default for terraform-alibaba: context canceled
```
* Feat: add cache for remote terraform module in vela show
I have:
> Fix: provider can't be added since 1.4 as context abused && Feat: add cache for remote terraform module in vela show 

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/cue/model/value/value.go
- pkg/velaql/view_test.go
- pkg/workflow/hooks/data_passing.go
- pkg/workflow/operation/operation.go
- pkg/workflow/tasks/custom/task.go
Previously, if the component was not ready, its output would not be stored in the context. This PR fixes the problem and now we can pass the status of the component even if it's failed like:
```yaml
metadata:
name: err-with-always
namespace: default
spec:
components:
- name: invalid
properties:
image: invalid
ports:
- port: 8000
workflow:
steps:
- name: comp
type: apply-component
timeout: 5s
outputs:
- name: status
valueFrom: output.status.conditions[0].type + output.status.conditions[0].status
properties:
component: invalid
- name: notification
type: notification
inputs:
- from: status
parameterKey: slack.message.text
if: always
properties:
slack:
url:
value: <url> …
```
> Feat: store outputs for unsuccessful steps in workflow context

- pkg/velaql/parse.go
- references/cli/velaql.go
It supports this kind of usage:
```
cat <<EOF | vela ql -f -
import (
"vela/ql"
)
configmap: ql.#Read & {
value: {
kind:       "Secret"
apiVersion: "v1"
metadata: {
name:      "outputs-ecs"
namespace: "default"
}
}
}
status: configmap.value.data["this_public_ip"]
EOF
```
And read from URL.
I have:
> Fix: support stdin and url for vela ql

- charts/vela-core/templates/defwithtemplate/service-account.yaml
- charts/vela-minimal/templates/defwithtemplate/service-account.yaml
- vela-templates/definitions/internal/trait/service-account.cue
Allow writing privileges in the ServiceAccount trait which will create roles and rolebindings automatically.
I have:
> Feat: enhance ServiceAccount trait to support privileges

- pkg/policy/topology.go
- pkg/policy/topology_test.go
Controller use cluster client to support empty label selector selecting local cluster.
Writing
```yaml
- name: topology
type: topology
properties:
clusterLabelSelector: {}
```
will select all the clusters including the local cluster.
I have:
> Fix: controller topology policy use cluster client

- charts/vela-core/README.md
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/features/controller_features.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-test/application_test.go
When rollout trait is not used in component, the component revision will not be created. (The computation of revision hash and revision name remains.)
I have:
> Feat: disable comprev when rollout trait not used

- pkg/addon/addon.go
Signed-off-by: huiwq1990 <huiwq1990@163.com>
Fixes #
I have:
> Feat: addon use cluster sdk to check deploy

- pkg/appfile/appfile.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
context.namespace use override namespace when rendering component and trait
I have:
> Fix: context.namespace use the namespace from override policy

- pkg/auth/userinfo.go
- pkg/resourcekeeper/dispatch.go
The UserInfo is injected to the context for kube.#Apply. But kube.#Apply will call ResourceKeeper.Dispatch and therefore the write of ResourceTracker will misuse the userinfo-carried context and cause some trouble.
Fixes #4296
I have:
> Fix: kube apply ignore userinfo for rt

- pkg/builtin/http/http.go
Fixes #4294
I have:
@wonderflow
> Fix: fix the goroutine leak in CUE when use http request

- pkg/apiserver/domain/service/velaql.go
- pkg/stdlib/pkgs/query.cue
- pkg/velaql/providers/query/handler.go
Fixes #4118
Current, like this:
I have:
> Fix: fail to query the application logs with the special characters

- charts/vela-core/templates/defwithtemplate/ref-objects.yaml
- charts/vela-minimal/templates/defwithtemplate/ref-objects.yaml
- vela-templates/definitions/internal/component/ref-objects.cue
invalid field of parameter cause validating webhook or application apply failed when use ref-objects component. so update the parameter definition to the correct version, according to [ObjectReferrer](https://github.com/jiangshantao-dbg/kubevela/blob/92fa67cd6961a28fd388298a9bb8b5162b301271/apis/core.oam.dev/v1alpha1/component_types.go#L33)
use the correct version of the `ref_objects.ObjectReferrer` to define the optional fields of the cue parameter type `#K8sObject`
Fixes  #4318
I have:
> Fix: ref-objects parameter with invalid field definition

- references/cli/addon.go
> Chore: refine the output of velaux addon 

- pkg/apiserver/domain/service/cloudshell.go
- pkg/apiserver/domain/service/env.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/event/sync/convert/convert.go
- pkg/apiserver/event/sync/cr2ux_test.go
- pkg/apiserver/event/sync/store.go
- pkg/apiserver/event/sync/testdata/test-app4.yaml
- pkg/apiserver/interfaces/api/dto/v1/types.go
Allow different env to bind the same target when syncing the application.
Fixes #
I have:
> Fix: the target conflict when syncing the application

- cmd/core/main.go
- pkg/monitor/watcher/application.go
Reuse application informer for recording application metrics to reduce memory use.
I have:
> Feat: reuse informer for app metrics

- pkg/apiserver/domain/repository/application.go
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/application_test.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/interfaces/api/application.go
- pkg/apiserver/interfaces/api/dto/v1/types.go
refer to kubevela/velaux#572
Fixes: #4233
I have:
> Feat: supports multiple difference compare modes

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component.go
- pkg/resourcekeeper/containsresources.go
- pkg/utils/k8s.go
Kubernetes resources support names containing character ':', but label does not allow it. This PR escapes the name when filling it into the value of label.
> Fix: escape resource name for label selector

- pkg/appfile/appfile.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope.go
- pkg/cue/definition/template.go
- pkg/oam/util/helper.go
HealthCheck will get applied resources. The resource will use the following procedure to determine the namespace:
1. If namespace is overrode by `topology` policy / other, use the override namespace
2. If not overrode, and the resource is specified with namespace (for example, use ref-objects or k8s-objects), use the original namespace
3. If not override and not explicitly specified, use the application's namespace.
Previously, Rule 2 is not working so HealthCheck will fail in cases that resources are explicitly specified with namespace. This PR fixes it.
I have:
> Fix: health check use original ns if no override and original exists

- charts/vela-core/templates/defwithtemplate/expose.yaml
- charts/vela-minimal/templates/defwithtemplate/expose.yaml
- vela-templates/definitions/internal/trait/expose.cue
Add status check for expose trait.
If the expose service is LoadBalancer, the health check will wait the ingress ip to be available.
I have:
> Feat: add status check for expose trait

- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/application_test.go
- pkg/apiserver/domain/service/config_test.go
- pkg/apiserver/domain/service/util.go
- pkg/apiserver/domain/service/util_test.go
- pkg/apiserver/interfaces/api/dto/v1/types.go
- pkg/apiserver/utils/bcode/001_application.go
> Feat: velaux support override policy

- pkg/apiserver/domain/service/rbac.go
> Fix: the project manager no permission to query the project base info

- apis/types/types.go
- charts/vela-core/templates/defwithtemplate/gateway.yaml
- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/gateway.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- go.mod
- go.sum
- pkg/stdlib/pkgs/query.cue
- pkg/utils/common/common.go
- pkg/velaql/providers/query/collector.go
- pkg/velaql/providers/query/endpoint.go
- pkg/velaql/providers/query/handler.go
- pkg/velaql/providers/query/handler_test.go
- pkg/velaql/providers/query/suite_test.go
- pkg/velaql/providers/query/testdata/gateway/crds/gateway.networking.k8s.io_gateways.yaml
- pkg/velaql/providers/query/testdata/gateway/crds/gateway.networking.k8s.io_httproutes.yaml
- pkg/velaql/providers/query/testdata/gateway/gateway.yaml
- pkg/velaql/providers/query/testdata/gateway/http-route.yaml
- pkg/velaql/providers/query/tree_test.go
- pkg/velaql/providers/query/types/type.go
- references/cli/status.go
- vela-templates/definitions/internal/component/webservice.cue
- vela-templates/definitions/internal/trait/gateway.cue
1. Support HTTPRoute to generate endpoint.
2. Remove the ExternalName option from the webservice definition, because this option can not work.
3. Add a new field `inner` for the endpoint, the endpoint is only accessible within the cluster.
I have:
@wonderflow
> Feat: support HTTPRoute to generate endpoint

- .github/workflows/apiserver-test.yaml
- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/e2e-test.yml
- .github/workflows/go.yml
- .github/workflows/unit-test.yml
1. split unit test from e2e test for apiserver
2.  use skip-dup v4
I have:
> Chore: split unit test from e2e test for apiserver and use skip-dup v4

- docs/apidoc/swagger.json
- e2e/plugin/plugin_test.go
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/application_test.go
- pkg/apiserver/domain/service/envbinding.go
- pkg/apiserver/interfaces/api/application.go
- pkg/apiserver/interfaces/api/dto/v1/types.go
- pkg/apiserver/utils/bcode/001_application.go
- pkg/appfile/dryrun/diff.go
- pkg/appfile/dryrun/diff_test.go
- pkg/appfile/dryrun/dryrun.go
- pkg/appfile/dryrun/suit_test.go
- pkg/utils/apply/apply.go
- references/cli/debug.go
- references/cli/dryrun.go
- references/cli/dryrun_test.go
1. Support to dry run the application on the server-side.
2. Optimize the dry run API.
3. Optimize the dry run report.
Refer to: kubevela/velaux#577
I have:
> Feat: optimize the dry run feature

- pkg/apiserver/domain/service/application.go
It should compare with the specified environment.
I have:
> Fix: only compare with the default environment

- apis/core.oam.dev/common/types.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/monitor/watcher/application.go
- pkg/workflow/hooks/data_passing.go
- pkg/workflow/hooks/data_passing_test.go
- pkg/workflow/tasks/custom/task.go
- pkg/workflow/tasks/custom/task_test.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/tasks/discover_test.go
- pkg/workflow/types/types.go
- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
This PR adds pending phase for workflow step, for example, if the step is executed but waiting for its inputs or depends on other steps, now its phase is `pending` and message is `Pending on Inputs/DependsOn: xxx`.
Previously, if the step is executed but waiting for its inputs, the step will have no status, and the backoff time will not work.
I have:
> Feat: add pending phase in workflow step

- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
> [Backport-1.4]: fix backoff time after default backoff times (backport of #4413)

- pkg/utils/load.go
Signed-off-by: ZhongsJie <zhongsjie@cmbchina.com>
I have:
> Fix: ignore save when source is local path

- pkg/utils/file.go
- references/cli/addon_test.go
- references/cli/kube.go
- references/cli/kube_test.go
- references/cli/test-data/kubeapply/kube.cue
- references/cli/test-data/kubeapply/kube.json
- references/cli/test-data/kubeapply/kube.yaml
1. Support the following format and add tests.
```
vela kube apply -f my.cue --cluster cluster-1
vela kube apply -f my.json --cluster cluster-1
```
2. Align the dry-run flag from `--dryrun` to `--dry-run`. This is a break change but only CLI usage affect.
I have:
> Feat: support vela kube apply for CUE and JSON files

- references/cli/status.go
- references/cli/utils.go
- references/cli/utils_test.go
Added support for getting raw Application yaml in Vela CLI, via `-o` `--output` parameter.
Looking at some examples will give you a better understanding:
---
`vela status first-vela-app -o yaml`
<details>
<summary>Click to see command output</summary>
```yaml
metadata:
annotations:
app.oam.dev/last-applied-configuration: '{"kind":"Application","apiVersion":"core.oam.dev/v1beta1","metadata":{"name":"first-vela-app","namespace":"default","creationTimestamp":null,"labels":{"oam.dev/render-hash":"ea855623cc3ffbb9"}},"spec":{"components":[{"name":"express-server","type":"webservice","properties":{"image":"oamdev/hello-world","ports":[{"expose":true,"port":8000}]},"traits":[{"type":"scal …
```
> Feat: get raw Application yaml, json or jsonpath

- pkg/addon/addon.go
- pkg/addon/addon_test.go
- references/cli/addon.go
Fixes #4311 
How to fix it:
Merge legacy parameters and new input parameters.
1. if legacy parameters do not exist, use new parameters
2. if legacy parameters exists, merge them and new parameter overwrite the legacy one
I have:
> Fix: vela addon upgrade missing the history args

- pkg/apiserver/domain/model/application.go
- pkg/apiserver/domain/model/whole.go
- pkg/apiserver/domain/model/workflow.go
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/image.go
- pkg/apiserver/domain/service/workflow.go
- pkg/apiserver/domain/service/workflow_test.go
- pkg/apiserver/event/event.go
- pkg/apiserver/event/sync/cache.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/event/sync/convert/convert.go
- pkg/apiserver/event/sync/cr2ux.go
- pkg/apiserver/event/sync/store.go
- pkg/apiserver/event/sync/worker.go
- pkg/apiserver/event/sync/worker_test.go
- pkg/apiserver/interfaces/api/assembler/v1/dto2do.go
- test/e2e-apiserver-test/application_sync_test.go
- test/e2e-apiserver-test/suite_test.go
- test/e2e-apiserver-test/testdata/component-pod-view.yaml
- test/e2e-apiserver-test/testdata/example-app.yaml
- test/e2e-apiserver-test/velaql_test.go
1. Sync the application revision to the datastore, this is useful to back up the application configuration. But currently, only sync the application spec.
2. Sync the workflow record to the datastore, users could resume the workflow via UI.
3. Do not allow to change the inner labels via API. such as `ux.oam.dev/from-namespace` `app.oam.dev/source-of-truth` `ux.oam.dev/synced-generation`
4. Optimized the logic during application synchronization.
Fixes #
I have:
> Feat: support to sync the revision and the workflow status

- pkg/addon/addon.go
- pkg/addon/addon_suite_test.go
- pkg/addon/addon_test.go
- pkg/addon/error.go
- pkg/addon/render.go
- pkg/addon/render_test.go
- pkg/addon/source.go
- pkg/addon/type.go
- references/cli/addon.go
This pr support writing basic addon application template framework by cue, so addon-developer can define the final app with parameter.Will allow user define a `parameter.cue` file  outside `resource` dir. All parameters defined in this file will affect resources in `resources` dir and `template.cue`.
So  a new addon dir is like this:
```dir
definitions/
resources/
——component1.cue
——component2.yaml
template.cue
parameter.cue
metadata.yaml
```
Besides, this pr also dose such things:
1. Keep compatibility for old addon, new version CLI can still enable old version addon.
2. If an addon defines `deployTo.runtimeCluster=true` want to deploy to runtime clusters but still don't have a topology polocy, we assume it's a legacy addon, will attach a topology policy to this app,  not two …
> Feat: Addon support app template written by cuelang.

- pkg/apiserver/domain/model/system_info.go
- pkg/apiserver/domain/service/authentication.go
- pkg/apiserver/domain/service/authentication_test.go
- pkg/apiserver/domain/service/user.go
- pkg/apiserver/domain/service/velaql.go
This PR support login with the code but does not need to set the login mode to dex. In this way, the user can test the use of dex to complete the authentication before switching the login mode.
In addition, added more dex configuration parameters.
I have:
> Fix: support to test authentication with dex

- Dockerfile.cli
- pkg/utils/common/common.go
- pkg/velaql/providers/query/types/type.go
- references/cli/portforward.go
- references/cli/status.go
- references/cli/utils.go
- references/cli/velaql.go
- references/cli/velaql_test.go
- references/common/application.go
- references/docgen/def-doc/trait/service-account.eg.md
- references/docgen/parser.go
adapt vela port-forward with the velaql 
I have:
> Feat: adapt vela port-forward with the velaql

- pkg/addon/addon.go
- pkg/addon/render.go
- pkg/addon/render_test.go
- pkg/addon/utils.go
> Feat: support outputs for addon

- pkg/appfile/parser.go
- pkg/features/controller_features.go
For security issues, allowing url in ref-objects could lead to potential risks. This PR allows administrator to decide whether to enable this feature. (By default, this is enabled.) 
I have:
> Feat: add featuregates to disallow url in ref-objects

- pkg/workflow/providers/kube/handle.go
> Fix: The apply failure error is ignored when the workflow is executed

- pkg/addon/init.go
- pkg/addon/render.go
The addon internal rendering logic (black-box) may confuse some users, e.g.:
- app `name` in `template.yaml/cue` is not working
- app `namespace` in `template.yaml/cue` is not working
- `deployTo` in metadata/yaml is not working when they have `topology` enabled
**This pr shows some warnings to let the user know what's going on and what to do**
```
W0726 21:19:31.278144 3891326 render.go:194] Application name some-name will be overwritten with addon-sample-addon-cue. Consider removing metadata.name in template.
W0726 21:19:31.278162 3891326 render.go:199] Namespace some-ns will be overwritten with vela-system. Consider removing metadata.namespace in template.
W0726 21:19:31.278477 3891326 render.go:357] deployTo in metadata will …
```
> Feat: show warnings about internal addon rendering logic

- pkg/policy/common_test.go
- pkg/policy/envbinding/utils.go
- pkg/policy/override.go
- pkg/policy/override_test.go
- pkg/policy/topology.go
- pkg/policy/topology_test.go
- pkg/resourcekeeper/gc.go
- pkg/workflow/providers/multicluster/deploy.go
- pkg/workflow/providers/multicluster/deploy_test.go
The [topology doc](https://kubevela.net/docs/next/end-user/policies/references#specification-topology) shows that every property is not required.
<details>
<summary>Click to see app sample</summary>
```yaml
metadata:
spec:
components: []
policies:
- name: target-default
type: topology
properties:
```
</details>
But if we actually don't provide any properties in topology, after applying the sample app, vela-core will 
- crash immediately due to nil pointer dereference
- will **NOT** recover after restarting, because the reconcilation starts again
So the vela-core will keep restarting over and over, and no Application can be created afterwards.
This pr fixes …
> Fix: address vela-core crash due to empty policy properties

- pkg/policy/common_test.go
- pkg/policy/envbinding/utils.go
- pkg/policy/override.go
- pkg/policy/override_test.go
- pkg/policy/topology.go
- pkg/policy/topology_test.go
- pkg/resourcekeeper/gc.go
- pkg/workflow/providers/multicluster/deploy.go
- pkg/workflow/providers/multicluster/deploy_test.go
> [Backport release-1.5] Fix: address vela-core crash due to empty policy properties

- pkg/policy/common_test.go
- pkg/policy/envbinding/utils.go
- pkg/policy/override.go
- pkg/policy/override_test.go
- pkg/policy/topology.go
- pkg/policy/topology_test.go
- pkg/resourcekeeper/gc.go
- pkg/workflow/providers/multicluster/deploy.go
- pkg/workflow/providers/multicluster/deploy_test.go
* Fix: fix topology core crash
* Test: add tests
* Fix: same problem in other places
* Style: remove empty line
* Feat: raise error when empty topology is used
* Feat: raise error when empty override policy is used
Fixes #
I have:
> [Backport release-1.4] Fix: address vela-core crash due to empty policy properties (#4473)

- references/cli/delete.go
- references/common/application.go
Signed-off-by: suxiang <704427617@qq.com>
Fixes #4271
I have:
```
vela delete vela-app-01 vela-app-02 vela-app-03
vela delete vela-app-01 vela-app-02 vela-app-03 -y
vela delete vela-app-01 vela-app-02 vela-app-03 -y -w -f
vela delete vela-app-01 vela-app-02 vela-app-03 -y -w
```
> Feat: delete multi apps from vela delete cli command

- pkg/apiserver/domain/service/config.go
Fix: Repeat query configuration type #4487
I have:
> Fix: repeat query configuration type

- references/cli/cli.go
- references/cli/system.go
Signed-off-by: foursevenlove <foursevenlove@gmail.com>
Feat #3924
I have:
- run ` vela system info ` to check all detail system information
- run ` vela system diagnose ` to diagnose system's health
@Somefive
> Feat: System Info & Diagnose

- pkg/addon/addon.go
- pkg/addon/addon_suite_test.go
- pkg/addon/addon_test.go
- pkg/addon/utils.go
- pkg/addon/utils_test.go
- references/cli/addon.go
1. fix bug check an  addon whether been used when disable.
2. add check definitions of an addon whether exist.
3. fix check addon system requirement special case bug: `actual: v1.5.0-beta.1` require:  `>=1.5.0` res: `ture`
Fixes #
I have:
> Fix: check definition of addon whether is conflict 

- pkg/apiserver/domain/service/cloudshell.go
- pkg/apiserver/domain/service/cloudshell_test.go
- pkg/apiserver/domain/service/rbac.go
- pkg/apiserver/interfaces/api/cloudshell.go
- pkg/apiserver/utils/auth.go
- pkg/auth/privileges.go
The role is only bound to the group, the user is bound to the group and gets permissions. the relationship between the user and the group save to the cert in the Kube config, which will be updated before the cloud shell environment is created.
Fixes #4489
I have:
> Fix: CloudShell read-only authorization is not automatically revoked

- pkg/appfile/appfile.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/cue/definition/template.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-bad-resource.yaml
When dispatching resources for application component, 
- `apply-component`: directly apply component, then check health
- `deploy`: first check if component is healthy, if not healthy, apply the component
Therefore, it apply component fails, the `apply-component` will always block the workflow step (which is correct). But for `deploy` step, if apply component fails but health check passes (this is weird but could happen if we do not have healthPolicy in component definition), the workflow step will fail for the first time (since RT has no records) but then succeeded directly for the second time.
This PR fixes it by enforcing object existence check even if healthPolicy is empty.
Besides, there is another bug fixed in this PR. When trait …
> Fix: empty health policy do not check object existence

- pkg/apiserver/interfaces/api/authentication.go
Backport of https://github.com/kubevela/kubevela/pull/4512 to release-1.5.
> [Backport release-1.5] Fix: missing return when token is null

- pkg/builtin/http/http.go
- pkg/workflow/providers/http/do_test.go
Signed-off-by: suxiang <704427617@qq.com>
Fixes #3157
I have:
> Feat: add http status and code from http cmd run

- pkg/velaql/providers/query/collector.go
- pkg/velaql/providers/query/tree.go
- pkg/velaql/providers/query/tree_test.go
1. Add a  default tree rule: `DaemonSet->Pod`.
2. Add a default label selector function.
3. Support binding the default label selector for the custom rule.
Example:
```
- parentResourceType:
group: apps.kruise.io
kind: CloneSet
childrenResourceType:
- apiVersion: v1
kind: Pod
defaultLabelSelector: true
```
This means querying the pod by label selector. If not, it will list all pods in the namespace and filter by OwnerReferences.
The requirement is the resource(CloneSet) has the field `spec.selector`.
I have:
> Feat: add the daemonset resource rule for building the tree

- apis/core.oam.dev/v1alpha1/garbagecollect_types.go
- apis/core.oam.dev/v1beta1/resourcetracker_types.go
- apis/core.oam.dev/v1beta1/resourcetracker_types_test.go
- charts/vela-core/crds/core.oam.dev_resourcetrackers.yaml
- charts/vela-minimal/crds/core.oam.dev_resourcetrackers.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_resourcetrackers.yaml
- pkg/resourcekeeper/componentrevision.go
- pkg/resourcekeeper/delete.go
- pkg/resourcekeeper/dispatch.go
- pkg/resourcekeeper/dispatch_and_delete_test.go
- pkg/resourcekeeper/gc.go
- pkg/resourcekeeper/gc_suite_test.go
- pkg/resourcekeeper/gc_test.go
- pkg/resourcekeeper/options.go
- pkg/resourcekeeper/options_test.go
- pkg/resourcetracker/app.go
- pkg/resourcetracker/app_test.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-gc-policy-change.yaml
This PR allows changing resource recycle strategy from **onAppUpdate** (default behaviour) to **never** (**onAppDelete**) also supported. But once it becomes **never** or **onAppDelete**, it cannot be changed anymore. So the feature in this PR is WEAK and NOT WELL FORMED.
> P.S. This feature is not documented. It is against the initial design and weirdly implemented.
I have:
> Feat: support change resource gc policy from onAppUpdate to Never

- e2e/addon/mock/testdata/mock-addon/definitions/json-patch.cue
- e2e/addon/mock/testdata/mock-addon/readme.md
- pkg/addon/addon.go
- pkg/addon/utils.go
- pkg/addon/utils_test.go
- pkg/addon/versioned_registry.go
- pkg/apiserver/domain/service/addon.go
- pkg/oam/labels.go
- test/e2e-apiserver-test/addon_test.go
1. addon check definition whether binding a  component, if this component not exist don't apply it.
2. apiserver show readme.md
3. apiserver show cue definition
Fixes #
I have:
> Feat: Check def binding to a component

- pkg/addon/addon.go
- pkg/addon/render.go
- pkg/addon/utils.go
Signed-off-by: ghostloda <78798447@qq.com>
Fixes #2982
I have:
./vela addon enable catalog-master/addons/velaux/
enable addon by local dir: catalog-master/addons/velaux/ 
W0803 10:13:47.394796   41115 render.go:194] Application name velaux will be overwritten with addon-velaux. Consider removing metadata.name in template.
Error: render addon definitions' schema fail: error rendering file addon-uischema-velaux.yaml: yaml: mapping values are not allowed in this context
> Feat: report the manifest name when addon enabling failed

- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_test.go
To handle resources from AggregatedServer like vela-prism that has no resource version (like GrafanaDashboard and GrafanaDatasource), ignore the owner label check while dispatching resource.
Work around for issue https://github.com/kubevela/prism/issues/23.
I have:
> Feat: ignore control check for resource from aggregate apiserver without resource version

- apis/core.oam.dev/v1beta1/resourcetracker_types.go
- apis/core.oam.dev/v1beta1/resourcetracker_types_test.go
When application upgrades, sometimes, resources also have version upgrade but different version of the resource are still one identical resource. For example, application v1 dispatch `networking.k8s.io/v1beta1` Ingress and v2 dispatch `networking.k8s.io/v1` Ingress, although they are the same, since ResourceTracker compares resource with version previously, they are treated as different resources and therefore delete the old Ingress.
This PR skips the check for equality for version but only compares the APIGroup and Kind.
I have:
> Fix: compare resource without version

- pkg/apiserver/domain/service/config.go
- pkg/apiserver/domain/service/config_test.go
- pkg/apiserver/domain/service/tags.go
- pkg/apiserver/domain/service/tags_test.go
- pkg/definition/definition.go
- references/cli/provider.go
- references/cli/provider_test.go
In vela CLI < v1.5.0, `vela addon enable` will add a prefix ("custom.definition.oam.dev") to label of definition came with addon.  This logic is removed in v1.5.0
However it effect `vela provider list` behavior. Which still reading ComponentDefinition with Label `"custom.definition.oam.dev:type.config.oam.dev": terraform-xxx`. This PR make provider command compatible with both type of label.
Fixes #4558
I have:
UT added
> Fix: vela CLI provider compatibility

- pkg/appfile/parser.go
- pkg/appfile/parser_test.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go
This PR is a follow up of: https://github.com/kubevela/kubevela/pull/4473
Previously, applying such app will succeed.
```yaml
metadata:
spec:
components: []
policies:
- name: target-default
type: topology
properties:
```
Now, it will be rejected by validating admission webhooks:
```
Error from server: error when creating "vela.yaml": \
admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: \
field "spec": Invalid value error encountered, \
failed to parsePolicies: policy topology named target-default must not have empty properties. 
```
Fixes #
I have:
> Fix: reject applications with empty policy properties

- pkg/resourcekeeper/cache.go
- pkg/resourcekeeper/cache_test.go
While recycling resources, the old logic ignores the resource that does not have the correct owner label, which will make it unable to recycle GrafanaDashboard/GrafanaDatasource. This PR disable this check when resource has no ResourceVersion.
I have:
> Fix: gc resource without resourceversion

- .github/workflows/issue-commands.yml
The backport bot uses `ubuntu-18.04`, which will be deprecated by 12/1/22 and failures are expected to start since 8/22/22
This pr upgrades it to `ubuntu-20.04`. 
Should buy us two more years.
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
Fixes #
I have:
> Chore: update backport bot os

- pkg/apiserver/event/sync/store.go
- pkg/apiserver/event/sync/worker_test.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_test.go
- references/cli/addon.go
Before updating the policy should assign the create time by the old data.
Fixes #
I have:
> Fix: the create time of the synced policies is zero

- pkg/resourcekeeper/gc.go
SkipGC uses the incorrect context while updating labels for multi-cluster resources.
I have:
> Fix: skipGC remove labels for multi-cluster resource not use correct ctx

- pkg/cue/model/sets/operation.go
- pkg/cue/model/sets/utils.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-with-env-labels-storage.yaml
When env exists in webservice component, the use of labels + storage traits will eliminate the env field in webservice.
For example:
```yaml
metadata:
name: test
spec:
components:
- name: test
properties:
cmd:
- sleep
- -c
- "86400"
env:
- name: testKey
value: testValue
image: busybox
imagePullPolicy: IfNotPresent
traits:
- properties:
key: val
type: labels
- properties:
pvc:
- accessModes:
- ReadWriteOnce
mountOnly: false
mountPath: /data
name: lvhyca
resources:
requests:
storage: 4096Mi
storageClassName: default
volumeMode: Filesystem
type: storage
```
The reason is that when `labels` trait patches, it uses `json-merge-patch`, which convert CUE into JSON and patch, then …
> Fix: open basic lit fails lookup path to KubeVela 1.5

- apis/core.oam.dev/v1beta1/resourcetracker_types.go
- apis/core.oam.dev/v1beta1/resourcetracker_types_test.go
- charts/vela-core/README.md
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- go.mod
- go.sum
- makefiles/e2e.mk
- pkg/features/controller_features.go
- pkg/resourcetracker/app.go
- pkg/utils/compression/types.go
- pkg/utils/compression/zstd.go
- pkg/utils/compression/zstd_test.go
This pr continues #4613 
Fixes #4392
[`zstd`](https://github.com/facebook/zstd) is a modern real-time compression algorithm developed by Meta, which is fast and efficient. In terms of speed, it is typically 2x as fast as the stdlib deflate/gzip in its fastest mode. The compression ratio compared to stdlib is around level 3, but usually 3x as fast.
It is not only faster, but also compresses data better. We can get size-reductions while not giving up much on performance by adopting `zstd`.
There are benchmarks which use real CRDs to simulate a real use-case in `resourcetracker_types_test.go`. The user must have large ResourceTrackers if they want to use compression, so we load real CRDs to test, instead of generating fake data.
To …
> Feat: support zstd compression in resourcetracker

- pkg/apiserver/domain/model/system_info.go
- pkg/apiserver/domain/service/authentication.go
- pkg/apiserver/domain/service/system_info.go
> Fix: fix signedKey using platform id

- references/cli/top/config/color.go
- references/cli/top/model/cluster_namespace.go
- references/cli/top/model/managed_resource_test.go
- references/cli/top/model/namespace.go
- references/cli/top/model/namespace_test.go
- references/cli/top/model/pod.go
- references/cli/top/model/pod_test.go
- references/cli/top/model/resource.go
- references/cli/top/model/resource_test.go
- references/cli/top/model/suit_test.go
- references/cli/top/model/type.go
- references/cli/top/utils/metrics.go
- references/cli/top/utils/time.go
- references/cli/top/utils/time_test.go
- references/cli/top/view/managed_resource_view.go
- references/cli/top/view/pod_view.go
- references/cli/top/view/pod_view_test.go
- references/cli/top/view/resource_view.go
At present, there are only two levels in the resource level of `vela top`, namely `Application view` and  `Managed resource view`. However, in fact, there is a pod level under the managed resource. The status of the pod may be an information that users are very concerned about. Therefore, it is very necessary to continue to explore the resource level of `vela top` to the pod level.
In the managed resource view, we can add the feature of continuing to explore at the resource level. We can select a managed resource and view the status of the pod created by the resource.
There are many status information of the pod. You can select some important information for display, such as:
- Name
- Namespace
- Ready Condition
- Status
- CPU and MEM usage condition
- IP
- Node
- Age
Signed-off-by: …
> Feat: add a new resource level view: `Pod view` to `vela top`

- charts/vela-core/README.md
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- cmd/core/main.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/features/controller_features.go
- pkg/resourcekeeper/dispatch.go
Fixes #4642
Add FeatureFlag `ApplyOnce` which will enable the apply-once feature for all applications. This will
1. Disable the storage of resource data in ResourceTracker (only metadata is kept).
2. Skip the StateKeep stage in application controller.
3. The re-sync period for application is set to the informer sync period (by default 10 hours).
The re-sync period for application is also configuration in controller now. (Not available in helm chart since it is not recommended to configure for the most time. The default value of 10 hours is aligned with the [controller-runtime settings](https://github.com/kubernetes-sigs/controller-runtime/blob/bf71fc56485f6bf03e95ef6b0233ff36c695d4c9/pkg/cache/cache.go#L133).)
I have:
> Feat: add controller parameters for apply-once

- pkg/definition/definition.go
fix bug, use labels to replace annotation
Fixes #
I have:
> Fix: vela def wrongly use annotation to store user label

- test/e2e-multicluster-test/suite_test.go
Fix flaky test here: https://github.com/kubevela/kubevela/runs/8104046030?check_suite_focus=true by deleting addons in order to avoid app stuck in `deleting` status.
Fixes #
I have:
> Fix: flaky CI test

- .github/workflows/apiserver-test.yaml
- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/e2e-test.yml
- test/e2e-multicluster-test/multicluster_standalone_test.go
1. Add v1.23 to regular CI test.
2. Add concurrency constraints to make efficient use of self-hosted machines.
Fixes #
I have:
> Chore: Add v1.23 to regular CI test

- pkg/addon/addon_suite_test.go
- pkg/addon/utils.go
fix bug of enabling addon cannot update definition
Fixes #
I have:
> Fix: enabling addon cannot update definition bug

- pkg/velaql/providers/query/tree.go
Change the logging level of `error to list sub-resources` from "error" to "warning".
Fixes #4614 
I have:
This PR just changes the logging level. No need to add extra tests.
> Fix: useless log when enabling addon

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- vela-templates/definitions/internal/component/webservice.cue
Enable user to specify nodePort if use nodePort type Service.
Adding this argument because we want to expose VelaUX with fixed nodeport. See https://github.com/kubevela/catalog/pull/461
Finally, rewrite the installation part of kubevela.io
Fixes #
I have:
> Feat: add nodeport in webservice

- references/cli/uninstall.go
- references/cli/uninstall_test.go
Issue: when running `vela uninstall`, the uninstallation process **continues** even when the user said **NO**.
This PR fixes this issue.
Fixes #
I have:
> Fix: resolve an issue where uninstallation continues even if user says no

- go.mod
- go.sum
Signed-off-by: barnettZQG [barnett.zqg@gmail.com](mailto:barnett.zqg@gmail.com)
Backport of https://github.com/kubevela/kubevela/pull/4721 to release-1.4.
> [Backport release-1.4] Fix: CVE-2022-27664 (#4721)

- e2e/commonContext.go
- e2e/trait/trait_test.go
- e2e/workload/workload_test.go
- references/cli/show.go
```
docgen/GenrateReerenceDocs  (dm already init) ----> CreateMarkdown -> GenerateMakrdownForCap (Need DiscoveryMapper)
show/startReferenceDocsSite (add dm init here) --|
show/ShowReferenceMarkdown (add dm init here)  --|
```
Fixes #4697
I have:
Add e2e test for markdown format
> Fix: vela show panic for component markdown format

- pkg/velaql/providers/query/endpoint.go
- pkg/velaql/providers/query/endpoint_test.go
- pkg/velaql/providers/query/handler_test.go
- pkg/velaql/providers/query/types/type.go
- references/cli/velaql_test.go
When service type is LoadBalancer, the actual exposed port is `port.nodePort` in status. per https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
Test: 
Fixes #
I have:
> Fix: wrong endpoint for LoadBalancer type service

- pkg/workflow/step/generator.go
WorkflowStepGenerator will panic (DeployPreApproveWorkflowStepGenerator) when deploy step properties is not set.
I have:
> Fix: panic when properties empty

- pkg/addon/addon.go
- pkg/addon/addon_suite_test.go
- pkg/addon/utils.go
- references/cli/addon.go
Fixes #4371
Ref: https://github.com/kubevela/kubevela/discussions/4366
Users can use like this:
```
vela addon enable velaux --dry-run > test.yaml
kubectl apply -f test.yaml
```
or 
```
vela addon enable velaux --dry-run | kubectl apply -f -
```
I have:
> Feat: support addon dry-run to get the yaml results

- references/cli/top/component/app.go
- references/cli/top/component/crumbs.go
- references/cli/top/component/crumbs_test.go
- references/cli/top/component/menu.go
- references/cli/top/component/menu_test.go
- references/cli/top/component/pages.go
- references/cli/top/component/pages_test.go
- references/cli/top/component/table.go
- references/cli/top/model/info_test.go
- references/cli/top/model/stack.go
- references/cli/top/model/stack_test.go
- references/cli/top/view/app.go
- references/cli/top/view/application_view.go
- references/cli/top/view/application_view_test.go
- references/cli/top/view/cluster_namespace_view.go
- references/cli/top/view/cluster_namespace_view_test.go
- references/cli/top/view/cluster_view.go
- references/cli/top/view/cluster_view_test.go
- references/cli/top/view/managed_resource_view.go
- references/cli/top/view/managed_resource_view_test.go
- references/cli/top/view/namespace_view.go
- references/cli/top/view/namespace_view_test.go
- references/cli/top/view/page_stack.go
- references/cli/top/view/page_stack_test.go
- references/cli/top/view/pod_view.go
- references/cli/top/view/pod_view_test.go
- references/cli/top/view/resource_view.go
- references/cli/top/view/resource_view_test.go
- references/cli/top/view/yaml_view.go
1. Add the key action R related to the refresh action. Users can press the key **R** to refresh the resource view. And more the view will refresh auto in every 10 second.
2. I separate view initialization and data loading. Data loading uses a separate goroutine, and then the UI is redrawn after loading. On the user side, it seems that the view switching is responsive in seconds, but the data will be refreshed later.
Fixes #4741 
Fixes #4742
I have:
> Feat: add feature of refreshing resource view and fix the bug of stucking

- pkg/addon/addon.go
- pkg/addon/init.go
- pkg/appfile/helm/schema.go
- pkg/controller/utils/capability.go
- pkg/definition/definition.go
- pkg/utils/common/common.go
- pkg/utils/common/common_test.go
- references/cli/def.go
Fix: use value instead of instance in openapi.gen
I have:
> Fix: use value instead of instance in openapi.gen

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
Bug: Workflow will rerun when application struct in go changes, this is the hash library's feature.
Fix: do not compare application spec hash, instead, only compare application revision name.
I have:
> Fix: disable workflow rerun when appspec struct change (v1.5)

- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-minimal/templates/kubevela-controller.yaml
Legacy rollout apiGroup `standard.oam.dev` is not included in the privileges of the controller.
I have:
> Fix: rollout privileges lack in controller

- pkg/resourcekeeper/gc.go
- pkg/resourcekeeper/gc_suite_test.go
- pkg/resourcekeeper/utils.go
- pkg/utils/k8s.go
- pkg/utils/k8s_test.go
The legacy ResourceTracker records resources without the removal of `namespace` field for cluster-scoped resources. Like fluxcd addon records `helmrelease` CRD in ResourceTracker with namespace `vela-system` which is inaccurate. 
PR #4193 fixes this but leave a comparison between legacy RTs and latest RTs. In latest fluxcd addon, when upgraded with v1.5+, the `helmrelease` CRD is recorded without the recording of namespace `vela-system` and therefore the controller mis-recognize the `helmrelease` CRD 'in vela-system' is not in-use so it is removed.
This PR adds a ResourceTracker regularization process before GC and therefore help keep compatibility between legacy RTs and latest RTs.
Fixes:
- https://github.com/kubevela/catalog/issues/470) …
> Fix: gc legacy rt with regularization

- cmd/apiserver/main.go
- cmd/core/main.go
- pkg/apiserver/config/config.go
- pkg/apiserver/event/sync/worker.go
- pkg/utils/pprof.go
There are two points:
1. The `json.Marshal` and `json.Unmarshal` consume much memory.
2. Not call the `Done` function of the queue. The app object will pile up in a queue.
Now:
|  Item  | Before | Now |
|  ----  | ----  | ----  |
| Application Number  | 700+ |  1.4K |
| Application Create/Update  | 3 request/second |   10 request/second |
| KubeVela Core Memory  | 600Mi+ | 1057Mi |
| APIServer Memory(Master) | 900Mi+ | 300Mi | 
I have:
> Fix: memory leak of the apiserver

- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/workflow/workflow.go
Bug: Workflow will rerun when application struct in go changes, this is the hash library's feature.
Fix: do not compare application spec hash, instead, only compare application revision name.
NOTE: release-1.5 uses #4754.
I have:
P.S. This PR is for master (v1.6+), for v1.5 and before, refer to #4754.
> Fix: prevent workflow rerun when app spec struct change

- references/common/application.go
- references/common/application_test.go
deleting app with configuration
Fixes #
I have:
Add unit test case。
> Fix: allow to read definition from user's namespace when force delete

- pkg/utils/env/env.go
Add duplicate name check when creating env through vela env init
Fixes #4793 
I have:
> Fix: it does not check the same name for 'vela env init'

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-lite-with-workflow.yaml
> Feat: workflow will rerun when application workflow changes

- references/cli/top/model/application.go
- references/cli/top/model/application_test.go
- references/cli/top/model/cluster.go
- references/cli/top/model/managed_resource.go
- references/cli/top/model/managed_resource_test.go
- references/cli/top/model/suit_test.go
- references/cli/top/view/app.go
- references/cli/top/view/app_test.go
- references/cli/top/view/application_view.go
- references/cli/top/view/application_view_test.go
- references/cli/top/view/cluster_namespace_view.go
- references/cli/top/view/cluster_view.go
- references/cli/top/view/help_view.go
- references/cli/top/view/managed_resource_view.go
- references/cli/top/view/resource_view.go
- references/cli/top/view/yaml_view.go
At present, the data in the app view and managed resource view are relatively thin. We should add some fields to these fields.
About application, add:
- workflow step mode
- finished workflow / total workflow
- running service / total service
About managed resource, add:
- of which component
---
And more, change the key to return to the previous view to **Q** key, the function of the ESC key is to exit on the home page.
Fixes #4780
I have:
> Feat: Add more data field to application view and managed resource view in vela top

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-lite-with-workflow.yaml
Cherry-pick #4808 into release-1.5.
I have:
> [Backport release-1.5] Feat: workflow will rerun when application workflow changes

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/gc_policy_test.go
Fixes #4818 
I have:
Pass the application_controller_test which was failed before in testenv 1.24.
> Fix: Update Ingress APIVersion form v1beta1 to v1 in test case

- references/cli/top/component/tree_node.go
- references/cli/top/component/tree_node_test.go
- references/cli/top/model/application.go
- references/cli/top/model/application_test.go
- references/cli/top/model/suit_test.go
- references/cli/top/view/application_topology_view.go
- references/cli/top/view/application_topology_view_test.go
- references/cli/top/view/application_view.go
- references/cli/top/view/application_view_test.go
- references/cli/top/view/cluster_namespace_view.go
- references/cli/top/view/cluster_view.go
- references/cli/top/view/command.go
- references/cli/top/view/help_view.go
- references/cli/top/view/help_view_test.go
- references/cli/top/view/managed_resource_view.go
- references/cli/top/view/namespace_view.go
- references/cli/top/view/pod_view.go
- references/cli/top/view/yaml_view.go
Every application deployment plan can be composed by multiple components with attachable operational behaviors (traits), deployment policy and workflow. So, the first topology we show is to show the four components of the application, this topology is called the "App Topology".
In addition, these components will actually eventually be loaded as native resources or CRDs in Kubernetes, and these resources constitute another resource topology. As a user, you must want to know whether the sub-resources of the application are correctly deployed as required, you can get the answer from this topology, which we call the "Resource Topology".
Fixes #4787
I have:
> Feat: add resource topology view in `vela top`

- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/cue/process/handle.go
- pkg/cue/process/keyword.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-component-with-cluster-context.yaml
- test/e2e-multicluster-test/testdata/def/cluster-config.yaml
```cue
output: {
apiVersion: "v1"
kind: "ConfigMap"
metadata: name: context.name
data: cluster: context.cluster
}
parameter: {}
```
```yaml
metadata:
name: app-component-with-cluster-context
spec:
components:
- name: test
type: cluster-config
policies:
- name: topology
type: topology
properties:
clusterLabelSelector: {}
```
The above application will create a ConfigMap in each cluster. The data in the ConfigMap contains the name of the corresponding cluster.
I have:
> Feat: support context.cluster in applyComponent

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
In version before v1.6.0-alpha.4, applications with revision under v1.5.7 (not released yet) and revision under v1.6.0-alpha.4 (released), application revision (without PublishVersion) does not record workflow in Application Spec inside, which will lead to inequality with revisions created by latest KubeVela.
This PR adds additional rules for bypassing the comparing application workflow when
1. PublishVersion is not used
2. Application is created under KubeVela version v1.5.7. 
I have:
> Fix: prevent rerun app while upgrade due to old apprev lack app workflow

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
Backport #4852 to release-1.5.
I have:
> [Backport release-1.5] Fix: prevent rerun app while upgrade due to old apprev lack app workflow

- pkg/config/factory.go
The output objects of the config maybe are cluster scope resources or belong to other namespaces. So, cannot set the owner references.
I have:
> Fix: remove the owner references

- apis/core.oam.dev/v1alpha1/policy_types.go
- charts/vela-core/templates/defwithtemplate/topology.yaml
- charts/vela-minimal/templates/defwithtemplate/topology.yaml
- pkg/policy/topology.go
- pkg/policy/topology_test.go
- vela-templates/definitions/internal/policy/topology.cue
In the past, if no cluster is selected from clusterLabelSelector, an error will be thrown.
In addon, now we have one scenario where only non-control-plane clusters are selected and used, which means in single cluster mode there will be no cluster selected for this selector. To prevent the error, this PR adds an `allowEmpty` field to bypass the empty cluster error.
I have:
> Feat: allow empty cluster for cluster selector

- references/cli/top/model/log.go
- references/cli/top/model/log_test.go
- references/cli/top/model/pod.go
- references/cli/top/model/pod_test.go
- references/cli/top/model/suit_test.go
- references/cli/top/model/type.go
- references/cli/top/view/command.go
- references/cli/top/view/help_view.go
- references/cli/top/view/help_view_test.go
- references/cli/top/view/log_view.go
- references/cli/top/view/log_view_test.go
- references/cli/top/view/pod_view.go
- references/cli/top/view/pod_view_test.go
1. add the feature of viewing log of pod in `vela top`
2. add content to help view
3. add cluster data field to pod view
Fixes #4869
I have:
> Feat: add the feature of viewing log of pod in `vela top`

- references/cli/addon.go
The workflow is already failed, but the CLI still waiting it.
I have:
> Fix: exit waiting after the workflow failed

- pkg/addon/addon.go
- pkg/config/factory.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componetrevision_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/test-data/webservice-cd.yaml
- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
- pkg/controller/utils/capability.go
- pkg/cue/script/schema.go
- pkg/cue/script/template.go
- pkg/cue/script/template_test.go
We can not look up the values from the template CUE which maybe has incomplete values or context values. Because of this, the definition can not generate the API schema. This issue is introduced by #4794 
I have:
> Fix: the api schema can not be generated

- apis/types/multicluster.go
- charts/vela-core/templates/defwithtemplate/gateway.yaml
- charts/vela-minimal/templates/defwithtemplate/gateway.yaml
- cmd/core/main.go
- pkg/apiserver/domain/service/cluster.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/cue/definition/template_test.go
- pkg/cue/process/handle.go
- pkg/cue/process/handle_test.go
- pkg/cue/process/keyword.go
- pkg/multicluster/cluster_management.go
- pkg/multicluster/cluster_metrics_management_test.go
- pkg/multicluster/virtual_cluster.go
- pkg/multicluster/virtual_cluster_test.go
- pkg/workflow/operation/operation.go
- references/cli/cluster.go
- test/e2e-multicluster-test/suite_test.go
- vela-templates/definitions/internal/trait/gateway.cue
Fixes #4785
1. Use case 1: use minor version to judge api
```
outputs: ingress: {
if context.clusterVersion.minor < 19 {
apiVersion: "networking.k8s.io/v1beta1"
}
if context.clusterVersion.minor >= 19 {
apiVersion: "networking.k8s.io/v1"
}
kind: "Ingress"
}
```
2. Use case 2: use gitVersion to judge provider
```
import "strings"
if strings.Contains(context.clusterVersion.gitVersion, "k3s") {
provider: "k3s"
}
if strings.Contains(context.clusterVersion.gitVersion, "aliyun") {
provider: "aliyun"
}
```
I have:
> Feat: support context.clusterVersion for definition graceful upgrade

- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/application_test.go
- references/cli/addon.go
After we apply the application, the controller may be can not reconcile it timely. At this time the generation is greater than the observed generation. 
I have:
> Feat: Refer to the generation when checking the application status

- pkg/controller/utils/capability_test.go
- pkg/cue/script/schema.go
- pkg/utils/common/common.go
- pkg/utils/common/common_test.go
- pkg/utils/common/testdata/workload1.cue
- pkg/utils/common/testdata/workload1.json
> Fix: deprecated resolve reference in gen open API

- e2e/addon/mock/testdata/not-match-addon/metadata.yaml
- pkg/apiserver/domain/service/addon.go
- test/e2e-apiserver-test/addon_test.go
Enabling an addon with velaux, if system requirement not match explicit error info.
Fixes #
I have:
> Fix: explicit error info for enabling addon with velaux

- pkg/apiserver/infrastructure/datastore/mongodb/mongodb.go
Signed-off-by: liutiangang <liutiangang@cmbchina.com>
It is unnecessary to judge that the index function is not null
I have:
> Fix: delete redundant null pointer operation

- pkg/utils/k8s.go
update namespace only if it doesn't have the env label
Fixes #4929 
I have:
> Fix: update namespace only if it doesn't have the env label

- pkg/apiserver/domain/service/application_test.go
- pkg/apiserver/domain/service/env.go
- pkg/apiserver/domain/service/env_test.go
- pkg/apiserver/utils/bcode/011_env.go
Enable users to edit the workflow to determine targets for the application to be published to the environment.
I have:
> Fix: do not change the workflow after the env changed

- pkg/apiserver/domain/model/pipeline.go
- pkg/apiserver/domain/service/pipeline.go
- pkg/apiserver/domain/service/pipeline_test.go
- pkg/apiserver/interfaces/api/dto/v1/types.go
- test/e2e-apiserver-test/pipeline_test.go
1. fix mongodb can not decode runtime.Object, use JSONStruct instead.
2. no logs return when no filter passed to `getResourceLog`
Fixes #
I have:
> Fix: mongodb can not decode runtime.Object

- pkg/apiserver/domain/service/helm.go
- pkg/utils/common/common.go
- pkg/utils/common/common_test.go
- pkg/utils/helm/helm_helper.go
forbid 302 request to avoid SSRF of list helm chart endpoint of apiServer.
Fixes #
I have:
> Fix: forbid 302 request to avoid SSRF

- pkg/multicluster/cluster_management.go
> Fix: vela cluster join reports 'resource name may not be empty' error

- pkg/velaql/providers/query/endpoint.go
- pkg/velaql/providers/query/endpoint_test.go
vela status endpoint report error with k8s 1.24
Fixes #5008 
I have:
> Fix: vela status endpoint report error with k8s 1.24

- pkg/velaql/providers/query/handler_test.go
- references/cli/velaql_test.go
Remove the reference of  v1beta1 ingress. The main logic hasn't used v1beta1 ingress yet, this pr just remove all references from test.
Fixes #
I have:
> Fix: remove the reference of  v1beta1 ingress

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- vela-templates/definitions/internal/component/webservice.cue
Support webservice containing duplicate port with different protocol.
Fixes #4986
I have:
> Feat: support webservice containing duplicate port

- apis/core.oam.dev/common/types.go
- e2e/application/application_test.go
- e2e/commonContext.go
- references/cli/init.go
- references/cli/print.go
- references/cli/status.go
- references/cli/up.go
- references/common/application.go
Fixes #5072
```
$ vela up -f vela.yaml -w --timeout=10s
Applying an application in vela K8s object format...
I1115 19:50:23.918135   10372 apply.go:119] "updating object" name="first-vela-app" resource="core.oam.dev/v1beta1, Kind=Application"
✅ App has been deployed 🚀🚀🚀
Port forward: vela port-forward first-vela-app
SSH: vela exec first-vela-app
Logging: vela logs first-vela-app
App status: vela status first-vela-app
Endpoint: vela status first-vela-app --endpoint
Application /first-vela-app applied.
⠋ Waiting app to be healthy ...
❌  Timeout waiting Application to be healthy!
```
```
$ vela up -f vela.yaml -w
Applying an application in vela K8s object format...
I1115 19:51:40.543135   10447 apply.go:119] "updating object" …
```
> Feat: support vela up --wait and --timeout

- references/cli/dryrun.go
- references/cli/dryrun_test.go
- references/cli/livediff.go
- references/cli/test-data/dry-run/app.yaml
- references/cli/test-data/dry-run/my-comp.cue
```
vela dry-run -f app.yaml -d my-comp.cue
```
I have:
> Feat: support dry-run with cue format definition

- pkg/cue/definition/template.go
- pkg/cue/definition/template_test.go
When multiple outputs exist in the component, but the trait only patch one outputs, the previous logic will fail.
I have:
> Fix: patchOutputs bug for multiple outputs

- .github/workflows/apiserver-test.yml
- .github/workflows/back-port.yml
- .github/workflows/chart.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/commit-lint.yml
- .github/workflows/core-api-test.yml
- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/go.yml
- .github/workflows/issue-commands.yml
- .github/workflows/license.yml
- .github/workflows/registry.yml
- .github/workflows/release.yml
- .github/workflows/sync-api.yml
- .github/workflows/trivy-scan.yml
- .github/workflows/unit-test.yml
Signed-off-by: basefas <basefas@hotmail.com>
For more information see: 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
directly change: 
1. actions/checkout@v2 to actions/checkout@v3
2. actions/setup-go@v2 to actions/setup-go@v3
3. bruceadams/get-release@v1.2.2 to bruceadams/get-release@v1.3.2
4. actions/upload-artifact@v2 to actions/upload-artifact@v3
5. actions/download-artifact@v2 to actions/download-artifact@v3
6. actions/cache@v2 to actions/cache@v3
7. thehanimo/pr-title-checker@v1.3.1 to thehanimo/pr-title-checker@v1.3.5
8. actions/setup-node@v2 to actions/setup-node@v3
9. docker/setup-qemu-action@v1 to docker/setup-qemu-action@v2
10. docker/setup-buildx-action@v1 to docker/setup-buildx-action@v2
11. …
> Fix: update actions to solve 「 deprecated 」warnings

- pkg/addon/utils.go
- pkg/addon/utils_test.go
filter registry func flaky which will cause flaky tests.
Fixes #
I have:
> Fix: bug of filter registry func will modify origin data

- references/cli/addon.go
Signed-off-by: zhaohuihui <zhaohuihui_yewu@cmss.chinamobile.com>
Fixes #5142 
I have:
run the `vela addon upgrade fluxcd --clusters={local}` command
@Somefive
> Fix: addon upgrade command does not recognize the --clusters flag

- go.mod
- go.sum
- references/cli/top/view/application_topology_view.go
- references/cli/top/view/application_view.go
- references/cli/top/view/cluster_namespace_view.go
- references/cli/top/view/cluster_view.go
- references/cli/top/view/container_view.go
- references/cli/top/view/managed_resource_view.go
- references/cli/top/view/namespace_view.go
- references/cli/top/view/pod_view.go
- references/cli/top/view/resource_view.go
- references/cli/top/view/resource_view_test.go
In #5151, due to the lack of timeout mechanism, the data in the cache will not be clear, so we update the LRU cache to LRU cache with expired time to ensure the data in cache will be clear after some time.
But only clearing the cached data will not make the topology refresh immediately. Therefore, we introduce an automatic refresh mechanism in the topology view.
In addition, we found that the view refresh requires network requests, and the blocking of network IO will further affect the loading speed of the interface. Therefore, we optimized the network IO, added a timeout abandonment mechanism to the network request, and terminated the timeout request in time to prevent blocking.
Fixes #5151  
Fixes #5152
I have:
> Feat: Introduce timeout mechanism into cache and update network request mechanism in `vela top`

- references/docgen/def-doc/trait/env.eg.md
- references/docgen/markdown.go
- references/docgen/parser.go
- references/docgen/parser_test.go
- references/docgen/testdata/parameter/command.cue
- references/docgen/testdata/parameter/condition.cue
- references/docgen/testdata/parameter/env.cue
Part of #5136
Before, we can't generate doc for composition definition such as `env` or `command` trait:
```
Name | Description | Type | Required | Default
-- | -- | -- | -- | --
-- | Composition type. | parameter: cannot use value {containerName:"" \| string,replace:false \| bool,env:{},unset:*[] \| []} (type struct) as string | false |  
```
Now it can generate docs like below:
```
Name | Description | Type | Required | Default 
---- | ----------- | ---- | -------- | ------- 
|  | [PatchParams](#patchparams) or [type-option-2](#type-option-2) | false |  
Name | Description | Type | Required | Default 
---- | ----------- | ---- | -------- | ------- 
containerName | Specify the name of the target container, if not set, use the component name. | string | false | empty 
command | Specify …
```
> Fix: vela show docs can't generate composition type

- pkg/addon/helper.go
- pkg/addon/helper_test.go
- references/cli/addon.go
- references/cli/addon_suite_test.go
- references/cli/addon_test.go
* Feat: add options for addon parameter (cherry-pick #5166) 
* Fix: wrongly report disbaled when addon is not existed
I have:
> Feat: add options for addon parameter (cherry-pick #5166)

- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
> Feat: support outputs objects for policy

- pkg/oam/util/helper.go
- pkg/utils/common/args.go
- pkg/utils/common/common_test.go
- pkg/utils/common/testdata/testkube.conf
- references/cli/dryrun.go
- references/cli/env.go
> Feat: support fallback to kubeconfig namespace when env not set

- references/common/application.go
Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>
When deleting an app from a namespace,if there is not the app in the namespace, it should return the error of "notFound".
I have:
> Feat: return notFound error when deleting app

- pkg/addon/addon.go
- pkg/addon/addon_suite_test.go
- pkg/addon/addon_test.go
- pkg/addon/helper.go
- pkg/addon/render.go
- pkg/addon/testdata/test-notes/NOTES.cue
- pkg/addon/testdata/test-notes/metadata.yaml
- pkg/addon/type.go
- pkg/apiserver/domain/service/addon.go
- references/cli/addon.go
> Feat: support NOTES.cue in addon for additional info printer

- references/cli/ls.go
Signed-off-by: zhaohuihui <zhaohuihui_yewu@cmss.chinamobile.com>
Fixes #5200 
I have:
1. `vela addon enable vegeta`
2. `vela ls -n vela-system`
@joelhy
> Fix: addon ls command does not show the componentless application

- .github/workflows/scorecards.yml
- README.md
Add ossf scorecard action to secure workflows, I've followed the guide here: https://github.com/marketplace/actions/ossf-scorecard-action.
This is also a recommendation from ToC, refer to https://github.com/cncf/toc/pull/890 .
I have:
> Chore: add ossf/scorecard-action to secure workflows

- .github/workflows/registry.yml
Add write package permission in registry CI. We need this CR to push image to ghcr.
Fixes #
I have:
> Fix: add write package permission in registry CI

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/oam/labels.go
- pkg/resourcekeeper/cache.go
- pkg/resourcekeeper/gc.go
- pkg/resourcekeeper/utils.go
- references/cli/delete.go
- references/common/application.go
- test/e2e-multicluster-test/multicluster_cli_test.go
- test/e2e-multicluster-test/testdata/app/app-orphan-delete.yaml
Support `vela delete --orphan <appname>`. This will only remove the owner label in managed resources while deleting application, instead of recycling resources.
Users can also add `app.oam.dev/orphan-resource` to finalizers.
NOTE: `kubectl delete app <appname> --orphan` is handled by Kubernetes internal controller, so we are unable to reuse the official command by far.
Fixes #4694
I have:
> Feat: gc orphan resources

- charts/vela-core/templates/defwithtemplate/build-push-image.yaml
- charts/vela-core/templates/defwithtemplate/clean-jobs.yaml
- charts/vela-minimal/templates/defwithtemplate/build-push-image.yaml
- charts/vela-minimal/templates/defwithtemplate/clean-jobs.yaml
- references/docgen/def-doc/workflowstep/build-push-image.eg.md
- references/docgen/def-doc/workflowstep/clean-jobs.eg.md
- vela-templates/definitions/internal/workflowstep/build-push-image.cue
- vela-templates/definitions/internal/workflowstep/clean-jobs.cue
> Fix: optimize build push image step

- apis/types/componentmanifest.go
- pkg/appfile/appfile.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatcher.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope.go
- pkg/cue/definition/template.go
- pkg/workflow/providers/multicluster/deploy.go
- pkg/workflow/providers/multicluster/deploy_test.go
- pkg/workflow/providers/multicluster/multicluster.go
- pkg/workflow/providers/oam/apply.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-deploy-io.yaml
This PR add component level input/output capability for `deploy` step. Now `deploy` can correctly deal with components like:
```YAML
components:
- name: podinfo
outputs:
- name: message
valueFrom: output.status.conditions[0].message
properties:
image: stefanprodan/podinfo:4.0.3
- name: configmap
properties:
apiVersion: v1
kind: ConfigMap
metadata:
name: deployment-msg
type: raw
inputs:
- from: message
parameterKey: data.msg
```
There are two possible variable matching ways:
1. First try to match the var strictly. Find var with key `<cluster>/<namespace>/<replication>/<var>`.
2. As fallback, if no matching in the first step, restriction on <replication> can be given up. Try to match var with …
> Feat: support data-passing in deploy step

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- vela-templates/definitions/internal/component/webservice.cue
Add the args parameter to the webservice component
Signed-off-by: xingming01 <whatissoftware@163.com>
Fixes #
I have:
> Feat: the webservice component has no args parameter #5226

- references/cli/top/model/pod.go
remove `clusterName` when load pod details. This field is not actually returned by anyone. And it will be remove in the next version of `k8s.io/api` and cause compatibility problem. This PR removes it.
Code in k8s.io/api
```go
// The name of the cluster which the object belongs to.
// This is used to distinguish resources with same name and namespace in different clusters.
// This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.
// +optional
ClusterName string `json:"clusterName,omitempty" protobuf:"bytes,15,opt,name=clusterName"`
```
Fixes #
I have:
> Fix: remove useless field when loading pod in top

- makefiles/dependency.mk
Fix var error in makefile 
```
makefiles/dependency.mk:10: *** Recursive variable `GOLANGCILINT' references itself (eventually).  Stop.
```
Fixes #
I have:
> Fix: dependency makefile variable error

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-disconnection-test.yaml
In the past, when application needs to rerun workflow, it will clear the steps status first. However, since steps are array attribute, it cannot be updated through patch request, so it needs update request.
In the case when garbage collection could fail due to the potential problems like cluster disconnection or other things, it will redirect the steps clear to use the patch request, which will cause workflow restart but with outdated step status. This will let the workflow directly finished without any step executed. Then it will further lead to all resources under the application being recycled.
This PR enforces using update request for clear workflow step status, even if the garbage collection fails. I also recommend to add additional …
> Fix: gc failure cause workflow restart not working properly

- pkg/apiserver/domain/service/application.go
Signed-off-by: old.prince <di7zhang@gmail.com>
Fixes:Dry-run from revision application,Problems caused by resource version lower than the current version
I have:
> Fix: dry run from revision application patch error

- charts/vela-core/templates/defwithtemplate/vela-cli.yaml
- charts/vela-minimal/templates/defwithtemplate/vela-cli.yaml
- vela-templates/definitions/internal/workflowstep/vela-cli.cue
Puts the `label` under `metadata` so it applies properly. Allows the output of the pod to be available in `vela workflow logs`. Fixes #5247.
I have:
I'm unsure how to write an automated test for this, but I have tested by running a workflow with a `vela-cli` step and saw the output in VelaUX UI and also with `vela workflow logs`. (I re-ran the workflow from #5247).
To ensure it doesn't cause a regression, I ran `make test` and `make e2e-test`. The unit tests passed. The E2E tests failed with the same errors they fail with when I make no code change, so I don't think I broke them.
Nothing.
> Fix: apply label to pod for vela-cli workflow step definition. Fixes #5247

- go.mod
- go.sum
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
Previously, if the key in `inputs.parameterKey` is also specified in `parameter`, it will cause conflict like:
```yaml
workflow:
steps:
- inputs:
- from: context.name
parameterKey: slack.message.text
name: slack-message
properties:
slack:
message:
text: myText
url:
value: <url>
type: notification
```
This PR update workflow vendor and resolve conflicts like this.
I have:
cc @barnettZQG
> Fix: fix inputs conflict for workflow

- charts/vela-core/templates/defwithtemplate/storage.yaml
- charts/vela-core/templates/defwithtemplate/vela-cli.yaml
- charts/vela-minimal/templates/defwithtemplate/storage.yaml
- charts/vela-minimal/templates/defwithtemplate/vela-cli.yaml
- vela-templates/definitions/internal/trait/storage.cue
- vela-templates/definitions/internal/workflowstep/vela-cli.cue
> Feat: support hostpath in storage and vela cli

- docs/apidoc/swagger.json
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/application_test.go
- pkg/apiserver/domain/service/config.go
- pkg/apiserver/domain/service/project.go
- pkg/apiserver/domain/service/rbac.go
- pkg/apiserver/domain/service/workflow.go
- pkg/apiserver/domain/service/workflow_test.go
- pkg/apiserver/event/sync/convert/convert.go
- pkg/apiserver/interfaces/api/application.go
- pkg/apiserver/interfaces/api/dto/v1/types.go
- pkg/apiserver/interfaces/api/pipeline.go
- pkg/apiserver/server.go
- pkg/apiserver/utils/auth.go
- pkg/apiserver/utils/bcode/001_application.go
- pkg/auth/privileges.go
- pkg/utils/app/app.go
- references/cli/up.go
- test/e2e-apiserver-test/application_rollback_test.go
- test/e2e-apiserver-test/suite_test.go
Rollback rules:
1. If the application revision in the hub cluster exits, rollbacking based on them.
2. If not exist, rollbacking based on the revision save in the database. It will use the latest definition to render.
3. Rollbacking will execute the workflow in revision, not the latest workflow.
Fixes: #4222
I have:
> Feat: add the API that rollbacks the application

- charts/vela-core/templates/velaql/component-pod.yaml
- charts/vela-core/templates/velaql/component-service.yaml
- references/cli/install.go
…la install
Add vela def check-system and check the legacy definitions in vela install.
I have:
cc @barnettZQG @wonderflow
> Fix: check the legacy definitions in vela install

- e2e/application/application_test.go
- e2e/commonContext.go
- go.mod
- go.sum
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_finalizer_test.go
- pkg/oam/labels.go
- pkg/resourcekeeper/cache.go
- pkg/resourcekeeper/gc.go
- pkg/resourcekeeper/options.go
- references/cli/cli.go
- references/cli/delete.go
- references/common/application.go
- references/common/application_test.go
Rework `vela delete` command. Now `vela delete` supports:
1. delete multiple applications `vela delete app-1 app-2 -n example`
2. delete application with orphan option `vela delete app-1 --orphan`
3. **NEW** `vela delete` by default will wait and print out the deletion error message controller encountered. This can be helpful for user to understand why the deletion of application has not finished and know what specific resource deletion is blocking the deletion of the application.
4. `vela delete -f` inherits the function provided by old codes but would might be refactored in the future. It now works more like delete at client-side.
5. **NEW** support interactive deletion for application. This is useful when unexpected error happens to the recycle of resources, like cluster disconnection …
> Feat: support interactive mode to manually skip encountered errors

- pkg/apiserver/domain/repository/envbinding.go
- pkg/apiserver/domain/repository/workflow.go
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/workflow.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/event/sync/convert/convert.go
- pkg/apiserver/event/sync/cr2ux_test.go
- pkg/apiserver/event/sync/worker_test.go
The workflow name format with `workflow-<envName>`.
Fixes #
I have:
> Fix: make the synced workflow name normative

- pkg/apiserver/domain/model/workflow.go
> Fix: keep the workflow data structure in MongoDB

- pkg/addon/addon.go
- pkg/addon/cache.go
- pkg/apiserver/domain/service/addon.go
- pkg/apiserver/domain/service/application.go
- pkg/apiserver/domain/service/service.go
- pkg/apiserver/event/sync/cache.go
- pkg/apiserver/event/sync/cache_test.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/event/sync/convert/convert.go
- pkg/apiserver/event/sync/cr2ux.go
- pkg/apiserver/server.go
- pkg/apiserver/utils/auth.go
This PR includes some related changes:
1. The Addon service shares the auth Kube client to support the user impersonation.
2. Add the `publish-version` for the addon application. Users could retry to deploy the Addon.
3. The sync cache key change from the application generation to resource version. This is useful to sync the workflow record.
4. The `APIServerEnableAdminImpersonation` feature implementation change to always bind `kubevela:ux` group. This allows the administrator to have maximum permissions.
I have:
> Fix: the addon management APIs support the user impersonation

- charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
> Feat: upgrade cluster-gateway to support client-identity-exchange config

- pkg/addon/helper_test.go
The addon helper tests previously used real upstream KubeVela repository, which will sometimes change and make this test flacky.
This PR sets up a local mock server instead, in an effort to make this test more stable.
Fixes #
I have:
> Test: use mock server in addon tests

- apis/core.oam.dev/common/types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
Signed-off-by: old.prince <di7zhang@gmail.com>
If the workflow is not completed, the endtime should be null, and the deletion of the application will fail.
```shell
E0106 08:12:02.807341       1 controller.go:317] controller/application "msg"="Reconciler error" "error"="Application.core.oam.dev \"test\" is invalid: status.workflow.endTime: Invalid value: \"null\": status.workflow.endTime in body must be of type string: \"null\"" "name"="test" "namespace"="test" "reconciler group"="core.oam.dev" "reconciler kind"="Application"
```
+nullable tag for status.workflow.endTime fields
I have:
> Fix: delete appplication fails if status.workflow.endTime not specified.

- pkg/velaql/providers/query/tree.go
Signed-off-by: hnd4r7 <307365651@qq.com>
Subresource list loop should continue if not found.
`ChildrenResourcesRule` of `HelmRelease` workload has 2 subresource crd type that cannot be found in my remote cluster(my `fluxcd` addon version 2.1.9 and vela-core version 1.6.5 ).  The method `iterateListSubResources` then returns err `the server could not find the requested resource (get gateways.gateway.networking.k8s.io)` which will cause other subresources (such as pods of statefulSet) of my helm workload cannot be seen as well.
```
{
ResourceType: ResourceType{APIVersion: "gateway.networking.k8s.io/v1alpha2", Kind: "HTTPRoute"},
},
{
ResourceType: ResourceType{APIVersion: "gateway.networking.k8s.io/v1alpha2", Kind: "Gateway"},
},
```
Fixes #
I have:
> Fix: don't return err if subresource type is not found when listing application resources.

- pkg/addon/addon.go
- pkg/addon/helper.go
- pkg/addon/utils.go
- pkg/addon/utils_test.go
- references/cli/addon.go
more explicit error when addon package hasn't a metadata.yaml
before:
after:
Fixes #
I have:
> Fix: more explicit error when addon package hasn't a metadata.yaml

- pkg/apiserver/domain/model/application.go
- pkg/apiserver/domain/model/cluster.go
- pkg/apiserver/domain/model/env.go
- pkg/apiserver/domain/model/envbinding.go
- pkg/apiserver/domain/model/pipeline.go
- pkg/apiserver/domain/model/project.go
- pkg/apiserver/domain/model/system_info.go
- pkg/apiserver/domain/model/target.go
- pkg/apiserver/domain/model/user.go
- pkg/apiserver/domain/model/workflow.go
- pkg/apiserver/domain/service/workflow.go
- pkg/apiserver/infrastructure/datastore/datastore.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_test.go
- pkg/utils/strings.go
- pkg/utils/strings_test.go
Signed-off-by: old.prince <di7zhang@gmail.com>
Fixes #5263
Value of non-string type stored in mongo is not string.Resulting in inconsistent results obtained by filtering non-string type by index.The reason is that when mongo stores the index is still filtered by string value but the actual value is not a string.
I have:
> Fix: Index structure map[string]string,Mongo resulting in inconsistent results obtained by filtering non-string type by index.

- pkg/addon/addon.go
- pkg/apiserver/domain/model/whole.go
- pkg/apiserver/domain/repository/suite_test.go
- pkg/apiserver/domain/service/suite_test.go
- pkg/apiserver/event/collect/suit_test.go
- pkg/apiserver/event/collect/system_info_collect.go
- pkg/apiserver/event/collect/system_info_collect_test.go
- pkg/apiserver/event/sync/cache.go
- pkg/apiserver/event/sync/cache_test.go
- pkg/apiserver/event/sync/convert.go
- pkg/apiserver/event/sync/cr2ux.go
- pkg/apiserver/event/sync/cr2ux_test.go
- pkg/apiserver/event/sync/suit_test.go
- pkg/apiserver/event/sync/worker.go
- pkg/apiserver/event/sync/worker_test.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi.go
- pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_suite_test.go
- pkg/apiserver/infrastructure/datastore/kubeapi/migrate.go
- pkg/apiserver/infrastructure/datastore/kubeapi/migrate_test.go
- pkg/apiserver/interfaces/api/api_suite_test.go
- pkg/apiserver/interfaces/api/target.go
- pkg/apiserver/server.go
- pkg/apiserver/utils/auth.go
- pkg/auth/round_trippers.go
- test/e2e-apiserver-test/application_sync_test.go
Before, we use the generation number as the cache key. If users only change the publish version to rerun the workflow, the application spec does not change, the generation does not change, so the revision and the workflow record can not be synced.
In PR #5282 try to use the resource version as the cache key. The resource version changes constantly When the application workflow running. We did not need to sync the record status in the application synchronizer, so, this resulted in excessive database requests.
Now, we use the revision as the cache key. When the new revision is generated the app synchronizer should resync the application.
This PR makes the API server use the unitive auth client to request the kube API.
I have:
> Feat: enhance the application synchronizer

- pkg/addon/addon.go
- pkg/addon/init.go
- references/cli/addon.go
1. fix error info when there is no note.cue of addon 
3. optimize addon init command, set the component name and add oci helm repo  for helm 
name the compoennt
Fixes #
I have:
> Fix: fix error info when there is no note.cue and optimize addon init command

- references/cli/system.go
Fix typo in the long cli description of vela system command
Ad hoc
I have:
just run `vela system`
> Fix: correct typo in the long cli description of vela system command

- pkg/velaql/parse.go
- pkg/velaql/parse_test.go
Signed-off-by: hnd4r7 <307365651@qq.com>
Support indexing array field in the exported value of the velaql query result to satisfy certain needs such as getting the cluster name of the first pod in component-pod-view.
Before, 
After,
Fixes #
I have:
> Feat: velaql support indexing into exported array field

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/cue/definition/template.go
- pkg/cue/definition/template_test.go
Fix: optimize skip reconcile and expose error if the traits patch an invalid workload like terraform
I have:
> Fix: optimize skip reconcile and expose error if the traits patch an invalid workload like terraform

- references/cli/addon.go
- references/cli/addon_test.go
Fixes `vela addon enable fluxcd --cluster={c1,c2}` not working bug. 
Error msg: `clusters parameter must be a list of string`
I have:
> Fix: the --cluster not work when enable addon

- .github/workflows/apiserver-test.yaml
- .github/workflows/unit-test.yml
- pkg/resourcekeeper/gc.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-gc-shared.yaml
Backport #5330 into release-1.6
I have:
> [Backport release-1.6] Fix: conflict while using gc policy and shared-resource policy concurrently (#5330)

- references/cli/addon.go
- references/cli/addon_test.go
- references/cli/cluster.go
Issue: https://github.com/kubevela/kubevela/issues/5171
Signed-off-by: Gokhan Karadas <gokhan.karadas@trendyol.com>
It allows adding a cluster label when new target cluster is added.
https://github.com/kubevela/kubevela/issues/5171
Fixes #5171
I have:
> Feat: vela cluster join supports label setting arg

- charts/vela-core/templates/defwithtemplate/apply-terraform-config.yaml
- charts/vela-core/templates/defwithtemplate/apply-terraform-provider.yaml
- charts/vela-core/templates/defwithtemplate/build-push-image.yaml
- charts/vela-core/templates/defwithtemplate/request.yaml
- charts/vela-core/templates/defwithtemplate/vela-cli.yaml
- charts/vela-minimal/templates/defwithtemplate/apply-terraform-config.yaml
- charts/vela-minimal/templates/defwithtemplate/apply-terraform-provider.yaml
- charts/vela-minimal/templates/defwithtemplate/build-push-image.yaml
- charts/vela-minimal/templates/defwithtemplate/request.yaml
- charts/vela-minimal/templates/defwithtemplate/vela-cli.yaml
- vela-templates/definitions/internal/workflowstep/apply-terraform-config.cue
- vela-templates/definitions/internal/workflowstep/apply-terraform-provider.cue
- vela-templates/definitions/internal/workflowstep/build-push-image.cue
- vela-templates/definitions/internal/workflowstep/request.cue
- vela-templates/definitions/internal/workflowstep/vela-cli.cue
Fix: delete example url in definitions that refer to workflowrun example
I have:
> Fix: delete example url in definitions that refer to workflowrun example

- references/cli/cli.go
- references/cli/cluster.go
- test/e2e-multicluster-test/multicluster_test.go
Support export multi-cluster kubeconfig.
```
Export multi-cluster kubeconfig
Load existing cluster kubeconfig and list clusters registered in KubeVela. Export the proxy access of these clusters to
KubeConfig and print it out.
Usage:
vela cluster export-config [flags]
Examples:
vela cluster export-config
KUBECONFIG=./my-hub-cluster.kubeconfig vela cluster export-config
vela cluster export-config -l gpu-cluster=true
vela cluster export-config > my-vela.kubeconfig
KUBECONFIG=my-vela.kubeconfig kubectl get namespaces --cluster c2
Flags:
-h, --help              help for export-config
-l, --selector string   LabelSelector for select clusters to export.
Global Flags:
-y, --yes   Assume yes for all user prompts
```
I have:
> Feat: vela cluster export config

- pkg/apiserver/domain/service/application.go
> Fix: failed to create the record when rollbacking the application

- go.mod
- go.sum
Update workflow version to fix panic.
**What's Changed**
[Backport release-0.4] Fix: add requeue in skip and optimize readme by @github-actions in https://github.com/kubevela/workflow/pull/121
[Backport release-0.4] Fix: fix panic when workflow is skipped by @github-actions in https://github.com/kubevela/workflow/pull/123
Ref: https://github.com/kubevela/workflow/releases/tag/v0.4.1
I have:
> Chore: update workflow version to fix panic

- .github/workflows/apiserver-test.yml
We missed server side coverage report. Send it to codecov. Check the `apiserver-e2etests` below to see the effect.
Fixes #
I have:
> Fix: rework on apisrever e2e test covergae

- pkg/utils/apply/patch.go
When annotation `app.oam.dev/last-applied-configuration` is set to `-` or `skip`, the threewaymergepatch cannot properly recognize it and report error. This PR fixes it.
I have:
> Fix: skip last-applied-configuration error for threewaymergepatch

- pkg/appfile/validate.go
Ref-objects typed component has a load operation on apply component. So for the validation webhook, it will not properly recognize the content of referred objects and therefore cause trait patch error due to the lack of proper workload data.
This PR skip the validation check for ref-objects typed component.
Fixes #
I have:
> Fix: ignore validation webhook for ref-objects typed component

- e2e/addon/addon_test.go
- references/cli/addon.go
fix bugs of specified addon registry
Fixes #
I have:
> Fix: fix bugs of specified addon registry

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-minimal/templates/defwithtemplate/webservice.yaml
- pkg/appfile/appfile.go
- test/e2e-multicluster-test/multicluster_test.go
- vela-templates/definitions/internal/component/webservice.cue
1. support bypass component check: For webservice, when the rendered deployment carries the annotation "app.oam.dev/skip-health-check", the health check of webservice will skip. This allow traits to override the default health check in component.
2. add parameter to context when rendering. Therefore, it is possible for component&trait to use `context.parameter` during health check.
I have:
> Feat: enhance health check

- references/cli/adopt.go
Signed-off-by: Karanjot Singh <drquark@duck.com>
This pull request adds the ability for the vela adopt command to override an existing application when the adopted resource has the same name. When the --yes flag is used and an application with the same name already exists, the user will be prompted to confirm the override. If confirmed, the existing application will be replaced with the adopted one.
Fixes #5369
I have:
> Fix: Add confirmation prompt for vela adopt --apply with existing app name

- pkg/apiserver/domain/service/target.go
- pkg/utils/k8s.go
Sometimes, the namespace cannot be created (only update and get are allowed). At this time, CreateOrUpdateNamespace will fail. This PR fixes it.
I have:
> Fix: use get before create or update

- .krew.yaml
Fixes https://github.com/kubernetes-sigs/krew-index/pull/2928
I have:
> Chore: fix krew release with new binary format for .exe

- charts/vela-core/templates/velaql/component-pod.yaml
When returned pod does not have podIP/hostIP/nodeName, it could lead to the incomplete value for VelaQL pod-view to run.
I have:
> Fix: pod view invalid cue for special pod output

- charts/vela-core/templates/kubevela-controller.yaml
Previously, turning RT compression on will enable both RT compression and AppRev compression, due to the usage of a wrong Helm Value. This pr fixes this.
I have:
> Fix: use correct helm value when setting apprev compression

- charts/vela-core/templates/defwithtemplate/cron-task.yaml
- charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
- vela-templates/definitions/internal/component/cron-task.cue
Signed-off-by: Vasco Lameiras <lameiras@gmail.com>
Fixes #5476 
I have:
Tested it locally with k3s `v1.25.5+k3s2`
> Fix: apiVersion of CronJob for 1.25+ clusters

- cmd/core/app/server.go
> Fix: recover application watcher when sharding disabled

- .github/CODEOWNERS
Add myself @chivalryq as codeowner.
Fixes #
I have:
> Chore: add codeowner

- pkg/resourcekeeper/cache.go
- pkg/resourcekeeper/cache_test.go
- pkg/resourcekeeper/gc.go
- pkg/resourcekeeper/statekeep.go
Parallelize state-keep to enhance the state-keep efficiency.
Effect: In the load-testing with 3k applications, the average reconcile time could be reduced by 30%~40% while using state-keep. (Each application contains 1 deployment, 1 secret, 1 configmap)
I have:
> Feat: parallelize state-keep

- pkg/apiserver/domain/service/helm.go
- pkg/apiserver/domain/service/helm_test.go
- pkg/apiserver/interfaces/api/repository.go
- pkg/utils/helm/helm_helper.go
- pkg/utils/helm/helm_helper_test.go
- test/e2e-apiserver-test/repository_test.go
- test/e2e-apiserver-test/suite_test.go
vela-apiserver support helm chart values
rebase
Fixes #
I have:
> Feat: The vela-apiserver supports displaying chart values stored in the OCI registry

- hack/load-test/README.md
- hack/load-test/app-templates/light.yaml
- hack/load-test/deploy.sh
- pkg/utils/pprof.go
> Feat: add load testing script (batch apply applications)

- pkg/apiserver/domain/service/config_test.go
- pkg/apiserver/utils/bcode/016_config.go
- pkg/config/factory.go
- pkg/config/provider/provider_test.go
- test/e2e-apiserver-test/config_test.go
> Fix: removes `default` parameter name for terraform provider

- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_applications.yaml
- go.mod
- go.sum
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- pkg/apiserver/domain/service/pipeline.go
- pkg/apiserver/domain/service/workflow.go
- pkg/apiserver/domain/service/workflow_test.go
- pkg/apiserver/interfaces/api/application.go
- pkg/apiserver/interfaces/api/pipeline.go
- pkg/apiserver/interfaces/api/workflow.go
- pkg/workflow/operation/operation.go
- pkg/workflow/operation/operation_test.go
- references/cli/workflow.go
Support resume a specific suspend step in workflow like:
```
vela workflow resume --step=step1
```
I have:
> Feat: support resume a specific suspend step in workflow

- pkg/apiserver/interfaces/api/pipeline.go
Swagger body should be one of [string number boolean integer array] 
Fixes #
paths./api/v1/pipelines.get.parameters.type in body should be one of [string number boolean integer array]
I have:
@wonderflow
> Fix: swagger DateType

- pkg/apiserver/domain/service/authentication.go
LastloginTime and CreateTime wrong for _login_ information.
Fixes #
I have:
> Fix: createTime and LoginTime wrong for login information

- pkg/velaql/providers/query/tree.go
Fixes #5566
I have:
I have carried out local debugging to verify this function, and it can normally solve the display problem of the job-associated pod under the resource topology
> Fix: The resource topology fails to display the pods under the job #5566

- pkg/apiserver/domain/service/util.go
- pkg/apiserver/domain/service/util_test.go
> Fix: the array type cannot be converted to interface type

- references/cli/top/view/application_topology_view.go
- references/cli/top/view/application_topology_view_test.go
Based on the fact that KubeVela can already provide the ability to collect the number of resources in an application and metrics status, I introduced the obtained information into vela top, and now I can provide more resource information in the topology view.
Fixes #5375
I have:
> Feat: add more information about resource in vela top's topology view

- pkg/appfile/parser.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/monitor/metrics/application.go
- pkg/monitor/metrics/workflow.go
- pkg/resourcekeeper/gc.go
Align the time metrics for different stages of application reconcile into one unified metric with labels.
For example, previously, use `create_app_handler_time_seconds` to record time cost for creating AppHandler. Now use `kubevela_app_reconcile_time_seconds{stage="create-app-handler"}`.
Additionally add stage time recording for `execute-workflow`, `gc-rev`, `state-keep`, etc.
I have:
> Feat: refactor prom metrics for app reconcile

- charts/vela-core/README.md
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- makefiles/e2e.mk
If `--set multicluster.clusterGateway.direct=true` is set, core controller will connect to cluster-gateway directly instead of go to Kubernetes APIServer for delegation.
This has two advantages:
1. The latency of multi-cluster request can be reduced as shown above, 11ms to 6ms. The burden of managed cluster apiserver can be reduced.
2. It does not require hub cluster apiserver and cluster-gateway are mutually connectable. Only require cluster-gateway to be able to connect to hub cluster apiserver.
I have:
> Feat: support direct connection mode for cluster gateway

- pkg/apiserver/interfaces/api/validate.go
- test/e2e-apiserver-test/suite_test.go
Name can not be more than 31. When app name is `ab012345678901234567890123456789 `, I create it failed. 
Fixes #5548 
I have:
> Fix: length of name should be less than 32

- pkg/addon/addon.go
- pkg/addon/addon_test.go
Fixes #5554 
I have:
vela addon enable rollout --clusters={b,a}
@wangyikewxgm
> Fix: render addon application checkDeployClusters invalid

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_test.go
- pkg/utils/apply/patch.go
- test/e2e-multicluster-test/multicluster_test.go
Enhance performance by reducing reconcile time from 56ms to 44ms, ~20% optimization.
I have:
> Feat: optimize empty patch request

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
Fix: stores workflow status in revison if it is restarted
Fixes #5597
I have:
cc @Somefive
> Fix: stores workflow status in revison if it is restarted

- .github/workflows/sdk-test.yml
- .github/workflows/sync-sdk.yaml
- hack/sdk/sync.sh
- pkg/definition/gen_sdk/_scaffold/go/README.md
- pkg/definition/gen_sdk/_scaffold/go/pkg/apis/common/application.go
1. Sync SDK to https://github.com/kubevela-contrib/kubevela-go-sdk when
1. SDK generating logic is changed
2. Any Built-in Definition is changed.
2. Add `ToJSON` method to application.
3. Modify SDK readme.
I have:
The sync has been tested
> Feat: sync sdk automatically

- charts/vela-core/README.md
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- pkg/features/controller_features.go
- pkg/multicluster/virtual_cluster.go
… vela-core
Add featuregate `DisableBootstrapClusterInfo` to prevent the scanning of all joined clusters at the beginning of running vela-core.
I have:
> Feat: add feature gate to allow disable cluster watch at the start of vela-core

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatcher.go
When we add a trait to a component with an inline policy, the trait's definition isn't stored in the application revision. As a result, to determine if the traitDefinition's stage is predispatch or postdispatch, we must retrieve it from the cluster.
This pr is a fix for https://github.com/kubevela/kubevela/pull/5416
Fixes #
I have:
> Fix:  loading definitions if lack in the revision when calculate dispatch stage of trait.

- references/cli/addon-registry.go
Fixes #5645 
I have:
replace `token` with `gitToken`
vela addon registry add my-repo --type git --endpoint=https://git --path=experimental/addons --gitToken=ghp_T3
> Fix: add addon registry

- pkg/utils/load_test.go
- test/e2e-multicluster-test/multicluster_standalone_test.go
Fixes multi-cluster e2e test flaky problem caused by informer late update definition.
I have:
> Fix: mc flaky e2e test

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
> [Backport release-1.7] Fix: stores workflow status in revison if it is restarted (#5604)

- pkg/definition/gen_sdk/gen_sdk.go
- pkg/definition/gen_sdk/gen_sdk_test.go
- pkg/definition/gen_sdk/openapi-generator/templates/go/model_oneof.mustache
Fix the case that setting default value of basic types to fields with multi-types in CUE when generating SDK. The default value should belongs to the corresponding type of all candidates.  e.g. 
```cue
cpu?: *1 | number | string
```
In this example, default `1` should be the default value when CPU is `number` type.
Fix: https://github.com/kubevela/kubevela/actions/runs/4400853066/jobs/7706538333 
cc @StevenLeiZhang 
I have:
> Feat: set right default value for oneOf schema if set

- charts/vela-minimal/README.md
- charts/vela-minimal/templates/kubevela-controller.yaml
- charts/vela-minimal/values.yaml
It seems that the `vela-minimal` helm chart became out of sync from the `vela-core`  chart and rest of the repo.
The following issues have been witnessed on instantiation of the controller when using the `vela-minimal` chart
```
Error: invalid argument "" for "--autogen-workload-definition" flag: strconv.ParseBool: parsing "": invalid syntax
```
```
Error: unknown flag: --apply-once-only
```
Fixes #
Made the mimimum alignment changes in `vela-minimal` chart to resolve the above errors and have it aligned with `vela-core`
Other changes may be required to cover some of the gap introduced in configuration that still exist between the 2 charts.
I have:
I have run the vela-minimal chart with the changes
> Fix: fix vela-minimal helm chart unrecognised options

- .github/workflows/sdk-test.yml
- design/vela-cli/sdk_generating.md
- hack/sdk/sync.sh
- pkg/definition/gen_sdk/_scaffold/go/go.mod_
- pkg/definition/gen_sdk/_scaffold/go/pkg/apis/common/application.go
- pkg/definition/gen_sdk/_scaffold/go/pkg/client/client.go
- pkg/definition/gen_sdk/gen_sdk.go
- pkg/definition/gen_sdk/gen_sdk_test.go
- pkg/definition/gen_sdk/go.go
- references/cli/def.go
This PR allows user to generate a group of definitions as sub-module to KubeVela Go SDK. Usage:
```shell
vela def gen-api -f ./addons/fluxcd/definitions -g go -o ../kubevela-go-sdk --api-dir pkg/apis/addon/fluxcd/ --package github.com/kubevela-contrib/kubevela-go-sdk --init --submodule
```
Added flags to `vela def gen-api`
- submodule: generate this group of definitions to a sub-module
- api-dir: which directory to place the generated API
- language-args: specify language-specific arguments for genereting.
Command help output:
```shell
bin/vela def gen-api -h                                                                                                                                                                                
Generate SDK from X-definition file.
* This command …
```
> Feat: add sub-module to Golang SDK

- pkg/appfile/parser.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validation.go
- test/e2e-test/application_test.go
Remove component name duplication check in Webhook. Now we allow duplicated component name across different applications.
I have:
> Feat: remove comp name dup check

- references/cuegen/convert.go
- references/cuegen/convert_test.go
- references/cuegen/option.go
- references/cuegen/option_test.go
- references/cuegen/testdata/nullable.cue
- references/cuegen/testdata/nullable.go
- references/cuegen/testdata/valid.cue
Part of #5364 
- Support nullable option for generation
- Adjust testdata
I have:
Unit tests
> Feat: support nullable option

- references/cli/top/config/color.go
- references/cli/top/config/color_test.go
Fixes https://github.com/kubevela/kubevela/issues/5744
I have:
run `vela top` to switch theme.
`~/.vela/theme` doesn't have executable permission.
> Fix: vela top cannot set theme

- go.mod
- go.sum
Checkout the release of workflow v0.5.0: https://github.com/kubevela/workflow/releases/tag/v0.5.0
I have:
> Chore: stable the version of workflow to 0.5.0 for 1.8 release

- references/cuegen/convert_test.go
- references/cuegen/generator.go
- references/cuegen/generator_test.go
Part of #5364 
Split Generate function into Generate and Format functions, so we can modify generated decls before format.
I have:
Unit tests
> Refactor: split Generate function

- references/cli/addon.go
add list addon with specify registry. 
when there are multiple registry,` vela addon ls` command merges the addon's occures in multiple registry. Thus, we can not list all addon in specify registry.
for exampla:
in kubevela and testzhh registry, there are both fluxcd/rollout/vegeta
vela addon ls commond only displays the fluxcd/rollout/vege addon in kubevela registry.
I have:
1. add testzhh registry to addon
2. push fluxcd/rollout/vegeta addon to testzhh registry
3. run command `vela addon ls`
@wangyikewxgm
> Feat: list addon with specify registry

- pkg/multicluster/cluster_management.go
- references/cli/cluster.go
- test/e2e-multicluster-test/multicluster_test.go
Previous `vela cluster join --name <cluster-name>` will report `cluster already exist error` when the target cluster already exists.
Now it will ask you if you would like to overwrite the old one or pass `-y/--yes` to overwrite it by default.
```shell
$ vela cluster join --name cluster-worker my.kubeconfig                                                                                                                                                            
Cluster already exists, do you want to overwrite it? (y/n)y
Successfully add cluster cluster-worker, endpoint: <endpoint>
```
I have:
> Feat: vela cluster join support overwrite

- pkg/oam/labels.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
[PR](https://github.com/kubevela/catalog/pull/648)  provides a rolling-release trait for using Kruise-rollout in workflow. However, our `vela workflow resume` command currently resumes both the app workflow and the rollout under the app. This PR filters out the rollout resources created by the rolling-release trait.
Fixes #
I have:
> Fix:  filter rollout created by rolling-release in `vela workflow resume`

- references/cuegen/convert.go
- references/cuegen/convert_test.go
- references/cuegen/option.go
- references/cuegen/option_test.go
- references/cuegen/testdata/valid.go
Part of #5364 
cuegen previously ignored the generation of field and embedded struct by json tag, now we need type filter to ignore the generation of top struct. This will be used by provider-gen to filter out the required structs, such as `providers.Params[T]` and `providers.Returns[T]`
I have:
Unit tests
> Feat: add type filter option

- references/cli/logs.go
- references/cli/workflow.go
> Fix: fix step id to name in workflow logs

- references/cli/logs.go
- references/cli/workflow.go
Fix: use step id to filter the log data and fix the regex
I have:
> Fix: use step id to filter the log data and fix the regex

- references/cuegen/testdata/valid.cue
- references/cuegen/testdata/valid.go
Part of #5364 
Add a test case 
I have:
> Chore: add special field name test case

- apis/core.oam.dev/v1alpha1/garbagecollect_policy_types.go
- charts/vela-core/templates/defwithtemplate/garbage-collect.yaml
- charts/vela-minimal/templates/defwithtemplate/garbage-collect.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/resourcekeeper/context.go
- pkg/resourcekeeper/gc.go
- pkg/resourcekeeper/gc_test.go
- vela-templates/definitions/internal/policy/garbage-collect.cue
> Feat: support mark stage in gc when workflow failed

- hack/docgen/cli/gen.go
- references/cli/cli.go
- references/cli/exec.go
- references/cli/help.go
- references/cli/logs.go
- references/cli/portforward.go
- references/cli/status.go
Refactor `vela help` command.
NOTE: `vela` / `vela -h` / `vela help` output the same thing.
```shell
$ vela help
A Highly Extensible Platform Engine based on Kubernetes and Open Application Model.
Getting Started:
show           	Show the reference doc for a component, trait, policy or workflow.
up             	Deploy one application                                            
init           	Create scaffold for an application.                               
env            	Manage environments for vela applications to run.                 
Managing Applications:
dry-run        	Dry Run an application, and output the K8s resources as result to stdout
revision       	Manage Application Revisions                                            
ls             	List applications …
```
> Feat: refactor vela help

- references/cuegen/README.md
- references/cuegen/convert.go
- references/cuegen/convert_test.go
- references/cuegen/generator_test.go
- references/cuegen/option.go
- references/cuegen/option_test.go
- references/cuegen/testdata/valid.cue
- references/cuegen/util.go
- references/cuegen/util_test.go
Part of #5364 
After an offline discussion, we decided to treat top value as any. This way there is no need to distinguish between `{...}` `[... {...}]` .
I have:
> Fix: make any as top value in cue

- references/cuegen/generators/provider/provider.go
- references/cuegen/generators/provider/provider_test.go
- references/cuegen/generators/provider/testdata/invalid/no_provider_map.go
- references/cuegen/generators/provider/testdata/valid.cue
- references/cuegen/generators/provider/testdata/valid.go
Part of #5364 
This is initial impl of provider generator. The impl is a bit hacky currently and I will refactor it in the future. So it's helpful to just look into testings instead of impl code.
How it works: 
1. Provider generator extracts providers from `map[string]github.com/kubevela/pkg/cue/cuex/runtime.ProviderFn` in target go file.
2. Call cuegen to generate struct decls.
3. Modify and compose decls, and call cuegen `Format`.
I have:
> Feat: initial provider generator

- .github/CODEOWNERS
> Chore: update code owners

- charts/vela-core/templates/kubevela-controller.yaml
KubeVela controller should not mount cluster-gateway secret when it is not enabled.
I have:
> Fix: multicluster disable installation

- e2e/addon/addon_test.go
- e2e/addon/mock/testdata/mock-dependence-rely2/README.md
- e2e/addon/mock/testdata/mock-dependence-rely2/metadata.yaml
- e2e/addon/mock/testdata/mock-dependence-rely2/parameter.cue
- e2e/addon/mock/testdata/mock-dependence-rely2/template.cue
- e2e/addon/mock/testdata/mock-dependence2/README.md
- e2e/addon/mock/testdata/mock-dependence2/metadata.yaml
- e2e/addon/mock/testdata/mock-dependence2/parameter.cue
- e2e/addon/mock/testdata/mock-dependence2/template.cue
- pkg/addon/addon.go
- pkg/addon/addon_suite_test.go
install dependency is invalid for runtime addon when it's cluster arg is nil. Because the runtime addon will be render all clusters when there is no clusters arg.
I have:
`vela cluster join config --name devops`
`vela addon enable fluxcd --clusters={local}`
`vela addon enable rollout`
then you will find the fluxcd is not automatically installed on the devops cluster after enable rollout.
@wangyikewxgm
> Fix: install dependency is invalid for runtime addon when it's cluster arg is nil

- .github/workflows/issue-commands.yml
Support "/retest" comment to rerun CI tests. By default, commenting "/retest" will rerun
- Go
- UnitTest
- E2e
- Multicluster E2E
Contributors can comment "/retest e2e-multicluster-test" to run one of it or comment "/retest core-api-test" to rerun other CI tests.
For the cases that multiple jobs included in one CI workflow, like `Go`, contributors can comment "/retest-failed go" to only rerun the failed ones.
When the command is correctly recognized and processed, an "eyes" reaction will be made to the comment, like
I have:
> Chore: support /retest comment

- .github/dependabot.yml
1. Ignore auto updates for k8s.io packages.
2. Set frequency to 1 week for go mod update.
I have:
> Chore: update dependabot settings

- .github/workflows/e2e-multicluster-test.yml
- .github/workflows/e2e-rollout-test.yml
- .github/workflows/e2e-test.yml
Cherry-pick #5926 to release-1.8.
I have:
> [Backport release-1.8] Chore: add e2e ci env bootstrap & remove multlcluster legacy rollout ci #5926

- apis/core.oam.dev/v1beta1/application_types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- pkg/appfile/parser.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-anonymous-policies.yaml
Support using anonymous policy, like
```yaml
metadata:
name: test
spec:
components:
- type: webservice
name: test
properties:
image: nginx
policies:
- type: topology
properties:
clusters: ["cluster-worker"]
- type: override
properties:
components:
- properties:
image: nginx:1.21
```
Fixes #
I have:
> Feat: allow empty policy name

- pkg/addon/render.go
- pkg/addon/render_test.go
Fixes #5932
I have:
vela addon enable rollout --version 1.3.1
vela addon enable rollout --version 1.3.2
@wangyikewxgm
> Fix: restrict the rules that automatically add topology strategy to ddons to be valid only for the yaml type

- references/cli/install.go
Remove the version upper bound limitation for `vela install`.
I have:
> Feat: remove vela install version requirement upper bound

- hack/cuegen/cuegen.sh
- makefiles/develop.mk
Part of #5364 
```
$ make help | grep gen-cue
gen-cue                        Generate CUE files from Go files. Variable DIR is the directory of the Go files, FLAGS is the flags for vela def gen-cue command.
$ make gen-cue DIR=references/cuegen/generators/provider/testdata/ FLAGS='-t provider'
./hack/cuegen/cuegen.sh references/cuegen/generators/provider/testdata/ -t provider
Generating CUE files from go files in references/cuegen/generators/provider/testdata/
========
- Generating CUE file for references/cuegen/generators/provider/testdata/invalid/no_provider_map.go
- Generating CUE file for references/cuegen/generators/provider/testdata/valid.go
========
Waiting for all background processes to finish
Error: no provider function map found like …
```
> Feat: add gen-cue to Makefile

- references/cli/adopt.go
Vela adopt cli support multi-cluster. So add cluster description for vela adopt help. 
Fixes #5959
I have:
> Fix: add cluster description for vela adopt help

- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/cue/definition/template.go
- pkg/multicluster/utils.go
- pkg/oam/auxiliary.go
- pkg/oam/auxliary_test.go
- references/cli/adopt-templates/default.cue
- references/cli/adopt.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-with-fixed-location.yaml
In this PR, we support setting the cluster to dispatch with the rendered resource directly, through setting the "app.oam.dev/cluster" label manually.
For example,
```yaml
metadata:
name: app
spec:
components:
- type: k8s-objects
name: app
properties:
objects:
- apiVersion: v1
kind: ConfigMap
metadata:
name: "x"
labels:
app.oam.dev/cluster: local
data:
key: "x"
- apiVersion: v1
kind: ConfigMap
metadata:
name: "y"
data:
key: "y"
policies:
- type: topology
name: topology
properties:
clusters: ["cluster-worker"]
```
The above application will create the ConfigMap "x" in the local cluster and the ConfigMap "y" in the "cluster-worker" cluster.
With this capability, it is possible for users to design ComponentDefinition/TraitDefinitions that …
> Feat: support force resource location with dispatch

- .github/workflows/registry.yml
The ACR registry could be potentially out-of-maintenance. It will block the release CI if failed. Like https://github.com/kubevela/kubevela/actions/runs/5087995501/jobs/9143901790
I have:
> Chore: remove acr in ci

- pkg/velaql/providers/query/tree.go
Ref #6014
Read max depth from env if not found return the default const which is 5
> Feat(velaql): read max depth for query iterator from env.

- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_client.go
- pkg/utils/apply/apply_client_test.go
- test/e2e-multicluster-test/multicluster_test.go
- test/e2e-multicluster-test/testdata/app/app-test-subresource.yaml
- test/e2e-multicluster-test/testdata/def/fake-app.yaml
With this PR, KubeVela controller will be able to apply resources with updating the resource status as well, if set.
Normally, KubeVela will not do it for now since we do not have ComponentDefinition or TraitDefinition that output resources with status field. But as mentioned in #3783, in some customized scenario, we might need to allow users to update their custom resource's status with the abstraction capability of KubeVela.
Fixes #3783
I have:
> Feat: support applicator applying resources and update status

- references/cli/cli.go
- references/cli/log/logger.go
- references/cli/log/logger_test.go
Add "--verbosity"/"-V" global flag for vela cli. By default 0.
When 0, all "klog.Info" will be omitted. "klog.Error" will be written to stderr.
When greater than 0, "klog.Info" will be written to stdout.
When greater than 3, the call file and time will be printed.
When greater than 6, all details will be printed.
Fixes #5561
I have:
> Chore: set CLI verbose output to be hidden by default

- .github/workflows/issue-commands.yml
The VELA_BOT_TOKEN seems to expire and the issue-command CI breaks. This PR uses the default github workflow token for doing this CI.
I have:
> Fix: issue command permission error

- pkg/controller/core.oam.dev/v1beta1/application/application_controller.go
- pkg/resourcekeeper/gc_rev.go
- pkg/resourcekeeper/gc_rev_test.go
- test/e2e-multicluster-test/multicluster_test.go
Issue #5710 mention that we should let the application controller to handle the garbage collection of application revision. Previously we rely on the ownerReference mechanism to recycle application revision for application. However, in the case that Kubernetes does not recycle those revisions immediately, it could lead to problems for recreated same-named applications.
PR #5739 refactors the code, moving the gc part into resourceKeeper but does not solve this problem. This PR is to work continue on that and let the application controller to delete application revisions before removing the finalizer of application.
Fixes #5710
I have:
> Fix: application gc not blocked by apprev gc

- pkg/utils/common/common.go
- references/cli/addon-registry.go
In #5000, to avoid SSRF security issue, the http client is configured to forbid redirection. However, at the Client side, we do not to handle the SSRF issue and the client-side validation for the registry url should allow redirection.
If not supported, registry like https://kubevela.github.io/catalog/official will not be able to add directly as it is redirected to https://kubevela.io/catalog/official.
Fixes #
I have:
> Fix: vela addon registry add allow redirect

- Dockerfile
- Dockerfile.cli
- apis/core.oam.dev/common/types.go
- apis/core.oam.dev/common/types_test.go
- apis/core.oam.dev/v1beta1/resourcetracker_types.go
- apis/core.oam.dev/v1beta1/resourcetracker_types_test.go
- charts/vela-core/crds/core.oam.dev_resourcetrackers.yaml
- pkg/controller/core.oam.dev/v1beta1/application/generator.go
- pkg/oam/labels.go
- pkg/workflow/providers/multicluster/deploy.go
- pkg/workflow/providers/multicluster/deploy_test.go
- pkg/workflow/providers/oam/apply.go
- pkg/workflow/providers/oam/apply_test.go
The "env" parameter for envbinding is not used as the envbinding is deprecated for a while and removed in this version.
I have:
> Chore: remove useless envbinding env

- charts/vela-core/templates/addon_registry.yaml
- references/cli/addon.go
1. Let the default addon registry installed to be "kubevela.github.io".
2. Fix redirect forbidden while running `vela addon list`.
Fixes #
I have:
> Fix: addon registry use kubevela.github.io and support redirect

- .github/workflows/definition-lint.yml
> Fix: ci definition lint wrong config

- charts/vela-core/README.md
- references/cli/install.go
- references/cli/install_test.go
> Fix: vela install chart switch place

- charts/vela-core/templates/defwithtemplate/apply-component.yaml
- pkg/controller/core.oam.dev/v1beta1/application/generator.go
- pkg/workflow/template/static/builtin-apply-component.cue
- references/docgen/def-doc/workflowstep/apply-component.eg.md
- vela-templates/definitions/internal/workflowstep/apply-component.cue
Reverts kubevela/kubevela#6228 due to the lack of test to `k8s-objects` type component. 
In a application with `k8s-objects` component, a default workflow will be generated with `apply-component` step with no `namespace` specified. It means the objects in this componets will be dispatched to application's namespace.
Now it is the reason the CI is blocking.
> Chore: revert "Feat: apply-component supports namespace"

- references/cli/cluster.go
- references/cli/def.go
- references/cli/workflow.go
Sets stdout channel to print the output. The Cobra cmd instance has `SetOut` method that takes IO out writer, setting this will ensure that the output always uses stdout to print the output.
Fixes #6268 
I have:
Run `vela def list` and pipe the output to grep it. The status code of the command execution should be zero.
> Fix: Print command output using stdout channel #6268

- makefiles/build.mk
remove `build-apiserver` in build.mk
Fixes #
I have:
> Fix: update build.mk

- Makefile
- charts/vela-core/templates/kubevela-controller.yaml
- makefiles/dependency.mk
This PR adds the target namespace to the Helm Chart. For use cases where `helm template` is being used to obtain the rendered YAML entities, some of the entities did not contain the expected namespace that is being generated.
Additionally, this PR also adds a new makefile constant `CUE_VERSION` as the `latest` was updated two weeks ago and it is not compatible with the underlying golang version. Previous reported error was:
```bash
/go/pkg/mod/cuelang.org/go@v0.7.0/cue/decode.go:74:5: x.SetZero undefined (type reflect.Value has no field or method SetZero)
/go/pkg/mod/cuelang.org/go@v0.7.0/cue/decode.go:381:12: mapElem.SetZero undefined (type reflect.Value has no field or method SetZero)
/go/pkg/mod/cuelang.org/go@v0.7.0/cue/types.go:1340:16: undefined: bytes.Clone
note: module requires Go …
```
> Fix: helm template adding namespace

- pkg/utils/common/args.go
Fixes issue where `vela dry-run --offline` fails when the `KUBECONFIG` environment variable is unset.
The fix passes a default rest client to avoid calling `config.GetConfig()`.
I have:
Prior to fix:
```bash
❯ unset KUBECONFIG
❯ vela dry-run -f ./app.yaml --offline -d definitions/internal
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
With the fix, the Application resources are rendered properly.
N/A
> Fix: prevent kube client lookup in GetFakeClient

- charts/vela-core/templates/defwithtemplate/hpa.yaml
- vela-templates/definitions/internal/trait/hpa.cue
I fixed build-in hpa trait which is using cpu parameters when try to use memory.
I have:
e2e test
> Fix: hpa trait corresponding to cpu parameters when try to use memory

- Makefile
> Chore: updates the make fmt command

- references/cli/delete.go
Previously, the deletion message for applications contained a typo where "application" was misspelled as "appplication". This commit corrects the spelling to "application" in the message:
- Before: "Start deleting appplication %s/%s\n"
- After: "Start deleting application %s/%s\n"
This change improves the clarity of the output message when deleting applications.
Fixes #6626
I have:
This code has been tested by running the following steps:
- Applied a sample application using the KubeVela CLI.
- Attempted to delete the application using the vela delete command.
- Verified that the deletion message correctly displays "Start deleting application" instead of the previous typo "Start deleting appplication".
This is a minor fix for a typo in the deletion message. No additional testing beyond …
> Fix: Correct spelling of "application" in deletion message (#6626)

- apis/core.oam.dev/v1alpha1/garbagecollect_policy_types.go
- pkg/resourcekeeper/gc.go
When specifying orphan propagation for garbage collect policy for a component it still deletes the workload associated with the component. This PR fixes this issue by skipping deletion for orphan propagated resources.
Fixes [#6703](https://github.com/kubevela/kubevela/issues/6703)
I have:
Manual Testing
> Fix: fix for skipping deletion of orphan resources

- pkg/addon/addon_test.go
- pkg/addon/helper.go
- pkg/multicluster/cluster_management.go
This PR does these changes:
1. When user detaches the cluster using `vela cluster detach` command then we remove references for that cluster from all resource trackers.
2. Modified GetAddonStatus to skip those clusters if it is not registered in KubeVela.
Fixes [#6727](https://github.com/kubevela/kubevela/issues/6727)
I have:
This is tested locally by building the vela cli from the modified code and testing the scenario described in the issue.
> Fix: removing detached clusters from resource trackers

- charts/vela-core/templates/defwithtemplate/task.yaml
- vela-templates/definitions/internal/component/task.cue
…nt name
In KubeVela, we have a task component that creates a Kubernetes Job internally. However, when we modify properties of the task, the KubeVela controller attempts to update the existing job, which fails since updating a Job is not allowed in Kubernetes. The purpose of the Task component is to trigger a one-time run to completion. Therefore, whenever an application containing this component is deployed, we always want a new job to be triggered, even if no changes have been made to the spec.
To address this, I've implemented a solution to ensure that each time the application is applied, a unique job name is generated, and the task component creates a new Job instead of modifying the existing one. Here's a summary of the changes:
Custom Component Definition:
Modify the …
> Fix: support task component to be one-time run to completion

- references/cli/cluster.go
- references/cli/cluster_test.go
When user runs vela cluster join command, we iterate through all Application resources in the cluster and updates those that have a cluster-level label selector defined in topology policy. For each matching application, it sets or updates publish version annotation. This makes sure the workflow in the application gets retrigerred which makes sure the app resources gets deployed to the newly joined cluster.
Fixes [#6765](https://github.com/kubevela/kubevela/issues/6765)
I have:
Tested locally by applying applications with topology policy and enabling fluxcd addon. Verified that on joining the new cluster, the resources are deployed in the newly created cluster.
> Fix: update apps with topology policy during cluster join

- README.md
Replace the API URL of openssf badge with the UI URL
> Chore: Replace the openssf badge with UI link

- docs/examples/config/helm-repository/README.md
- e2e/addon/mock/testdata/terraform/template.yaml
- e2e/registry/registry_test.go
- pkg/cue/cuex/providers/config/config_test.go
- pkg/utils/helm/helm_helper_test.go
- pkg/utils/helm/repo_index_test.go
- pkg/utils/helm/testdata/index.yaml
- references/cli/addon_suite_test.go
- references/cli/registry.go
- references/cli/top/view/log_view_test.go
Updates the helm repo path in test cases. 
I have:
Ran unit tests in GA, which were failing with the cert issue because of the deprecations of the older kubvela chart path.
> Chore: update helm repo path in tests

- references/cli/common.go
- references/cli/dryrun.go
- references/cli/dryrun_test.go
- references/cli/env.go
- references/cli/exec.go
- references/cli/export.go
- references/cli/init.go
- references/cli/livediff.go
- references/cli/logs.go
- references/cli/ls.go
- references/cli/portforward.go
- references/cli/revision.go
- references/cli/show.go
- references/cli/status.go
- references/cli/top.go
- references/cli/workflow.go
- references/cli/workloads.go
Fixes the behaviour of `vela dry-run` command to consider the namespaces provided in flags, namespace filed in the yaml file and the vela env
I have:
Tested the code by building the cli locally.
> Fix: vela cli namespace behaviour

- pkg/cmd/utils.go
- references/cli/up.go
- references/cli/up_test.go
Modified the `vela up -f` command behaviour to align with the kubectl command by throwing the error when there are conflicting namespace in the `-n` flag and the application file.
I have:
Written the relevant test cases and tested the behavior by building the CLI.
The behavior of the `vela up -f <app-file.yaml> -n <namespace>` command has been modified to throw an error when there are conflicting namespaces specified in the `-n` flag and the application file. Previously, the `-n` flag would be overriden by the namespace defined in the application file.
> Fix: vela up command to behave similarly with kubectl

- pkg/policy/envbinding/placement_test.go
- pkg/resourcekeeper/containsresources_test.go
- pkg/resourcekeeper/gc_test.go
- pkg/resourcetracker/tree_test.go
- pkg/schema/schema_test.go
- Fixes #6888
This pull request introduces a comprehensive suite of unit tests across several core packages to improve test coverage and ensure the correctness and reliability of existing functionality.
The following packages have been enhanced with new tests:
- **`pkg/resourcekeeper`**: Adds new tests for resource management logic, including `ContainsResources` and `UpdateSharedManagedResourceOwner`.
- **`pkg/resourcetracker`**: Improves tests for the resource tree display logic, including tree printing and HTTP transport mechanisms.
- **`pkg/policy/envbinding`**: Adds robust tests for placement logic, covering `WritePlacementDecisions` and `UpdateClusterConnections`.
- **`pkg/schema`**: Introduces tests for CUE schema parsing and OpenAPI conversion logic.
I have:
The changes in this …
> Feat(tests): Add unit test coverage for core packages

- .github/workflows/sync-sdk.yaml
The `sync-sdk.yaml` workflow was failing with the error:
`Error: failed to get client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`
This occurred when running `bash ./hack/sdk/sync.sh` because the `bin/vela def gen-api` command requires access to a Kubernetes cluster to generate API definitions.
- Fixed the Kubernetes cluster access issue in the sync SDK workflow
I have:
> Fix: add KinD setup step to sync-sdk workflow

- .github/workflows/release.yml
This fixes the failure in the release workflow —
[`Error: Tapping homebrew/core is no longer typically necessary.`](https://github.com/kubevela/kubevela/actions/runs/18149681613/job/51659048948) —
by updating the `dawidd6/action-homebrew-bump-formula` action version to `v5`.
While addressing this, another Homebrew check surfaced:
the `kubevela` formula in `homebrew-core` is already auto-bumped by **BrewTestBot** every few hours. This caused manual bump attempts to fail with:
> “Whoops, the kubevela formula has its version update pull requests automatically opened by BrewTestBot.”
To handle this cleanly, the redundant **manual Homebrew bump step** has been **removed** from the release workflow.
BrewTestBot will continue to automatically open formula update PRs within a few hours of each …
> Chore: update homebrew bump action
