kubevela/kubevela

- pkg/cmd/ls.go
- pkg/cmd/util/helpers.go
Use the new way to retrieve namespace
> Fix `rudr list` issue

- pkg/cmd/workload_run.go
Fix issue #91 of "panic: assignment to entry in nil map"
> Fix containerized:run issue

- README.md
- cmd/vela/main.go
- pkg/cmd/completion.go
- pkg/cmd/init.go
- pkg/plugins/cluster.go
> Add Auto completion command

- design/restful-interface
Added the appConfig and xxxDefinition REST API draft. Let's see if the style is ok
> RESTful Draft

- Makefile
- cmd/vela/main.go
- pkg/cmd/addon.go
- pkg/cmd/env.go
- pkg/cmd/system.go
- version/version.go
> fix vela system:init info

- cmd/vela/main.go
- config/samples/traits/manualscaletraits_definition.yaml
- e2e/application/application_test.go
- e2e/commonContext.go
- e2e/trait/trait_test.go
- pkg/cmd/ls.go
- pkg/cmd/status.go
- pkg/cmd/system.go
- pkg/cmd/trait_bind.go
- pkg/cmd/util/helpers.go
- pkg/plugins/cluster.go
Use trait type instead of its name in application list.
Fix app:status issue and refactor code
Fix #90
> Show trait type in `app:ls`

- pkg/cmd/ls.go
if do not have application
```shell
vela app:ls
NAME    WORKLOAD        TRAITS  STATUS  CREATED-TIME%        
```
Signed-off-by: guoxudong <sunnydog0826@gmail.com>
> fixed some err in print info

- integration/integration_suite_test.go
- integration/server_test.go
- pkg/server/api-server.go
- pkg/server/route.go
- pkg/server/util/errors.go
Added the example integration test for our Restful server.  Please add at least one test per API there
> add integration test for RESTful server

- .gitignore
- cmd/vela/main.go
- e2e/cli.go
- integration/integration_suite_test.go
- pkg/cmd/dashboard.go
- pkg/cmd/env.go
- pkg/cmd/ls.go
- pkg/cmd/system.go
- pkg/oam/application.go
- pkg/oam/env.go
- pkg/oam/trait.go
- pkg/server/api-server.go
- pkg/server/handler/appHandlers.go
- pkg/server/route.go
- pkg/server/util/errors.go
- pkg/server/util/middleware.go
implement API `api/envs/default/apps/ and refactor code
> Implement API `api/envs/default/apps/

- .github/workflows/go.yml
- Makefile
- api/types/types.go
- e2e/apiserver/apiserver_suite_test.go
- e2e/apiserver/apiserver_test.go
- e2e/cli.go
- e2e/commonContext.go
- e2e/env/env_suite_test.go
- e2e/env/env_test.go
- e2e/setup/setup_suite_test.go
- e2e/setup/setup_test.go
- e2e/system/system_suite_test.go
- e2e/trait/trait_suite_test.go
- go.mod
- go.sum
- pkg/cmd/dashboard.go
- pkg/cmd/env.go
- pkg/cmd/env_test.go
- pkg/oam/env.go
- pkg/server/api-server.go
- pkg/server/apis/types.go
- pkg/server/handler/appHandlers.go
- pkg/server/handler/envHandlers.go
- pkg/server/route.go
- pkg/server/util/api.go
implemented APIs for env and make api-test
and e2e-setup
> Implement env APIs

- e2e/apiserver/apiserver_test.go
- e2e/application/application_test.go
- e2e/commonContext.go
- e2e/workload/workload_test.go
- go.mod
- pkg/cmd/workload_run.go
- pkg/oam/env.go
- pkg/oam/trait.go
- pkg/oam/workload.go
- pkg/server/apis/types.go
- pkg/server/handler/workloadHandler.go
Implement Workload Run API
implemented workload run api and write e2e test
cases for workload run cli and API
> Implement Workload Run API

- e2e/apiserver/apiserver_test.go
- pkg/server/apis/types.go
- pkg/server/handler/workloadHandler.go
implemented the API to list workloaddefinitions with
the workloadtype name and all its parameters
> Implement listing WorkloadDefinitions API

- pkg/cmd/capability.go
feat: #165 
add list all capability centers cli
```
$ vela cap:center:ls
NAME     	ADDRESS                                                                           	
mycenter 	https://github.com/cloud-native-application/RudrX/tree/master/pkg/plugins/testdata
mycenter2	https://github.com/cloud-native-application/RudrX/tree/master/pkg/plugins/testdata
```
> add list all capability centers cli

- pkg/cmd/capability.go
- pkg/cmd/traits.go
- pkg/cmd/traits_test.go
- pkg/oam/trait.go
- pkg/oam/trait_test.go
- pkg/plugins/local.go
- pkg/server/apis/types.go
- pkg/server/handler/traitHandler.go
- pkg/server/handler/workloadHandler.go
implemented getting and listing traitsdefinition,
getting a workloaddefinitions
> Implement API for listing/getting workloads/traits

- pkg/oam/trait.go
- pkg/server/handler/traitHandler.go
check parameter `staging` before converting it
to bool and add logs
> API request parameter check for trait attach

- pkg/oam/application.go
> Sort application list in inverse order of created time.

- documentation/api/vela-restful-api-reference.md
- e2e/capability/capability_test.go
- pkg/cmd/capability.go
- pkg/oam/capability.go
- pkg/server/handler/capabilityHandlers.go
- pkg/server/route.go
feat: #218 #219 
add remove capability center cli
```
$ vela cap center remove xxx 
xxx capability center removed successfully
```
add delete capability center api
```
DELETE
/api/capability-centers/xxx
```
> add remove cap center cli and api

- pkg/cmd/ls.go
Fixed content errors in `app ls` commands
> fix app ls example

- charts/vela-core/values.yaml
- documentation/samples/metrics-demo/appConfig.yaml
- documentation/samples/metrics-demo/autoscale-component.yaml
- pkg/webhook/containerized/validating_handler.go
- pkg/webhook/metrics/validating_handler.go
fix webhook issues and push image to docker hub
> fix webhook issues and push image to docker hub

- pkg/cmd/delete.go
Signed-off-by: guoxudong <sunnydog0826@gmail.com>
> fix comp delete err

- go.mod
- pkg/cmd/comp.go
- pkg/cmd/workloads.go
fix #220 
/cc @zzxwill 
Signed-off-by: guoxudong <sunnydog0826@gmail.com>
> clear hints for comp run

- e2e/application/application_test.go
- e2e/commonContext.go
- go.mod
- go.sum
- pkg/cmd/app.go
- pkg/cmd/delete.go
- pkg/cmd/status.go
- pkg/cmd/workloads.go
- implement `vela app status` #227 
- refine output of `vela comp status` #150 
> implement "vela app status"

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- charts/third_party/cert-manager/download-cert-manager.sh
- charts/vela-core/crds/prometheus-operator-servicemonitor-crd.yaml
- charts/vela-core/templates/containerized.yaml
- charts/vela-core/templates/healthscopes.yaml
- charts/vela-core/templates/manualscalars.yaml
- charts/vela-core/templates/metricstraits.yaml
- charts/vela-core/templates/velaConfig.yaml
- charts/vela-core/values.yaml
- documentation/samples/metrics-demo/README.md
- pkg/controller/dependency/setup.go
- pkg/controller/dependency/setup_test.go
- pkg/controller/v1alpha1/metrics/suite_test.go
adjust the helm setting and README
> adjust the helm setting and README

- README.md
Add warning for not play around it for now
> Add warning for not play around it for now

- .github/workflows/docker.yml
- .github/workflows/release.yml
Will remove pull-request after test succeed
> Add Image upload for Docker Hub and Github Docker package

- charts/vela-core/values.yaml
always using the latest in the master branch
> update image tag to latest and change image pull policy

- .github/workflows/release.yml
- .gitignore
- Makefile
- README.md
- go.sum
Use compressed file for release, so users will download faster
> use compressed file for release

- pkg/commands/system.go
> fix duplicate `vela system info` failure message

- .gitignore
- hack/chart/generate.go
Temporarily corrects spec.validation.openAPIV3Schema issue, and it would be removed
after this issue was fixed https://github.com/oam-dev/kubevela/issues/284.
> Fix OpenAPIV3Schema Validation Issue

- pkg/commands/status.go
Exception cases handled by `vela comp status` currently:
- The component is unhealthy => show diagnosis 
- The component is not referenced by a HealthScope => show status as `Not Diagnosed` and workload status
- The component is unknown to the HealthScope => show status as `Not Diagnosed` and workload status
- The component's workload controller is not working => show status as `Not Diagnosed` and warning info
> fix bug: handle exception cases in `vela comp status`

- pkg/oam/trait.go
- pkg/plugins/capcenter.go
- pkg/server/apis/types.go
- pkg/server/handler/workloadHandler.go
almost all of names in `json` of struct fileds
should be in `lowerUpper` format
> Fix naming in `json` of struct fields

- README.md
- cmd/vela/main.go
- documentation/api/vela-restful-api-reference.md
- pkg/commands/show.go
- pkg/oam/application.go
- pkg/oam/common.go
- pkg/oam/component.go
- pkg/oam/trait.go
- pkg/server/apis/types.go
- pkg/server/handler/componentHandlers.go
- pkg/server/handler/traitHandler.go
- pkg/server/main/startAPIServer.go
- pkg/server/route.go
- pkg/server/util/api.go
- Update app list/show, implmented component show
- Update trait attach/detach with the introduction of component
- implemented component delete API
> Implemente Component api

- pkg/commands/env.go
fix #313 ,support delete multi env
> support delete multi env

- pkg/controller/v1alpha1/containerized/containerized_controller.go
fix #327 Add not creating service when ports are not set.
> Determine whether it is necessary to create a service

- e2e/capability/capability_test.go
- pkg/plugins/cluster.go
- pkg/plugins/cluster_test.go
add back the test after the cue templates are updated
> add back the test after the cue templates are updated

- pkg/commands/ls.go
- pkg/oam/application.go
- pkg/oam/workload.go
- pkg/server/apis/types.go
- pkg/server/handler/appHandlers.go
- pkg/server/handler/workloadHandler.go
- pkg/server/route.go
- fixed trait attach issue
- allow leaving out `/` to make API more friendly
- merge similar struct
> Refine and fix API

- README.md
Add more details for the readme to clarify its relationship with other projects, architecture, purpose and goals.
> Add details for the project

- hack/chart/generate.go
It broke the function revising CRD.
> fix minor bug in generate.go

- Makefile
- e2e/application/application_test.go
- e2e/cli.go
- e2e/commonContext.go
- go.mod
- go.sum
- pkg/commands/init.go
- pkg/commands/status.go
#310 
- track status changing in vela init
- add loop checking in "vela comp status"
- fix e2e-test
- update oam-k8s-runtime dependency to latest tag
Demo as below :
[Gif demo click here](https://gifyu.com/image/4JQe)
> track status changing in vela init

- charts/vela-core/templates/manualscalars.yaml
- charts/vela-core/templates/metricstraits.yaml
- charts/vela-core/templates/routetrait.yaml
- pkg/oam/trait.go
updated appliesToWorkloads fileds in traitdefinition
for three workloads, webservice, task and backend.
fix issue #346
> Update appliesToWorkloads field in traitdefinition

- pkg/commands/system.go
- pkg/commands/util/init.go
- pkg/commands/util/init_test.go
- pkg/controller/dependency/install.go
> fix check resource exists

- e2e/application/application_test.go
Comment out several e2e test cases for blocking issue. I will get them back and revise them as soon as #379 is done.
> comment out e2e blocking cases

- charts/vela-core/templates/backend.yaml
- charts/vela-core/templates/manualscalars.yaml
- charts/vela-core/templates/podspecworkload.yaml
- charts/vela-core/templates/routetrait.yaml
- charts/vela-core/templates/tasks.yaml
- charts/vela-core/templates/webservices.yaml
- pkg/cue/convert.go
- pkg/cue/testdata/traits/manualscaler.cue
- pkg/cue/testdata/traits/rollout.cue
- pkg/cue/testdata/traits/route.cue
- pkg/cue/testdata/workloads/deployment.cue
- pkg/cue/testdata/workloads/metrics.cue
- pkg/plugins/testdata/manualscalars.yaml
- pkg/plugins/testdata/traitDef.yaml
- pkg/plugins/testdata/workloadDef.yaml
- vela-templates/backend.cue
- vela-templates/metrics.cue
- vela-templates/route.cue
- vela-templates/task.cue
- vela-templates/web-service.cue
Per discussion in #239 , changing the name.
> cue: rename 'data' to 'output'

- pkg/controller/dependency/install.go
> fix make core-run panic

- Makefile
- e2e/application/application_test.go
- e2e/cli.go
- e2e/commonContext.go
- fix e2e test setup
- revert commented e2e cases
> revert commented e2e cases

- .github/workflows/e2e.yml
- Makefile
- cmd/core/main.go
- e2e/cli.go
- pkg/commands/system.go
currently the CI is broken because my last PR introduced a BUG. But that PR wasn't successfully checked by CI because we're  always using old image for test, so we don't really test the right thing. 
In this PR I build the image before e2e test and fix the BUG.
> add args for vela install and fix E2E with fresh image build

- Makefile
- hack/unit_test.sh
See https://codecov.io/gh/oam-dev/kubevela
Ref https://github.com/codecov/example-go
Also set up CODECOV_TOKEN in secrets.
> Setup codecov

- .github/workflows/go.yml
- hack/unit_test.sh
https://codecov.io/gh/oam-dev/kubevela
> move codecov upload to github workflow

- documentation/samples/rollout-demo/README.md
- documentation/samples/rollout-demo/RolloutTraitDesign.md
- documentation/samples/rollout-demo/deploy-component.yaml
- e2e/commonContext.go
> rollout trait high level design

- .gitignore
- go.mod
- go.sum
> fix race and update oam-runtime dependency

- Makefile
install the Prometheus CRD in the local dev environment manually
> fix local dev environment

- pkg/appfile/appfile.go
- pkg/appfile/service.go
Pulling some bug fix from https://github.com/oam-dev/kubevela/pull/402
> fix bugs on pkg/appfile

- pkg/application/app.go
- pkg/application/app_test.go
- pkg/commands/ls.go
refined error message for `vela app run`
and correct help message for `vela comp ls`
To fix #320
> Refine help and error message

- cmd/core/main.go
- e2e/commonContext.go
- pkg/commands/dashboard.go
- pkg/commands/status.go
- pkg/commands/system.go
fix #292 
output screenshot
fix #339 
output screenshot
> wait until runtime ready during vela install

- pkg/commands/up.go
> add support for `vela up` specify file path

- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/appfile/service.go
Signed-off-by: Hongchao Deng <hongchaodeng1@gmail.com>
> remove image constraint

- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/appfile/config_getter.go
- pkg/appfile/service.go
- pkg/application/app.go
- pkg/commands/cli.go
- pkg/commands/config.go
- pkg/commands/config_test.go
- pkg/commands/env.go
- pkg/commands/env_test.go
- pkg/commands/init.go
- pkg/cue/base_template.go
- pkg/oam/trait.go
- pkg/server/handler/appHandlers.go
- pkg/server/handler/componentHandlers.go
- pkg/server/handler/envHandlers.go
- pkg/server/handler/workloadHandler.go
- pkg/utils/config/config.go
- pkg/utils/env/env.go
- pkg/utils/system/system.go
> vela config command

- api/v1alpha1/podspecworkload_types.go
- charts/vela-core/crds/standard.oam.dev_podspecworkloads.yaml
- documentation/samples/rollout-demo/README.md
- documentation/samples/rollout-demo/RolloutTraitDesign.md
- documentation/samples/rollout-demo/appConfig-rollback-v1.yaml
- documentation/samples/rollout-demo/appConfig-rollout-v1.yaml
- documentation/samples/rollout-demo/appConfig-rollout-v2.yaml
- documentation/samples/rollout-demo/definitions.yaml
- documentation/samples/rollout-demo/deploy-component-v1.yaml
- documentation/samples/rollout-demo/deploy-component-v2.yaml
- documentation/samples/rollout-demo/podSpec-component-v1.yaml
- documentation/samples/rollout-demo/podSpec-component-v2.yaml
- hack/appfile/cue-templates/canary.cue
- hack/appfile/cue-templates/route.cue
- hack/appfile/cue-templates/scale.cue
- hack/appfile/cue-templates/webservice.cue
- Add Flagger OAM integration example README
- Add scale subresource to podSpecWorkload
- Add flagger design doc
> Add Flagger OAM integration example README

- e2e/trait/trait_test.go
- pkg/commands/comp.go
- pkg/commands/exec.go
- pkg/commands/logs.go
- pkg/commands/trait.go
- pkg/commands/util/helpers.go
- pkg/plugins/suit_test.go
> refact cmds from comp-centric into app-centric style

- README.md
- docs/README.md
- docs/developers/config-enviroments.md
- docs/developers/set-route.md
- docs/install.md
Minor fix based on @hongchaodeng 's follow up.
> Minor fix on doc framework

- docs/design.md
- docs/platform-engineers/extending-kubevela.md
- docs/roadmap.md
> Add roadmap doc and update extending doc

- README.md
- docs/introduction.md
As the title said, please review carefully since this doc delivers important messages.
> Add introduction doc

- CONTRIBUTING.md
- OWNERS.md
- OWNERS_ALIASES.md
- docs/developers/deploy-app.md
As the title said.
Please don't merge until @wonderflow approved the #bootstrap-contributors section (in case there's mistake).
> Add onwers file and fix typo

- docs/introduction.md
This change revises the introduction.md to better explain this project.
> Revise introduction.md

- charts/vela-core/templates/defwithtemplate/manualscale.yaml
- docs/developers/devex/appfile.md
- examples/testapp/vela.yaml
- hack/vela-templates/cue/manualscale.cue
update manualscale cue to set default replica 1 and update appfile example to exclude scaler trait
> update manualscale cue template and appfile guide

- pkg/commands/up.go
- pkg/commands/up_test.go
Due to decrease of code coverage, added unit-test
for `vela up`
> Add unit-test for `vela up`

- Makefile
- docs/developers/check-logs.md
- docs/developers/devex/appfile.md
- docs/developers/exec-cmd.md
- docs/developers/port-forward.md
- docs/install.md
- docs/quick-start.md
- examples/kubecondemo/vela.yaml
- examples/testapp/vela.yaml
- pkg/appfile/appfile.go
- pkg/application/run.go
- pkg/commands/init.go
- pkg/commands/run.go
- pkg/oam/application.go
- pkg/oam/trait.go
- pkg/oam/workload.go
ref https://github.com/oam-dev/kubevela/issues/441
> doc for quick start, exec/logs/port-forward; add render-only to init cmd

- cmd/core/main.go
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Fix invalid defer in waitWebhookSecretVolume.
> Fix invalid defer in waitWebhookSecretVolume

- api/v1alpha1/metricstrait_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- charts/vela-core/crds/standard.oam.dev_metricstraits.yaml
- charts/vela-core/templates/defwithtemplate/metrics.yaml
- docs/developers/set-metrics.md
- e2e/commonContext.go
- e2e/raw-objects/samples/metrics-demo/README.md
- e2e/raw-objects/samples/metrics-demo/dashboard/grafana-oam-datasource.yaml
- e2e/raw-objects/samples/metrics-demo/dashboard/workload-dashboard.yaml
- hack/vela-templates/cue/metrics.cue
- pkg/commands/status.go
- pkg/controller/common/error.go
- pkg/controller/utils/utils.go
- pkg/controller/v1alpha1/metrics/metricstrait_controller.go
- pkg/controller/v1alpha1/metrics/metricstrait_controller_integration_test.go
- pkg/controller/v1alpha1/routes/route_controller.go
- pkg/controller/v1alpha1/routes/util.go
- pkg/oam/trait_checker.go
> fix metric capability and add tutroial

- README.md
- docs/introduction.md
The concern I had in previous PR is it's  too long for a single page introduction doc. 
So I tried to shrink the content as I can. Please kindly review and ensure the original messages are conveyed properly.
> Follow up introduction doc

- docs/introduction.md
Small editions for better readability.
> Fix some small nits for introduction

- charts/vela-core/templates/defwithtemplate/manualscale.yaml
- cmd/core/main.go
- docs/developers/set-metrics.md
- e2e/raw-objects/samples/metrics-demo/prometheus/prometheus-oam.yaml
- hack/vela-templates/cue/manualscale.cue
- pkg/commands/util/init.go
- pkg/controller/dependency/install.go
- pkg/controller/dependency/promethus.go
- pkg/controller/v1alpha1/metrics/metricstrait_controller.go
> start promethus instance on installation

- charts/vela-core/templates/defwithtemplate/autoscale.yaml
- charts/vela-core/templates/velaConfig.yaml
- docs/README.md
- docs/developers/set-autoscale.md
- docs/developers/set-autoscaling.md
- hack/vela-templates/cue/autoscale.cue
- hack/vela-templates/definitions/autoscale.yaml
- pkg/commands/status.go
- pkg/controller/v1alpha1/autoscaler/autoscaler_controller.go
added Autoscaler docs and add spec.extension.template
for cli and appfile
> Add Autoscaler docs and support cli and appfile

- docs/install.md
the copy-paste friendly thing could be handled on website.
> minor update

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-core/templates/defwithtemplate/worker.yaml
- hack/vela-templates/cue/webservice.cue
- hack/vela-templates/cue/worker.cue
> don't specify replica in template

- pkg/commands/capability.go
- pkg/server/handler/capabilityHandlers.go
This function is called one more time.
> Function SyncCapabilityFromCenter Called twices.

- docs/concepts.md
This is a suggested revision for better readability.
> Revise concepts.md

- api/types/capability.go
- charts/vela-core/templates/defwithtemplate/autoscale.yaml
- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-core/templates/velaConfig.yaml
- docs/developers/set-autoscale.md
- e2e/commonContext.go
- examples/testapp/vela.yaml
- hack/vela-templates/cue/autoscale.cue
- hack/vela-templates/cue/webservice.cue
- hack/vela-templates/definitions/autoscale.yaml
- pkg/controller/v1alpha1/autoscaler/keda.go
- pkg/controller/v1alpha1/autoscaler/types.go
- pkg/cue/convert.go
- pkg/oam/trait_checker.go
- pkg/oam/workload.go
completed spec.extension.template to support autoscale in
cli and appfile
> Autoscaler for appfile

- docs/design/appfile-design.md
> Fix `capabilities system of OAM` links

- docs/en/developers/set-autoscale.md
- examples/testapp/vela.yaml
- pkg/oam/trait_checker.go
fixed autoscale Cli and Appfile inconsistence
and refactor `vela status` output for autoscale
Fix #545
> Fix autoscale inconsistence UI

- docs/en/design.md
This change fixes various gramma issues and improves the readability.
> Revise design.md

- docs/_sidebar.md
- docs/en/platform-engineers/extending-kubevela.md
- docs/en/quick-start.md
> Revert "Focus on appfile in docs (part 1)"

- docs/_sidebar.md
- docs/en/install.md
- docs/en/platform-engineers/trait.md
- docs/en/quick-start.md
> Fix the previous missing directory

- docs/en/developers/references/traits/rollout.md
- docs/en/developers/references/traits/route.md
- docs/en/developers/set-metrics.md
- docs/en/developers/set-rollout.md
> update rollout doc

- api/types/capability.go
- docs/examples/raw/raw.yaml
- e2e/commonContext.go
- pkg/appfile/service.go
- pkg/commands/refresh.go
- pkg/commands/status.go
- pkg/commands/traits.go
- pkg/commands/util/helpers.go
- pkg/commands/workloads.go
- pkg/cue/convert_test.go
- pkg/cue/testdata/workloads/empty.cue
- pkg/plugins/cluster.go
1. keep silence when no Capability discovered
2. clean code
>  keep silence when no Capability discovered && clean code

- docs/_sidebar.md
> Fix typo in previous fix

- docs/_sidebar.md
- docs/en/developers/learn-appfile.md
- docs/en/introduction.md
As titled said. Also hided empty docs.
> Fix typos in docs

- docs/_sidebar.md
The previous comment doesn't work for website.
> Hide empty docs

- charts/vela-core/templates/defwithtemplate/autoscale.yaml
- charts/vela-core/templates/defwithtemplate/manualscale.yaml
- charts/vela-core/templates/defwithtemplate/metrics.yaml
- charts/vela-core/templates/defwithtemplate/rollout.yaml
- charts/vela-core/templates/defwithtemplate/route.yaml
- charts/vela-core/templates/defwithtemplate/task.yaml
- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-core/templates/defwithtemplate/worker.yaml
- hack/vela-templates/definitions/autoscale.yaml
- hack/vela-templates/definitions/manualscale.yaml
- hack/vela-templates/definitions/metrics.yaml
- hack/vela-templates/definitions/rollout.yaml
- hack/vela-templates/definitions/route.yaml
- hack/vela-templates/definitions/task.yaml
- hack/vela-templates/definitions/webservice.yaml
- hack/vela-templates/definitions/worker.yaml
> update descriptions of capabilities

- docs/en/developers/references/traits/rollout.md
ref https://github.com/oam-dev/kubevela/issues/601
explained a bit rollout fields.
> Fix nits in rollout ref doc

- docs/en/platform-engineers/workload-type.md
Fix the doc with more details.
> Refactor workload type doc

- docs/en/developers/cap-center.md
> Add details in cap mgmt

- docs/en/roadmap.md
> Update roadmap a bit

- Makefile
- api/api.go
- api/generate.go
- charts/vela-core/crds/standard.oam.dev_podspecworkloads.yaml
- hack/chart/generate.go
- hack/crd/update.go
> refactor crd generate mode

- README.md
> Use doc site for quick start

- README.md
> add README badges

- charts/vela-core/templates/defwithtemplate/autoscale.yaml
- charts/vela-core/templates/defwithtemplate/webservice.yaml
- docs/en/developers/references/workload-types/web-service.md
- e2e/commonContext.go
- hack/vela-templates/cue/autoscale.cue
- hack/vela-templates/cue/webservice.cue
based on the comments https://github.com/oam-dev/kubevela/pull/566#discussion_r522385511
and https://github.com/oam-dev/kubevela/issues/585#issuecomment-726253432,
update docs and comments on webservice and autoscale
> Minor updates on webservice/autoscale docs/comments

- Makefile
- e2e/commonContext.go
- e2e/workload/workload_test.go
- pkg/commands/cli.go
- pkg/commands/completion.go
- pkg/commands/config_test.go
- pkg/commands/exec.go
- pkg/commands/exec_test.go
- pkg/commands/ls.go
- pkg/commands/portforward.go
- pkg/commands/portforward_test.go
- pkg/commands/refresh.go
- pkg/commands/show.go
- pkg/commands/traits.go
- pkg/commands/up_test.go
- pkg/controller/core.oam.dev/applicationdeployment/applicationdeployment_controller.go
- pkg/controller/utils/utils.go
- pkg/controller/v1alpha1/autoscaler/autoscaler_controller.go
- pkg/cue/convert.go
- pkg/oam/application.go
- pkg/oam/component.go
- pkg/oam/trait_checker.go
- pkg/oam/workload.go
- pkg/plugins/cluster.go
- pkg/server/traitHandler.go
- pkg/utils/common/common.go
> fix go imports lint complain

- docs/en/design.md
> Update design description

- docs/en/quick-start.md
- docs/examples/vela.yaml
> change demo app name to avoid see unhealthy status too quick

- docs/en/introduction.md
> Fix broken link in introduction

- pkg/commands/cli.go
To make it consistent to the description of KubeVela repo
> Update vela Cli description

- pkg/commands/dashboard.go
Hide this command until we renovate the tool with CUE schema.
> hide dashboard command

- pkg/utils/helm/helm.go
ref #629
This could make `vela workloads/traits` a little faster
> check helm release first before add repo and install chart

- pkg/commands/system.go
- pkg/plugins/cluster.go
it could self-heal after background installation succeed
ref #630
> add tips about vela install capability not ready instead of directly fail

- pkg/controller/v1alpha1/routes/ingress/api.go
- pkg/controller/v1alpha1/routes/ingress/contour_ingress.go
- pkg/controller/v1alpha1/routes/ingress/contour_ingress_test.go
support contour ingress controller
> support contour ingress controller

- design/vela-core/componenttrait-composing-and-trait-CR-naming.md
Add the design docs for OAM Kubernetes Runtime PR
https://github.com/crossplane/oam-kubernetes-runtime/pull/305
> ComponentTrait composing and trait CR naming design

- .github/workflows/docker.yml
- .github/workflows/release.yml
Publish multi image when tags `v*`
> Version tags should handle in workflow docker.yml

- pkg/server/appHandlers.go
Ref #645 
This PR adds comments into the file to solve the lint errors.
> Fix lints in appHandlers.go

- cmd/core/main.go
correct the usage desc of flag 'log-file-path'
> correct usage of flag 'log-file-path'

- .golangci.yml
- pkg/commands/comp.go
- pkg/commands/dashboard.go
- pkg/commands/env.go
- pkg/commands/exec.go
- pkg/commands/init.go
- pkg/commands/logs.go
- pkg/commands/ls.go
- pkg/commands/status.go
- pkg/commands/system.go
- pkg/commands/template.go
- pkg/commands/trait.go
- pkg/commands/traits.go
- pkg/commands/up.go
- pkg/commands/util/helpers.go
- pkg/commands/workloads.go
> fix lint issues in /pkg/commands

- design/vela-core/apply-once-only.md
> doc for apply-once-only

- docs/en/install.md
- docs/install.ps1
- docs/install.sh
Supported macOS/Linux/Windows platform.
Fix #625
> Install KubeVela Cli by script

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/oam/util/test_utils.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/handler_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler_test.go
- fix validating-webhook of appconfig controller cannot recognize workloadDefinitionName
- fix minor lint issues
> fix webhook about Trait-Applyto

- codecov.yml
- docs/examples/argo/Dockerfile
- docs/examples/argo/app.yaml
- docs/examples/argo/argo-cm.yaml
- docs/examples/argo/deploy.yaml
- docs/examples/argo/run.sh
- docs/examples/argo/vela-cm.yaml
- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/application/app.go
- pkg/commands/cli.go
- pkg/commands/export.go
- pkg/commands/up.go
fix https://github.com/oam-dev/kubevela/issues/674
> add export command and argo gitops sample

- design/vela-core/migrate-from-oam-runtime.md
> add doc for users to migrate from oam-runtime to kubevela

- docs/_sidebar.md
To fix 404 issue https://kubevela.io/#/en/developers/references/workload-types/web-service
and add manualscalertrait link
> Fix Webservice/worker reference link 404 and add Scaler link

- docs/en/developers/references/devex/faq.md
Added another case in FAQ.
Fix #701
> Add "warning: Namespace cert-manager exists" in FAQ

- design/vela-core/appfile-design.md
- docs/en/developers/learn-appfile.md
Fixed broken link for `Capability Oriented` in appfile-design.md
> Fix broken link

- .github/workflows/go.yml
- OWNERS
- OWNERS_ALIASES
- e2e/cli.go
remove oam-k8s-runtime referrence
> update owners file

- Makefile
> add release version into README

- docs/_navbar.md
- docs/blog/_navbar.md
- docs/blog/en/README.md
- docs/blog/en/_sidebar.md
- docs/blog/en/kubevela-the-extensible-app-platform-based-on-open-application-model-and-kubernetes.md
- docs/blog/zh/README.md
- docs/blog/zh/_sidebar.md
- docs/blog/zh/kubevela-the-extensible-app-platform-based-on-open-application-model-and-kubernetes.md
- docs/en/_sidebar.md
- docs/en/blog/README.md
- docs/en/blog/_sidebar.md
- docs/en/install.md
- docs/index.html
- add blog tab
- add blog: **KubeVela: The Extensible App Platform Based on Open Application Model and Kubernetes**
- update footer
- update install docs: add `brew install kubevela`
- fix some issues
> Docs update

- pkg/appfile/appfile.go
> fix: load appfile

- docs/en/developers/references/devex/faq.md
Added the question from #704 in FAQ
> Add `what's the difference between Kubevela and helm` in FAQ

- docs/en/platform-engineers/trait.md
In extending trait docs, correct heading level for "Step 3"
> Minor docs fix

- e2e/cli.go
- hack/chart/generate.go
- hack/references/generate.go
- hack/utils/common.go
- pkg/controller/dependency/install.go
> fix golint issues

- Makefile
> Add make target to start both OpenAPI server and dashboard

- pkg/commands/exec.go
- pkg/commands/exec_test.go
add svc flag for exec command.
> add svc flag for exec command.

- pkg/application/app.go
- pkg/application/app_test.go
- pkg/commands/exec.go
- pkg/commands/exec_test.go
- pkg/commands/portforward_test.go
- pkg/commands/trait.go
- pkg/serverlib/workload.go
> application not found return error. fix #685

- dashboard/config/routes.ts
- dashboard/src/components/RightContent/WorkSpaceDropDown.tsx
- dashboard/src/locales/en-US/menu.ts
- dashboard/src/locales/zh-CN/menu.ts
- dashboard/src/pages/Application/index.tsx
- dashboard/src/pages/System/Environment/index.tsx
- dashboard/src/services/API.d.ts
- dashboard/src/services/application.ts
- dashboard/src/utils/compatibleDayjs.ts
- pkg/serverlib/application.go
1.add application list page
2.ignore the deleted applicationconfig resource instead return nil
3.code style fix
> add application list

- pkg/commands/system.go
- pkg/plugins/cluster.go
Refined error message for vela installation and increase
timeout to 5 minutes from 2 minutes. And did some code
refactoring
To fix issue #783
> Refine error message for vela installation

- docs/static/toc.css
Fixed toc display bug when screen is too narrow
> [Docs] fix toc of docs

- apis/core.oam.dev/v1alpha2/core_types.go
- apis/core.oam.dev/v1alpha2/zz_generated.deepcopy.go
- charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler_test.go
> implement conflictsWtih feature in trait definition

- charts/vela-core/templates/webhook.yaml
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go
- test/e2e-test/suite_test.go
- enable webhooks: validating&mutating for appconfig&component 
- fix e2e tests
> enable webhooks for AppConfig/Comp

- config/samples/vela-server/README.md
- config/samples/vela-server/template.yaml
- pkg/dsl/definition/template.go
- pkg/dsl/definition/template_test.go
- pkg/dsl/model/instance.go
- pkg/dsl/model/sets/operation.go
- pkg/dsl/model/sets/operation_test.go
- pkg/dsl/model/sets/utils.go
- pkg/dsl/model/sets/walk.go
- pkg/dsl/model/sets/walk_test.go
base template as follow
```
containers: [{
name: "x1"
}, {
name: "x2"
image:  string
envs: [{
key: "OPS"
value: string
}, ...]
}, ...]
```
define patch template
```
// +patchKey=name
containers: [{
name: "x2"
image:  "test-image"
// +patchKey=key
envs: [{
key: "OPS1"
value: "V-OPS1"
},{
key: "OPS"
value: "V-OPS"
}, ...]
}, ...]
```
and the result template after patch is follow 
```
containers: [{
name: "x1" 
},{
name: "x2"
image:  "test-image"
envs: [{
key: "OPS1"
value: "V-OPS1"
},{
key: "OPS"
value: "V-OPS"
}, ...]
}, ...]
```
> supports strategy patch for definition template

- OWNERS
- OWNERS_ALIASES
to reflect the community membership: https://github.com/oam-dev/kubevela/blob/master/community.md
> update owner file

- OWNERS_ALIASES
ref https://github.com/oam-dev/kubevela/issues/693#issuecomment-749696403
@sunny0826 has contributed major code in the website and dashboard. Added him into dashboard-reviewer now.
Thanks for sunny0826's contributions and congratulations!
> add sunny0826 (Xudong Guo) as reviewer

- docs/en/developers/references/devex/faq.md
…configuration exists?"
Added another question.
To cover issue #794
>     Add "How to fix issue: MutatingWebhookConfiguration mutating-webhook-configuration exists?"

- dashboard/src/pages/Capability/Workloads/index.tsx
Added `description` field for workloads.
To fix #821
> Add description field for Capability/Workloads list

- pkg/controller/core.oam.dev/v1alpha2/application/builder/build.go
> Use the correct cue parse api

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_without_traitdefinition_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/controller/standard.oam.dev/v1alpha1/autoscaler/autoscaler_controller.go
- pkg/oam/util/helper.go
Fix the issue of applying trait if its traitdefinition
doesn't exits.
To fix issue #839
> Allow trait to work without TraitDefinition

- dashboard/src/pages/Capability/Components/ShowComponent/index.tsx
- dashboard/src/pages/Capability/Traits/index.tsx
- dashboard/src/pages/Capability/Workloads/index.tsx
- dashboard/yarn.lock
Fix the problem discussed in https://github.com/oam-dev/kubevela/pull/834#discussion_r549551292
> Fix `each child in a list should have a unique "key" prop.'

- charts/vela-core/templates/defwithtemplate/route.yaml
- hack/vela-templates/cue/route.cue
#849 add provider to route,and default with nginx
> Add provider parameter to route trait

- dashboard/src/locales/zh-CN/menu.ts
- dashboard/src/pages/Capability/Components/ShowComponent/index.tsx
- dashboard/src/pages/Capability/Traits/index.tsx
- dashboard/src/pages/Capability/Workloads/index.tsx
- dashboard/src/services/API.d.ts
- dashboard/yarn.lock
1.fix repeated click does not show component bug
2.typed
3.fix locales
> Dashboard fix

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_without_traitdefinition_test.go
> fix unstable unit test

- .github/workflows/go.yml
- apis/core.oam.dev/v1alpha2/appdeploy_types.go
- apis/standard.oam.dev/v1alpha1/rollout_plan_types.go
- charts/vela-core/crds/core.oam.dev_applicationdeployments.yaml
- charts/vela-core/crds/standard.oam.dev_rollouttraits.yaml
- design/vela-core/rollout-design.md
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationdeployments.yaml
- legacy/charts/vela-core-legacy/crds/standard.oam.dev_rollouttraits.yaml
> Rollout Design Doc

- docs/en/developers/references/restful-api/index.html
- pkg/server/definitionHandler.go
- pkg/server/docs/docs.go
- pkg/server/docs/swagger.json
- pkg/server/docs/swagger.yaml
- pkg/server/route.go
Added Getdefinition api docs and update email contact
> Add Getdefinition OpenAPI in Restful-api docs

- docs/index.html
Use variable-year in copyrights.
> happy new year

- design/vela-core/APIServer-Catalog.md
- add application creation workflow
- make application adaptable to multiple env and clusters
- add module into catalog package format and adapt to helm/terraform
The design will fix https://github.com/oam-dev/kubevela/issues/864 https://github.com/oam-dev/kubevela/issues/895
> update APIServer + Catalog design

- cmd/core/main.go
- pkg/appfile/storage/storage.go
- pkg/appfile/storage/storage_test.go
- pkg/application/app.go
- pkg/utils/system/system.go
Issue: https://github.com/oam-dev/kubevela/issues/751
> support env and config storage driver

- Makefile
- apis/core.oam.dev/v1alpha2/application_types.go
- apis/core.oam.dev/v1alpha2/application_types_test.go
- cmd/core/main.go
- pkg/controller/core.oam.dev/v1alpha2/application/appfile_parser_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_parser_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationdeployment/applicationdeployment_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationdeployment/workload.go
- pkg/oam/util/helper.go
- pkg/oam/util/template.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/common.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/common_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/validating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/validation.go
- test/e2e-test/kubernetes_workload_test.go
added code dealing with fetching component from application
> some initial code for app deployment controller/webhook

- go.mod
- go.sum
fix assert.Equal can't reflect deep equal for object.
> upgrade github.com/stretchr/testify try fix CI

- apis/core.oam.dev/v1alpha2/appdeploy_types.go
- apis/core.oam.dev/v1alpha2/application_types.go
- design/vela-core/rollout-design.md
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/oam/labels.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler_test.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validation.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/validation.go
1.  application controller don't touch applications with this annotation
2. webhook blocks any rollout annotation to be added to an existing application
> Add rollout annotation logic in application

- docs/en/developers/references/restful-api/index.html
- e2e/apiserver/apiserver_test.go
- pkg/commands/export.go
- pkg/commands/up.go
- pkg/commands/up_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/appconfig_suit_test.go
- pkg/server/apis/types.go
- pkg/server/appHandlers.go
- pkg/server/docs/docs.go
- pkg/server/docs/swagger.json
- pkg/server/docs/swagger.yaml
- pkg/server/route.go
- pkg/server/workloadHandler.go
- pkg/serverlib/application.go
Implemented Application creation OpenAPI based on new Application object
To #913
> OpenAPI: Application creation based on Application object

- e2e/apiserver/apiserver_test.go
- e2e/commonContext.go
- pkg/serverlib/application.go
+ fix #718 
Signed-off-by: mahao <allenhaozi@gmail.com>
> update delete app prompt information

- e2e/capability/capability_test.go
- pkg/oam/util/helper.go
- pkg/oam/util/helper_test.go
- pkg/plugins/testdata/ingressDef.yaml
> allow traitDefinition to omit definitionRef

- .github/workflows/release.yml
- Makefile
fix #961
I have tested in my repo https://github.com/wonderflow/kubevela/releases/tag/v0.1.16
> build linux/arm64 cli command

- Makefile
- charts/vela-core/values.yaml
- docs/en/install.md
1. Introduce `helm install` instead of `vela install`
2. don't install cert-manager by default in kubevela chart
3. remove unused doc
> update kubevela installation guide

- charts/vela-core/templates/definitions/containerizedworkloads.yaml
- pkg/controller/core.oam.dev/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go
> fix inner containerizedworkload not work

- .github/workflows/registry.yml
Short the description will be better.
> minor change for CI name

- .github/workflows/registry.yml
```
Warning  Failed     27s (x3 over 75s)  kubelet            Failed to pull image "oamdev/vela-core:0.3.1": rpc error: code = Unknown desc = Error response from daemon: manifest for oamdev/vela-core:0.3.1 not found: manifest unknown: manifest unknown
```
> fix pull image error

- .github/workflows/registry.yml
> bump #981 into release-0.3

- pkg/commands/cli.go
- pkg/commands/show.go
Also updated help vela help message
> Change "vela show" function name

- pkg/commands/system.go
This PR will resolve the issue #979 .
> Fixed wrong chart name

- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/helper.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/helper_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler_test.go
- to fix #919   fix #988
- move the basic validation on traits into the preparing validating phase
> use dummy trait definition in appconfig webhook

- .github/workflows/registry.yml
- legacy/README.md
- legacy/charts/vela-core-legacy/Chart.yaml
Also pushed it to oss bucket
To fix #528
> Build KubeVela legacy chart

- design/vela-core/APIServer-Catalog.md
> Fix link in APIServer-Catalog Examples

- docs/en/platform-engineers/overview.md
Remove the verbose details and focus on building abstractions for now.
> Fix doc detail

- docs/en/_sidebar.md
- docs/en/platform-engineers/overview.md
We should use `Application Encapsulation` instead of abstraction. This reflects what we are doing better.
> Update the details of the doc

- apis/standard.oam.dev/v1alpha1/rollout_plan_types.go
- apis/standard.oam.dev/v1alpha1/rollout_state.go
- charts/vela-core/crds/core.oam.dev_applicationdeployments.yaml
- charts/vela-core/crds/standard.oam.dev_rollouttraits.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationdeployments.yaml
- legacy/charts/vela-core-legacy/crds/standard.oam.dev_rollouttraits.yaml
- pkg/controller/common/rollout/rollout_plan_controller.go
- pkg/controller/common/rollout/workloads/cloneset_controller.go
- pkg/controller/common/rollout/workloads/common.go
- pkg/controller/common/rollout/workloads/controller.go
- pkg/webhook/common/rollout/rollout_plan.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/validation.go
add more code to cloneset rollout plan
1. Add rollout plan mutation
2. Add validation
3. completed the rollout state transitions
> add more code to cloneset rollout plan

- apis/core.oam.dev/v1alpha2/core_types.go
- charts/vela-core/crds/core.oam.dev_applicationconfigurations.yaml
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- cmd/core/main.go
- design/vela-core/apply-once-only.md
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationconfigurations.yaml
- pkg/controller/core.oam.dev/oamruntime_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
> implement ApplyOnceOnlyForce

- pkg/serverlib/capability.go
> fix cap error message

- pkg/serverlib/capability.go
- pkg/serverlib/capability_test.go
fix #1029
fix issue  [1029](https://github.com/oam-dev/kubevela/issues/1029)
add source info into workload/trait definition's **extension** field
> fix vela traits not compatible with installed capability

- pkg/appfile/parser_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_trait_test.go
> quick fix unstable unit test

- .github/workflows/dashboard.yml
- .github/workflows/release.yml
- Makefile
- dashboard/src/pages/CreateApplication/index.tsx
- dashboard/src/services/API.d.ts
- dashboard/src/services/application.ts
Submit application creation form to create an application, currently
only creating workloads is supported.
To partly implement #1039
> [Dashboard] Create application (without trait)

- config/samples/application/README.md
- config/samples/application/template.yaml
- docs/en/cue/trait.md
> update doc about traitDef definitionRef

- docs/en/_sidebar.md
- docs/en/application.md
- docs/en/concepts.md
- docs/en/cue/basic.md
- docs/en/cue/status.md
- docs/en/cue/trait.md
- docs/en/cue/workload-type.md
- docs/en/platform-engineers/overview.md
- docs/en/platform-engineers/trait.md
- docs/en/platform-engineers/workload-type.md
- docs/en/quick-start.md
Revise the whole doc site and updated App CRD doc.
> Revise the doc site and app crd doc

- pkg/commands/cli.go
- pkg/commands/help.go
According to[ this doc](https://github.com/spf13/cobra#defining-your-own-help) fix it. Fix Issue:https://github.com/oam-dev/kubevela/issues/134
> fix vele help cli

- docs/en/_sidebar.md
- docs/en/cue/basic.md
- docs/en/cue/trait.md
- docs/en/cue/workload-type.md
- docs/en/platform-engineers/trait.md
- docs/en/platform-engineers/workload-type.md
> Fix link in cap docs

- docs/en/concepts.md
- docs/en/developers/learn-appfile.md
- docs/en/quick-start.md
Update other docs based on app crd content.
> Fix quick start and concept based on app crd

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_test.go
to fix #1011 
Bug: the error is caused by ScopeDefinition not found. In normal cases, we need ScopeDefinition to get `workloadRefPath`. 
Solution: During finalizing AppConfig, if ScopeDefinition is not found, omit the NotFound error and regard it as finalizing successfully.
> ScopeDefinition not found should not block finalizer

- docs/en/quick-start.md
A follow up, some typos need fix.
> Fix typo in vela appfile doc

- dashboard/config/routes.ts
- dashboard/src/locales/en-US/menu.ts
- dashboard/src/locales/zh-CN/menu.ts
- dashboard/src/pages/Application/Create/index.tsx
- dashboard/src/pages/Application/index.tsx
- dashboard/src/types/FormRender/index.d.ts
- dashboard/yarn.lock
1.Organize the menu
2.Add application menu locales
3.Fix create application button style
4.Add FormRender d.ts
> [Dashboard] Application creation UI optimization

- dashboard/config/defaultSettings.ts
> [Dashboard] Add KubeVela Dashboard logo

- dashboard/config/routes.ts
1.set applications as homepage
2.path use lowercase
> [Dashboard] Route optimization

- docs/en/install.md
> Add sync capability section in install doc

- dashboard/src/pages/Application/Create/components/CapabilityFormItem/index.tsx
- dashboard/src/pages/Application/Create/components/CapabilitySelector/index.tsx
- dashboard/src/pages/Application/Create/components/FormGroup/index.tsx
- dashboard/src/pages/Application/Create/components/ServiceForm/index.tsx
- dashboard/src/pages/Application/Create/components/TraitsFrom/index.tsx
- dashboard/src/pages/Application/Create/index.tsx
- dashboard/src/pages/Application/index.tsx
1.Create app impl
2.Polling waiting for the app to be deleted
> [Dashboard] Create application with traits

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render_test.go
Special treatment for names in appConfig generated by an Application
1. in-place upgradable workload name will be component 
2. otherwise, it will be componentRevision Name
3. We ban name in the metadata field
> render the workload and trait name differently

- pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/mutating_handler.go
fix #1057  , use json.Marshal print Object spec field
> fix issue#1057

- .github/workflows/go.yml
> enable CI for release-*

- cmd/core/main.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go
- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_suite_test.go
- pkg/utils/apply/apply_test.go
also add log for apply-only-once
> fix apply only once observedGeneration should mark after all dependency requirements meet

- cmd/core/main.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go
- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_suite_test.go
- pkg/utils/apply/apply_test.go
add log for apply only once
cherry-pick(#1094)
> cherry-pick(#1094) fix apply only once observedGeneration should mark after meet all dependency requirements

- config/samples/application/README.md
- config/samples/application/template.yaml
- docs/en/cue/trait.md
- docs/en/platform-engineers/trait.md
- pkg/appfile/parser_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/cue/testdata/traits/manualscaler.cue
- pkg/cue/testdata/traits/rollout.cue
- pkg/cue/testdata/traits/route.cue
- pkg/cue/testdata/workloads/metrics.cue
- pkg/dsl/definition/template.go
- pkg/dsl/definition/template_test.go
- pkg/dsl/process/handle.go
- pkg/dsl/process/handle_test.go
- pkg/webhook/core.oam.dev/v1alpha2/application/suite_test.go
- references/plugins/testdata/manualscalars.yaml
- references/plugins/testdata/traitDef.yaml
> output not allowed in traitdefinition, should use outputs

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component_custom_revision_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
the status of component update will trigger controller reconcile and create component revision again and again
> fix component custom revison loop infinitely create revision

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
add a unit test to cover: if ApplyOnceOnlyForce is enabled, for the AC with unsatisfied dependencies, it should create the workloads correctly once the dependencies are all satisfied.
> add unit test

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
> cherry-pick(#1099) add unit test

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
fix application controller loop
> fix application controller loop

- pkg/appfile/parser_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_without_traitdefinition_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_trait_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/dependency_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
cherry-pick #1041 and #1036 
fix merging conflicts
> cherry-pick(1041&1036) fix unit test 

- apis/core.oam.dev/v1alpha2/core_types.go
- charts/vela-core/crds/core.oam.dev_applicationconfigurations.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationconfigurations.yaml
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
fix test case and fix a bug that workload was not created the first time AC created
> update CRD and fix workload not create first time

- docs/en/concepts.md
- docs/en/cue/trait.md
- docs/en/install.md
- docs/en/platform-engineers/workload-type.md
modified some document writing errors
> fix:fix doc, error link and format

- .github/workflows/release.yml
- Makefile
Fixed Issue: https://github.com/oam-dev/kubevela/issues/1125
Because of [this issue](https://github.com/mitchellh/gox/issues/92). Revert PR：#967
> fix arm64 build failed and block our release pipeline

- .github/workflows/go.yml
- Makefile
- apis/standard.oam.dev/v1alpha1/rollout_plan_types.go
- charts/vela-core/crds/core.oam.dev_applicationdeployments.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-core/crds/standard.oam.dev_rollouttraits.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationdeployments.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/standard.oam.dev_rollouttraits.yaml
- pkg/controller/common/rollout/rollout_webhook.go
- pkg/controller/common/rollout/rollout_webhook_test.go
> Add webhook test

- pkg/controller/core.oam.dev/oamruntime_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
> fix garbage collection for apply once force model

- docs/en/developers/port-forward.md
fix https://github.com/oam-dev/kubevela/issues/996
> fix vela svc ls error

- docs/en/install.md
fix https://github.com/oam-dev/kubevela/issues/1149
> improve install doc command style

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_suite_test.go
- pkg/utils/apply/apply_test.go
> use klog/v2 as logger in util/apply

- docs/en/cue/workload-type.md
add a application use **webserver** workload
> doc: add demo for webserver workload

- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/workloaddefinition/workloaddefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/workloaddefinition/workloaddefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/workloaddefinition/workloaddefinition_suite_test.go
- pkg/controller/utils/capability.go
- pkg/controller/utils/capability_integrate_test.go
- pkg/controller/utils/capability_suite_test.go
- pkg/controller/utils/capability_test.go
Added or updated copyright in newly added files for
orkloaddefinition and traitdefinition controllers and
its dependencies
> Add or update copyright for workload/trait definition controllers

- pkg/appfile/parser.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationdeployment/suite_test.go
- pkg/controller/utils/utils.go
- pkg/controller/utils/utils_test.go
- pkg/dsl/definition/template.go
- pkg/dsl/definition/template_test.go
- pkg/dsl/process/handle.go
- pkg/dsl/process/handle_test.go
- pkg/oam/labels.go
- references/appfile/addon.go
> add appRevision into context

- .github/workflows/release.yml
- Makefile
issue ref: https://github.com/oam-dev/kubevela/issues/1163
> fix arm64 build failed 

- pkg/controller/common/rollout/workloads/cloneset_controller.go
- pkg/webhook/common/rollout/rollout_plan.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/common_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationdeployment/validation.go
- test/e2e-test/rollout_plan_test.go
- test/e2e-test/testdata/rollout/cloneset/app-target.yaml
enable a few add rollout e2e tests after they are stable enough
> Enable more rollout e2e tests

- test/e2e-test/appconfig_finalizer_test.go
- test/e2e-test/containerized_workload_test.go
- test/e2e-test/rollout_plan_test.go
enable rollout failure then revert  e2e test
> enable rollout fail revert e2e test

- .github/workflows/license.yml
- .license/README.md
- .license/dependency_decisions.yml
add license checker in CI https://github.com/pivotal/LicenseFinder
> add license checker into CI

- pkg/utils/env/env.go
fix: #1157 
Check if namespace exists before create it.
> fix: check if namespace exists

- docs/en/_sidebar.md
- docs/en/platform-engineers/definition-and-templates.md
> add doc about definition and template

- test/e2e-test/component_version_test.go
- test/e2e-test/health_scope_test.go
- test/e2e-test/helm_app_test.go
- test/e2e-test/suite_test.go
related to #1188 
Add a workaround to trigger reconcile appconfig
> fix unstable e2e test

- .github/workflows/go.yml
> test run e2e on github native action runner

- .github/workflows/go.yml
- Makefile
> move out rollout e2e

- pkg/controller/common/rollout/workloads/deployment_controller.go
Signed-off-by: Herman Zhu <zhuhuijunzhj@gmail.com>
> fix spelling mistake

- .github/workflows/go.yml
> Revert "test run e2e on github native action runner"

- .github/workflows/go.yml
fix #1219 
add skip condition on e2e-rollout CI
> add skip condition on e2e-rollout CI

- references/common/application.go
Fix #1129
Since we use Application CRD to generate `ApplicationConfiguration`, the `ListApplications` method should get `ApplicationMeta` from `Application` rather than `ApplicationConfiguration`.
The dashboard will also be able to delete `Application` as expected.
> fix(api-server): application meta list reads from application crd

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/oam/util/template.go
Compatible with WorkloadDefinition, the Application allows ApplicationComponent refers to an exited WorkloadDefinition.
> Compatible with WorkloadDefinition for Application

- docs/en/_sidebar.md
Reverts oam-dev/kubevela#1225
We should keep the sidebar organized.
> Revert "refactor docs into 2 layers"

- apis/standard.oam.dev/v1alpha1/rollout_state.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
allow state transition to be modified at any state so someone can revert a rollout at anytime
> allow state transition to be modified at any state

- references/cli/capability.go
- references/cli/help.go
> Clean up code duplicate

- pkg/controller/common/rollout/rollout_webhook_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/dag_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller_helper_test.go
- references/appfile/driver/cfgmaps_test.go
- references/appfile/driver/local_test.go
Function and method names should comply with a naming convention
> Code normalization

- Makefile
- cmd/core/main.go
Signed-off-by: kushthedude <kushthedude@gmail.com>
> feat: add debug-flag for enabling logs in core-run

- docs/en/README.md
Missed a message fix in previous change.
> Fix message in doc readme

- docs/en/cue/basic.md
- docs/examples/dry-run/README.md
- docs/examples/dry-run/app.yaml
- docs/examples/dry-run/definitions/myingress.yaml
- docs/examples/dry-run/definitions/myworker.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/dsl/definition/package.go
- pkg/dsl/definition/package_suit_test.go
- pkg/dsl/definition/package_test.go
- pkg/dsl/definition/suit_test.go
- pkg/dsl/definition/template.go
- pkg/utils/common/common.go
- references/appfile/run.go
- references/cli/dryrun.go
- test/e2e-test/component_version_test.go
- test/e2e-test/rollout_plan_test.go
- test/e2e-test/suite_test.go
1. Add a demo for `vela system dry-run` which is handy for `debug`
2. fix a bug of `CreateOrUpdateObjects` that only update the first object.
> more useful vela system dry-run

- docs/en/_sidebar.md
/cc @wonderflow , now is much better!
> Make sidebar even better

- apis/core.oam.dev/v1alpha2/core_types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-core/crds/core.oam.dev_components.yaml
- docs/examples/cloneset-rollout/README.md
- e2e/application/application_test.go
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_components.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- pkg/oam/labels.go
- test/e2e-test/helm_app_test.go
swap appConfig with appContext
> swap appConfig with appContext

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
> Remove duplicated logic of reset appRollout status

- test/e2e-test/appcontext_test.go
Add e2e test for App Context
test 4 cases
1.AC only have workload
2.AC have a workload and a trait
3.update AC to add a trait
4.update AC to delete a trait
> Add e2e test for App Context

- docs/en/helm/component.md
- docs/examples/helm-module/webapp-chart-cd.yaml
- pkg/appfile/helm/helm.go
- pkg/appfile/helm/helm_test.go
- pkg/appfile/helm/schema.go
- pkg/appfile/helm/schema_test.go
- pkg/appfile/helm/testdata.yaml
- pkg/appfile/helm/testdata/values.schema.json
- pkg/appfile/helm/testdata/values.yaml
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
- pkg/controller/utils/capability.go
- pkg/oam/util/helper.go
- test/e2e-test/component_version_test.go
- test/e2e-test/helm_app_test.go
> generate OpenAPI schema for Helm schematic compDef

- README.md
- docs/README.md
- docs/_coverpage.md
- docs/en/README.md
- docs/en/introduction.md
- docs/en/quick-start.md
1. add more info into the Github Redame, so users can get information of what is kubevela quickly.
2. update the website to point to introduction.
3. minor fix for 404 pages
> update to the website

- README.md
- docs/en/README.md
- docs/en/_sidebar.md
- docs/en/concepts.md
- docs/en/introduction.md
- docs/en/quick-start-appfile.md
Details are added to readme - target on v1.0 release.
Ref: https://github.com/oam-dev/kubevela/pull/1259
> Add more details in readme

- test/e2e-test/component_version_test.go
https://github.com/oam-dev/kubevela/runs/2180778710
> fix a flaky test in  ci

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- test/e2e-test/component_version_test.go
- test/e2e-test/helm_app_test.go
- test/e2e-test/suite_test.go
> re-open e2e-test for helm schematic

- docs/en/application.md
- docs/examples/registry/hpa.cue
- docs/examples/registry/hpa.yaml
- pkg/dsl/definition/template.go
- pkg/dsl/definition/template_test.go
1. add a hpa trait in readme
2. fix render template with nil params.
> add hpa trait and fix render template with nil params

- Makefile
- apis/core.oam.dev/v1beta1/componentdefinition_types.go
- pkg/appfile/parser.go
- pkg/dsl/definition/package_suit_test.go
- pkg/oam/mock/mocks.go
- pkg/oam/util/template.go
- pkg/oam/util/template_test.go
- pkg/oam/util/test_utils.go
- test/e2e-test/helm_app_test.go
When Application containing helm moudle which defined by WorkloadDefinition, we set workload.DefinitionReference refer to
the DefinitionReference in workloadDefinition.
> Compatible with Application containing WorkloadDefinition type helm moudle

- cmd/core/main.go
> Delay vela-core related controller sync time

- references/apiserver/apis/types.go
- references/appfile/addon_suit_test.go
- references/appfile/api/appfile.go
- references/appfile/api/appfile_test.go
- references/appfile/app.go
- references/appfile/modify.go
- references/appfile/run.go
- references/appfile/testdata/terraform-aliyun-oss-workloadDefinition.yaml
- references/appfile/testdata/workloadDef.yaml
- references/cli/cli.go
- references/cli/components.go
- references/cli/exec.go
- references/cli/logs.go
- references/cli/ls.go
- references/cli/portforward.go
- references/cli/status.go
- references/cli/workloads.go
- references/common/application.go
- references/common/capability.go
- references/common/trait.go
- references/plugins/capcenter.go
- references/plugins/cluster.go
- references/plugins/suit_test.go
- references/plugins/testdata/ingressDef.yaml
- references/plugins/testdata/manualscalars.yaml
- references/plugins/testdata/websvcWorkloadDef.yaml
- references/plugins/testdata/workloadDef.yaml
> Upgrade CRD types called in vela-cli from v1alpha2 to v1beta1 

- apis/standard.oam.dev/v1alpha1/rollout_plan_types.go
- apis/standard.oam.dev/v1alpha1/rollout_state.go
- pkg/controller/common/rollout/rollout_plan_controller.go
- pkg/controller/common/rollout/workloads/cloneset_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/webhook/common/rollout/rollout_plan.go
- pkg/webhook/common/rollout/rollout_plan_test.go
- test/e2e-test/rollout_plan_test.go
we need an abandoning state in the rollout to handle user abandon the rollout in the middle of it
> add abandoning state to the rollout

- .github/README.md
- docs/en/application.md
- docs/en/concepts.md
- docs/en/cue/basic.md
- docs/en/cue/component.md
- docs/en/cue/development-guide.md
- docs/en/cue/status.md
- docs/en/cue/trait.md
- docs/en/helm/component.md
- docs/en/helm/known-issues.md
- docs/en/helm/trait.md
- docs/en/install.md
- docs/en/platform-engineers/cloud-services.md
- docs/en/platform-engineers/definition-and-templates.md
- docs/en/platform-engineers/openapi-v3-json-schema.md
- docs/en/platform-engineers/overview.md
- docs/en/quick-start.md
- docs/examples/vela-app.yaml
> update the docs v1alpha2->v1beta1

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
- test/e2e-test/rollout_plan_test.go
fix appRevision label getting overridden (with a dedicated test)
> fix appRevision label getting overridden

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render_test.go
- test/e2e-test/component_version_test.go
- test/e2e-test/helm_app_test.go
> fix isControlledByApp function in AC controller

- README.md
Minor fix to make readme better.
> Minor fix for docs

- docs/en/_sidebar.md
- docs/en/platform-engineers/openapi-v3-json-schema.md
- docs/en/platform-engineers/trait.md
> better docs for build trait and use parameters

- references/common/capability.go
- references/common/trait.go
- references/plugins/capcenter.go
- references/plugins/local.go
1. fix the problem which vela components/workloads repeat get components/workloads list.
2. `vela cap center` only deal with ComponentDefinition and TraitDefinition
> fix vela components/workloads and vela cap

- docs/en/platform-engineers/cloud-services.md
> add cloud resource story doc

- test/e2e-test/appcontext_test.go
> fix unstable appcontext e2e test

- pkg/controller/common/rollout/rollout_webhook_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/workloads.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/workloads_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_helper.go
- pkg/oam/labels.go
- test/e2e-test/appcontext_test.go
- test/e2e-test/application_test.go
- test/e2e-test/rollout_plan_test.go
- test/e2e-test/testdata/app/app1.yaml
- test/e2e-test/testdata/app/app2.yaml
- test/e2e-test/testdata/app/app3.yaml
- test/e2e-test/testdata/app/app4.yaml
fix https://github.com/oam-dev/kubevela/issues/1196
> fix app upgrade without rollout and rollout plan will create multiple version resources

- docs/en/kube/component.md
- docs/en/kube/trait.md
- test/e2e-test/application_test.go
- test/e2e-test/helm_app_test.go
- test/e2e-test/kube_app_test.go
- test/e2e-test/rollout_plan_test.go
- test/e2e-test/suite_test.go
fix to catch up with the change related to workload name mechanism.
> fix e2e test of kube schematic

- docs/en/developers/cap-center.md
- docs/en/helm/component.md
- docs/en/helm/trait.md
- references/common/capability.go
- references/plugins/cluster.go
- references/plugins/cluster_test.go
- references/plugins/local.go
- references/plugins/suit_test.go
- references/plugins/testdata/componentDef.yaml
- references/plugins/testdata/websvcComponentDef.yaml
Remove kubewatch demo from docs and fix `vela cap uninstall`
> fix rest CLI align with ComponentDefinition

- docs/en/concepts.md
- docs/en/cue/component.md
- docs/en/cue/status.md
- docs/en/developers/learn-appfile.md
- docs/en/helm/component.md
- docs/en/platform-engineers/debug-test-cue.md
> fix some error links in docs

- .github/workflows/registry.yml
- docs/blog/zh/README.md
- docs/blog/zh/_sidebar.md
fix publish-charts and remove useless md in docs/blog
> fix publish-charts in github-action

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
> Fix revision hash compute

- docs/en/install.mdx
- docs/en/rollout/appdeploy.md
- docs/index.js
- docs/sidebars.js
- pkg/dsl/definition/package_suit_test.go
1. change get-start link to quick-start
2. add upgrade step in installation
> fix get-start link and add upgrade step in installation.md

- docs/docusaurus.config.js
https://github.com/oam-dev/kubevela.io/actions/runs/696625968
> fix docs build

- .github/workflows/check-docs.yml
- hack/website/test-build.sh
add action to check the correctness of docs
> add github action to check the correctness of docs

- pkg/dsl/definition/package.go
- pkg/dsl/definition/package_suit_test.go
pkg/dsl/definition/package_suit_test.go has occasional error “package not found”
> fix unstable test case for crd package

- docs/en/application.md
- docs/examples/registry/sidecar.yaml
> add demo for app doc

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- pkg/oam/util/helper.go
- test/e2e-test/app_resourcetracker_test.go
- test/e2e-test/application_test.go
- test/e2e-test/rollout_plan_test.go
as the title said
fix https://github.com/oam-dev/kubevela/issues/1314
> use ApplicationContext as the owner of all the resources if it controlled by Application

- .gitignore
- CONTRIBUTING.md
- Makefile
- README.md
- docs/README.md
- docs/en/cue/basic.md
- docs/en/platform-engineers/debug-test-cue.md
- docs/sidebars.js
- references/cli/system.go
1. add guide for update kubevela docs
2. fix some link error
> fix docs: add guide for update docs

- references/plugins/cluster.go
fix vela show error.
fix https://github.com/oam-dev/kubevela/issues/1363
> fix cli: fix vela show error

- docs/en/install.mdx
> fix doc: fix upgrade step in install.mdx

- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- test/e2e-test/rollout_plan_test.go
> the application context should not own application object

- README.md
- docs/en/introduction.md
Better introduction and readme.
> Update readme and doc

- docs/sidebars.js
> fix doc: fix the navigation relationship of the sidebar

- pkg/utils/apply/apply.go
- pkg/utils/apply/apply_test.go
- test/e2e-test/app_resourcetracker_test.go
> fix cannot update cross namespace workload application issue

- docs/index.js
Better introduction for kubevela, align with https://github.com/oam-dev/kubevela.io/pull/9
> fix doc: update some description in website homepage

- charts/vela-core/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
- charts/vela-core/templates/admission-webhooks/validatingWebhookConfiguration.yaml
> upgrade kubevela webhook configuration chart to v1

- docs/en/introduction.md
changed "an success story" to "a success story"
> Fix grammar error: changed "an success story" to "a success story"

- docs/en/platform-engineers/cloud-services.md
Refer to the reason https://github.com/oam-dev/kubevela/issues/1128#issuecomment-811590631
> Remove outputSecretName in cloud service provisoning and consuming

- docs/README.md
> fix docs: update contributing guide

- README.md
- docs/en/README.md
- docs/en/application.md
- docs/en/concepts.md
- docs/en/introduction.md
- docs/en/platform-engineers/definition-and-templates.md
- docs/en/platform-engineers/openapi-v3-json-schema.md
- docs/en/platform-engineers/overview.md
- docs/en/rollout/appdeploy.md
- docs/en/rollout/rollout.md
- docs/sidebars.js
> Update docs to reflect app delivery idea

- README.md
> Reword readme for clearer message 

- pkg/appfile/parser.go
- pkg/appfile/parser_test.go
remove all the duplicate fields in parser above as template contains
fix #1388
Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>
> refactor(workload) remove all the duplicate fields

- docs/en/platform-engineers/keda.md
> fix docs: fix some grammar errors in keda.md

- pkg/dsl/definition/package.go
- pkg/dsl/definition/package_suit_test.go
fix the bug that the registered k8s built-in gvk does not exist
> Fix the bug that the registered k8s built-in gvk does not exist

- test/e2e-test/kubernetes_workload_test.go
https://github.com/oam-dev/kubevela/runs/2293896980
> fix flaky test: check component exist

- README.md
- docs/en/README.md
> Finalize the message

- hack/website/release.sh
Stop Chinese document synchronization for translation activities.
> stop zh-CN docs sync

- pkg/controller/core.oam.dev/v1alpha2/appdeployment/appdeployment_controller.go
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>
> Remove useless code

- pkg/controller/common/rollout/workloads/cloneset_controller_integration_test.go
- pkg/controller/common/rollout/workloads/cloneset_controller_test.go
- pkg/controller/common/rollout/workloads/cloneset_rollout_controller.go
- pkg/controller/common/rollout/workloads/deployment_controller.go
- pkg/controller/common/rollout/workloads/deployment_controller_integration_test.go
- pkg/controller/common/rollout/workloads/deployment_controller_test.go
- pkg/controller/common/rollout/workloads/suite_test.go
- pkg/controller/common/rollout/workloads/testdata/apps.kruise.io_clonesets.yaml
Part I: pkg/controller/common/rollout
> Add unit-tests for ApplicationRollout related packages

- README.md
> Update doc for v1.1

- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_suit_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/handler.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go
- pkg/controller/utils/capability.go
- pkg/oam/util/helper.go
- pkg/oam/util/helper_test.go
update crd(ComponentDefinition, TraitDefinition) from v1alpha2 to v1beta1
> fix controller: update crd from v1alpha2 to v1beta1 in ComponentDefinition/TraitDefinition Controller

- apis/standard.oam.dev/v1alpha1/rollout_state.go
- docs/examples/cloneset-rollout/appRollout-scale.yaml
- pkg/controller/common/rollout/workloads/cloneset_controller_integration_test.go
- pkg/controller/common/rollout/workloads/cloneset_rollout_controller.go
- pkg/controller/common/rollout/workloads/cloneset_scale_controller.go
- pkg/controller/common/rollout/workloads/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller_test.go
- pkg/webhook/common/rollout/rollout_plan.go
- pkg/webhook/common/rollout/rollout_plan_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationrollout/mutating_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationrollout/validation.go
- test/e2e-test/rollout_plan_test.go
1. Add default for rolloutStrategy
2. Attempt to fix flaky e2e validation
> fix webhooks and try to fix e2e

- .github/workflows/go.yml
- charts/vela-core/templates/test/test-application.yaml
Create an action to test helm charts, as required in https://github.com/oam-dev/kubevela/issues/1406
> update: add helm test step

- .github/workflows/release.yml
- hack/website/release.sh
> add release docs when have tagged new release

- README.md
Fix readme to align with website.
> Update readme for 1.0

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-core/templates/defwithtemplate/worker.yaml
- docs/examples/app-with-volumes/app-websvc-volumes.yaml
- docs/examples/app-with-volumes/app-worker-volumes.yaml
- hack/vela-templates/cue/webservice.cue
- hack/vela-templates/cue/worker.cue
to fix #1291 
@wonderflow  any suggestion about where I should add a doc for this?
> add volumes definition in worker/webservice

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> skip applying helm-release if app spec not change

- pkg/appfile/parser.go
> Remove duplicated logic

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> ignore error not found when deleting resourceTracker

- test/e2e-test/component_version_test.go
https://github.com/oam-dev/kubevela/runs/2320180669
> fix flaky test

- README.md
- docs/en/advanced-install.md
- docs/en/application.md
- docs/en/concepts.md
- docs/en/developers/references/README.md
- docs/en/developers/references/component-types/task.md
- docs/en/developers/references/component-types/webservice.md
- docs/en/developers/references/component-types/worker.md
- docs/en/developers/references/traits/autoscale.md
- docs/en/developers/references/traits/ingress.md
- docs/en/developers/references/traits/metrics.md
- docs/en/developers/references/traits/rollout.md
- docs/en/developers/references/traits/route.md
- docs/en/developers/references/traits/scaler.md
- docs/en/helm/component.md
- docs/en/install.mdx
- docs/en/platform-engineers/cloud-services.md
- docs/en/platform-engineers/definition-and-templates.md
- docs/en/platform-engineers/openapi-v3-json-schema.md
- docs/en/platform-engineers/overview.md
- docs/en/rollout/appdeploy.md
- docs/en/rollout/rollout.md
- docs/sidebars.js
> Add user docs with name of `Application Deployment`

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_trait_test.go
- test/e2e-test/kube_app_test.go
[track log](https://github.com/oam-dev/kubevela/runs/2331067190) of the flaky unit test
> fix falky unit test

- hack/website/release.sh
> fix CI: change release-website action web contributor

- docs/en/introduction.md
> Fix introduction

- design/vela-core/APIServer-Catalog.md
- design/vela-core/app_deployment.md
- design/vela-core/apply-once-only.md
- design/vela-core/apply-workload-and-trait.md
- design/vela-core/restful-interface.md
- design/vela-core/rollout-design.md
- docs/en/cue/cross-namespace-resource.md
- docs/en/platform-engineers/debug-test-cue.md
Signed-off-by: Gallardot <tttick@163.com>
> fix tiny typo

- docs/en/platform-engineers/keda.md
> Add keda trait

- hack/website/release.sh
> fix CI: fix release-website action

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
> add app name as label for AppRevision

- .github/workflows/release.yml
- Makefile
- docs/en/end-user/diagnose.md
> fix CI: add action to release kubectl-vela binary file

- pkg/controller/common/rollout/rollout_webhook_test.go
> randomize port to listen to separate tests

- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
> fix appContext update failed error

- pkg/dsl/definition/template_test.go
Some tests are not named which make it difficult to
read test cases and add more
> Refactor template_test.go to make it readable

- charts/vela-core/templates/defwithtemplate/cpuhpa.yaml
- charts/vela-core/templates/defwithtemplate/ingress.yaml
- charts/vela-core/templates/defwithtemplate/manualscale.yaml
- charts/vela-core/templates/defwithtemplate/sidecar.yaml
- charts/vela-core/templates/defwithtemplate/task.yaml
- docs/en/end-user/explore.md
- hack/vela-templates/cue/cpuhpa.cue
- hack/vela-templates/cue/ingress.cue
- hack/vela-templates/cue/manualscale.cue
- hack/vela-templates/cue/sidecar.cue
- hack/vela-templates/cue/task.cue
> fix docs: add the usage of kubectl vela show in the docs

- charts/vela-core/templates/defwithtemplate/sidecar.yaml
- docs/en/end-user/sidecar.md
- hack/vela-templates/cue/sidecar.cue
show end-user how to use `sidecar` trait
> fix docs: add attach sidecar docs for the end-user 

- docs/en/end-user/cloud-resources.md
- docs/en/platform-engineers/cloud-services.md
Added parameter comments for ComponentDefinition alibaba-oss
alibaba-rds and TraitDefinition service-binding
> Add parameters comments for crossplane definitions

- docs/en/end-user/cloud-resources.md
- docs/en/introduction.md
> fix docs: fix error url link

- README.md
this is really good video talking about kubevela and oam. add it to readme. \cc @resouer
> add video from DevOps Toolkit

- README.md
- design/vela-core/APIServer-Catalog.md
- design/vela-core/rollout-design.md
- hack/references/conflictsWithAndMore/rollout.md
> fix docs: update picture links in some md files

- docs/en/end-user/volumes.md
- docs/examples/app-with-volumes/app-aws-ebs-volume.yaml
- docs/examples/app-with-volumes/app-azure-disk-volume.yaml
- docs/examples/app-with-volumes/td-awsEBS.yaml
- docs/examples/app-with-volumes/td-azureDisk.yaml
> add docs for volumes

- .github/workflows/sync-api.yml
- hack/apis/sync.sh
fix https://github.com/oam-dev/kubevela/issues/1428
EveryTime a new version is released and apis is modified, 
it will be automatically sycn to https://github.com/oam-dev/kubevela-core-api
> add action: sync vela api code to the repo(kubevela-core-api)

- charts/vela-core/templates/defwithtemplate/ingress.yaml
- charts/vela-core/templates/defwithtemplate/worker.yaml
- hack/vela-templates/cue/worker.cue
- hack/vela-templates/definitions/ingress.yaml
> fix cue tmpl of worker and ingress

- README.md
- docs/en/README.md
- docs/en/concepts.md
> Align with doc site

- pkg/controller/common/rollout/rollout_plan_controller.go
- pkg/controller/common/rollout/workloads/deployment_scale_controller.go
- pkg/controller/common/rollout/workloads/deployment_scale_integration_test.go
add deployment scale controller
add ut latter
> add deployment scale controller

- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
> fix componentDefinition ignore error bug

- charts/vela-core/templates/admission-webhooks/validatingWebhookConfiguration.yaml
> delete duplicate key in webhook yaml

- .github/workflows/go.yml
- Dockerfile.e2e
- Makefile
- cmd/core/main_e2e_test.go
- hack/e2e/end_e2e.sh
- hack/e2e/modify_charts.sh
Hey, I wrote a process to obtain e2e test coverage profile.
By this pr, total coverage will raise from **58.0%** to **61.5%**
fix #1443
> calculate e2e-test into coverage

- codecov.yml
* relative cov >= 70%
* total cov drop <=1%
fix #1581
> add: PR code coverage requirement

- docs/en/rollout/rollout.md
fix  appRollout docs small issue
> fix  appRollout docs small issue

- docs/en/end-user/terraform.md
- docs/en/platform-engineers/terraform.md
- docs/en/roadmap/template.md
Added applying Terraform Provider introduction, and removed `.md`
to make it work in official site
> Refine Terraform doc

- .github/workflows/check-docs.yml
- .github/workflows/release-docs.yaml
- hack/website/clean-md.py
- hack/website/test-build.sh
> fix CI: add Clean-Up step to convert error link in Markdown file

- test/e2e-test/app_embed_rollout_test.go
1.add tests for update application in the middle of a rollout process
2.fix error tests
> add middle state test and fix app embed rollout error test

- test/e2e-test/app_embed_rollout_test.go
pause rollout in the middle of rollout process
> add app embed rollout pause test

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler_test.go
- pkg/webhook/core.oam.dev/v1alpha2/application/validation.go
- test/e2e-test/application_test.go
- test/e2e-test/testdata/app/app5.yaml
> fix application rollout annotation false issue

- docs/en/platform-engineers/definition-and-templates.md
> update the revision doc

- go.mod
- go.sum
- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/testdata/crds/terraform.core.oam.dev_configurations.yaml
- pkg/utils/common/common.go
> Fix Terraform application status issue

- docs/en/quick-start.md
Easy for users to copy the correct command.
> [IMP]easy for users to copy

- .github/workflows/go.yml
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
fix staticcheck lint ST1023.
make CI work consistenly with Makefile/staticcheck
> fix staticcheck lint

- e2e/cli.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go
- pkg/oam/discoverymapper/mapper.go
- pkg/oam/discoverymapper/suit_test.go
- test/e2e-test/app_resourcetracker_test.go
> make ResourceTracker to own cluster-scope resource

- design/vela-core/workflow_policy.md
ref https://github.com/oam-dev/kubevela/issues/1613
> design: Application-Level Policies and Customized Control-Logic Workflow

- Makefile
- docs/README.md
- hack/website/Dockerfile
- hack/website/website-dev.sh
we provide a new docker image `oamdev/vela-webtool:v1`, you can find `Dockerfile` in `/hack/website`.
> fix makefile: update docker image in make docs-start/docs-build

- docs/en/platform-engineers/openapi-v3-json-schema.md
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller_test.go
- pkg/controller/utils/capability.go
[Feature] add new label for configmap which store the parameter json schema of the Definition 
Add a new feature described and fix #1615
> Add new label for configmap which store the parameter json schema of the Definition 

- README.md
- docs/en/concepts.md
- docs/en/end-user/traits/service-binding.md
- docs/en/introduction.md
- docs/en/platform-engineers/crossplane.md
> Minor fix on wording

- docs/en/install.mdx
> fix docs link

- test/e2e-test/app_resourcetracker_test.go
fix flaky e2e-test of app-resourcetracker
> fix flaky e2e test

- hack/website/clean-md.py
fix bug which clean-md.py will miss `.mdx` file and handle links with `.mdx` incorrectly
> fix script clean-md.py 

- docs/en/install.mdx
```
helm repo add https://charts.kubevela.net/core
```
> use custom domain for vela charts

- pkg/dsl/definition/template.go
- pkg/dsl/definition/template_test.go
> Support patch data-pass object in CUE

- docs/en/roadmap.md
- docs/en/roadmap/README.md
- docs/sidebars.js
> fix roadmap website docs

- .github/workflows/registry.yml
> Sync definitions to oss bucket, which acts as a capability center

- docs/en/platform-engineers/terraform.md
Update terraform.md.
Fix Terraform controller version to avoid mistake.
Added other CSP supported by Terraform Controller
> Fix Documentation for Terraform Controller

- pkg/appfile/appfile.go
- pkg/appfile/parser.go
- pkg/appfile/template.go
separated from https://github.com/oam-dev/kubevela/pull/1708
> refactor appfile pkg for adding workflow

- pkg/controller/core.oam.dev/v1alpha2/application/assemble/assemble.go
- pkg/controller/core.oam.dev/v1alpha2/application/assemble/assemble_suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/assemble/helper.go
- pkg/controller/core.oam.dev/v1alpha2/application/assemble/options.go
- pkg/controller/core.oam.dev/v1alpha2/application/assemble/options_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/assemble/testdata/apprevision.yaml
related to #1705 
init [assemble phase](https://github.com/oam-dev/kubevela/issues/1705#issuecomment-847574326)
> duplicate AppConfig logic into app/assemble pkg

- .github/workflows/go.yml
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go
> cp oam pr 329 avoid out of bound

- Makefile
> fix the fmt command of the Makefile

- Makefile
Fixed the wrong directory of cue files when formating
> Fix wrong cue directory

- pkg/appfile/template.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
- pkg/controller/utils/capability.go
- pkg/controller/utils/capability_test.go
- pkg/oam/util/helper.go
- pkg/utils/common/common.go
- pkg/utils/common/common_test.go
- references/plugins/references.go
> Generate OpenAPI JSON schema for Terraform Component

- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/definitionrevision_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/definitionrevision_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/setup.go
- pkg/oam/labels.go
Separated from #1708 
Adds test coverage for it.
> add PolicyDefinition and WorkflowStepDefinition controller

- test/e2e-test/app_resourcetracker_test.go
- test/e2e-test/kube_app_test.go
> fix flaxy e2e-test

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/name.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/name_test.go
related to #1705 
implement [dispatch pkg](https://github.com/oam-dev/kubevela/issues/1705#issuecomment-851124206)
> dispatch resources into cluster with one package

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go
> don't use appRevision as resource tracker's owner

- cmd/core/main.go
- pkg/controller/core.oam.dev/v1alpha2/appdeployment/appdeployment_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/controllerhooks.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/suit_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller_helper.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller_helper_test.go
- pkg/controller/core.oam.dev/v1alpha2/setup.go
fix https://github.com/oam-dev/kubevela/issues/378
this PR mainly improve the log system in AppConfig and remove all old version log system.
Please refer to https://github.com/oam-dev/kubevela/pull/1735 for the writing rules of klog/v2.
> Improve log system in AppConfig 

- pkg/cue/definition/template_test.go
Now CUE will render Auxiliary Array according to the writing order of the outputs in the template, 
this PR add test to check the render order
> add test to check the order of Auxiliary Array rendered by CUE

- Makefile
- charts/vela-core/templates/kubevela-controller.yaml
- charts/vela-core/values.yaml
- cmd/core/main.go
- design/api/vela-controller-params-reference.md
- pkg/commands/system.go
- pkg/controller/core.oam.dev/oamruntime_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
1. add ConcurrentReconciles for setting the concurrent reconcile number of the controller
2. add DependCheckWait for setting the time to wait for ApplicationConfiguration's dependent-resource ready
> add more options for vela-controller

- Makefile
- charts/vela-core/values.yaml
- cmd/core/main.go
- pkg/controller/core.oam.dev/oamruntime_controller.go
- pkg/controller/core.oam.dev/v1alpha2/appdeployment/appdeployment_controller.go
- pkg/controller/core.oam.dev/v1alpha2/appdeployment/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
1. add ConcurrentReconciles for setting the concurrent reconcile number of the controller
2. add DependCheckWait for setting the time to wait for ApplicationConfiguration's dependent-resource ready
> set concurrent reconcile number for controller

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/rollout_handler.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationrollout/common_test.go
> add log and unit-tests

- .github/workflows/e2e-test.yml
- .github/workflows/go.yml
- .github/workflows/unit-test.yml
> Split workflow to enable re-run single jobs

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/rollout_handler.go
- test/e2e-test/rollout_plan_test.go
fix comments and add sourceRevision dispatch
> fix comments and add sourceRevision dispatch

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/rollout_handler.go
- test/e2e-test/rollout_plan_test.go
fix sourceRevision assemble manifest and fix flaky test
> fix sourceRevision assemble manifest and fix flaky test

- docs/examples/workflow/README.md
- docs/examples/workflow/app.yaml
- docs/examples/workflow/definition.yaml
- docs/examples/workflow/wf-patch.yaml
- pkg/appfile/appfile.go
- pkg/appfile/parser.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
Final part of https://github.com/oam-dev/kubevela/pull/1708
> app controller: reconcile workflow and create resources configmap

- docs/examples/deployment-rollout/README.md
- docs/examples/deployment-rollout/app-rollout-scale.yaml
fix rollout deployment example
> fix deployment example

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/rollout_handler.go
> fix missed logic

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper_test.go
- test/e2e-test/app_embed_rollout_test.go
fix a bug that maybe cause reconcile succeed/failed rollout when vela restart
> fix rollout check completed bug

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- ISSUE_TRIAGE.md
- contribute/README.md
- contribute/coding-conventions.md
- contribute/create-pull-request.md
- contribute/developer-guide.md
- contribute/triage-issues.md
Add more guides and regulations
> refine our contributing guides

- docs/en/end-user/scopes/advanced-rollout.md
> add field  specification doc for rollout and add scale demo

- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper.go
- pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper_test.go
- pkg/webhook/core.oam.dev/v1alpha2/applicationrollout/validation.go
- test/e2e-test/rollout_plan_test.go
- test/e2e-test/testdata/rollout/cloneset/appRolloutScale.yaml
support restart a scale rollout.fix #1674
> support restart scale operation by modify targetSize of AppRollout

- pkg/webhook/core.oam.dev/v1alpha2/applicationrollout/validating_handler.go
- test/e2e-test/rollout_plan_test.go
> skip validate removed rollout and fix flaky test

- design/vela-core/environment.md
> add initializer design

- .github/workflows/check-docs.yml
- .github/workflows/release-docs.yaml
- .github/workflows/release.yml
- hack/website/format.py
- hack/website/helpers.sh
- hack/website/release.sh
fix CI: fomat versions.json before generating a new version of the doc.
1. fomat versions.json before run `yarn run docusaurus docs:version vX.X`
2. fix shell func  `checkDocusaurus`
> fix CI: fomat versions.json before generating a new version of the doc

- test/e2e-test/app_resourcetracker_test.go
- test/e2e-test/rollout_plan_test.go
retry create application when meet an error
related failed test : https://github.com/oam-dev/kubevela/pull/1824/checks?check_run_id=2873658500
> fix rt flaky test

- charts/vela-core/templates/defwithtemplate/annotations.yaml
- charts/vela-core/templates/defwithtemplate/labels.yaml
- charts/vela-core/templates/defwithtemplate/sidecar.yaml
- hack/vela-templates/definitions/annotations.yaml
- hack/vela-templates/definitions/labels.yaml
- hack/vela-templates/definitions/sidecar.yaml
> Cherry pick pr 1838 to release-1.0 branch

- test/e2e-test/rollout_plan_test.go
fix rollout-plan flaky test.
The cause is  `applyTwoAppVersion` func aim to generate 2 apprevs. But update application request comes too fast, the application controller is still generating first apprev probably. In this case cluster will have  only  one apprev.
> fix rollout falky test 

- pkg/appfile/parser.go
- test/e2e-test/definition_revision_test.go
Fixes https://github.com/oam-dev/kubevela/discussions/1810
Fix invalid metadata.labels error when specify the version of the trait in the app
> fix invalid metadata.labels error when specify the version of the trait in the app

- pkg/appfile/parser.go
- test/e2e-test/definition_revision_test.go
as title, fix invalid metadata.labels error when specify the version of the trait in the app.
> Cherry pick pr 1855 to release-1.0 branch

- apis/types/componentmanifest.go
- docs/examples/insert-secret/app.yaml
- docs/examples/insert-secret/insertsecret.yaml
- pkg/appfile/appfile.go
- pkg/appfile/parser.go
- pkg/appfile/parser_test.go
- pkg/appfile/validate.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/assemble/assemble.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/oam/util/helper.go
- references/appfile/dryrun/testdata/dryrun-exp-comp.yaml
This PR allows components won't be blocked when one of components don't have the secret and configmap ready.
Fixes #1350
> allow component have defer insert secret and config

- docs/en/end-user/application.md
Tell user the appRev gc mahcanism  in docs
Fixes #
> add revision listmit

- pkg/appfile/helm/flux2apis/helmrepository_types.go
- pkg/appfile/helm/flux2apis/reference_types.go
- pkg/appfile/helm/helm_test.go
- pkg/appfile/helm/schema_test.go
Support reference secret for helm repository
Fixes #1846 
> support helm repo secret

- apis/core.oam.dev/v1beta1/application_types.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_finalizer_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_clean_up_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller.go
- pkg/controller/standard.oam.dev/v1alpha1/podspecworkload/podspecworkload_controller.go
- pkg/oam/util/helper.go
- pkg/oam/util/helper_test.go
Add util functions to handle ending reconciliation with conditions.
Fixes #1188
> end controller reconcile with conditions

- e2e/plugin/testdata/dynamic-sa.yaml
- references/plugins/registry.go
- references/plugins/registry_test.go
- vela-templates/registry/auto-gen/kustomize.yaml
- vela-templates/registry/definitions/kustomize.yaml
fix kustomize registry yaml, fix testdata yaml
1. There are some unstable test in registry unit test. This PR provide more infomation for this.
2. fix kustomize yaml for registry and dynamic-sa for test data.
none
> add more test error info

- README.md
Add workflow information in readme.
Fixes #
> Update with workflow inforamtion

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- charts/vela-core/templates/defwithtemplate/worker.yaml
- e2e/application/application_test.go
- vela-templates/internal/cue/webservice.cue
- vela-templates/internal/cue/worker.cue
add image pull policy and pull secrets parameters for worker and webservice
> add image pull policy and pull secrets for worker and webservice

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_clean_up_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
Change `apphandler` scope, which could be imported outside of the package.   It will very useful when users manage KubeVela Application by themselves.
Fixes #
> Feat change appHandler library for external usage

- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
The KubeVela will failed to aggregate status if application use a kube/helm type component
Fixes https://github.com/oam-dev/kubevela/issues/1865
> fix bug: failed to aggregate status if application use a kube/helm type component

- apis/core.oam.dev/common/types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-core/crds/core.oam.dev_initializers.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_initializers.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
**What this PR does / why we need it:**
Perceive the version difference between status and spec, from #1817
**Which issue(s) this PR fixes:**
Fixes #1817 
**Special notes for your reviewer:**
> add observedGeneration field in status of Application

- pkg/controller/core.oam.dev/v1alpha2/application/application_finalizer_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
- test/e2e-test/rollout_plan_test.go
[1786](https://github.com/oam-dev/kubevela/issues/1786)
[1818](https://github.com/oam-dev/kubevela/issues/1818)
Fixes #
> Feat: no need create appRevision if it already presents in histories

- README.md
> Align with doc

- charts/vela-core/templates/addons/ocm-cluster-manager.yaml
- go.mod
- go.sum
- vela-templates/addons/auto-gen/fluxcd.yaml
- vela-templates/addons/auto-gen/ocm-cluster-manager.yaml
- vela-templates/addons/ocm-cluster-manager/resource/cluster-role/cluster-manager-binding.yaml
- vela-templates/addons/ocm-cluster-manager/resource/cluster-role/cluster-manager-role.yaml
- vela-templates/addons/ocm-cluster-manager/resource/cluster-role/cluster-manager.yaml
- vela-templates/addons/ocm-cluster-manager/resource/crds/clustermanager.yaml
- vela-templates/addons/ocm-cluster-manager/resource/hub/clustermanager.yaml
- vela-templates/addons/ocm-cluster-manager/resource/operator/operator.yaml
- vela-templates/addons/ocm-cluster-manager/template.yaml
- vela-templates/gen_addons.go
Add ocm-cluster-manager  Controller as KubeVela built-in
Fixes #
> Add ocm-cluster-manager controller as built-in addon

- .github/bot.md
- .github/workflows/issue-commands.yml
Add  self-assign function in kubevela-github-actions repo，
and change the release version for repo reference.
> Add self-assign function and change release version for github action

- pkg/controller/common/rollout/rollout_plan_controller.go
- pkg/controller/common/rollout/workloads/common.go
- pkg/controller/common/rollout/workloads/deployment_rollout_controller.go
- pkg/controller/common/rollout/workloads/statefulset_controller.go
- pkg/controller/common/rollout/workloads/statefulset_scale_controller.go
- pkg/controller/common/rollout/workloads/statefulset_scale_integration_test.go
This PR adds support for the StatefulSet scale controller. It's a part of #1653.
> Support scale controller for StatefulSet

- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
componentdefinition controller should skip `RefreshPackageDiscover` step when the workload type of componentDefinition is `autodetects.core.oam.dev`
> fix bug: skip pkg discover when workload type of componentdefinition is autodetect

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go
related to #1923 
In dispatch phase, When GC is done, retrieve all resource trackers of this application and delete the legacy ones.
> bugfix some legacy revision resource tracker can be missed from deleting

- pkg/appfile/appfile.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/workflow/tasks/custom/task.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/types/types.go
> add context to taskGenerator

- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
> Add workflow integration test

- pkg/cue/model/value/value.go
- pkg/cue/model/value/value_test.go
- pkg/stdlib/op.go
- pkg/stdlib/packages.go
- pkg/stdlib/packages_test.go
- pkg/workflow/context/context.go
- pkg/workflow/context/context_test.go
- pkg/workflow/context/interface.go
- pkg/workflow/providers/kube/handle.go
- pkg/workflow/providers/providers.go
- pkg/workflow/providers/providers_test.go
- pkg/workflow/providers/workspace/workspace.go
- pkg/workflow/providers/workspace/workspace_test.go
- pkg/workflow/tasks/custom/task.go
- pkg/workflow/tasks/custom/task_test.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/tasks/discover_test.go
- pkg/workflow/types/types.go
> Workflow WIP

- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
- pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go
> allow create application with empty components

- docs/examples/workflow/README.md
- docs/examples/workflow/app.yaml
- docs/examples/workflow/definition.yaml
- docs/examples/workflow/wf-patch.yaml
This is a Simple workflow examples and documentation.
> Update workflow example

- docs/examples/terraform/cloud-resource-provision-and-consume/ComponentDefinition-alibaba-rds.yaml
As Terraform alicloud provider has upgrade to 1.26.0, some
HCL synatx have to been updated
Fixes #
> Update Terraform typed Componentdefinition

- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/workflow/interface.go
- pkg/workflow/providers/kube/handle.go
- pkg/workflow/providers/kube/handle_test.go
- pkg/workflow/suit_test.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
Upgrade the code of the provider `kube` and call resource GC after the workflow is completed.
> Workflow Support Resource GC

- pkg/stdlib/op.go
fix the bug that op.#Steps is close.
> open op.#Steps

- apis/core.oam.dev/v1beta1/core_types.go
- charts/oam-runtime/crds/core.oam.dev_traitdefinitions.yaml
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
add skipAffectAppRev in traitDefinition, modify this trait won't generate a new applciationRevision
eg.
```yaml
kind: TraitDefinition
metadata:
name: rollout
namespace: default
spec:
manageWorkload: true
skipAffectAppRev: true
schematic:
cue:
template: |
outputs: rollout: {
apiVersion: "standard.oam.dev/v1alpha1"
kind:       "Rollout"
metadata: {
name:  context.name
namespace: context.namespace
}
spec: {
targetRevisionName: context.revision
componentName: "myweb1"
rolloutPlan: {
rolloutStrategy: "IncreaseFirst"
rolloutBatches:[
{ replicas: 3}]    
targetSize: 5
}}}
```
related issue: #1605 
Fixes #
> add skipAffectAppRev in traitDefinition to don't generate new appRev when modify this trait

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
ginkgo test order is random, when create rollout traitDefinition,  it maybe already exist.
related CI task: https://github.com/oam-dev/kubevela/pull/1978/checks?check_run_id=3182219846
> fix  flaky test of application-controller

- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
fix bug: inject context metadata conflict
> fix workflow bug

- pkg/appfile/parser.go
- pkg/appfile/parser_test.go
> don't filter not found error in load template to avoid panic

- go.mod
- go.sum
- references/a/preimport/preimport.go
Fixes #1995
Upgrade containerd to newer version. The upgrade changes some interface and breaks #1991, this MR fixes this problem.
> Bump github.com/containerd/containerd from 1.3.2 to 1.4.8

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_test.go
It's a compatible fix for legacy ownerRef case
> fix resource tracker ownerRef override

- pkg/controller/common/rollout/rollout_plan_controller.go
- pkg/controller/core.oam.dev/v1alpha2/appdeployment/suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
set to 0 means disable it
Fixes #1779 
> disable metrics server port in tests and add log for rollout

- pkg/oam/testutil/helper.go
fix lint and typo in oam testutil
Fixes #
> Fix(lint): fix lint and typo in oam testutil

- pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
> ApplicationContext status patch nothing

- design/platform/ml-platform-design.md
Submitting this design doc to upstream first.
We will revisit this later to implement it.
> design: add scenarios of ML Platform Building

- .github/comment.userlist
- .github/workflows/issue-commands.yml
Add comment user list and fig bug: when assign the specific user in githubname way, it was disrupted by the self-assign logic.
Fixes #
> Add comment user list and fix bug in action

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler_suit_test.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler_test.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/suite_test.go
- pkg/oam/labels.go
- test/e2e-test/rollout_trait_test.go
1.mechanism of application to skip GC resource.
2. rollout controller pass ownerReference(resourceTracker) to targetWorkload
> application skip gc resource and rollout set workload ownerReference

- charts/vela-core/templates/addons/fluxcd.yaml
- vela-templates/addons/auto-gen/fluxcd.yaml
- vela-templates/addons/fluxcd/definitions/helm-release.yaml
Added `version`, `targetNamespace` and `value` for trait helm
co-authored-by:  qiaozp <47812250+chivalryq@users.noreply.github.com>
Fixes #
> Add more properties for trait helm

- pkg/oam/util/helper.go
> fix data race in compatibility-test

- design/vela-cli/def.md
- design/vela-cli/def_zh.md
Add vela-def design documents.
> [Docs] add vela-def design documents

- references/a/preimport/preimport.go
The previous upgrade cause client-go use klog/v2 which makes the klog silence not working. This PR fix it by upgrading the suppress klog library to v2. 
> update klog surpress

- docs/examples/workflow/Li-Auto-Inc/app.yaml
- docs/examples/workflow/Li-Auto-Inc/common-definitions.yaml
- docs/examples/workflow/Li-Auto-Inc/workflow-step-definitions.yaml
> Demo of Li-Auto-Inc scene

- design/vela-core/APIServer-Catalog.md
- design/vela-core/apply-once-only.md
- design/vela-core/apply-workload-and-trait.md
- design/vela-core/environment.md
- design/vela-core/restful-interface.md
- design/vela-core/workflow_policy.md
fix typos in design docs
Fixes #
> Chore(docs): fix typos in design docs

- charts/vela-core/templates/addons/kruise.yaml
- vela-templates/addons/auto-gen/kruise.yaml
- vela-templates/addons/kruise/definitions/cloneset-service.yaml
- vela-templates/addons/kruise/template.yaml
> Add cloneset as kruise addon's componentDefinition

- docs/examples/workflow/apply-remaining/app.yaml
- docs/examples/workflow/basic-app.yaml
- docs/examples/workflow/definition.yaml
when kubectl apply -f definition.yaml, the error is occurred
```
The ComponentDefinition "singletonServer" is invalid: metadata.name: Invalid value: "singletonServer": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Fixes #
> fix metadata.name to lower case

- docs/examples/workflow/apply-remaining/definition.yaml
- docs/examples/workflow/definition.yaml
fix workflow example
Fixes #
/cc @leejanee
> Fix(example): fix workflow example

- docs/examples/workflow/README.md
- docs/examples/workflow/basic-app.yaml
- docs/examples/workflow/definition.yaml
Fix some configuration errors, and make this example workable.
Fixes #
> fix workflow example

- .github/workflows/timed-task.yml
> fix CI: Clean up the docker image on the CI machine every hour

- charts/vela-core/templates/addons/kruise.yaml
- docs/examples/imagepulljob/README.md
- docs/examples/imagepulljob/applydemo-definition.yaml
- docs/examples/imagepulljob/basic_image_pull.yaml
- vela-templates/addons/auto-gen/kruise.yaml
- vela-templates/addons/kruise/definitions/imagepulljob-step.yaml
- vela-templates/addons/kruise/template.yaml
add image pull job workflow definition and demo
Fixes #
> Application: Add imagePullJob workflow

- charts/vela-core/values.yaml
- docs/examples/vela-app.yaml
Support patch self-defined namespace in web hook  which  is used in application crd
Details are in [this repo](https://github.com/oam-dev/kube-webhook-certgen/pull/2/files)
part of #1897
> update cert image

- pkg/apiserver/rest/apis/core.go
- pkg/apiserver/rest/rest_server.go
- pkg/apiserver/rest/services/application.go
- pkg/apiserver/rest/services/application_test.go
- pkg/apiserver/rest/services/catalog_test.go
add create or update app apiserver and tests
> add create or update app apiserver

- charts/vela-core/templates/defwithtemplate/rollout.yaml
- vela-templates/definitions/internal/rollout.cue
support batchPatition in rollout definition
Fixes #
> add batch partition

- .github/workflows/registry.yml
Storing OSS bucket and endpoint to Github Action secret will help
a developer to test the function without needing to changing code,
revert code. Instead, he/she just need to configure the secret contect
Fixes #
> Store OSS bucket and endpoint to Github Action secret

- .github/workflows/registry.yml
This is a patch for https://github.com/oam-dev/kubevela/pull/2103
Fixes #
> Fix the issue to set the latest nighty build chart name

- apis/core.oam.dev/common/types.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/workflow/workflow.go
- references/cli/addon.go
- references/cli/cli.go
- references/cli/workflow.go
- references/cli/workflow_test.go
> Feat(vela): add vela workflow suspend command

- .github/workflows/registry.yml
align with the github docs: https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
> try fix github action push to image hub

- references/cli/workflow.go
- references/cli/workflow_test.go
add vela workflow resume command and ut
Ref #2078
/cc @leejanee
> Feat(vela): add vela workflow resume command and ut

- Makefile
- docs/examples/cloneset-rollout/README.md
- go.mod
- go.sum
update openkruise version from v0.7.0 to v0.9.0
Fixes #
> Update kruise version

- charts/vela-core/templates/addons/fluxcd.yaml
- charts/vela-core/templates/addons/keda.yaml
- charts/vela-core/templates/addons/kruise.yaml
- charts/vela-core/templates/addons/observability.yaml
- charts/vela-core/templates/addons/prometheus.yaml
- charts/vela-core/templates/addons/terraform.yaml
- e2e/addon/addon_test.go
- vela-templates/addons/auto-gen/fluxcd.yaml
- vela-templates/addons/auto-gen/keda.yaml
- vela-templates/addons/auto-gen/kruise.yaml
- vela-templates/addons/auto-gen/observability.yaml
- vela-templates/addons/auto-gen/prometheus.yaml
- vela-templates/addons/auto-gen/terraform.yaml
- vela-templates/addons/fluxcd/definitions/helm-release.yaml
- vela-templates/addons/keda/template.yaml
- vela-templates/addons/kruise/template.yaml
- vela-templates/addons/observability/template.yaml
- vela-templates/addons/prometheus/template.yaml
- vela-templates/addons/terraform/template.yaml
Some helm chart are from AWS s3/Google cloud storage/Aliyun OSS... This PR add Bucket type for helm componentDefinition attached to fluxcd addon.
Verifide usage example：
1. add Secret:
```shell
$ kubectl create secret generic bucket-secret --from-literal=accesskey=<your-ak> --from-literal=secretkey=<your-sk>
secret/bucket-secret created
```
2. deploy chart from private bucket. 
```yaml
metadata:
name: bucket-app
spec:
components:
- name: bucket-comp
type: helm
properties:
repoType: oss
secretRef: bucket-secret
chart: ./chart/podinfo-5.1.3.tgz
url: oss-cn-beijing.aliyuncs.com
oss:
bucketName: definition-registry
```
> helm add bucket support

- charts/vela-core/templates/defwithtemplate/rollout.yaml
- docs/examples/workflow-with-ocm/rollout/README.md
- docs/examples/workflow-with-ocm/rollout/app-first-scale.yaml
- docs/examples/workflow-with-ocm/rollout/app-revert.yaml
- docs/examples/workflow-with-ocm/rollout/app-scale-down-v1.yaml
- docs/examples/workflow-with-ocm/rollout/app-update-v2.yaml
- docs/examples/workflow-with-ocm/rollout/app-v2-scale.yaml
- docs/examples/workflow-with-ocm/rollout/dispatchRevDef.yaml
- docs/examples/workflow-with-ocm/rollout/dispatchTraits.yaml
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler_suit_test.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler_test.go
- test/e2e-test/rollout_trait_test.go
- vela-templates/definitions/internal/rollout.cue
rollout OCM demo and defer rollout pass owner to `handleSucceed` phase.
Fixes #
> rollout OCM demo and defer rollout pass owner to handleSucceed

- charts/vela-core/templates/addons/kruise.yaml
- vela-templates/addons/auto-gen/kruise.yaml
- vela-templates/addons/kruise/definitions/cloneset-service.yaml
Fix cloneset componentDef in kruise addon. Add lost #ENV and #HealthProbe definition in cue.
Fixes #
> Fix cloneset componentDefinition in kruise addon 

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- test/e2e-test/rollout_trait_test.go
fix bug: support  use context.revisionName when specify externalRevision
Fixes #
> fix external revision bug

- CONTRIBUTING.md
Add commit message convention.
Ref:
* [Kubernetes commit message guidelines](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines)
* [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
Fixes #
> Feat(contributing): add commit message convention

- pkg/apiserver/rest/apis/core.go
- pkg/apiserver/rest/rest_server.go
- pkg/apiserver/rest/services/application.go
- pkg/apiserver/rest/services/application_test.go
Add get and delete method for app in api server
part of issue #2107  
Fixes #
> Add get and delete method for app in api server

- apis/core.oam.dev/common/types.go
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/workflow/workflow.go
- references/cli/workflow.go
- references/cli/workflow_test.go
add vela workflow terminate and restart command
Fixes #2078
/cc @leejanee
> Feat(vela): add vela workflow terminate and restart command

- test/e2e-test/rollout_trait_test.go
Fix flaky test: https://github.com/oam-dev/kubevela/runs/3379927227
The reason is CI environment resource is not enough cause pod pending , and rollout process got block. change rollout strategy `IncreaseFirst` to `DecreaseFirst`  and  `cpu requests` to 0  to avoid pod pending.
Fixes #
> fix rollout trait test

- charts/vela-core/templates/test/test-application.yaml
> fix helm test failed

- docs/examples/dry-run/README.md
- e2e/plugin/plugin_test.go
- references/appfile/dryrun/dryrun.go
- references/appfile/dryrun/testdata/diff-apprevision.yaml
- references/appfile/dryrun/testdata/dryrun-exp-comp.yaml
- references/cli/dryrun.go
add default name and namespace in dry run
Fixes #2105
> Fix(dryrun): add default name and namespace in dry run

- .github/workflows/commit-lint.yml
- commitlint.config.js
add commit lint ci
Fixes #2154 
/cc @wonderflow @hongchaodeng
> Feat(ci): add commit lint ci

- docs/examples/workflow-with-ocm/rollout/README.md
Signed-off-by: shaowenchen <mail@chenshaowen.com>
fix some typo
> docs: fix typo about workflow rollout

- charts/vela-core/templates/defwithtemplate/volumes.yaml
- vela-templates/definitions/internal/volumes.cue
Fix missing patchKey in volumes definition.
Fixes #
> Fix: add patchkey to volumes

- cmd/core/main.go
- design/api/vela-controller-params-reference.md
Add pprof [optional] for profiling KubeVela performance.
Fixes #
> Feat: add pprof

- README.md
old doc link 404, fix it.
Fixes #
> Fix: error doc link in README

- pkg/controller/utils/capability.go
- pkg/controller/utils/capability_test.go
Including null, list(...), map(...) Terraform types
To fix the issue like 
Fixes #
> Fix: support more Terraform variable types

- design/vela-core/environment.md
Update the design:
- Remove Initializer and replace it with Application + depends-on-app workflow step + env-binding policy + multi-env workflow step.
- Focus on two user scenarios using KubeVela:
- Using KubeVela to initialize Environment
- Using KubeVela to compose multi-env application rollout
> Docs: update environment design

- charts/vela-core/templates/defwithtemplate/service-binding.yaml
- vela-templates/definitions/internal/service-binding.cue
as title said, please note it was not fixing #2208 , but only make it more clear.
> Fix: modify service-binding with more accurate type

- pkg/workflow/tasks/custom/task.go
- pkg/workflow/tasks/custom/task_test.go
Use paths notation to describe the `input.ParameterKey` in workflow.
Fixes #
for example:
```
---application---
...
workflow:
- steps:
- name: "step1"
... 
- name: "step2"
inputs: 
- from: "ip"
parameterKey: "env.ip"  
---definition---
parameter: {
env: ip: string
}
...
```
> Feat(workflow): input.ParameterKey described like paths notation

- charts/vela-core/templates/defwithtemplate/env-binding.yaml
- docs/examples/workflow-with-ocm/README.md
- docs/examples/workflow-with-ocm/app.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- vela-templates/definitions/internal/env-binding.cue
1. When the policy in application is specified, the resources in the app need to be rendered and created 
2. update policyDefinition env-binding
Fixes #
> Fix(app): When only the policy is specified, the resources in the app need to be rendered and created 

- pkg/cue/model/value/value.go
- pkg/cue/model/value/value_test.go
- pkg/workflow/tasks/custom/task.go
Workflow step `outputs`  support `cue-script` notation 
Fixes #
usage:
```
workflow:
steps:
- name: "xx"
outputs: 
- name: "var"
exportKey: "apply.status.conditions[0].message"
```
> Feat(workflow): outputs support script notation

- charts/vela-core/templates/_helpers.tpl
- charts/vela-core/templates/kubevela-apiserver.yaml
- charts/vela-core/values.yaml
- entrypoint.sh
add api-server to helm chart, if user set `apiServer.enabled` is `true`, the helm will create a deployment to start a apiserver service.
Fixes #
> Feat(apiserver): add api-server to helm chart

- cmd/core/main.go
- design/api/vela-controller-params-reference.md
- hack/pressure-test/README.md
- hack/pressure-test/app-templates/community.yaml
- hack/pressure-test/app-templates/sae.yaml
- hack/pressure-test/dashboard.json
- hack/pressure-test/tolerate-hollow-node.cue
- pkg/controller/common/context.go
1. Add k8s client qps & burst parameter to enhance throughput for massive application scenario.
2. Add PerfEnabled flag for switching perf logging. (Not working now but will be useful in other PR. Reduce other PR load.)
2. Add bootstrap parameter documentation.
3. Add pressure test guide.
4. Add pressure test related files. (Application template & Pressure Test Dashboard)
Fixes #
> Feat: add pressure-test parameter for optimizing

- pkg/controller/core.oam.dev/v1alpha1/envbinding/engine.go
- pkg/controller/core.oam.dev/v1alpha1/envbinding/envbinding_controller_test.go
align the configured Application name with the original Application name
Fixes #
> Fix(envbinding):align the configured Application name with the original Application

- pkg/stdlib/op.cue
add status check for op.#ApplyEnvBindApp
Fixes #
> Feat(workflow): add status check for op.#ApplyEnvBindApp

- charts/vela-core/templates/addons/fluxcd.yaml
- vela-templates/addons/auto-gen/fluxcd.yaml
- vela-templates/addons/fluxcd/definitions/json-patch.yaml
Fix wrong cue def in json-patch trait
Fixes #
> Fix: kustomize json patch trait definition

- .github/workflows/sync-api.yml
- apis/core.oam.dev/v1beta1/appdeployment_types.go
- apis/core.oam.dev/v1beta1/application_types.go
- apis/core.oam.dev/v1beta1/applicationrevision_types.go
- apis/core.oam.dev/v1beta1/approllout_types.go
- apis/core.oam.dev/v1beta1/cluster_types.go
- apis/core.oam.dev/v1beta1/componentdefinition_types.go
- apis/core.oam.dev/v1beta1/core_types.go
- apis/core.oam.dev/v1beta1/definitionrevision_types.go
- apis/core.oam.dev/v1beta1/initializer_type.go
- apis/core.oam.dev/v1beta1/policy_definition.go
- apis/core.oam.dev/v1beta1/register.go
- apis/core.oam.dev/v1beta1/workflow_step_definition.go
- hack/apis/clientgen.sh
- hack/apis/sync.sh
- Add client generator code comment
- Add AddToScheme to register.go
- Sync generated client to kubevela-core-api
using code-generator to generate client
Fixes https://github.com/oam-dev/kubevela-core-api/issues/2
> [Feature] Support using code-generator to generate client

- go.mod
- go.sum
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope.go
Bumped the version of Terraform controller to change the filed of
Configuration's status.
Related issue: https://github.com/oam-dev/terraform-controller/pull/104
Fixes #
> Fix: bump version of Terraform Controller

- .github/CODEOWNERS
as title said, we should add backup for code owner to avoid blocks.
> Chore: add backup for code owners

- charts/vela-core/templates/addons/fluxcd.yaml
- vela-templates/addons/auto-gen/fluxcd.yaml
- vela-templates/addons/fluxcd/definitions/kustomize.yaml
add image auto update for gitops
Fixes #
/cc @wonderflow @chivalryq
> Feat: add image auto update for gitops

- test/e2e-test/app_embed_rollout_test.go
> Fix: pending the flaky rollout test

- charts/vela-core/templates/defwithtemplate/webservice.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- vela-templates/definitions/internal/webservice.cue
remove matchlabels in webservice template 
Fixes #
> Fix: remove matchlabels in webservice template

- charts/vela-core/templates/definitions/terraform-alibaba-rds.yaml
Fixed the output `DB_PASSWORD` for ComponentDefinition alibaba-rds
Fixes #
> Fix: fix the output `DB_PASSWORD` for rds definition

- charts/vela-core/templates/definitions/terraform-alibaba-eip.yaml
Added another ComponentDefinition alibaba-eip, which will be applied
with vela-core installation
Fixes #
> Add ComponentDefinition alibaba-eip

- pkg/appfile/appfile.go
- pkg/cue/model/sets/utils.go
- pkg/cue/model/value/value_test.go
> Fix: E2E Test

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- test/e2e-test/rollout_test.go
> Test: fix rollout e2e test

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/workflow/context/context.go
- pkg/workflow/tasks/discover.go
- pkg/workflow/tasks/discover_test.go
- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
> Fix: Bugs (as follows) 

- apis/core.oam.dev/common/types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-core/crds/core.oam.dev_initializers.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_initializers.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- Change base reconcile wait time to 500 millisecond
- Add exponential backoff wait time to 256x
- Add WaitCount in status
> Fix (Controller): add exponential backoff wait time for workflow reconciling

- apis/core.oam.dev/common/types.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_applications.yaml
- charts/vela-core/crds/core.oam.dev_envbindings.yaml
- charts/vela-core/crds/core.oam.dev_initializers.yaml
- charts/vela-core/crds/core.oam.dev_workflows.yaml
- design/vela-core/environment.md
- docs/examples/workflow-with-ocm/initializers/init-managed-cluster.yaml
- docs/examples/workflow/Li-Auto-Inc/app.yaml
- docs/examples/workflow/basic-app.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_envbindings.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_initializers.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_workflows.yaml
- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
- pkg/workflow/hooks/data_passing.go
- pkg/workflow/hooks/data_passing_test.go
- pkg/workflow/tasks/custom/task_test.go
change field exportKey to valueFrom
Fixes #
> Refactor: change field exportKey to valueFrom

- pkg/appfile/appfile.go
- pkg/appfile/template.go
- test/e2e-test/definition_revision_test.go
- test/e2e-test/definition_test.go
fix resource tracker e2e
Fixes #
> Test: fix resource tracker e2e

- charts/vela-core/values.yaml
- docs/examples/apiserver.md
- hack/e2e/end_e2e.sh
> Fix(helm): enable apiserver by default

- pkg/controller/standard.oam.dev/v1alpha1/rollout/rollout_controller.go
- test/e2e-test/rollout_test.go
rollout controller revert in middle of a rollout
Fixes #
> Fix(rollout):revert in middler of rollout

- charts/vela-core/templates/addons-default/terraform.yaml
- charts/vela-core/templates/addons/fluxcd.yaml
- charts/vela-core/templates/addons/istio.yaml
- charts/vela-core/templates/addons/keda.yaml
- charts/vela-core/templates/addons/kruise.yaml
- charts/vela-core/templates/addons/ns-flux-system.yaml
- charts/vela-core/templates/addons/ns-istio-system.yaml
- charts/vela-core/templates/addons/observability-asset.yaml
- charts/vela-core/templates/addons/observability.yaml
- charts/vela-core/templates/addons/ocm-cluster-manager.yaml
- charts/vela-core/templates/addons/prometheus.yaml
- charts/vela-core/templates/addons/terraform-provider-alibaba.yaml
- charts/vela-core/templates/addons/terraform.yaml
- e2e/addon/addon_test.go
- pkg/oam/labels.go
- references/cli/addon.go
- vela-templates/addons/auto-gen/terraform-provider-alibaba.yaml
- vela-templates/addons/auto-gen/terraform.yaml
- vela-templates/addons/terraform-provider-alibaba/template.yaml
- vela-templates/addons/terraform/template.yaml
- vela-templates/gen_addons.go
Add first provider for terraform controller addon
usage:
```shell
vela addon enable terraform/provider-alibaba ALICLOUD_ACCESS_KEY=xxx ALICLOUD_SECRET_KEY=yyy ALICLOUD_SECURITY_TOKEN=zzz
```
Ref: https://github.com/oam-dev/kubevela/discussions/2173
> Feat: alibaba provider addon

- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/workflow_test.go
Fixes #
Input/output invalid in workflow.
> Fix: apply-component bug

- pkg/stdlib/op.cue
> Fix: fix apply application

- charts/vela-core/templates/addons/fluxcd.yaml
- vela-templates/addons/auto-gen/fluxcd.yaml
- vela-templates/addons/fluxcd/definitions/kustomize.yaml
add commit msg in kustomize
Fixes #
> Feat: add commit msg in kustomize

- charts/vela-core/templates/addons/terraform-provider-alibaba.yaml
- vela-templates/addons/auto-gen/terraform-provider-alibaba.yaml
- vela-templates/addons/terraform-provider-alibaba/template.yaml
alibaba terraform provider addon can be enabled with argument ALICLOUD_REGION:
```shell
vela addon enable terraform/provider-alibaba ALICLOUD_ACCESS_KEY=xxx ALICLOUD_SECRET_KEY=yyy ALICLOUD_SECURITY_TOKEN=zzz ALICLOUD_REGION=cn-hongkong
```
Fixes #
> Feat: Allow user specify alibaba provider addon's region

- charts/vela-core/templates/definitions/terraform-alibaba-rds.yaml
> Revert "Fix: fix alibaba cloud rds module"

- charts/vela-core/templates/addons/istio.yaml
- docs/examples/canary-rollout-use-case/first-deploy.yaml
- docs/examples/canary-rollout-use-case/revert-in-middle.yaml
- docs/examples/canary-rollout-use-case/rollout-v2.yaml
- vela-templates/addons/auto-gen/istio.yaml
- vela-templates/addons/istio/definitions/canary-rollout-wf-def.yaml
- vela-templates/addons/istio/definitions/traffic-trait-def.yaml
delete expose for reviews component
Fixes #
> Fix: generate service in canary-traffic trait

- references/a/preimport/preimport.go
- references/cli/cli.go
- references/cli/cluster.go
- references/cmd/cli/main.go
Current vela cli also show loggings from request.go if connection is slow. This PR fixes it.
Fixes #
> Fix: fix cli logging

- charts/vela-core/templates/addons/kruise.yaml
- vela-templates/addons/auto-gen/kruise.yaml
- vela-templates/addons/kruise/definitions/cloneset.yaml
Fix: imagePullSecrets error from cloneset
Fixes #
Based on #2283
/cc @withlin @wonderflow
> Fix: imagePullSecrets error from cloneset

- charts/vela-core/templates/addons/observability.yaml
- vela-templates/addons/auto-gen/observability.yaml
- vela-templates/addons/observability/template.yaml
Added a Grafana dashboard for application logging
Fixes #
> Feature: add application logging dashboard

- pkg/cue/model/instance_test.go
- pkg/cue/model/sets/utils.go
- pkg/cue/model/sets/utils_test.go
- pkg/cue/model/value/value.go
- pkg/cue/model/value/value_test.go
- pkg/stdlib/op.cue
- pkg/workflow/providers/oam/apply.go
- pkg/workflow/providers/oam/apply_test.go
> Feat: Make applicationComponent can be modified in step

- charts/vela-core/templates/addons/istio.yaml
- pkg/stdlib/op.cue
- vela-templates/addons/auto-gen/istio.yaml
- vela-templates/addons/istio/definitions/canary-rollout-wf-def.yaml
fix apply reaming bug and modify rollout demo
Fixes #
> Fix apply remaing bug

- charts/vela-core/templates/kubevela-controller.yaml
> Fix(helm chart): change initialDelaySeconds of readinessProbe to 30s

- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
> Fix: fix typo

- docs/examples/workflow/Li-Auto-Inc/workflow-step-definitions.yaml
- docs/examples/workflow/apply-remaining/definition.yaml
- docs/examples/workflow/basic-app.yaml
- docs/examples/workflow/definition.yaml
> Fix: workflow example

- charts/vela-core/values.yaml
The default values for `cluster-gateway` is not correctly configured.
Fixes #
> Fix: fix multicluster values bug

- charts/vela-core/templates/addons/observability-asset.yaml
- charts/vela-core/templates/addons/observability.yaml
- docs/examples/obervability/README.md
- docs/examples/obervability/initializer-observability.yaml
- docs/examples/obervability/trait-import-grafana-dashboard.cue
- docs/examples/obervability/trait-register-grafana-datasource.cue
- vela-templates/addons/auto-gen/observability-asset.yaml
- vela-templates/addons/auto-gen/observability.yaml
- vela-templates/addons/observability-asset/definitions/trait-import-grafana-dashboard.yaml
- vela-templates/addons/observability/template.yaml
Charts in Github repo is not always avaialable for some users, so
moved them to OSS repo
Fixes #
> Fix: move charts from github repo to Alibaba Cloud OSS repo

- charts/vela-core/templates/addons/observability.yaml
- docs/examples/obervability/initializer-observability.yaml
- vela-templates/addons/auto-gen/observability.yaml
- vela-templates/addons/observability/template.yaml
Co-authored-by: Hongchao Deng <hongchaodeng1@gmail.com>
Fixes #
> Fix: add comments and adjust helm typed component's spec

- charts/vela-core/templates/cluster-gateway.yaml
Previously, disable multicluster function will still create cluster-gateway service and APIService which will lead to crd problems described in issue #2319. This PR fixes it.
Fixes #2319 
> Fix: fix multicluster template bug

- charts/vela-core/templates/defwithtemplate/init-container.yaml
- charts/vela-core/templates/defwithtemplate/sidecar.yaml
- vela-templates/definitions/internal/init-container.cue
- vela-templates/definitions/internal/sidecar.cue
> Feat: add args for init-contianer and sidecar

- Makefile
Currently, we use `cluster-gateway` and do not use OCM. Therefore, we should not test OCM in our Makefile procedure.
Fixes #
> Fix: remove ocm addon enable in Makefile

- charts/oam-runtime/templates/certmanager.yaml
- charts/oam-runtime/values.yaml
- charts/vela-core/templates/certmanager.yaml
- charts/vela-core/values.yaml
When using cert-manager certificates it is good practice to set revisionHistoryLimit. Today you have to unpack the chart and edit the template.
It should be possible to set the value.
Fixes #2342
> Feat: add revisionHistoryLimit to helm chart

- go.mod
- go.sum
> Fix: runc security issue

- .github/comment.userlist
- README.md
Docs: add a WeChat QR code, for faster user communication and retention.
> Docs: add a WeChat QR code

- charts/vela-core/templates/kubevela-apiserver.yaml
- charts/vela-minimal/templates/kubevela-apiserver.yaml
Fix  https://github.com/oam-dev/kubevela/pull/2358/checks?check_run_id=3716608919#step:10:390
> Fix(helm chart): fix startup args for apiserver

- pkg/cue/model/value/value.go
- pkg/cue/model/value/value_test.go
- pkg/workflow/hooks/data_passing.go
> Feat: inputs support setting value in array

- Makefile
- charts/vela-core/templates/kubevela-controller.yaml
delete deprecated vela dashboard in e2e setup
Fixes #
/cc @chivalryq
> Fix: delete deprecated vela dashboard in e2e setup

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- test/e2e-test/definition_test.go
> Fix: try fix CI unit test

- go.mod
- go.sum
> Chore(deps): bump go.mongodb.org/mongo-driver from 1.3.2 to 1.5.1

- charts/vela-core/templates/addons/istio.yaml
- vela-templates/addons/auto-gen/istio.yaml
- vela-templates/addons/istio/template.yaml
Fix istio addon, use aliyun oss chart 
Fixes #
> Fix: use aliyun oss istio chart

- apis/core.oam.dev/common/types.go
- charts/oam-runtime/crds/core.oam.dev_traitdefinitions.yaml
- charts/oam-runtime/crds/core.oam.dev_workloaddefinitions.yaml
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_componentdefinitions.yaml
- charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-core/crds/core.oam.dev_policydefinitions.yaml
- charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml
- charts/vela-core/crds/core.oam.dev_workflowstepdefinitions.yaml
- charts/vela-core/crds/core.oam.dev_workloaddefinitions.yaml
- charts/vela-core/templates/addons/terraform.yaml
- charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_policydefinitions.yaml
- charts/vela-minimal/crds/core.oam.dev_traitdefinitions.yaml
- charts/vela-minimal/crds/core.oam.dev_workflowstepdefinitions.yaml
- charts/vela-minimal/crds/core.oam.dev_workloaddefinitions.yaml
- go.mod
- go.sum
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_componentdefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_policydefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_workflowstepdefinitions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_workloaddefinitions.yaml
- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- vela-templates/addons/auto-gen/terraform.yaml
- vela-templates/addons/terraform/definitions/terraform-alibaba-eip.yaml
Besides inline HCL Configuration, supprted remote git repo Configuration
Fixes #
> Support remote git repo for Terraform configuration

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/cue/model/instance.go
- pkg/cue/model/instance_test.go
- pkg/cue/model/sets/utils.go
- pkg/cue/model/sets/utils_test.go
- pkg/cue/model/value/value.go
- pkg/cue/model/value/value_test.go
- pkg/workflow/tasks/custom/task.go
- test/e2e-test/application_test.go
> Feat: add inputs test cases and optimize code

- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/handler_suit_test.go
- pkg/controller/standard.oam.dev/v1alpha1/rollout/rollout_controller.go
If rollout failed pass resouceTracker to target and source workload
Fixes #2246 
> Fix: pass owner to workload if rollout failed

- charts/vela-core/templates/addons/terraform-provider-alibaba.yaml
- vela-templates/addons/auto-gen/terraform-provider-alibaba.yaml
- vela-templates/addons/terraform-provider-alibaba/template.yaml
To make the secret name of Terraform credential more clear and avoid the
impact on the feature of #2336
Fixes #
> Fix: make the name of Terraform credential secret same to component name

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision.go
- pkg/controller/core.oam.dev/v1alpha2/application/revision_clean_up_test.go
Fix revision GC in workflow mode
Fixes #2316
/cc @leejanee
> Fix: revision GC in workflow mode

- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope_controller.go
> Fix: Applied Resources Statistics  Error

- .github/workflows/e2e-multicluster-test.yml
#2368 introduces CLI coverage which causes the overall coverage drops a lot. This PR keeps the CLI coverage out of the statistic of overall coverage while remaining the test to be passed for correctness.
Fixes #
> Fix: fix multicluster coverage bug

- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/cluster.go
- pkg/apiserver/rest/utils/bcode/cluster.go
- pkg/apiserver/rest/webservice/cluster.go
- pkg/cloudprovider/aliyun.go
- pkg/cloudprovider/cluster.go
- test/e2e-apiserver-test/cluster_test.go
1. use PUT for cluster modify api
2. add invalid AK/SK error code and check
3. add kubeConfig in cluster get api
I have:
> Fix: enhance cluster api

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go
- pkg/stdlib/op.cue
- pkg/stdlib/pkgs/oam.cue
- pkg/workflow/providers/oam/apply.go
- pkg/workflow/providers/oam/apply_test.go
Use ApplyComponentRemaing like:
```yaml
apply: op.#ApplyComponentRemaining & {
component: "component-name"
exceptions: ["trait-name"]
}
```
I have:
/cc @wangyikewxgm @leejanee
> Feat: add render component and apply component remaining

- pkg/cue/definition/template.go
- pkg/cue/definition/template_test.go
> Feat: allow import package in custom status cue template

- apis/core.oam.dev/v1beta1/workflow_step_definition.go
- charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-core/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-core/crds/core.oam.dev_workflowstepdefinitions.yaml
- charts/vela-core/templates/defwithtemplate/webhook-notification.yaml
- charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_definitionrevisions.yaml
- charts/vela-minimal/crds/core.oam.dev_workflowstepdefinitions.yaml
- charts/vela-minimal/templates/defwithtemplate/webhook-notification.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_definitionrevisions.yaml
- legacy/charts/vela-core-legacy/crds/core.oam.dev_workflowstepdefinitions.yaml
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
- pkg/controller/utils/capability.go
- pkg/cue/packages/package.go
- pkg/oam/util/helper.go
- pkg/stdlib/packages.go
- pkg/stdlib/pkgs/slack.cue
- vela-templates/definitions/internal/webhook-notification.cue
> Feat: store workflow step def properties in cm

- .github/workflows/issue-commands.yml
> Fix: fix backport param

- pkg/workflow/context/context.go
- pkg/workflow/context/context_test.go
- pkg/workflow/hooks/data_passing_test.go
- pkg/workflow/workflow.go
- pkg/workflow/workflow_test.go
> Fix: add owner reference in workflow context cm

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/stdlib/pkgs/kube.cue
- pkg/workflow/providers/kube/handle.go
- pkg/workflow/providers/kube/handle_test.go
Fix op.Delete bugs:
1. Delete resource don't remove appliedResource from app.status.AppliedResource
2.  Closure op.Delete cue action will generate error when resource haven't exist.
I have:
ping @leejanee @FogDong
> Fix: op.delete bugs

- cmd/core/main.go
Display the reconcile error:
I have:
> Fix: show reconcile error log

- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/definition_test.go
Fixes #
I have:
- [ x] Added `backport release-x.y` labels to auto-backport this PR if necessary.
> Fix: fix definition schema struct

- docs/apidoc/swagger.json
- pkg/apiserver/model/application.go
- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/applicationplan.go
- pkg/apiserver/rest/usecase/applicationplan_test.go
- pkg/apiserver/rest/utils/bcode/application.go
- pkg/apiserver/rest/webservice/applicationplan.go
- pkg/apiserver/rest/webservice/validate_test.go
- pkg/apiserver/rest/webservice/webservice.go
- pkg/apiserver/rest/webservice/workflow.go
- test/e2e-apiserver-test/application_test.go
- test/e2e-apiserver-test/testdata/workflow.json
The current version of the dashboard does not directly expose the management of the policy. It has independent business processes for multi-environment delivery.
This PR implements the management of the application multi-environment policy plan.
> Feat: supports setting environment differences for application plan

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
Fix patchStatus in application controller. Sometimes, users may modify or delete application during reconcile, which will lead to patchStatus failure. However, our controller relies on the status to work properly. For example, if the workflow is deploying resources and user delete the app at this time, the controller would not be able to add newly created resources in status and the gc will skip them.
I have:
> Fix: patch status retry while conflict happens

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> Backport #2629 to release-1.1: patch status retry while conflict happens

- pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller_test.go
- pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller_test.go
- pkg/controller/utils/capability.go
- pkg/controller/utils/capability_integrate_test.go
- references/plugins/references.go
- test/e2e-test/helm_app_test.go
- test/e2e-test/kube_app_test.go
> Fix: allow definition schema cm can be same name in different definition type

- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/definition.go
- pkg/apiserver/rest/usecase/definition_test.go
> Fix: fix apiserver definition schema struct

- e2e/application/application_test.go
- pkg/utils/common/common.go
- references/cli/exec.go
- references/cli/logs.go
support vela exec in multiple clusters
> Feat: add vela exec for multi cluster

- apis/types/types.go
- pkg/appfile/appfile.go
- pkg/appfile/appfile_test.go
- pkg/clustermanager/cluster_manager.go
- pkg/controller/core.oam.dev/v1alpha2/application/apply.go
- pkg/controller/core.oam.dev/v1alpha2/application/generator.go
- pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope.go
- pkg/cue/process/handle.go
- pkg/workflow/providers/multicluster/multicluster.go
- references/cli/cluster.go
> Fix: health check will check for multiclusters

- Dockerfile
- pkg/utils/common/common.go
> Fix: minor fix for vela cli printing

- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/addon.go
- pkg/controller/utils/capability.go
> Feat: add addon parameter openAPI schema

- .github/workflows/registry.yml
Added Github action to push docker images to Alibaba Cloud ACR
Fixes #
I have:
> Fix: push docker images to Alibaba Cloud ACR

- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/addon.go
- pkg/apiserver/rest/utils/bcode/addon.go
- pkg/apiserver/rest/webservice/addon_registry.go
> Feat: add addon registry update API

- charts/vela-core/templates/addons/terraform.yaml
- docs/examples/terraform/cloud-resource-provision-and-consume/application-vpc.yaml
- docs/examples/terraform/cloud-resource-provision-and-consume/application-vswitch.yaml
- vela-templates/addons/auto-gen/terraform.yaml
- vela-templates/addons/terraform/definitions/terraform-alibaba-vpc.yaml
- vela-templates/addons/terraform/definitions/terraform-alibaba-vswitch.yaml
> Docs: add vpc and vswitch cloud resource templates of alicloud

- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_suite_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_test.go
- pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go
- test/e2e-test/rollout_trait_test.go
- test/e2e-test/testdata/rollout/deployment/multi_comp_app.yaml
Fixes #2674
When handle skipGC resource, if related component has been deleted, do not skipGC
I have:
> Fix: fix delete a component from application not delete workload

- charts/vela-core/templates/addons/terraform.yaml
- docs/examples/terraform/cloud-resource-provision-and-consume/application-ask.yaml
- vela-templates/addons/auto-gen/terraform.yaml
- vela-templates/addons/terraform/definitions/terraform-alibaba-ask.yaml
Added Serverless Kubernetes (ASK) for Alibaba Cloud
Fixes #
I have:
> Fix: add Alibaba Cloud ASK

- .github/workflows/issue-commands.yml
> Fix: fix backport script

- pkg/utils/url.go
- pkg/utils/url_test.go
- references/cli/cluster.go
Cherry pick #2675 into release-1.1.
> Backport 1.1: Fix cluster url (#2675)

- pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> Revert "Backport #2629 to release-1.1: patch status retry while conflict happens"

- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/delivery_target.go
- pkg/apiserver/rest/usecase/delivery_target_test.go
- pkg/apiserver/rest/utils/bcode/delivery_target.go
- pkg/apiserver/rest/webservice/delivery_target.go
- pkg/apiserver/rest/webservice/webservice.go
add delivery-target API
Fixes #
I have:
> Feat: add delivery-target API

- apis/types/capability.go
- pkg/addon/addon.go
- pkg/addon/error.go
- pkg/apiserver/model/addon.go
- pkg/apiserver/rest/apis/v1/types.go
- pkg/apiserver/rest/usecase/addon.go
- pkg/apiserver/rest/utils/bcode/addon.go
- pkg/apiserver/rest/webservice/addon.go
- pkg/velaql/providers/query/suite_test.go
- test/e2e-apiserver-test/addon_test.go
move general code to pkg/addon to reuse it later in CLI
Fixes #
I have:
> Refactor: refactor addon for later reusing code in CLI
