kubevela/kubevela

pkg/cmd/workload_run.go
Why create this label?
To show `appconfig`, need to get component's parameters. The component is rendered by `workloaddef`, there two way to get the origin `workloaddef`:
1. Using the component's name as workloaddef's name
2. Label the component
This PR is the second method.
=> Add component's workload label

pkg/cmd/traits.go
fix issue #68 by split workload name into multiple lines.
=> Fix overlap of workloads in column `APPLIES TO` for command `rudr traits`

cmd/rudrx/main.go, pkg/cmd/addon.go
Store addon center configuration in ~/.rudr/addon_config;
list workloaddefinitions and traitdefinitions, and check
wheter they are intalled.
=> Implement `addon:config` and `addon:ls`

cmd/vela/main.go, pkg/cmd/delete.go, pkg/cmd/env.go, pkg/cmd/env_test.go, pkg/cmd/init.go, pkg/cmd/ls.go, pkg/cmd/traits.go, pkg/cmd/util/helpers.go, pkg/cmd/workloads.go, pkg/test/cli.go, pkg/utils/system/system.go
1. remove kube flags
2. make env help pretty
```
$ vela env --help
Prepare environments for applications
Usage:
vela env              List all environments
vela env:init         Create environment and switch to it
vela env:sw           switch to another environment
vela env:delete               Delete environment
Examples:
vela env [env-name]
vela env:init test --namespace test
vela env:sw test
vela env:delete test
Flags:
-h, --help   help for env
--namespace string   specify K8s namespace for env (default "default")
```
3. fixes #81
```
$ vela env
NAME    CURRENT NAMESPACE
default *       default  
xs              default  
```
4. fixes  #79 
```
$ vela env xxx
env xxx not exist
```
5. fixes #77
=> Clean up env issues

README.md, api/types/types.go, cmd/vela/main.go, pkg/builtin/deployment.go, pkg/cmd/addon.go, pkg/cmd/admin.go, pkg/cmd/completion.go, pkg/cmd/delete.go, pkg/cmd/env.go, pkg/cmd/ls.go, pkg/cmd/refresh.go, pkg/cmd/status.go, pkg/cmd/trait_bind.go, pkg/cmd/workload_run.go, pkg/utils/logs/logs.go
```
vela
✈️  A Micro App Plafrom for Kubernetes.
Usage:
vela [flags]
vela [command]
Available Commands:
Getting Started:
env       	List all environments
env:delete	Delete environment
env:init  	Create environment and switch to it
env:sw    	switch to another environment
version   	Prints out build version information
Applications:
app:delete [APPLICATION_NAME]	Delete OAM Applications
app:ls                       	List applications with workloads, traits, status and created time
app:status                   	get status of an application, including its workload and trait
Workloads:
containerized:run <appname> [args]	Run containerized workloads
deployment:run <appname> [args]   	Run deployment workloads
Traits:
manualscaler <appname> [args]	Attach manualscaler trait to an app …
```
=> pretty help

cmd/vela/main.go, pkg/cmd/app_show.go, pkg/cue/convert.go
I have no idea to get parameter's origin value by `cue`, so this is my template resolve:
```
go run cmd/vela/main.go app:show test5
About:
Appset: test5
ENV: default
apiVersion: apps/v1
kind: Deployment
metadata:
name: test5
spec:
containers:
- env: []
image: nginx
name: test5
ports:
- containerPort: 8080
name: default
protocol: TCP
Traits:
- trait:
apiVersion: core.oam.dev/v1alpha2
kind: ManualScalerTrait
metadata:
name: test5-manualscaler-trait
spec:
replicaCount: 2
```
=> Show command

Makefile
#117 
command version doesn't show correctly.
The Old
```
./bin/vela version                                                                                                                                                                         !10966
Version: UNKNOWN
GitRevision: git-f38c55a
GolangVersion: go1.14.2
```
fixed
```
./bin/vela version                                                                                                                                                                         !10979
Version: 0.1.0
GitRevision: git-f38c55a
GolangVersion: go1.14.2
```
=> Fix version info

cmd/vela/main.go
Help message of all subcommands are overridden by
root command. Fix issue #124, #113
=> Fix help message overridden issue

cmd/vela/main.go, pkg/cmd/completion.go
Fix #131 
Removing field `Use: "vela",` causes the bash autocomplete script to fail.
=> Fix failure of bash autocomplete script

.github/workflows/go.yml, e2e/application/application_suite_test.go, e2e/application/application_test.go, e2e/cli.go, e2e/commonContext.go, e2e/env/env_suite_test.go, e2e/system/system_suite_test.go, e2e/system/system_test.go, e2e/trait/trait_suite_test.go, e2e/workload/workload_suite_test.go, pkg/builtin/traitdefinition/manualScaler.go, pkg/builtin/traitdefinition/simpleRollout.go, pkg/builtin/workloaddefinition/containerizedworkload.go, pkg/builtin/workloaddefinition/deployment.go, pkg/cmd/system.go, pkg/server/util/middleware.go
Fix builtin definitions not installed issue
And here is a test case.
```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX git:(system-init-issue) ✗ go run cmd/vela/main.go system:init
- Install OAM runtime:
Vela system along with OAM runtime already exist.
- Apply builtin capabilities:
Successful applied 4 kinds of Workloads and Traits.%                                                                                                                                                        
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX git:(system-init-issue) ✗ helm list -A
NAME                     	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                                   	APP VERSION
ack-node-problem-detector …
```
=> Apply builtin definition in system:init

e2e/apiserver/apiserver_test.go, pkg/oam/env.go, pkg/server/handler/appHandlers.go, pkg/server/util/errors.go
when hitting issue, the response struct should be the same as
normal response as below.
```
type Response struct {
Code int         `json:"code"`
Data interface{} `json:"data"`
}
```
Fix #169
=> Fix api response for error cases

pkg/cmd/ls.go
vela app list can use appName filter now
```
$ vela app:ls --app [appName]
or
$ vela app:ls -a [appName]
```
=> add flag `--app` for `app:ls`

pkg/oam/env.go
fix: #163 
Delete not existed env would print tips normally now.
```
$ vela env:delete xxxx
xxxx does not exist
```
=> fix not existed env successfully deleted

pkg/cmd/capability.go
fix: #186 
check err after `NewCenterClient`
```
$ vela cap:center:config abc http://abc.com
Successfully configured capability center: abc, start to sync from remote
Error: we only support github as repository now
```
=> fix `cap:center:config` panic

pkg/cmd/show.go
Before:
```
$ vela app show
Hint: please specify the application name**%**  
$ vela comp show
Hint: please specify the application name**%**  
```
After:
```
$ vela comp show
Hint: please specify the application name
$ vela app show 
Hint: please specify the application name
```
=> add a line break for 'vela xxx show' commands

pkg/commands/comp.go
Ref: #283 
`vela comp run` show help info now when args empty.
```
$ vela comp run
Init and Run workloads
Usage:
vela comp run [args]
Examples:
vela comp run -t <workload-type>
Flags:
-h, --help          help for run
-s, --staging       only save changes locally without real update application
-t, --type string   specify workload type for application
Global Flags:
-a, --app string   specify application name for component
-e, --env string   specify env name for application
```
=> fix `vela comp run` panic when args empty

charts/vela-core/templates/cert-manager.yaml
for some reason, images from quay.io can't easily visited, I upload image to docker hub for convenient
=> use image from docker hub instead of quay.io

pkg/commands/logs.go
use `return` instead of `break` to break out of the outer loop
=> use return instead of break

api/types/capability.go, api/types/types.go, charts/vela-core/templates/backend.yaml, charts/vela-core/templates/manualscalars.yaml, charts/vela-core/templates/metricstraits.yaml, charts/vela-core/templates/routetrait.yaml, charts/vela-core/templates/tasks.yaml, charts/vela-core/templates/webservices.yaml, pkg/commands/traits.go, pkg/commands/workloads.go, pkg/oam/trait.go, pkg/plugins/capcenter.go, pkg/plugins/cluster.go, pkg/plugins/cluster_test.go, pkg/server/apis/types.go
fixes #349
```
➜  ~ vela workloads
NAME      	DESCRIPTION
backend   	Backend worker without ports exposed
task      	One-time off task or job
webservice	Long running service with ports exposed
➜  ~ vela traits
NAME    	DESCRIPTION                       	APPLIES TO
metrics 	Add metric monitoring for workload
route   	Add a route for workload          	webservice
scale   	Scale replica for workload
```
=> add description for workload and trait

Makefile, charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml, cmd/core/main.go, cmd/core/main_test.go
#371 
- Controller-runtime allows [adding liveness & readiness probes for ctrl-mgr.](https://github.com/kubernetes-sigs/controller-runtime/pull/419) Use probes to help determining the manager is ready to go.
- Add a looping check for webhook secrets volume mounted before start mgr, which can avoid unnecessary pod restart.
=> add liveness & readiness probes

charts/vela-core/templates/definitions/routetrait.yaml
The route trait can auto discovery, so we don't need to specify any backend arguments.
=> fix route trait definition

examples/testapp/Dockerfile, pkg/commands/logs.go
```
➜  kubevela git:(logs) vela logs myapp
? You have multiple Component in your app. Choose one component for logs:  mycomp2
+ mycomp2-667957dbd9-zglzz › mycomp2
mycomp2-667957dbd9-zglzz mycomp2 2020-10-20T12:46:42.287212932Z /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
mycomp2-667957dbd9-zglzz mycomp2 2020-10-20T12:46:42.287273498Z /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
mycomp2-667957dbd9-zglzz mycomp2 2020-10-20T12:46:42.288166788Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
mycomp2-667957dbd9-zglzz mycomp2 2020-10-20T12:46:42.29590541Z 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
mycomp2-667957dbd9-zglzz mycomp2 …
```
=> support vela logs

pkg/plugins/cluster.go, pkg/plugins/cluster_test.go
If CueTemplateURI is assigned in workload/trait definition, while `vela system update`, before this fix, it will fetch the cue template through URI and save it as $VELA_HOME/capabilities/*.cue but not fulfill the template content into CueTemplate field.  Empty CueTemplate field will result in Appfile RenderService error.
=> fix getting CUE template from remote

e2e/application/application_test.go, e2e/commonContext.go, e2e/trait/trait_test.go, e2e/workload/workload_test.go, pkg/commands/comp.go, pkg/commands/delete.go, pkg/commands/exec.go, pkg/commands/init.go, pkg/commands/ls.go, pkg/commands/show.go, pkg/commands/status.go, pkg/commands/trait.go, pkg/commands/up.go, pkg/commands/util/helpers.go
related to #412 
This PR changed term "component" in CLI (usage and outputs) to "service". 
=> change term "component" to "service" in commands 

charts/vela-core/templates/velaConfig.yaml, cmd/core/main.go, docs/install.md, pkg/commands/dashboard.go, pkg/commands/system.go, pkg/commands/util/init.go, pkg/controller/dependency/install.go, pkg/controller/dependency/install_test.go, pkg/oam/capability.go, pkg/utils/helm/helm.go
ref https://github.com/oam-dev/kubevela/issues/441#issuecomment-716862454
Currently vela core server relies on CRD to install dependency components. But it doesn't work for ingress, doesn't update more dependencies over time, and doesn't uninstall them.
This PR rewrites server dependency component installation logic:
1. Don't rely on crd name. Continue installing all charts.
```
NAME                 	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
cert-manager         	cert-manager	1       	2020-10-28 19:44:39.877674984 -0700 PDT	deployed	cert-manager-v1.0.3        	v1.0.3
flagger              	vela-system 	1       	2020-10-28 19:47:21.716232979 -0700 PDT	deployed	flagger-1.2.0              	1.2.0
ingress-nginx …
```
=> Fix vela install to include all dependencies

pkg/appfile/service.go
Example:
```
version: "1.0-alpha.1"
name: test1
secrets: {}
services:
hello:
image: nginx:latest
name: hello
port: 80
route:
domain: hello.y
issuer: oam-env-default
type: webservice1
```
Error: eval service failed: capability webservice1 unexist
=> [Feature #443] should report capability not exist instead of file not found

pkg/controller/v1alpha1/routes/ingress/nginx_ingress.go, pkg/oam/trait_checker.go
Local kind cluster ingress will have hostname not IP.
`vela svc status` will complain with error. With this fix it will be fine:
```
route: 	Visiting URL: http://example.com	IP: localhost
```
=> fix check route status when using local kind

Makefile, pkg/commands/show.go
Fixed the issue of `charts/vela-core/crds/_.yaml` generation
by removing unkonwn struct in pkg/commands/show.go.
=> Fix `charts/vela-core/crds/_.yaml` generation issue

e2e/commonContext.go, pkg/commands/init.go, pkg/commands/up.go, pkg/commands/up_test.go
I focus on the printed out messages in the quick start example. 
I wish to change  
`specify app image` to `Specify application image`  
`specify port for container` to `specify application service port` 
as well but this requires a lot of changes since the texts come from the workload definition. Hence, I omit them in this change.
=> Some revisions for the printed out messages

Makefile, e2e/capability/capability_test.go
plan to change e2e into a mock UT to avoid remote call.
Signed-off-by: Hongchao Deng <hongchaodeng1@gmail.com>
=> skip capability e2e due to rate limit

pkg/appfile/build.go
When executing commands such as docker build/push, logs are required to be printed to the console in real time.
Look at the following example:
```
✗ ./vela up -f vela.yaml
Parsing vela.yaml ...
Loading templates ...
Building service (express-server)...
Sending build context to Docker daemon   75.2MB
Step 1/10 : FROM mhart/alpine-node:12
---> 33d2f6886442
Step 2/10 : WORKDIR /app
---> Using cache
---> 71ec0bca7ec3
Step 3/10 : COPY package.json ./
---> Using cache
---> 0d308ba67e7f
Step 4/10 : RUN npm install
---> Using cache
---> 466b273990f8
Step 5/10 : RUN npm ci --prod
---> Using cache
---> 16d7da32a4b7
Step 6/10 : FROM mhart/alpine-node:slim-12
---> e60b0704d22a
Step 7/10 : WORKDIR /app
---> Using cache
---> 590136de0706
Step 8/10 : COPY --from=0 /app .
---> Using cache
---> …
```
=> Logs need to be printed in real time when vela executes docker command

api/types/capability.go, e2e/commonContext.go, e2e/trait/trait_test.go, e2e/workload/workload_test.go, pkg/commands/cli.go, pkg/commands/refresh.go, pkg/commands/status.go, pkg/commands/traits.go, pkg/commands/workloads.go, pkg/plugins/cluster.go, pkg/plugins/cluster_test.go
- for `vela traits` and `vela workloads`, add a bool flag whose default value is true to indicate whether run `vela system update` before listing traits/workloads
- refine the output of `vela system update`: Show added/updated/deleted capabilities if exist any, otherwise(nothing changed), show all existing capabilities.
Demo screenshots:
add e2e-test
=> update local caps before listing workloads&traits

e2e/application/application_test.go, e2e/commonContext.go, pkg/commands/exec.go, pkg/commands/ls.go
before fixing:
```
➜  bin git:(master) ./vela ls
SERVICE             APP             TYPE    TRAITS  STATUS          CREATED-TIME                 
vela-go-demo    vela-demo                              Deployed        2020-11-05 11:47:50 +0800 CST
```
after fixing:
```
➜  bin git:(master) ./vela ls
SERVICE             APP                 TYPE                 TRAITS  STATUS          CREATED-TIME                 
vela-go-demo    vela-demo       webservice      route     Deployed        2020-11-05 11:47:50 +0800 CST
```
=> The return value of `vela ls` must contain the TYPE and TRAITS fields.

pkg/controller/v1alpha1/metrics/metricstrait_controller.go, pkg/controller/v1alpha1/metrics/metricstrait_controller_integration_test.go
fix #444
It will cause data race if we use pointer(map is pointer) for data construct when we get value with controller-runtime.client.
=> fix datarace for map

pkg/controller/utils/utils.go, pkg/controller/v1alpha1/routes/route_controller.go, pkg/controller/v1alpha1/routes/route_controller_test.go, pkg/controller/v1alpha1/routes/suite_test.go, pkg/controller/v1alpha1/routes/util.go
The original labels will select all label from podtemplate, this will introduce revision different labels, so the route trait can not route ingress and service to different revisions when they are rolling update. So I narrow the labels, only choose two labels which represent `OAM app config name` and `component name`
=> only choose OAM app labels for route trait

pkg/appfile/appfile.go, pkg/application/app.go, pkg/commands/ls.go, pkg/controller/v1alpha1/routes/route_controller_test.go
By default, all svc deployed without `--staging` will appear
to be `staging` in cmd `vela ls`.
To fix #534
=> Fix `vela ls` issue

charts/vela-core/templates/defwithtemplate/task.yaml, charts/vela-core/templates/defwithtemplate/webservice.yaml, charts/vela-core/templates/defwithtemplate/worker.yaml, design/api/vela-restful-api-reference.md, docs/en/developers/alternative-cmd.md, docs/en/developers/references/workload-types/task.md, docs/en/developers/references/workload-types/web-service.md, docs/en/quick-start.md, e2e/commonContext.go, hack/vela-templates/cue/task.cue, hack/vela-templates/cue/webservice.cue, hack/vela-templates/cue/worker.cue, pkg/commands/init.go, pkg/cue/convert_test.go, pkg/cue/testdata/workloads/deployment.cue, pkg/cue/testdata/workloads/test-param.cue, pkg/plugins/cluster_test.go, pkg/plugins/testdata/websvcWorkloadDef.yaml, pkg/plugins/testdata/workloadDef.yaml
fix #557 
Updated like this, the optional value was explicit declared:
```
Welcome to use KubeVela CLI! Please describe your application, user could just skip it.
Environment: myenv, namespace: default
? What is your email (optional, used to generate certification):
? What would you like to name your application (required):  myapp
? Choose the workload type for your application (required, e.g., webservice):  webservice
? What would you like to name this webservice (required):  myweb
? Which image would you like to use for your service (required):  nginx
? Which port do you want customer traffic sent to (optional, default is 80):  8080
? CPU core requests for the workload, specify like '0.5', '1'. (optional):
Deployment config is rendered and written to vela.yaml
⠋ Checking Status ...
✅ …
```
=> update vela init UI

pkg/commands/traits.go, pkg/commands/workloads.go
The help description of commands `vela traits`, `vela workload` are missing in `vela -h`.
Add correct `TagCommandType` annotation to fix it.
=> Add missing TagCommandType

api/types/types.go, pkg/commands/capability.go, pkg/commands/cli.go, pkg/commands/comp.go, pkg/commands/config.go, pkg/commands/delete.go, pkg/commands/env.go, pkg/commands/exec.go, pkg/commands/init.go, pkg/commands/show.go, pkg/commands/status.go, pkg/commands/template.go, pkg/commands/trait.go, pkg/commands/traits.go, pkg/commands/workloads.go
ref: https://github.com/oam-dev/kubevela/issues/590#issuecomment-726421554
```
Available Commands:
Getting Started:
init   	Init an OAM Application by one command
install	Install OAM runtime and vela builtin capabilities.
up     	Apply an appfile, by default vela.yaml
Managing Applications:
config                                                                                    	Manage application configurations under given env
delete APP_NAME                                                                           	Delete Applications
env                                                                                       	Manage application environments
exec [flags] APP_NAME -- COMMAND [args...]                                                	Execute a command in the 1st container of …
```
=> clean up vela cli help info to be app focused

docs/en/developers/set-rollout.md, docs/en/quick-start.md
As the title said.
I deleted the `If your cluster don't have ingress,` content. In that case (no ingress in cluster), you should not do Canary rollout.
=> Fixe several nits in the doc and guide

README.md
Gitter and Slack are not needed, they are highlighted in README.
Also, the Slack channel for kubevela is: https://cloud-native.slack.com/messages#kubevela
=> Remove duplicated badges

docs/en/platform-engineers/trait.md, docs/en/platform-engineers/workload-type.md, pkg/commands/cli.go, pkg/controller/dependency/install.go, pkg/controller/dependency/install_test.go, pkg/oam/capability.go, pkg/plugins/cluster.go, pkg/server/main/startAPIServer.go, pkg/server/util/middleware.go, pkg/utils/common/common.go, pkg/utils/helm/helm.go
1. teach how to extend trait from writing definition file step by step.
2. support install helm chart from cluster definition , before this PR, the chart can only installed from capability center, so the example in doc won't work.
3. create namespace if not exist when installing chart
=> refactor extend trait feature and doc

.github/workflows/docker.yml, Dockerfile
* Dockerfile updates to support multi-arch image （support `docker build` too）
* github workflow updates
* migrate to `ghcr.io` ([see more](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images)). need to add a new secret `CR_PAT`
* switch to `docker/login-action` && `docker/build-push-action@v2` for multi arch image build by `buildx`
examples:
https://github.com/users/morlay/packages/container/package/kubevela%2Fvela-core
=> multi-arch images support

pkg/commands/init.go, pkg/server/util/middleware.go
Ref #645
**1nd submission** pkg/commands/init.go
- fix lint error: put a space between `//` and comment text
- fix lint error: exported function `GetCapabilityByName` should have comment or be unexported
- fix lint error: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
**2nd submission** pkg/server/util/middleware.go
- fix lint error: put a space between `//` and comment text
- add comment to exported function/type
=> fix lints for pkg/commands/init.go and pkg/server/util/middleware.go

apis/types/args.go, pkg/commands/capability.go, pkg/commands/cli.go, pkg/commands/comp.go, pkg/commands/config.go, pkg/commands/dashboard.go, pkg/commands/delete.go, pkg/commands/env.go, pkg/commands/env_test.go, pkg/commands/exec.go, pkg/commands/exec_test.go, pkg/commands/init.go, pkg/commands/logs.go, pkg/commands/ls.go, pkg/commands/portforward.go, pkg/commands/portforward_test.go, pkg/commands/status.go, pkg/commands/system.go, pkg/commands/template.go, pkg/commands/trait.go, pkg/commands/traits.go, pkg/commands/traits_test.go, pkg/commands/up.go, pkg/commands/up_test.go, pkg/commands/workloads.go
Fix https://github.com/oam-dev/kubevela/issues/655
This PR move GetConfig into specific vela commands to make sure other commands can work without kubeconfig.
During updating, I found some commands that don't need the controller-runtime client arguments. Thus, I removed the controller-runtime client argument from their function parameters.
Moreover, I found some imports don't follow the `goimports` formatting, I sort them up as well.
=> Move GetConfig into specific commands

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Remove "[BUG]" from the default issue as maintainers can
use labeling mechanism to tell whether it is
=> Remove automatically prefixed "[BUG]" in the issue title

charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml, cmd/core/main.go, go.mod, go.sum, pkg/controller/common/types.go, pkg/controller/setup.go, pkg/controller/standard.oam.dev/v1alpha1/autoscaler/autoscaler_controller.go, pkg/controller/standard.oam.dev/v1alpha1/autoscaler/keda.go, pkg/controller/standard.oam.dev/v1alpha1/autoscaler/suite_test.go, pkg/controller/standard.oam.dev/v1alpha1/autoscaler/types.go, pkg/controller/utils/util_suite_test.go, pkg/controller/utils/utils.go, pkg/controller/utils/utils_test.go, pkg/webhook/register.go
Added vela core bootstrap flag `--enable-caps` to support no
installation for builtin capabilities
Feature #658
=> Support disable installation of builtin capabilities

pkg/commands/portforward.go
cut `port-forword` Usage text, add Example text
Close: https://github.com/oam-dev/kubevela/issues/696
=> fix long text port forword

.github/workflows/docker.yml, .github/workflows/release.yml, Dockerfile, Makefile, cmd/core/main.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/update_trait_test.go
1. This PR will use `sed` to replace image tag from `latest` to release version, so our chart will lock in the fixed image version. fix #712
2. Build vela-core image with version and git revision, so we can get the specified version for debug. fix #531
=> build version into vela-core and lock helm version on release

charts/vela-core/templates/defwithtemplate/task.yaml, hack/vela-templates/cue/task.cue
Update the restartpolicy default value Always-->Never。
Task creates job RestartPolicy by default with a value of Always, which obviously does not work. I define a parameter policy, which defaults to Never.
=> fix task( k8s job ) restartpolicy default Always

docs/en/platform-engineers/cloud-services.md, docs/examples/kubecondemo/script/def_db.yaml
When you use crossplane to apply for an rds instance, the rds crd name in the example does not correspond to the name created by crossplane, resulting in a vela workloads error: rds was not ready.
fix #748
=> Fixed the problem that the rds crd name is incorrect

pkg/commands/capability.go, pkg/commands/cli.go, pkg/commands/config.go, pkg/commands/env.go, pkg/commands/ls.go, pkg/commands/print.go, pkg/commands/refresh.go, pkg/commands/show.go, pkg/commands/status.go, pkg/commands/traits.go, pkg/commands/traits_test.go, pkg/commands/workloads.go
- Issue: too much content in one table cell makes the table mess.
Before:
Fix: specify `MaxColWidth=80 and Wrap=true` to uitable 
After:
- move funcs/vars used for printing into one go file.
=> fix cmd uitable wrap issue

README.md
It seems the previous link won't work if the user is not a CNCF slack member yet. Since we can't generate invitation link (we are not admin), let's use the full format for now.
Fixes: https://github.com/oam-dev/kubevela/issues/760
=> Update slack channel link

Makefile
`brew install kubevel` use `make vela-cli` install kubevela, the command `go run hack/chart/generate.go` needs to be added, otherwise the `vela install` command will not run
=> Adapted for brew installation

dashboard/config/proxy.ts
Make it work for `make start-dashboard`:
=> fix inconsistency for dev proxy config

pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/render.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/update_trait_test.go
the bug occurs when revisionEnabled trait is used.
Reproduce workflow, apply following yaml one by one:
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
annotations:
definition.oam.dev/description: '`Scaler` is used to configure replicas for your
service.'
name: scaler
spec:
definitionRef:
name: manualscalertraits.core.oam.dev
revisionEnabled: true
workloadRefPath: spec.workloadRef
```
```
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
name: example-component
spec:
workload:
apiVersion: core.oam.dev/v1alpha2
kind: ContainerizedWorkload
spec:
containers:
- name: wordpress
image: wordpress:4.6.1-apache
ports:
- containerPort: 80
name: wordpress
env:
- name: TEST_ENV
value: test
```
```
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration …
```
=> fix workload reconcile error when revision enable trait is attached

test/integration/appconfig_test.go
With webhooks of AppConfig enabled when creating an AppConfig, it's necessary to make sure WorkloadDefintion/TraitDefintion/Component are created successfully, otherwise the validating-webhook would fail.
=> fix unstable integration test

pkg/commands/refresh.go, pkg/plugins/cluster.go
Error message of trait without `spec.extension.template`
adheres with normal message when executing "vela workloads".
To fix #826
=> Refine error message for trait without `spec.extension.template`

pkg/server/apis/types.go, pkg/server/workloadHandler.go
Workload item doesn't have descriptin property, added it to help display
the description in capability list on Dashboard
Fix #821
=> Add "description" field for each workload from ListWorkloads API

.github/workflows/dashboard.yml, .github/workflows/go.yml
I have made CI checks(e2e, unit tests, lint, diff check as required), but if the CI ignore running these checks, it will hang on and couldn't be merged. So I remove the ignore path, let all changes to run a CI.
Our community is growing and more maintainers will come in, branch protect will help us maintain a repo in high quality.
=> run CI check for all PR including docs/ and *md

charts/vela-core/templates/defwithtemplate/autoscale.yaml, charts/vela-core/templates/defwithtemplate/manualscale.yaml, charts/vela-core/templates/defwithtemplate/metrics.yaml, charts/vela-core/templates/defwithtemplate/rollout.yaml, charts/vela-core/templates/defwithtemplate/route.yaml, charts/vela-core/templates/defwithtemplate/task.yaml, charts/vela-core/templates/defwithtemplate/webservice.yaml, charts/vela-core/templates/defwithtemplate/worker.yaml, docs/en/developers/references/traits/autoscale.md, docs/en/developers/references/traits/metrics.md, docs/en/developers/references/traits/rollout.md, docs/en/developers/references/traits/route.md, docs/en/developers/references/traits/scaler.md, docs/en/developers/references/workload-types/task.md, docs/en/developers/references/workload-types/webservice.md, docs/en/developers/references/workload-types/worker.md, hack/references/generate.go, hack/vela-templates/definitions/autoscale.yaml, hack/vela-templates/definitions/manualscale.yaml, hack/vela-templates/definitions/metrics.yaml, hack/vela-templates/definitions/rollout.yaml, hack/vela-templates/definitions/route.yaml, hack/vela-templates/definitions/task.yaml, hack/vela-templates/definitions/webservice.yaml, hack/vela-templates/definitions/worker.yaml, pkg/commands/traits.go, pkg/commands/workloads.go
Expended column width for `vela workloads/traits` and also
shortened the description for all workloads and traits.
Fixed a tiny issue in hack/reference/generate.go
To fix issue #827
=> Expend column width for "vela workloads/traits"

docs/en/developers/references/traits/autoscale.md, docs/en/developers/references/traits/rollout.md, hack/references/configurations/autoscale.yaml, hack/references/conflictsWithAndMore/rollout.md, hack/references/generate.go
Added `ConflictsWith` and `How Rollout Works` section to Rollout Reference Docs.
To fix #777
=> Add `ConflictsWith` and more sections for Rollout

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/parser/service.go, pkg/controller/core.oam.dev/v1alpha2/application/template/template.go, pkg/controller/core.oam.dev/v1alpha2/application/template/template_test.go, pkg/dsl/definition/template.go, pkg/dsl/definition/template_test.go
Vela is used for application release, and how to evaluate the success of an application release? Not only Vela creates workloads and traits, but more importantly, Vela should check the health of workloads and traits. HealthScope is hardcoded for the health check logic of various resources. Here providers a custom health check plan.
After the K8s resource is created, the relevant data will be written back to the status of CR. Whether the release is successful is actually a series of judgments and filter conditions combination, called health policy. Vela should combine with the data in CR and the policy to determine whether a resource object meets the conditions. For example, when the values of replicas and readyReplicas in the status of Deployment CR are equal, the release is successful. …
=> feature: add healthcheck policy for workload and trait by cue template

design/vela-core/apply-workload-and-trait.md, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_trait_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/dependency_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go, pkg/controller/standard.oam.dev/v1alpha1/rollout/webhook.go, pkg/oam/labels.go, pkg/utils/apply/apply.go, pkg/utils/apply/apply_resource_test.go, pkg/utils/apply/apply_suite_test.go, pkg/utils/apply/apply_test.go, pkg/utils/apply/patch.go, pkg/utils/apply/patch_test.go, test/integration/appconfig_test.go
to fix #848 
New applicator makes a patch through computing a three way diff in client side, just like what `kubectl apply` do under the hood.
---
The workload/trait update logic will changed:
the old json-merge patch will be replaced by using three-way-merge patch.
The reason why abandon json-merge patch is that, it cannot remove a field through unsettling value in the patched manifest. 
For example, apply below deployment as a workload. json-merge patch cannot remove `minReadySeconds` field through applying a modifiied manifest with `minReadySeconds` omitted .
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
minReadySeconds: 60
replicas: 3
template:
spec:
containers:
- name: nginx
image: nginx:1.14.2
---
apiVersion: apps/v1
kind: Deployment
...
spec:
replicas: 3
template:
spec: …
```
=> using 3-way-merge-patch instead of "json merge patch for workload" and "update for trait"

pkg/commands/dryrun.go, pkg/commands/system.go
Add dry-run command for platform builder for debugging
[Related Issue](https://github.com/oam-dev/kubevela/issues/925#issue-791792591)
fix #925 
usage:
```
vela system dry-run -f app.yaml
```
=> Add dry-run command

charts/vela-core/templates/cert-manager.yaml, charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/templates/webhook.yaml, charts/vela-core/values.yaml, pkg/commands/system.go
1. support `vela install ` with helm args.
For example:
```
vela install --set useWebhook=false --set image.pullPolicy=always 
```
Use `--set` to sepcify "key=value" pairs just like what `helm install` supports.
2. support cert manager to be optional, specify it as false will not install it. part of #928 
```
vela install --set installCertManager=false
```
3. remove webhook secret volume when webhook not enabled.
=> support vela install with helm args and make cert-manager optional

.github/workflows/charts.yaml
AccessKey was added as Github secret and it has only permission to write the specified oss bucket.
Users will be able to use it by:
1. Add repo
```
helm repo add kubevela https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core
```
2. Update repo
```
helm repo update
```
3. Search version
```
helm search repo kubevela
```
4. Install
```
helm install kubevela/vela-core
```
=> Upload vela core chart to alibaba cloud oss for every release and master commit

pkg/commands/traits_test.go, pkg/serverlib/trait.go
vela traits
fill up the `APPLIES TO` information when the trait can be applied to *
fixes #830
fixes #884
=> #884 #830 complete the trait info when it is applied to *

.github/workflows/registry.yml, README.md, hack/artifacthub/artifacthub-repo.yml
Set KubeVela team as a verified publisher of Artifacthub,
Add README to the repo and add helm badge in github readme
fix #977
=> Set KubeVela as verified publisher of ArtifactHub

charts/vela-core/templates/webhook.yaml, pkg/webhook/core.oam.dev/register.go, pkg/webhook/core.oam.dev/v1alpha2/traitdefinition/validating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/traitdefinition/validating_handler_test.go, pkg/webhook/core.oam.dev/v1alpha2/traitdefinition/validator_test.go
related to #907 
Add a validating webhook for TraitDefintion, and a validator:
TraitDefinition without `.spec.definitionRef` should satisfy one of below:
- it has at least one output, and all outputs must have GVK
- it has no output but has a patch
- it has a patch and outputs, and all outputs must have GVK
=> validating webhook for TraitDefinition

e2e/capability/capability_test.go, pkg/commands/capability.go, pkg/plugins/capcenter.go, pkg/serverlib/capability.go
to fix #998 
solution: use trait cap name instead of trait's CRD name as file name saved locally
because unit tests in pkg `capability` are skipped by CI, I just run those tests locally.
=> fix cannot sync trait without definitionRef

pkg/builtin/build/build.go
since image push operation is done here(https://github.com/oam-dev/kubevela/blob/a761e75c01b9305fe616f32d2646131ab6986fe4/pkg/builtin/build/build.go#L39)
it seems redudant to push image in image build function
=> remove redundant image push operation

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component.go, pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller.go, pkg/controller/standard.oam.dev/v1alpha1/metrics/metricstrait_controller.go, pkg/controller/standard.oam.dev/v1alpha1/podspecworkload/podspecworkload_controller.go, pkg/controller/standard.oam.dev/v1alpha1/routes/route_controller.go
It's would be better to update CR's status with retry.RetryOnConflict to avoid the conflicts caused by other code making unrelated updates to the resource at the same.
=> fix: update CR's status with retry.RetryOnConflict

.github/workflows/registry.yml, docs/en/install.md, legacy/README.md
Currently the latest chart is vela-core:latest, which could
not be supported by Artifacthub, add latest tag and make the
lastest chart version as `vx.y.z-latest`
=> Add latest release tag to be the prefix of latest version of Chart

docs/en/cue/trait.md
Check whether parameter.command is nill before setting the value of
spec.template.spec.initContainers.command
Fix #1062
=> Check whether parameter.command is nill for init-container trait

Makefile
An error occurs when running make core-install: 
```
❯ make core-install
go generate ./pkg/... ./apis/...
./hack/vela-templates/gen_definitions.sh
~/code/github/oam-dev/kubevela/hack/vela-templates ~/code/github/oam-dev/kubevela
done
~/code/github/oam-dev/kubevela
kubectl apply -f hack/namespace.yaml
namespace/vela-system created
kubectl apply -f charts/vela-core/crds/
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created …
```
=> Fix make core-install error

pkg/dsl/definition/template.go, pkg/dsl/process/handle.go, pkg/dsl/process/handle_test.go
use context.output instead of context.input to refer to the output object defined in the WorkloadDefinition
use case
```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
name: worker
spec:
definitionRef:
name: deployments.apps
extension:
template: |
output: {
apiVersion: "apps/v1"
kind:       "Deployment"
spec: {
selector: matchLabels: {
"app.oam.dev/component": context.name
}
template: {
spec: {
containers: [{
name:  context.name
ports:[{containerPort: 443}]
}]
}
}
}
}
---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
name: service
spec:
extension:
template: |
parameter: {
exposePort: int
}
outputs: service: {
apiVersion: "v1"
kind: "Service"
spec: {
selector:
app: context.name
ports: [
{
port: paramter.exposePort
// Previously used context.input …
```
=> Use context.output instead of context.input to refer to the output object defined in the WorkloadDefinition

pkg/commands/exec.go
I am used to use command ’kubectl exec ${pod} -c ${container}  ${command}‘
But i found error hint in 'vela exec' is not specified.
Shall we make it more clear?
=> improvement: specify 'vela exec' error hint

docs/en/cue/trait.md, pkg/dsl/definition/template.go, pkg/dsl/definition/template_test.go, pkg/dsl/process/handle.go, pkg/dsl/process/handle_test.go
use "context.outputs" to reference auxiliary objects defined in the definition template
reference issue: [context.output refer to workload output  object](https://github.com/oam-dev/kubevela/pull/1076)
Implement  refer to objects defined in the definition template also achieves the purpose of
[support simple data passing from workload to trait](https://github.com/oam-dev/kubevela/issues/1026)
fix https://github.com/oam-dev/kubevela/issues/1026
=> Use "context.outputs" to reference auxiliary objects defined in the definition template

apis/core.oam.dev/v1alpha2/core_types.go, charts/vela-core/crds/core.oam.dev_applicationconfigurations.yaml, design/vela-core/apply-once-only.md, legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationconfigurations.yaml, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go, pkg/oam/util/helper.go, pkg/oam/util/helper_test.go
1) AC will override its component/workload; 
2) AC will override its trait; 
3) workload will override child resources
---
4) apply once only will check component revision
5) refactor CRD status of AppConfig to make workload has Dependency and appliedGeneration
=> parent override child when annotation/labels conflicts && one revision will apply once only in force mode && AC.status CRD updated

apis/core.oam.dev/v1alpha2/core_types.go, charts/vela-core/crds/core.oam.dev_applicationconfigurations.yaml, design/vela-core/apply-once-only.md, legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationconfigurations.yaml, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_once_only_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/suite_test.go, pkg/oam/util/helper.go, pkg/oam/util/helper_test.go
parent override child when annotation/labels conflicts && one revision will apply once only in force mode && AC.status CRD updated (#1109)
* when annotation/labels passthrough from parent to child conflicts, the parent will override the child.
e.g. 1) AC will override its component/workload; 2) workload will override child-resource; 3) AC will override its trait
* apply once only force will block workload apply when revision not changed even ac generation updated
cherry-pick(#1109 and #1114)
please don't merge until #1114 merged
=> cherry-pick(1109 and 1114)

.github/workflows/go.yml, Makefile
add step **cleanup** to delete image after step **e2e-test** , the **cleanup** step will always executes(even if the previous step fails).
fix #1140
=> fix #1140 delete image after e2e test

.github/workflows/go.yml, Makefile
fix #1140, add step cleanup to delete image after step e2e-test , the cleanup step will always executes(even if the previous step fails).
=> cherry-pick(#1143) delete image after e2e test

pkg/commands/dryrun.go
quick fix vela system dryrun command cannot get namespaced definition, use env namespace for application namespace
=> fix vela system dryrun command cannot get namespaced definition

Dockerfile
fix #1177
Use ‘Ubuntu’ as default base image instead of 'Distroless' for debug convenience.
change log:
1. change args `BASE_DISTROLESS` to `BASE_IMAGE`
2. change default image from `gcr.io/distroless/static:nonroot` to `ubuntu:latest`
3. dockerfile reference to 
https://github.com/openkruise/kruise/blob/master/Dockerfile#L24-L28
=> Use ‘Ubuntu’ as default base image instead of 'Distroless' for debug convenience

.github/workflows/go.yml
Our CI is very heavy now, this configuration can help reduce duplicate jobs from running.
=> configure ci to skip duplicate job

charts/vela-core/values.yaml
To avoid using legacy `oamdev/vela-core: latest` image.
=> modify image pull policy

apis/core.oam.dev/v1alpha2/application_types_test.go, pkg/builtin/http/http_test.go, pkg/controller/common/rollout/rollout_webhook_test.go
Fix the function and method names that does not conform to the naming convention
=> Fix the function and method names that does not conform to the naming convention

references/appfile/modify.go
Fix duplicated string literals
Duplicated string literals make the process of refactoring error-prone, since you must be sure to update all occurrences.
On the other hand, constants can be referenced from many places, but only need to be updated in a single place.
=> Fix duplicated string literals

docs/en/concepts.md, docs/en/introduction.md
I think there is a typo in "introduction" and made other minor wording fixes in "concepts".
=> docs: minor fixes on introduction and concepts

Makefile, charts/vela-core/crds/core.oam.dev_applications.yaml
In CI image "ubuntu-20.04", kustomize v4.0.5 is pre-installed. So current makefile skips installing v3.8.2
> {Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}
And diff from v3.8.2, customize v4 has the problem that break too long sentences. 
That will fail any PR containing changes on crds/application.yml while author's local kustomize is truly v3.8.2.
to fix #1311 
=> fix CI check-diff

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/revision.go, pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go, pkg/controller/core.oam.dev/v1alpha2/application/testdata/revision/app1.yaml, pkg/controller/core.oam.dev/v1alpha2/application/testdata/revision/cd1.yaml, test/e2e-test/appconfig_render_workload_test.go, test/e2e-test/application_test.go, test/e2e-test/common_util_test.go
=> propagate AppRevision Into context.AppRevision 

docs/sidebars.js
The old location of cloud resource is behind `Define Trait`.
```
```
=> Add cloud service doc in official site

charts/vela-core/templates/kubevela-controller.yaml
The `system-definition-namespace` flag of `vela-core` should be added into `kubevela-controller.yaml` of the helm chart, and specified with chart value `systemDefinitionNamespace`, so that the parser can find the definitions from the same namespace which defined in the `ComponentDefinition/TraitDefinition`.
Without this, Application cannot be processed properly if the definition crds are not installed in `vela-system` namespace:
```
kubectl get application first-vela-app -o yaml
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"core.oam.dev/v1beta1","kind":"Application","metadata":{"annotations":{},"name":"first-vela-app","namespace":"default"},"spec":{"components":[{"name":"express-server","properti …
```
=> fix: add "system-definition-namespace" flag to container args

pkg/appfile/helm/schema.go, pkg/appfile/helm/schema_test.go, pkg/appfile/helm/testdata/podinfo.values.schema.json, pkg/appfile/helm/testdata/values.yaml
to fix #1369 
The values file contains such a snippet that, an array type property embedss an array type property in its items list.
```yaml
...
hosts:
- host: chart-example.local
paths:
- path: /
...
```
=> fix generate schema for helm values

Makefile, apis/types/types.go, charts/vela-core/templates/admission-webhooks/job-patch/clusterrole.yaml, charts/vela-core/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/vela-core/values.yaml, design/vela-core/route.md, docs/en/developers/config-enviroments.md, hack/crd/update.go, pkg/utils/env/env.go, references/cli/up_test.go
remove cert-manager in CI, by default, the webhook is enabled  in chart, it will use `wonderflow/kube-webhook-certgen:v2.1` if cert-manager is not enabled.
Repo: https://github.com/wonderflow/kube-webhook-certgen
fix https://github.com/oam-dev/kubevela/issues/1361
=> fix kube-webhook-certgen to patch CRD conversation && remove cert-manager in CI e2e test && remove issuer create from CLI env

apis/core.oam.dev/v1alpha2/application_types.go, apis/core.oam.dev/v1alpha2/applicationrevision_types.go, apis/core.oam.dev/v1alpha2/approllout_types.go, apis/core.oam.dev/v1alpha2/componentdefinition_types.go, apis/core.oam.dev/v1alpha2/core_types.go, apis/core.oam.dev/v1beta1/appdeployment_types.go, apis/core.oam.dev/v1beta1/application_types.go, apis/core.oam.dev/v1beta1/applicationrevision_types.go, apis/core.oam.dev/v1beta1/approllout_types.go, apis/core.oam.dev/v1beta1/componentdefinition_types.go, apis/core.oam.dev/v1beta1/core_types.go, charts/vela-core/crds/core.oam.dev_appdeployments.yaml, charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml, charts/vela-core/crds/core.oam.dev_applications.yaml, charts/vela-core/crds/core.oam.dev_approllouts.yaml, charts/vela-core/crds/core.oam.dev_componentdefinitions.yaml, charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml, charts/vela-core/crds/core.oam.dev_workloaddefinitions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_appdeployments.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_approllouts.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_componentdefinitions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_workloaddefinitions.yaml, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_trait_test.go
fix https://github.com/oam-dev/kubevela/issues/1368
shortname: `apps`
```
kubectl get apps
NAME          COMPONENT   TYPE         PHASE     HEALTHY   STATUS          AGE
example-app   testsvc     webservice   running   true      status message  14h
```
shortname: `revisions`,`apprev`
shortname: `approllout`,`rollout`
```
kubectl get rollout
NAME              TARGET   UPGRADED   READY   BATCH-STATE   ROLLING-STATE    AGE
rolling-example   5        5          5       batchReady    rolloutSucceed   13h
```
shortname: `appdeploy`
shortname: `comp`
```
kubectl get comp
NAME         WORKLOAD-KIND   DESCRIPTION              AGE
webservice   Deployment      Describes a webservice   13h …
```
=> fix crd: add additional print column and short Name for CRD

docs/en/install.mdx
Install the client via brew should update brew itself firstly.
Linked: oam-dev/kubevela#1391
=> Fix: update homebrew before install kubevela client

pkg/dsl/definition/package.go, pkg/dsl/definition/package_suit_test.go, pkg/dsl/definition/package_test.go
split test cases for third party package
and,Fix the bug that will cause the wrong package check result
=> fix import inner package in the format of third party package path and split test cases

apis/core.oam.dev/common/types.go, apis/core.oam.dev/v1alpha2/core_types.go, apis/core.oam.dev/v1beta1/core_types.go, charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml, charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml, charts/vela-core/templates/defwithtemplate/ingress.yaml, charts/vela-core/templates/defwithtemplate/manualscale.yaml, docs/en/cue/patch-trait.md, docs/en/cue/trait.md, docs/en/platform-engineers/definition-and-templates.md, docs/examples/app-with-status/template.yaml, docs/examples/dry-run/definitions/myingress.yaml, docs/examples/helm-module/virtual-group-td.yaml, docs/examples/kube-module/virtual-group-td.yaml, docs/examples/registry/autoscale.yaml, docs/examples/registry/for-loop.yaml, docs/examples/registry/hpa.yaml, docs/examples/registry/initcontainer.yaml, docs/examples/registry/kautoscale.yaml, docs/examples/registry/node-affinity.yaml, docs/examples/registry/patch-replica.yaml, docs/examples/registry/rollout.yaml, docs/examples/registry/route.yaml, docs/examples/registry/sidecar.yaml, docs/examples/registry/virtualgroup.yaml, hack/vela-templates/definitions/ingress.yaml, hack/vela-templates/definitions/manualscale.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml, references/cli/traits.go
fix #1123
Now when we deploy/upgrade an Application, only change some fields of trait , we don't know whether the underlying pod will restart or not, we should let the TraitDefinition tell. So we add a podDisruptive field  to TraitDefinition.
=> add podDisruptive to traitdefinition

docs/en/platform-engineers/debug-test-cue.md, references/cli/cue_packages.go, references/cli/system.go
fix https://github.com/oam-dev/kubevela/issues/1404
use `vela system cue-packages` to show what are the inner packages supported in cluster
```
$ vela system cue-packages
Definition-Name                 Import-Path                                      Usage                                                      
#Event                          kube/events.k8s.io/v1beta1                      Kube Object for events.k8s.io/v1beta1.Event                                 
#Event                          k8s.io/events/v1beta1                           Kube Object for events.k8s.io/v1beta1.Event                                 
#RolloutTrait                   kube/standard.oam.dev/v1alpha1                  Kube Object for standard.oam.dev/v1alpha1.RolloutTrait                      
#PodSpecWorkload …
```
=> vela-cli support use "vela system cue-packages" to list cue-package

pkg/dsl/model/sets/operation_test.go, pkg/dsl/model/sets/utils.go, pkg/dsl/model/sets/walk_test.go
Fix the bug that strategyUnify not work with close call
=> Fix Bug: strategyUnify not work with close call

pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/apply_trait_test.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_suit_test.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller_test.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go, pkg/controller/utils/capability.go, pkg/controller/utils/capability_integrate_test.go, pkg/controller/utils/capability_suite_test.go, pkg/controller/utils/capability_test.go, pkg/controller/utils/utils.go, pkg/oam/discoverymapper/mapper.go, pkg/oam/util/helper.go
fix https://github.com/oam-dev/kubevela/issues/1387
refresh package discover when component/trait definition are registered.
=> Add package discover refresh when component/trait definition are registered

.github/workflows/timed-task.yml
fix https://github.com/oam-dev/kubevela/issues/1429 
add timed task, clean up dangling docker image
=> fix CI: Add clean-image action to clean up dangling docker image

Dockerfile, Makefile, entrypoint.sh
Brief changes:
1. Improve makefile
- Add `-s -w` in `LDFLAGS` to strip debug information and reduce release binary size
- In Mac, the binary size of the `vela` is reduced from `79M` to `67M`, and the binary size of the `manager` is reduced from `53M` to `43M`
- Define docker image name such as `VELA_IMAGE`, `VELA_CORE_IMAGE` and `VELA_CORE_TEST_IMAGE`
- Define go build env `GOBUILD_ENV`
2.  Improve dockerfile
- Replace base image `ubuntu:latest` with `alpine:latest`, since in many docker libraries, debian and alpine are more popular
- The docker image size of `vela-core` is reduced from `140M` to `51.1M`
3. Add entrypoint.sh to support entrypoint and debugging
- Solve #1177 better
- The following commands can be supported:
```
docker run -it --rm vela-core:latest manager -use-webhook …
```
=> Improve makefile and dockerfile

pkg/controller/utils/capability.go, pkg/dsl/definition/package.go, pkg/dsl/definition/package_suit_test.go, pkg/dsl/definition/package_test.go, pkg/dsl/definition/template.go
when `cue` build a `*build.Instance` which contains build-in Kube package, if other thread refresh the package discover,
It will lead to data race, Because the different thread will read or write the `Imports` field of build.Instance.
This PR is to fix this problem.
=> Fix bug: fix data-race of package discover

test/e2e-test/appcontext_test.go
fix flaky appContext  test ref:https://github.com/oam-dev/kubevela/pull/1445/checks?check_run_id=2303479561
requeue the appContext if it's status isn't right for long time
=> fix flaky appContext e2e-test

pkg/dsl/model/instance.go, pkg/dsl/model/instance_test.go
fix https://github.com/oam-dev/kubevela/issues/1439
when CUE Template in ComponentDefinition/TraitDefinition contains "\_\|\_" in value, KubeVela will mistakenly think that the Template is compiled incorrectly.
This PR fix the bug, use `_\|_[\s]//.*` to match compile error like:
```
_|_ // undefined field "#Deployment"
```
=> Fix bug: fix bug which Component/TraitDefinition won't work when contains "_|_" in value

go.mod, go.sum, pkg/builtin/build/build.go, pkg/builtin/kind/client.go, pkg/builtin/kind/client_test.go
Just use
```
err := kind.LoadDockerImage(image)
```
instead of
```
cmd := exec.Command("kind", "load", "docker-image", image)
```
Refer to https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/load/docker-image/docker-image.go
This closes #413 and closes #1457
The `docker` command will be resolved after `kind`
=> [Improvement-1457] Use kind cmd code to load docker image instead of local kind binary

references/cli/dryrun.go, references/cli/livediff.go
Extract public functions to allow other packages to call:
1.` DryRunApplication(cmdOption *DryRunCmdOptions, c common.Args, namespace string) (bytes.Buffer, error)`
2. `LiveDiffApplication(cmdOption *LiveDiffCmdOptions, c common.Args, namespace string) (bytes.Buffer, error)`
=> refactor vela-cli: refactor dry-run and live-diff 

.github/workflows/go.yml, pkg/builtin/build/build.go
Brief changes:
- Keep docker binary command due to the issue #416
- Remove the redundant `DOCKER_BUILDX_VERSION`
This closes #416, and closes #1233 (pr)
=> Keep docker binary command due to the issue #416

charts/vela-core/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
[failurePolicy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) should be `Fail` instead of `Fails`.
=> Fix helm install error when disable webhook patch

docs/en/end-user/explore.md, pkg/oam/discoverymapper/suit_test.go, test/e2e-test/rollout_plan_test.go
```
------------------------------
• Failure [0.197 seconds]
Mapper discovery resources
/home/runner/work/kubevela/kubevela/pkg/oam/discoverymapper/suit_test.go:82
discovery CRD [It]
/home/runner/work/kubevela/kubevela/pkg/oam/discoverymapper/suit_test.go:98
Expected
<[]schema.GroupVersionKind | len:1, cap:1>: [
{Group: "example.com", Version: "v1", Kind: "Foo"},
]
to equal
<[]schema.GroupVersionKind | len:2, cap:2>: [
{Group: "example.com", Version: "v1", Kind: "Foo"},
{Group: "example.com", Version: "v1beta1", Kind: "Foo"},
]
/home/runner/work/kubevela/kubevela/pkg/oam/discoverymapper/suit_test.go:170
------------------------------
STEP: Check built-in resource
STEP: CRD should be discovered after refresh
```
=> fix flaky test

apis/core.oam.dev/v1alpha2/componentdefinition_types.go, apis/core.oam.dev/v1alpha2/core_types.go, apis/core.oam.dev/v1beta1/componentdefinition_types.go, apis/core.oam.dev/v1beta1/core_types.go, charts/vela-core/crds/core.oam.dev_componentdefinitions.yaml, charts/vela-core/crds/core.oam.dev_traitdefinitions.yaml, charts/vela-core/crds/core.oam.dev_workloaddefinitions.yaml, docs/en/end-user/labels.md, legacy/charts/vela-core-legacy/crds/core.oam.dev_componentdefinitions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_traitdefinitions.yaml
Remove useless printcolumn field AGE from  Component/Trait/Workload Definition.
```shell
$ kubectl get trait -n vela-system
NAME          APPLIES-TO                DESCRIPTION
annotations   ["webservice","worker"]   Add annotations for your Workload.
cpuscaler     ["webservice","worker"]   configure k8s HPA with CPU metrics for Deployment
ingress       ["webservice","worker"]   Configures K8s ingress and service to enable web traffic for your service. Please use route trait in cap center for advanced usage.
labels        ["webservice","worker"]   Add labels for your Workload.
scaler        ["webservice","worker"]   Configures replicas for your service by patch replicas field.
sidecar       ["webservice","worker"]   inject a sidecar container into your app
```
```shell
$ kubectl get comp …
```
=> remove printcolumn AGE from Component/Trait/Workload Definition 

docs/en/end-user/cloud-resources.md, docs/en/platform-engineers/cloud-services.md
Split cloud service into two section, one for platform engineers,
and the other for end-users
=> Add cloud service docs for end-users

pkg/plugin/cli/cli.go, references/cli/help.go
output of kubectl-vela -h
```
$ kubectl vela -h
A Highly Extensible Platform Engine based on Kubernetes and Open Application Model.
Usage:
kubectl vela [flags]
kubectl vela [command]
Available Commands:
dry-run     Dry Run an application, and output the K8s resources as     
result to stdout, only CUE template supported for now       
live-diff   Dry-run an application, and do diff on a specific app       
revison. The provided capability definitions will be used   
during Dry-run. If any capabilities used in the app are not 
found in the provided ones, it will try to find from        
cluster.                                                    
show        Show the reference doc for a workload type or trait         
version     Prints out build version information …
```
=> fix cli: fix output of kubectl-vela -h

docs/en/advanced-install.md
fix #1529 
As I see, the legacy file of the `applicationdeployments.core.oam.dev` has removed at this pr: #1166.
So I just removed a line of the doc.
=> Clean the docs of the applicationdeployments.core.oam.dev

apis/types/types.go, e2e/application/application_test.go, e2e/commonContext.go, e2e/env/env_test.go, e2e/trait/trait_test.go, e2e/workload/workload_test.go, references/cli/show.go, references/plugins/cluster.go
If env is default, and capabilities are located in
vela-system, it will continue to retrieve the capability in
vela-system directory.
Fix #1520
=> Enable "vela show" to support namespaced capability

.github/ISSUE_TEMPLATE/config.yaml, .github/ISSUE_TEMPLATE/config.yml
It will help direct developers to our recommended `Discussions` when trying to create a Question issue by `Issues --> new issue`.
=> Redirect to Discussions if users want to open Question issue

docs/en/install.mdx
The copied command that starts with `$` will not execute correctly.
This PR removes the command prompt to support fast copy/paste.
=> docs: remove the command prompt to support fast copy/paste

apis/types/capability.go, e2e/plugin/plugin_suit_test.go, e2e/plugin/plugin_test.go, hack/references/generate.go, references/cli/show.go, references/plugins/cluster.go, references/plugins/cluster_test.go, references/plugins/reference_test.go, references/plugins/references.go
fix https://github.com/oam-dev/kubevela/issues/1394
vela show now support list the parameter of ComponentDefinition which use helm charts as workload. 
When a new ComponentDefinition use helm charts is registered,  the ComponentDefinition controller will parse
the values.yaml in charts and store as openapi into configMap. (refer to https://github.com/oam-dev/kubevela/pull/1250)
vela show will get the openapi data in configMap, and list the parameters to the terminal.
take [webapp-chart](https://github.com/oam-dev/kubevela/blob/master/docs/examples/helm-module/webapp-chart-cd.yaml) as an example.
``` 
$ vela show webapp-chart
+----------------+-------------------------------------------+-----------------------------------+----------+---------+
|      NAME      |                DESCRIPTION …
```
=> fix cli: vela show support list the parameter of ComponentDefinition which use helm charts

pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componetrevision_test.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitrevision_test.go, pkg/oam/util/helper.go
When definitionRevision is not a new Revision, the controller still need to trigger the GC mechanism, This will fix failed cases in unit-tests.
=> fix bug: enable gc when definitionRevision is not a new revision

charts/vela-core/templates/defwithtemplate/sidecar.yaml, hack/vela-templates/cue/sidecar.cue
Deploying error with https://kubevela.io/zh/docs/application#step-2-design-and-deploy-application , error message:
```
evaluate template trait=sidecar app=frontend: invalid patch trait sidecar into workload: compile patch file: spec.template.spec.containers.0.command: reference \"parameter\" not found
```
This PR is referenced from https://github.com/oam-dev/kubevela/pull/1067/files
=> Check whether parameter.cmd is nill for sidecar trait

pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
When "metav1.Time" type "DeletionTimestamp" variable is nil, it cloud
not be printed while "fmt.Printf("%+v")" **in debug mod**
Fix #1578
=> Fix "nil pointer" issue in UT

.github/workflows/release.yml, .krew.yaml, docs/en/end-user/kubectlplugin.mdx
[kubectl vela krew plugin manifests](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/vela.yaml) has been merged into krew-index, and it is now possible to install kubectl vela via krew, now with the addition of an automatic release action that will automatically push each subsequent release to krew.
=> Add krew auto release and docs

cmd/core/main.go, pkg/dsl/definition/package.go
Refer to https://github.com/oam-dev/kubevela/issues/1313 , the format error of third-party CRD will lead to vela-controller exited. In this case, we need to keep the vela-controller run normally.
=> fix controller: fix the bug which the controller cannot start due to the format error of the third-party CRD 

references/cli/show.go, references/plugins/cluster.go
As we don't need to sync the defintiion .yaml and .cue to local and
then extract it, besides, there is a simliar function "SyncDefinitionsToLocal"
just besides it, rename function "SyncDefinitionToLocal" in order
not to cause confustions
=> Renaming the name of function "SyncDefinitionToLocal"

charts/vela-core/templates/admission-webhooks/validatingWebhookConfiguration.yaml, e2e/apiserver/apiserver_test.go, pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler.go, test/e2e-test/definition_revision_test.go
enable dynamic admission control for Application,  the admissionWebhooks will check the correctness of the fields in Application.
=> Enable Dynamic Admission Control for Application

pkg/controller/common/rollout/workloads/common.go, pkg/controller/common/rollout/workloads/common_test.go, pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler_test.go, pkg/webhook/core.oam.dev/v1alpha2/application/validation.go, test/e2e-test/application_test.go, test/e2e-test/testdata/app/app6.yaml
fix #1631
1.add validation webhook to verify `rolloutBatches` must not be empty
2.guarantee empty `rolloutBatches` couldn't crash whole controller even though disable webhook
=> fix empty rolloutBatch will panic whole controller bug

e2e/plugin/plugin_test.go, pkg/dsl/definition/template.go, pkg/dsl/definition/template_test.go, test/e2e-test/definition_revision_test.go
fix https://github.com/oam-dev/kubevela/issues/1595
The previous logic will not report an error for the following wrong `Application`, and will render incomplete workload which does not contain `env`.
```yaml
metadata:
name: myapp
spec:
components:
- name: mycomp
properties:
image: nginx:latest
port: 8080
env:
- name: SHOULD_BE_STRING_1
value: "I'm string"
- name: SHOULD_BE_STRING_2
value: 1234 # <=== webservice CUE template requires string type here
```
After fixing the bug, controller will provide a more detailed error logs.
```
{"level":"error","ts":1620785291.581014,"logger":
"Application","msg":"[Handle GenerateApplicationConfiguration]","application":"default/myapp",
"error":"evaluate base template app=myapp in …
```
=> fix bug: Use stricter syntax check for CUE

charts/vela-core/templates/admission-webhooks/mutatingWebhookConfiguration.yaml, charts/vela-core/templates/admission-webhooks/validatingWebhookConfiguration.yaml, e2e/cli.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/handler.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/utils/utils.go, pkg/oam/util/helper.go, pkg/oam/util/helper_test.go, pkg/webhook/core.oam.dev/register.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/mutating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/validating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/validating_handler_test.go, test/e2e-test/definition_revision_test.go, test/e2e-test/definition_test.go
fix https://github.com/oam-dev/kubevela/issues/1473, align with https://github.com/oam-dev/kubevela/issues/1563
Add dynamic admission control for ComponentDefinition.
**MutatingWebhook**
`MutatingWebhook` will generate WorkloadDefinition based on the `Spec.Workload.Definition` field(if workloaddefinition does not exist), and fill in the `Spec.Workload.Type` field to point to the created workloaddefinition.
``` yaml
kind: ComponentDefinition
metadata:
name: worker
namespace: default
spec:
workload:
definition:
apiVersion: apps/v1
kind: Deployment
schematic:
cue:
template: |
....
```
After being processed by `MutatingWebhook`
``` yaml
kind: ComponentDefinition
metadata:
name: worker
namespace: default
spec:
workload: …
```
=> Add Dynamic Admission Control for ComponentDefinition

CONTRIBUTING.md
case offical doc only show v3 installation, add the v2 installation here.
[kubebuilder quick start, install](https://book.kubebuilder.io/quick-start.html#installation)
[discussion](https://github.com/oam-dev/kubevela/discussions/1672)
=> add kubebuilder prerequisites in contributing.md

pkg/controller/utils/capability.go, pkg/controller/utils/capability_test.go, pkg/controller/utils/testdata/definition/workload1.cue, pkg/controller/utils/testdata/definition/workloadNoParameter.cue
fix https://github.com/oam-dev/kubevela/issues/1684
fix bug, when apply a definition which parameter is a non-structure type, controller will fail to store the configMap,like:
```yaml
kind: TraitDefinition
metadata:
annotations:
definition.oam.dev/description: "Add annotations for your Workload."
name: annotations
spec:
appliesToWorkloads:
- webservice
- worker
schematic:
cue:
template: |-
patch: {
spec: template: metadata: annotations: {
for k, v in parameter {
"\(k)": v
}
}
}
parameter: [string]: string
```
and if `parameter: [string]: string` start with space or tab it also fail to store configMap.
```yaml
kind: TraitDefinition
metadata:
annotations:
definition.oam.dev/description: "add vpc-id for ingress trait"
name: …
```
=> fix bug: store parameter to configMap for definition which parameter is a non-structure type

pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/utils/capability.go, pkg/controller/utils/capability_integrate_test.go, test/e2e-test/definition_revision_test.go
Refactor the way of get Open-API-Schema in trait/component definition controller.
Previously, the Definition would be got twice in the controller.  
1. this PR refactor function `GetOpenAPISchema`, only get the Definition once.
2. fix some unstable e2e-tests
=> refactor the way of get OpenAPISchema in trait/component definition controller

apis/types/types.go, charts/vela-core/templates/definitions/autodetect.yaml, pkg/appfile/appfile.go, pkg/appfile/appfile_test.go, pkg/appfile/template.go, pkg/appfile/template_test.go, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/mutating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/validating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/validating_handler_test.go, test/e2e-test/definition_test.go, test/e2e-test/helm_app_test.go
refer to https://github.com/oam-dev/kubevela/pull/1680#discussion_r634808401
The validating logic of the componentdeifnition webhook will reject if the componentDefinition doesn't refer to a workload.
Now we will set a default workloaddefinition `autodetect.core.oam.dev` for the componentDefinition.
=> fix webhook: set a default workload.type for componentdefinition which doesn't refer to a workload

charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml
```
2021-05-26T15:36:24.326+0800    DEBUG   kubevela        Cannot apply workload   {"controller": "oam/applicationcontext.core.oam.dev", "uid": "0daa7c7f-93fa-4b79-b445-21bf857b5816", "version": "", "error": "cannot apply trait \"apps/v1\" \"StatefulSet\" \"redis-replicas\": cannot create object: StatefulSet.apps \"redis-replicas\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/component\":\"replica\", \"app.kubernetes.io/name\":\"redis-dev\"}: `selector` does not match template `labels`", "errorVerbose": "StatefulSet.apps \"redis-replicas\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/component\":\"replica\", \"app.kubernetes.io/name\":\"redis-dev\"}: `selector` does not match template …
```
=> add chart debug value

docs/en/advanced-install.mdx, docs/en/developers/references/kubectl-plugin.mdx, docs/en/end-user/components/more.md, docs/en/end-user/traits/more.md, docs/en/install.mdx, docs/sidebars.js, pkg/plugin/cli/trait.go
To fix #1721 
1. add `Kubectl plugin` in sidebar under the `References`.
2. mention the installation about kubectl plugin in `Other Install Topics`
3. fix some outdate docs
=> arrange docs for kubectl plugin，fix #1721

e2e/plugin/plugin_test.go, references/plugins/references.go
###New
Only fix map type parameter (the resolution for cue parameter need to be struct kind ), for  single string , int and bool type  we need to fix in  pkg/cue/convert.go  and add  non-struct kind logic.
We should declare the parameter name and ”+usage"  in cue template
fix #1618 
the resolution for cue template in function GetCUEParameterValue has no problem
example for two parameter declare and resolution：
=> fix show annotations

charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml, cmd/core/main.go, pkg/controller/common/logs.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_finalizer_test.go, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go, pkg/controller/core.oam.dev/v1alpha2/application/revision.go, pkg/controller/core.oam.dev/v1alpha2/application/revision_clean_up_test.go, pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go, pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/component.go, pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/utils/utils.go, pkg/controller/utils/utils_test.go, pkg/oam/util/helper.go, pkg/oam/util/helper_test.go, pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/mutating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/applicationrollout/mutating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/component/mutating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/component/validating_handler.go, pkg/webhook/standard.oam.dev/v1alpha1/podspecworkload/mutating_handler.go, pkg/webhook/standard.oam.dev/v1alpha1/podspecworkload/validating_handler.go
refer to https://github.com/oam-dev/kubevela/issues/378
using klog/v2 as log system which can print out the file and line numbers
1. Remove string formatting from log message. refer to [Migration Instructions-**Remove string formatting from log message**](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message)
1. improve messages to comply with good practices:
* Start from a capital letter.
* Do not end the message with a period.
* Use active voice. Use complete sentences when there is an acting subject ("A could not do B") or omit the subject if
the subject would be the program itself ("Could not do B").
* Use past tense ("Could not delete B" instead of "Cannot delete B")
* …
=> Improve the logging system

charts/vela-core/templates/defwithtemplate/task.yaml, charts/vela-core/templates/defwithtemplate/webservice.yaml, charts/vela-core/templates/defwithtemplate/worker.yaml, docs/examples/app-with-probe/README.md, docs/examples/app-with-probe/app-with-probe.yaml, e2e/application/application_test.go, vela-templates/internal/cue/task.cue, vela-templates/internal/cue/webservice.cue, vela-templates/internal/cue/worker.cue
1. I add just probe and memory limit.
2. make all internal component definition contain below alternative paramter: `cmd`,`env`,`cpu`,`memory`,`volumns`,`livenessProbe`,`readinessProbe`.
3. organize paramater's order to make code clean.
4. add docs/example for probe usage.
Now, I tried with application config below and it worked great.
```yaml
metadata:
name: website
spec:
components:
- name: frontend
properties:
image: oamdev/testapp:v1
cmd: ["node", "server.js"]
port: 8080
cpu: "0.1"
memory: "100M"
livenessProbe: 
httpGet: 
path: /
port: 8080
readinessProbe: 
httpGet: 
path: /
port: 8080
httpHeaders:
- name: aName
value: bValue
```
And pod will be like
```yaml
$ k describe pod frontend-86bc89d8f5-rjljp
Name: …
```
=> Add more optional paramters to built-in component

pkg/controller/core.oam.dev/v1alpha2/application/assemble/assemble.go, pkg/controller/core.oam.dev/v1alpha2/application/assemble/options.go, pkg/controller/core.oam.dev/v1alpha2/application/assemble/options_test.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/name.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/name_test.go, pkg/oam/labels.go
separated from #1763 
assemble pkg:
- make sure the order of resources in the assembled result is same as defined in application
- fix helmDiscovery workload option bug (assembled workload only need a name but not all spec of helm-created workload)
dispatch pkg:
- add labels(appName + namespace) to resource tracker in order to list resource trackers of a specific app
- make dispatch/applyAndRecord to incrementally record applied resources
- scenario:  an app revision outcome 1 workload + 2 traits,  caller can dispatch the workload without traits first, until a specific condition is reached, caller then call dispatch again to dispatch traits. The resource tracker should track workload and traits.
- add exported functions about naming resource tracker in dispatch pkg
- refine and add more …
=> refine assemble and dispatch

CONTRIBUTING.md, pkg/controller/common/rollout/rollout_webhook.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
https://github.com/oam-dev/kubevela/pull/1735 and https://github.com/oam-dev/kubevela/pull/1758 refactored vela's log system using `klog`.  In order to unify the log style, we refer to these guides:[Logging Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md), [Structured Logging Guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#structured-logging-in-kubernetes) and sum up a few basic conventions.
=> Add Logging Convention in CONTRIBUTING.md

cmd/core/main.go
Now debug-level logs don't appear when vela-core is started with `log-debug=true`.
`flag.Parse` must be called before using variable `logDebug` to determine whether to set the verbosity, or `logDebug ` will always be false.
=> Fix invalid `log-debug` flag

docs/en/end-user/scopes/advanced-rollout.md
This PR fixes a typo: `Use` -> `User`.
=> Fix a  typo

charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml, cmd/core/main.go, design/api/vela-controller-params-reference.md, pkg/controller/core.oam.dev/oamruntime_controller.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/mutating_handler.go
You can use the option `autoGenWorkloadDefinition` to choose whether to automatically create `WorkloadDefinition` which `ComponentDefinition` refers to. 
The default value of `autoGenWorkloadDefinition` is `true`, which means the webhook will automatically create `WorkloadDefinition`  which `ComponentDefinition` refers to , if the `WorkloadDefinition` doesn't exist.
You can set the `autoGenWorkloadDefinition` to `false` to disable this feature.
=> add the option to choose whether to automatically generated workloaddef which componentdef refers to

pkg/controller/common/types.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationdeployment/applicationdeployment_controller.go, pkg/controller/core.oam.dev/v1alpha2/setup.go, pkg/controller/setup.go, pkg/controller/utils/utils.go, pkg/controller/utils/utils_test.go
This PR let application controller can be disabled by `--disable-caps=all`, so 0.3.x can be exist only for AppConfig and Component case.
And it remove the applicationdeployment controller.
=> add application  controller to caps which can be disabled and remove appdeployment

pkg/controller/common/rollout/rollout_plan_controller.go, pkg/controller/common/rollout/workloads/cloneset_rollout_integration_test.go, pkg/controller/common/rollout/workloads/cloneset_scale_integration_test.go, pkg/controller/common/rollout/workloads/deployment_rollout_controller.go, pkg/controller/common/rollout/workloads/deployment_rollout_integration_test.go, pkg/controller/common/rollout/workloads/deployment_scale_integration_test.go
This PR renames `NewDeploymentController` to `NewDeploymentRolloutController`.
=> Rename deployment-rollout-controller constructor

charts/vela-core/templates/defwithtemplate/labels.yaml, vela-templates/internal/definitions/labels.yaml
The label of traits will update `spec.template.metadata.labels`, which will trigger pod rebuild. But in the default template, podDisruptive=true is not declared, which will cause misunderstandings by users.
Fixes #
=> [FIX]incorrect pod-disruptive defalut configuration in label of traits

charts/vela-core/templates/defwithtemplate/sidecar.yaml, vela-templates/internal/definitions/sidecar.yaml
The label of traits will update spec.template.spec.containers, which will trigger pod rebuild. But in the default template, podDisruptive=true is not declared, which will cause misunderstandings by users.
Fixes #
=>  FIX incorrect pod-disruptive defalut configuration in sidecar of traits

pkg/appfile/appfile.go, pkg/appfile/appfile_test.go, pkg/appfile/parser.go, pkg/appfile/parser_test.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
add `insertSecretTo` feature in TraitDefinition Template, so that application can consumer cloud resource in `trait`.
=> TraitDefinition support use insertSecretTo in template to consumer cloud resource

pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/assemble/options.go, pkg/controller/core.oam.dev/v1alpha2/application/assemble/options_test.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/rollout_handler.go, test/e2e-test/app_embed_rollout_test.go
1.fix rolloutplan that do not limit only one component but the rollout only support one component. Make apply workload option works only for the target component
2.do not block other component to render if they're not rollout target
3.remove redundant step templateSourceManifest, it want's to apply the new resource with older ownerID and fails the update.
=> dont't template source in rollout and rollout first component

docs/examples/cloneset-rollout/appRollout-scale.yaml, docs/examples/deployment-rollout/app-rollout-scale.yaml, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/helper_suit_test.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/rollout_handler.go, pkg/controller/utils/utils.go, test/e2e-test/rollout_plan_test.go
Before, we don't override initial `replicas`  of workload. So when first scale, user must be aware of total `rolloutBatches+1=targetSize`.
This pr will override initial replicas of workload.So in first scale operation total `rolloutBatches=targetSize` is fine.
eg.
```yaml
kind: AppRollout
metadata:
name: rollout
spec:
targetAppRevisionName: rollout-v1
componentList:
- metrics-provider
rolloutPlan:
rolloutStrategy: "IncreaseFirst"
rolloutBatches:
- replicas: 2
targetSize: 2
```
1. override initial replicas of wokrload
2. reorder rollout phase  `prepare workload`->`determineCommonComponent`->`generate assemble manifest`
`generate assemble manifest` phase must know which is the common component between source and target …
=> override initial replicas of workload in first scale operation

vela-templates/gen_definitions.sh
This script is piping to `rm`, a command that doesn't read from stdin.
=> Fix the way to ignore errors for rm command

charts/vela-core/templates/addons/kruise.yaml, vela-templates/addons/auto-gen/kruise.yaml, vela-templates/addons/kruise/resource/kruise-rel.yaml, vela-templates/addons/kruise/resource/kruise-repo.yaml, vela-templates/addons/kruise/template.yaml
Add open-kruise as addon
run addon list after chart deployed:
```shell
$ bin/vela addon list            
NAME                    DESCRIPTION                                                                     STATUS     
fluxcd                  Flux is a set of continuous and progressive delivery solutions for Kubernetes   uninstalled  
kruise                  Kruise is a Kubernetes extended suite for application automations               uninstalled
ocm-cluster-manager     ocm-cluster-manager can deploy an OCM hub cluster environment.                  uninstalled
```
part-fix https://github.com/oam-dev/kubevela/issues/1760
=> Add open-kruise as addon

pkg/cue/model/sets/operation.go, pkg/cue/model/sets/operation_test.go
Let `patchKey` can specify the field of the substructure of the array element, in a format such as `x.y`
for example, base object as follow:
```
envFrom: [{
secretRef: {
name:  "my-secret-1"
}
}]
```
and, patcher is as follows:
```
// patchKey=secretRef.name
envFrom: [{
secretRef: {
name:  "my-secret-2"
}
}]
```
then, the result will be as follow after strategy merge:
```
// +patchKey=secretRef.name
envFrom: [{
secretRef: {
name: "my-secret-1"
}
}, {
secretRef: {
name: "my-secret-2"
}
}, ...]
```
fixes #1913
=> Strategy Merge: `patchKey` can specify the field of the substructure of the array element

charts/vela-core/templates/admission-webhooks/validatingWebhookConfiguration.yaml, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go, pkg/controller/core.oam.dev/v1alpha2/initializer/initializer_controller.go, pkg/controller/utils/utils.go, pkg/oam/util/helper.go, pkg/webhook/core.oam.dev/v1alpha2/initializer/validating_handler.go, references/cli/addon.go, test/e2e-test/initializer_test.go
Initializer:
1. When installing dependent initializer ,controller won't update status as `CheckingDepends` ,fix that
2. After initializer patch status, reconcile return an error, that will requeue the request twice, fix that.
3. Add delete webhook, forbid deletion of initializer that are depended by other initializer. Add test for that.
vela CLI:
1. enable: continually show initializer status
2. disable: remove deleting ns logic(all init are now in vela-system namespace)
=> Fix Initializer bugs & Enhance addon command 

pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_finalizer_test.go
**Prblem**:
App controller uses finalizer to garbage collect resource tracker according to its status latest revision.
If an error occurs in the middle of dispatching(applying) resources, even resource tracker is created but app status cannot record its revision as the latest revision. Thus, if we delete the application now, app controller cannot GC this resource tracker.
**Solution**:
During GC, list all resource trackers related to this application and delete them.
=> fix app finalizer bug

docs/examples/workflow/app.yaml, docs/examples/workflow/definition.yaml, pkg/stdlib/op.go, pkg/workflow/context/context.go, pkg/workflow/context/context_test.go, pkg/workflow/providers/kube/handle.go, pkg/workflow/providers/kube/handle_test.go, pkg/workflow/tasks/custom/task.go, pkg/workflow/tasks/custom/task_test.go, pkg/workflow/types/types.go, pkg/workflow/workflow.go, pkg/workflow/workflow_test.go
1. Optimize output mechanism
The content in the WorkflowStep can be output flexibly through the task step name
```
// workflowStep
...
myIP:  apply.status.podIP
---
// application.yaml
properties:
...
outputs: 
- name: serverIP
exportKey: myIp
```
2. Inject app's metadata for StepDefinition
You can use `context` to reference application metadata, as below
```
apply: op.#Apply & {
...
metadata: namespace: context.namespace
}
```
=> Optimize Workflow

go.mod, references/a/preimport/preimport.go, references/cmd/cli/main.go
The vela CLI tools prints "getCPUInfo" error for `darwin/arm64` architecture which confuses Mac M1 users. Besides, the "throttling request" message logged during the import process is not necessary for the CLI tool. This PR suppress these two loggings during the init stage. The logging is recovered when the import process is over and the CLI starts to execute. 
Fixes [#1924](https://github.com/oam-dev/kubevela/issues/1924)
The solution is to suppress loggings from `containerd` lib for "getCPUInfo" log and `klog` for "throttling request" in client-go. The `klog` logging is brought back when the CLI command starts execution.
=> suppress dirty logs during import libraries

pkg/controller/common/rollout/workloads/deployment_rollout_controller.go, pkg/controller/common/rollout/workloads/deployment_rollout_integration_test.go
This is a mis-match, and we don't find out it because the controller-runtime don't override data when the value is empty.
=> fix rollout test

pkg/controller/core.oam.dev/v1alpha2/appdeployment/suite_test.go, test/e2e-test/rollout_plan_test.go
Signed-off-by: Yue Wang <seiwy2010@gmail.com>
fix tests that may fail after upgrading to k8s 1.21, related to #1985
=> quick fix tests

charts/vela-core/templates/defwithtemplate/webservice.yaml, e2e/plugin/plugin_test.go, pkg/cue/testdata/workloads/webservice.cue, test/e2e-test/definition_revision_test.go, vela-templates/internal/cue/webservice.cue
Fix #1981
Signed-off-by: Xiaoxi He <tossmilestone@gmail.com>
=> Fix addRevisionLabel to selector

pkg/controller/common/context.go, pkg/controller/core.oam.dev/v1alpha2/appdeployment/appdeployment_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go, pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go, pkg/controller/core.oam.dev/v1alpha2/applicationrollout/applicationrollout_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller.go, pkg/controller/core.oam.dev/v1alpha2/envbinding/envbinding_controller.go, pkg/controller/core.oam.dev/v1alpha2/initializer/initializer_controller.go, pkg/controller/standard.oam.dev/v1alpha1/podspecworkload/podspecworkload_controller.go, pkg/controller/standard.oam.dev/v1alpha1/rollout/rollout_controller.go
Currently, not all controllers have a timeout during reconciling which may lead to long time reconciling blocking the controller.
Fixes [#1982](https://github.com/oam-dev/kubevela/issues/1982)
This solution is simply unifying the timeout settings for all controllers. We might need to abstract the common parts of reconcilers (not only the timeout setting) in later works.
=> add timeout context for controllers

pkg/controller/core.oam.dev/v1alpha2/appdeployment/appdeployment_controller.go
Signed-off-by: shaowenchen mail@chenshaowen.com
What this PR does / why we need it:
It raises an error Failed to reconcile appDeployment default/cross-cluster-app: cannot get object: an empty namespace may not be set when a resource name is provided when I test case refers to https://kubevela.io/docs/v1.1/end-user/scopes/appdeploy/#appdeployment
=> bugfix: workload namespace is empty while sync appdeployment

pkg/cue/model/value/value.go, pkg/cue/model/value/value_test.go, pkg/stdlib/op.go, pkg/workflow/tasks/custom/task.go, pkg/workflow/tasks/custom/task_test.go
1. Set the taskStep execution order by tag.
2. Automatically generate order tags for workflowStep definition 
```
#ApplyComponent: #Steps & {
component: string
_componentName: component
load: ws.#Load & {
component: _componentName
} @step(1)
workload: workload__.value
workload__: kube.#Apply & {
value: load.value.workload
...
} @step(2)
}
```
=> Order Steps by Field Tag

design/vela-cli/def.md, design/vela-cli/def_zh.md, references/common/definition.go
Previous `vela def init` generate definition templates with wrong variable `parameters` instead of `parameter`. This PR fixes it.
=> fix def init bug

pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componetrevision_test.go, pkg/controller/core.oam.dev/v1alpha2/core/policies/policydefinition/policydefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/revison.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitrevision_test.go, pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go, pkg/oam/labels.go, pkg/oam/util/helper.go, pkg/oam/util/helper_test.go, pkg/webhook/core.oam.dev/v1alpha2/componentdefinition/validating_handler.go, pkg/webhook/core.oam.dev/v1alpha2/traitdefinition/validating_handler.go, pkg/webhook/utils/utils.go, test/e2e-test/definition_revision_test.go, test/e2e-test/definition_test.go
Everytime you update the spec of deifnitions, KubeVela will automatic generated definitionRevision with name in
in the format of `definitionName@revisionNum`.  
Now, this PR supports you specify the revision name in annotation `definitionrevision.oam.dev/name`
```yaml
#worker.yaml
kind: ComponentDefinition
metadata:
name: worker
namespace: vela-system
annotations:
definition.oam.dev/description: "Describes long-running, scalable, containerized services that running at backend. They do NOT have network endpoint to receive external network traffic."
definitionrevision.oam.dev/name: "1.1.3"
spec:
workload:
definition:
apiVersion: apps/v1
kind: Deployment
schematic:
cue:
template: |
output: {
apiVersion: "apps/v1"
kind: …
```
=> definitions support specify the revision name

pkg/utils/common/common.go, pkg/utils/common/common_test.go
As discussed in #1939, the reason for the error reported in TraitController and ComponentController is due to a failure encountered while generating OpenAPI v3 schema. The real reason behind it is because we want only `parameter` field in template to generate schema, as mentioned in [#1773](https://github.com/oam-dev/kubevela/issues/1773) and fixed by [#1970](https://github.com/oam-dev/kubevela/pull/1790). 
To realize that, #1790 uses `inst.LookupDef` to extract `cue.Value` of field `parameter`, converting it into cue string, and then transforming it back to `cue.Instance`, which is needed for generating OpenAPI schema. Due to the improper implementation in cue v0.2.2 which we use, when getting `ast.Node` from `cue.Instance`, the IfClause and some …
=> fix definition controller log error cause by openapi schema generation error

Makefile, charts/vela-core/templates/defwithtemplate/ingress-1-20.yaml, charts/vela-core/templates/defwithtemplate/ingress.yaml, charts/vela-core/templates/defwithtemplate/rollout.yaml, charts/vela-core/templates/defwithtemplate/service-binding.yaml, charts/vela-core/templates/defwithtemplate/task.yaml, charts/vela-core/templates/defwithtemplate/volumes.yaml, charts/vela-core/templates/defwithtemplate/webservice.yaml, charts/vela-core/templates/defwithtemplate/worker.yaml, references/cli/def.go, references/cli/def_test.go, references/common/definition.go, references/common/definition_test.go, vela-templates/registry/auto-gen/kustomize.yaml
Previous `vela def` do not support internal package import such as `vela/op` or `kube/v1`. This PR enables it.
Fixes #2068
Notice that to support internal package use, users need to have connections with Kubernetes api-server, as the OpenAPI Schema is required. While no Kubernetes cluster is connected, the vela def will not support using internal package.
=> enable vela def to use import decl

.github/workflows/registry.yml
Rename the latest master chart name to x.y.z-nighty-build
Currently, the latest chart name is like `x.y.z-rc-master` conflicts with our release-candidate chart name. So we rename the chart.
Fixes #
=> Refine the latest chart name build on master branch

charts/vela-core/templates/addons/observability.yaml, vela-templates/addons/auto-gen/observability.yaml, vela-templates/addons/observability/template.yaml
As it's difficult to pull gcr.io iamge, so replace the image
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.0 to the one
hosted in dockerhub.io
Fixes #
=> Replace gcr.io image in chart kube-metrics-server

.github/workflows/registry.yml
ref to https://github.com/docker/buildx/issues/327
same case: https://github.com/jetstack/jetstack-secure/pull/227
=> fix(CI): use buildkit as docker build engine to avoid 401 unauthorized

pkg/cue/model/sets/utils.go, pkg/cue/model/sets/utils_test.go, pkg/cue/model/value/value.go, pkg/cue/model/value/value_test.go, pkg/workflow/tasks/custom/task.go, pkg/workflow/tasks/custom/task_test.go, pkg/workflow/tasks/discover.go
1.  Use case of `script` as follow: 
```
---def---
parameter: {
successChecker: string
}
// resource status
status: {phase: string}
op.#ConditionalWait & {
continue: script(parameter.successChecker)
}
---step---
workflow:
steps:
- name: "apply"
properties:
successChecker: status.phase=="ready"
```
2. Use case of `outputs` exportKey  as follow:
```
---def---
apply: op.#Apply & {
value: {
kind: "Service"
}
}
---step---
workflow:
steps:
- name: "apply"
outputs:
- exportKey: "apply.value.spec.ClusterIP"
name: "clusterIP"
```
=> Make the WorkflowStepDefinition to be Universal

references/plugins/cluster.go, references/plugins/cluster_test.go, references/plugins/testdata/helm.yaml
this PR fix bug which vela show will not show the parameters of componentDefinition, when componetdefinition's workload type is AutoDetectWorkloadDefinition.
Fixes https://github.com/oam-dev/kubevela/issues/2034
=> fix(cli) fix bug when vela show componetdefinition's workload type is AutoDetectWorkloadDefinition

.github/CODEOWNERS
Use github ownerfiles mechanism for code review. https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#example-of-a-codeowners-file
A code owner must have the write permission for the repo.
=> initilize KubeVela codeowner file

references/cli/cli.go, references/cli/cue_packages.go, references/cli/dryrun.go, references/cli/livediff.go, references/cli/system.go
We already have `live-diff` and `dry-run` command in `vela system`, now we add it into `vela` commands, then users can use it by:
```
vela live-diff ...
vela dry-run ...
vela cue-packages ...
```
=> Feat: add vela live-diff, dry-run, cue-packages into vela commands

apis/types/capability.go, apis/types/types.go, charts/vela-core/templates/definitions/terraform-alibaba-ack.yaml, charts/vela-core/templates/definitions/terraform-alibaba-oss.yaml, charts/vela-core/templates/definitions/terraform-alibaba-rds.yaml, e2e/workload/workload_test.go, references/cli/capability.go, references/cli/components.go, references/cli/traits.go, references/common/capability.go, references/common/capability_test.go, references/plugins/capcenter.go, references/plugins/cluster.go, references/plugins/cluster_test.go
Added flag `--flag` to filter when executing `vela componnets` and
`vela traits`
Fix https://github.com/oam-dev/kubevela.io/pull/222#discussion_r699214816
Fixes #
=> Fix: add flag `--label` to filer components and traits

references/plugins/reference_test.go, references/plugins/references.go
Lower two levels of the title of workloads/traits docs to adapt to
Kubevela.io
Fixes #
=> Lower title level to make definition docs generation adapt to kubevela.io

README.md
Docs: Fix 2 broken links in README
it fixes 2 broken links of of the 3 links in the README section "Getting started"
Clicking on the links "Installation" or "Design your first Deployment Plan" causes a 404 page not found
Fixes #
- Replaced with working links.
=> Docs: Updated broken Getting Started links in README

pkg/cue/model/sets/operation.go, pkg/cue/model/sets/operation_test.go
Fix https://github.com/oam-dev/kubevela/issues/2144
This will enable users to patch any keys, not just list. For example, patch metadata.name, or even kind.
@tatianguiqu @kinsolee
=> Fix (CUE): patch any key using `retainKeys` strategy

charts/vela-core/templates/definitions/terraform-alibaba-rds.yaml
Enable users to set `db_instance_storage_type`. This can fix the issue
happended since Sept. 14, 2021.
{"Code":"InvalidNetworkTypeClassicWhenCloudStorage","HostId":
"rds.aliyuncs.com","Message":"The Specified InstanceNetworkType
value Classic is not valid when choose cloud storage type."
Fixes #
=> Fix: fix alibaba cloud rds module

charts/vela-core/values.yaml
Previously, using `latest` tag for cluster-gateway will be automatically set to the tag of chart when release pipeline is triggered by [Github Action](https://github.com/oam-dev/kubevela/blob/8407c0bf4d01db70f580910c03c7792c2dd6798c/.github/workflows/release.yml#L29). This binds the KubeVela version to cluster-gateway.
Currently, as a quick fix, we retag the cluster-gateway:latest to cluster-gateway:v1.1.1. But in long term, they should be decoupled.  
Fixes #
Related to https://github.com/oam-dev/cluster-gateway/issues/4
=> Fix: fix cluster-gateway image tag in chart

hack/appfile/test.sh, references/apiserver/appHandlers.go, references/common/application.go
When using `vela up`, data will be write into a file at `.vela/deploy.yaml`. If creating another application, it will be overwrite. That's useless and confusing for users.\
Fixes #
=> Chore(cli): remove useless deploy.yaml

.github/workflows/e2e-rollout-test.yml
Remove `make e2e-api-test` in e2e-rollout-test, which are tested in e2e-test. e2e-rollout-test are always the slowest, this can speed up the whole test.
Fixes #
=> Chore: remove e2e-api-test in rollout test to speed up

Dockerfile.e2e
Previous Dockerfile.e2e file run test without environment variable configured which may cause docker image build problems.
P.S. On Mac M1, the previous version Dockerfile.e2e is unable to build probably due to the arch problem.
Fixes #
=> Fix: dockerfile e2e test command lack environment configuration

.github/workflows/e2e-multicluster-test.yml, Makefile, go.mod, go.sum, hack/e2e/end_e2e.sh, hack/e2e/end_e2e_core.sh, test/e2e-multicluster-test/multicluster_test.go, test/e2e-multicluster-test/suite_test.go, test/e2e-multicluster-test/testdata/app/example-envbinding-app.yaml
1. Bootstrap new CI action to run e2e test for multi-cluster.
2. Multi-cluster e2e test will start 2 kind clusters while running. One cluster (Hub) will install KubeVela as normal. The other one will be an empty cluster.
3. Multi-cluster e2e test use simplified setup process which only install vela-core without oam-runtime or any addon (like flux or terraform).
4. The e2e test coverage report will be uploaded so that multi-cluster related Vela CLI test could be implemented and covered.
Fixes #
=> Feat: bootstrap multicluster testing

pkg/utils/common/common.go, references/appfile/app.go, references/cli/logs.go
`vela logs` are now available for multicluster.
Fixes #
I have:
=> Feat: vela logs support multicluster

pkg/cue/process/handle.go, pkg/cue/process/handle_test.go
=> Fix: The `outputs` name with symbol `-` cause render error

go.mod, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/cluster.go, pkg/apiserver/rest/utils/bcode/cluster.go, pkg/apiserver/rest/webservice/cluster.go, pkg/cloudprovider/aliyun.go, pkg/cloudprovider/cluster.go, pkg/cloudprovider/terraform.go, pkg/utils/util/k8s.go
Add create cloud cluster API and support ACK.
+ Create ACK Cluster
+ Get creation status
+ List all creation
+ Cancel creation
I have:
This part of API does not have unit-test since creating cluster is heavy and is not suitable for being used in test. It has been tested manually.
**Implementation**:
Since currently the terraform part (terraform-controller:v0.2.6) do not support multi-tenant natively, the implementation of these APIs are directly working with underlying Terraform Configuration CRDs.
To create an ACK cluster, the creation API executes the following steps:
1. APIServer creates a secret containing AK/SK for providers to use.
2. APIServer creates a Terraform Provider to use the AK/SK.
3. APIServer creates a Terraform Configuration which leverages the provider established in …
=> Feat: add create cloud cluster interface

cmd/core/main.go, design/api/vela-controller-params-reference.md, pkg/controller/common/context.go
The current default reconcile timeout is 1 minute. However, while handling large application with lots of components such as fluxcd, some kubernetes might not be able to process so many component in 1 minute, which will further cause reconcile timeout error. This PR add reconcile timeout config where users can modify it depending on their clusters. For developers, it will be more convenient to set it to longer (such as 1h) to do step-by-step debug. 
I have:
=> Feat: add reconcile timeout configuration for vela-core

docs/apidoc/swagger.json, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go, pkg/apiserver/rest/utils/bcode/addon.go, pkg/apiserver/rest/utils/convert.go, pkg/apiserver/rest/webservice/addon.go, pkg/apiserver/rest/webservice/addon_registry.go, pkg/oam/labels.go, test/e2e-apiserver-test/addon_test.go
1. Parses new Addon format
2. Remove ConfigMap reading path
3. enable/disable to bundle templates and definitions into one Application
4. add `registry` to list addon request
5. define Definition API
Addon 信息返回如下：
=> Feat: rewrite Addon API to support new format

go.mod, go.sum
https://github.com/oam-dev/stern/commit/5a32374b27cbb1ab65cad6b7fcd9cd7771663a86
I have:
=> Fix: upgrade stern lib to avoid panic for vela logs

pkg/utils/common/common.go, references/cli/logs.go
Filter loggable workload in vela logs, now only applied `Deployment`, `StatefulSet`, `CloneSet` and `Job` will be `vela logs` options
Fixes #
I have:
=> Fix: filter loggable workload in vela logs

pkg/stdlib/op.cue, pkg/workflow/providers/oam/apply.go, pkg/workflow/providers/oam/apply_test.go
1.  load component cue action  can set patchedApp override default app
2. export some multiCluster cue action, let user can specify user defined workflow.
I have:
=> Fix: load component cue action  can set patchedApp override default app

e2e/application/application_test.go, go.mod, go.sum, pkg/clustermanager/cluster_manager.go, pkg/multicluster/proxy.go, pkg/utils/common/common.go, references/cli/exec.go, references/cli/logs.go, references/cli/portforward.go, references/cli/status.go, references/cli/utils.go
Support exec for pods in remote cluster. Support port-forward for workloads/service in remote cluster. Continue from #2658.
I have:
=> Feat: multicluster vela status/exec/port-forward

pkg/controller/core.oam.dev/v1alpha2/application/generator.go, pkg/controller/core.oam.dev/v1alpha2/application/revision.go, test/e2e-multicluster-test/multicluster_test.go
In envbinding, the component revisions are placed at the namespace where Application locates in hub cluster. However, it is not necessary for child cluster to have that namespace if user choose to deploy at a different namespace. This PR lets the `overrideNamespace` works for ComponentRevisions as well.
Fixes #2546
=> Fix: multicluster component revision location

docs/examples/velaql-views/componet-pod-view.yaml, pkg/stdlib/op.cue, pkg/stdlib/packages.go, pkg/stdlib/pkgs/kube.cue, pkg/stdlib/pkgs/query.cue, pkg/stdlib/pkgs/time.cue, pkg/stdlib/ql.cue, pkg/velaql/parse.go, pkg/velaql/parse_test.go, pkg/velaql/providers/query/collector.go, pkg/velaql/providers/query/handler.go, pkg/velaql/providers/query/handler_test.go, pkg/velaql/providers/query/suite_test.go, pkg/velaql/suite_test.go, pkg/velaql/testdata/apply-object.yaml, pkg/velaql/view.go, pkg/workflow/providers/kube/handle.go, pkg/workflow/providers/time/date.go, pkg/workflow/providers/time/date_test.go, pkg/workflow/tasks/discover.go, pkg/workflow/tasks/template/load.go, pkg/workflow/tasks/template/load_test.go, test/e2e-apiserver-test/testdata/component-pod-view.yaml, test/e2e-apiserver-test/testdata/read-view.yaml, test/e2e-apiserver-test/velaql_test.go
This PR add `query` provider  to support observe the status of runtime cluster resources. 
`query` provider now supports 3 kinds of query capabilities:
1. **`#ListResourcesInApp`**  can list all resources created by the app.  the query results are fedback to the `list` field.
```
// definition 
#ListResourcesInApp: {
#do:       "listResourcesInApp"
#provider: "query"
app: {
name:      string
namespace: string
// component wants to query 
components?: [...string]
enableHistoryQuery: false | bool
}
// list return the query results
list?: [...#App]
}
#App: {
components: [...{
name: string // component name
resources: [...{
cluster: string // which cluster the resource is deployed to
object: {...} // k8s object
}]
}]
metadata: {...} // metadata of application
revision: int // revision num of …
```
=> Feat: add query provider to support observe the status of runtime cluster resources

.github/workflows/e2e-test.yml, Makefile, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go, test/e2e-addon-test/addon_test.go, test/e2e-addon-test/suite_test.go, test/e2e-addon-test/testdata/app/app_terraform_oss.yaml
Function aggregateHealthStatus() in pkg/controller/core.oam.dev/v1alpha2/application/apply.go which is used to retrieve components status, was
abandoned. All unit-tests of it was abandoned too. Fixed it and restore all the unit
tests.
Fixes #
I have:
=> Fix: application status.services doesn't include Terraform typed components

pkg/utils/url.go, pkg/utils/url_test.go, references/cli/cluster.go
Using `vela cluster join` now only support kubeconfig with full apiserver url such as https://127.0.0.1:6443. It must include `scheme`, `host`, `port` three parts to work. This PR allows user only specify `host` and the added function will automatically add `scheme` and `port` to it.
I have:
=> Fix: cluster url automatically patch port and scheme

.github/workflows/e2e-multicluster-test.yml, charts/vela-core/templates/cluster-gateway.yaml, charts/vela-core/values.yaml, references/cli/exec.go, references/cli/portforward.go, test/e2e-multicluster-test/multicluster_cli_test.go, test/e2e-multicluster-test/suite_test.go, test/e2e-multicluster-test/testdata/app/example-vela-cli-tool-test-app.yaml
1. Upgrade ClusterGateway to v1.1.6 to support remote long-run connections such as `vela exec`.
2. Add `-n/--namespace` for `vela exec/port-forward`.
3. Add multi-cluster testing for remote exec/port-forward.
4. Split admission ServiceAccount for cluster-gateway from admission-webhook. Previously, ClusterGateway secureTLS cannot work without admission-webhook.
I have:
=> Feat: upgrade cluster gateway to support remote debug

charts/vela-core/templates/velaql-views/component-pod-view.yaml, charts/vela-core/templates/velaql-views/pod-view.yaml, charts/vela-core/templates/velaql-views/resource-view.yaml, pkg/apiserver/rest/usecase/velaql.go, pkg/velaql/providers/query/collector.go, test/e2e-apiserver-test/testdata/component-pod-view.yaml, test/e2e-apiserver-test/velaql_test.go
1. component-pod-view
request url 
```
http://127.0.0.1:8000/api/v1/query?velaql=component-pod-view{namespace=test-velaql,name=example-app,componentName=ql-worker}.status
```
response body
```
{
"podList": [
{
"clusterName": "",
"hostIP": "172.18.0.2",
"nodeName": "kind-control-plane",
"podIP": "10.244.0.196",
"podName": "ql-worker-27278072-jfcnv",
"revision": 2,
"status": "Succeeded"
},
{
"clusterName": "",
"hostIP": "172.18.0.2",
"nodeName": "kind-control-plane",
"podIP": "10.244.0.197",
"podName": "ql-worker-27278073-vt6d9",
"revision": 2,
"status": "Succeeded"
},
{
"clusterName": "",
"hostIP": "172.18.0.2",
"nodeName": "kind-control-plane",
"podIP": "10.244.0.198",
"podName": "ql-worker-27278074-b86hw",
"revision": 2,
"status": "Succeeded"
}
]
}
```
2. pod-view
request url 
``` …
```
=> Feat: add apis to monitor running application's status

Makefile
When golangci-lint doesn't locate in $PATH, it will be installed in
$GOBIN every single time.
Fixes #
I have:
=> Fix: stop installing golangci-lint each time in a CI

charts/vela-core/templates/addons/terraform.yaml, vela-templates/addons/auto-gen/terraform.yaml, vela-templates/addons/terraform/definitions/terrafom-alibaba-redis.yaml
1. add alibaba cloud redis definition
related #1770
I have:
=> Feat: add alibaba cloud redis definition

charts/vela-core/templates/defwithtemplate/depends-on-app.yaml, charts/vela-minimal/templates/defwithtemplate/depends-on-app.yaml, vela-templates/definitions/internal/depends-on-app.cue
Fixed the bug that when addon depends on a non-existent addon, it will not be installed automatically
Fixes #
I have:
=> Fix: fix workflowstep depends-on-app

charts/vela-core/templates/addons/istio.yaml, vela-templates/addons/auto-gen/istio.yaml, vela-templates/addons/istio/template.yaml
Addon's application should be in `vela-system` uniformly. `istio` addon isn't and fix this.
Fixes #
I have:
=> Fix: istio addon application namespace not in vela-system

pkg/apiserver/model/workflow.go, pkg/apiserver/rest/usecase/application.go, pkg/apiserver/rest/usecase/application_test.go, pkg/apiserver/rest/usecase/envbinding.go, pkg/apiserver/rest/usecase/testdata/ui-schema.yaml, pkg/apiserver/rest/usecase/workflow.go, pkg/apiserver/rest/webservice/application.go
=> Feat: add list application records api

apis/types/capability.go, charts/vela-core/templates/defwithtemplate/deploy2runtime.yaml, charts/vela-minimal/templates/defwithtemplate/deploy2runtime.yaml, pkg/addon/addon.go, pkg/apiserver/rest/usecase/addon.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/stdlib/op.cue, pkg/stdlib/pkgs/oam.cue, pkg/workflow/providers/oam/apply.go, vela-templates/definitions/internal/deploy2runtime.cue
Fix:
1. load component in arrary, so apply them in order addon's needNamespace will be apply firstly
2. apply application  in controle plane will be first workflowStep
3. bigger application reconcile timeout context get avoid of time out
Fixes #
I have:
=> Fix: fix several addon issue

pkg/apiserver/rest/webservice/addon.go, test/e2e-apiserver-test/addon_test.go
If an addon like `fluxcd` doesn't need arguments to be enabled, we
should not parse the arugments
Fixes #
I have:
=> Fix: enable addon without arguments

test/e2e-apiserver-test/addon_test.go
As addon example has been removed, the first addon on should not
be `example`
Fixes #
I have:
=> Fix: the first addon should not be `example`

apis/core.oam.dev/v1alpha1/envbinding_types.go, docs/examples/gc-policy/gc.md, pkg/appfile/appfile.go, pkg/appfile/appfile_test.go, pkg/appfile/parser.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc_test.go, pkg/controller/core.oam.dev/v1alpha2/application/gc_policy_test.go, pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go, pkg/controller/core.oam.dev/v1alpha2/application/revision.go
add a built in `garbage-collect` policy, while now only support one option  `keepLegacyResource`, which means gc mechanism will keep the legacy resource when application is updated. you can enable the `keepLegacyResource` options like: 
```yaml
metadata:
spec:
components:
- name: express-server
properties:
image: crccheck/hello-world
port: 8000
traits:
- type: ingress-1-20
properties:
domain: testsvc.example.com
http:
"/": 8000
policies:
- name: keep-legacy-resource
type: garbage-collect
properties:
keepLegacyResource: true
```
**what will the gc mechanism do when enable the `keepLegacyResource` options**
1. resources with the same GVK and name will be normal updated, and the `OwnerReference` of those …
=> Feat: add a built in garbage-collect policy to application

pkg/apiserver/rest/webservice/addon.go
With the fix #2766 to install addon without arguments, fix the issue of
installing addons with arguments.
Fixes #
I have:
=> Fix: addon with arguments could not be installed

pkg/addon/addon.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/webservice/addon.go, test/e2e-apiserver-test/addon_test.go
As there are bool typed arguments, the current arguments' type doesn't support them.
Fixes #
I have:
=> Fix: arguments map[string]string doesn't support observability's args

pkg/cue/model/value/value.go, pkg/cue/model/value/value_test.go
=> Fix: lookupByScript don't support `import`

e2e/application/application_test.go, e2e/commonContext.go, go.mod, go.sum, references/cli/delete.go, references/common/application.go
vela delete add `wait` and `force` options.
```
$ vela delete first-vela-app --wait
Deleting Application "first-vela-app"
waiting for delete the application "first-vela-app"...
try to delete the app for the 14 time, wait a total of 26.034524 s
app "first-vela-app" deleted from namespace "default"
```
after close vela controller
```
$ vela delete first-vela-app --force
Deleting Application "first-vela-app"
force delete the resources created by application
app "first-vela-app" deleted from namespace "default"
```
Fixes #
I have:
=> Feat: vela delete add wait and force options

pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope_controller.go
Fix HealthScope to support env-binding over namespace. Old HealthScope only support multi-cluster but not support multi-namespace across clusters. This PR fixes it. It also allows users to use `vela status` to check application status with env-binding and health-scope configured.
`vela status` effect
```bash
$ vela status example-app                                                                        
About:                                                                                    
Name:         example-app                                                               
Namespace:    default                                                                   
Created at:   2021-11-23 15:41:02 +0800 CST …
```
=> Fix: healthscope support envbinding (namespace)

pkg/addon/addon.go
Fixed the probelm of renderring cue template for terraform provider
after #2788
Fixes #
I have:
=> Fix: the way to renderCUETemplate for terraform provider is wrong

references/cli/workflow.go, references/cli/workflow_test.go
Fixes #
I have:
/cc @barnettZQG @wonderflow
=> Feat: add workflow rollback cli

pkg/addon/addon.go
If the component name has a suffix `.cue`, it will hit issue of not
matching a DNS name
Fixes #
I have:
=> Fix: remove .cue suffix from the component name of observability

pkg/addon/addon.go
Now addon's async read may cause concurrent error because slice in go is not safe in concurrency.
Fix this.
Fixes #
I have:
=> Fix: add lock to avoid addon concurrency read error

pkg/addon/addon.go
- Adding prefix `resources will hit issues as:
'unable to parse requirement: invalid label value:
"resources-prometheus-server-register-grafana-datasource-5576f7f6b4":
at key: "controller.oam.dev/component": must be no more than 63 characters'
- This won't avoid the name confliction with other components
Fixes #
I have:
=> Fix: addon name should not add prefix `resources`

Makefile
Fix the `make vela-cli` can't work as docker command not exist in the build env. Add a condition check in the command.
Fixes #2812
I have:
=> Fix: don't invoke docker command if not exist

pkg/controller/core.oam.dev/v1alpha2/application/apply.go, pkg/controller/core.oam.dev/v1alpha2/application/generator.go
Health Check do not check resource in correct namespace previous (inherit the app namespace), which might be override by envbinding config. This PR fixes it.
I have:
=> Fix: health check do not check resource in correct namespace

pkg/appfile/parser.go, pkg/controller/standard.oam.dev/v1alpha1/rollout/handler.go, pkg/controller/standard.oam.dev/v1alpha1/rollout/handler_suit_test.go
Health Check select target workloads by labels. One of the label is appRevision.
1. Workloads created by rollout inherits the labels from component revision which does not have appRevision. Amend it.
2. HealthScope controller label selector does not fill appRevision. Amend it.
I have:
=> Fix: health check appRev label bug

pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc.go
Current ResourceTracker mechanism does not garbage collect legacyRTs when previousRT is absent or equal to currentRT. However, in cases where latestRT is firstly updated but GC not executed due to the interruption of workflow, the recycle of outdated resources will be broken. This PR fixes it.
I have:
=> Fix: resourcetracker do not garbage collect legacyRTs correctly

charts/vela-core/templates/velaql-views/component-pod-view.yaml, pkg/stdlib/pkgs/query.cue, pkg/velaql/providers/query/collector.go, pkg/velaql/providers/query/handler.go, pkg/velaql/providers/query/handler_test.go, test/e2e-apiserver-test/testdata/component-pod-view.yaml
Fix bug: velaql will miss query the resources created by the old application version
Fixes #
I have:
=> Fix: velaQL miss query the resources created by the old application version

charts/vela-core/templates/addons/terraform.yaml, docs/examples/terraform/cloud-resource-provision-and-consume/application-rds.yaml, pkg/appfile/appfile.go, vela-templates/addons/auto-gen/terraform.yaml, vela-templates/addons/terraform/definitions/terraform-alibaba-oss.yaml, vela-templates/addons/terraform/definitions/terraform-alibaba-rds.yaml
To help users quickly navigate to the instance in the web console, exposing
necessary information in ComponentDefinition and convert them to Configuration
Fixes #
I have:
=> Fix: support exposing cloud resource identifier and console url

apis/core.oam.dev/common/types.go, apis/core.oam.dev/v1beta1/core_types.go, apis/core.oam.dev/v1beta1/resourcetracker.go, apis/core.oam.dev/v1beta1/zz_generated.deepcopy.go, apis/interfaces/resourcetracker.go, charts/vela-core/crds/core.oam.dev_resourcetrackers.yaml, charts/vela-minimal/crds/core.oam.dev_resourcetrackers.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_resourcetrackers.yaml, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/dispatch_test.go, pkg/controller/core.oam.dev/v1alpha2/application/dispatch/gc_test.go, pkg/controller/core.oam.dev/v1alpha2/application/revision.go, pkg/controller/standard.oam.dev/v1alpha1/rollout/handler.go, pkg/multicluster/gc.go, pkg/multicluster/gc_test.go, pkg/policy/envbinding/placement.go, pkg/resourcetracker/resourcetracker.go, pkg/utils/apply/apply.go, pkg/workflow/providers/multicluster/multicluster.go
Fix two problems:
1. Runtime Cluster Root ResourceTracker recorded in Management Cluster Root ResourceTracker, so that runtime-cluster GC can work without application status.
2. OwnerReference not must be controlled by UID, but filter by label name. So that outdated resource can be correctly recycled even when its outdated Resourcetracker has gone. #2767
I have:
This PR will help rework RT to support life-long/versioned resource & customized GC policy in the future.
=> Feat: rework resource tracker to solve bugs

apis/core.oam.dev/common/types.go, charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml, charts/vela-core/crds/core.oam.dev_applications.yaml, charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml, charts/vela-minimal/crds/core.oam.dev_applications.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, pkg/workflow/workflow.go, pkg/workflow/workflow_test.go
=> Fix: application conditions confusion.

pkg/controller/core.oam.dev/v1alpha2/application/apply.go
Synchronized the status of an Terraform typed components to .status.
services of the application
Fixes #
I have:
=> Fix: sync status of Terraform typed components to application

pkg/controller/utils/capability.go, pkg/utils/terraform/properties.go, references/plugins/references.go
Added `writeConnectionStringSecrecto`, `region` and `deleteResoruce`
fields for Terraform types definitions in OpenAPI schema
Fixes #
I have:
=> Fix: add more fields for Terraform types definitions in api schema

pkg/apiserver/rest/usecase/application.go, pkg/apiserver/rest/usecase/application_test.go, pkg/apiserver/rest/usecase/definition_test.go, pkg/apiserver/rest/usecase/testdata/ui-schema.yaml, pkg/apiserver/rest/usecase/testdata/webserver-cd.yaml, pkg/apiserver/rest/webservice/webservice.go
Users can configure differentiated variable data in the Target, including provider、region, and others, to automatically populate differentiated cluster data for cloud applications.
Here, the secret name is automatically populated with the name of the component.
I have:
=> Feat: automatically populate the provider and region configuration for cloud app

pkg/apiserver/rest/usecase/workflow.go
reset record status when a new one is created
I have:
=> Fix: reset record status when a new one is created

pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/application.go, pkg/apiserver/rest/usecase/envbinding.go, pkg/apiserver/rest/usecase/workflow.go, pkg/apiserver/rest/usecase/workflow_test.go
Cloud resource applications do not fully define Workload Type, so we also judge Kind.
I have:
=> Fix: cloud resource type applications could not be identified

pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/source.go, pkg/apiserver/rest/usecase/addon.go, test/e2e-apiserver-test/addon_test.go
1. fix query addon status api 500 because of secret
2. fix read problems from oss
Fixes #
I have:
=> Fix: query addon status api 500 because of secret

charts/oam-runtime/values.yaml, charts/vela-core/values.yaml, charts/vela-minimal/values.yaml
We changed the test image tag in this PR #2623
while the image tag will be automatically changed in the release pipeline: https://github.com/oam-dev/kubevela/blob/release-1.1/.github/workflows/registry.yml#L117-L141
In this PR, I mark the tag as a fixed one.
Fixes #2869 
I have:
Already pushed to docker hub
=> Fix: mark test chart image in a fixed tag to avoid changed by release

references/cli/addon.go
Now there is a bug: addon enable timeout won't quit the enable process.
This PR:
1. fix addon enable timeout is not used
2. better addon enable fail message 
I have:
Test by build a binary with very short timeout, timeout fail like this:
=> Fix: addon timeout is not acturally tracked

pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/source.go, pkg/addon/testdata/terraform-alibaba/metadata.yaml, pkg/addon/testdata/terraform/metadata.yaml, pkg/addon/testdata/test-error-addon/metadata.yaml, pkg/addon/testdata/test-error-addon/resources/parameter.cue, pkg/apiserver/rest/usecase/addon.go, pkg/apiserver/rest/webservice/addon_registry.go, pkg/apiserver/rest/webservice/webservice.go
Fix several problem.
1. When get `bucket.endpoint?prefix=terraform`, files in `terraform-alibaba` will be listed.(They all have "terraform" prefix) This will cause race. 
2. AddonRegistryMeta's Git or OSS can be set and should be access by SourceOf function.
3. Unify the interface
Fixes #
I have:
=> Fix: OSS read data race

.github/workflows/release.yml
Fix the failed release pipeline: 
https://github.com/oam-dev/kubevela/runs/4441258128?check_suite_focus=true
I have:
Tested in my repo https://github.com/wonderflow/kubevela/releases/tag/v0.1.20
=> Fix: use specific cli release download folder

apis/types/capability.go, pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/helper.go, pkg/apiserver/rest/usecase/addon.go, pkg/definition/definition.go, pkg/definition/definition_test.go, references/cli/addon.go, references/cli/def.go, references/cli/def_test.go
Now our definition in addons are all YAML, This PR support definition's CUE format.
This makes it possible to develop addon definition with `vela def`
Fixes #
I have:
1. Add one test.: render an addon with a cue format definition.
2. test by hand
- test cue definition
- enable addon    
- check addon
=> Feat: support addon definition in cue format

pkg/apiserver/rest/usecase/application.go, pkg/apiserver/rest/usecase/application_test.go, pkg/apiserver/rest/usecase/testdata/ui-schema.yaml
The purpose of automatically creating traits is as follows:
1. The replications parameter is not included in the`webservice` component.
2. Provide users with trait best practices.
I have:
=> Feat: support automatically creating scaler trait for webservice component

apis/types/capability.go, pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/helper.go, pkg/addon/source.go, pkg/addon/type.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go, pkg/apiserver/rest/webservice/addon.go, references/cli/addon.go
Addon's api shouldn't be in types.go. It will block sync api to kubevela-api-core. This PR move it to pkg/addon. 
I have:
=> Fix: move addon api to pkg/addon

design/vela-core/resourcetracker_design.md, docs/examples/app-with-policy/apply-once-policy/apply-once.md, docs/examples/app-with-policy/gc-policy/keep-legacy-resources.md, docs/examples/app-with-policy/gc-policy/persist-resources.md, e2e/application/application_test.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/resourcekeeper/statekeep.go, test/e2e-test/resource_policy_test.go, test/e2e-test/testdata/app/app_garbage_collect.yaml
- Add design docs for ResourceTracker.
- Add examples for garbage-collect policy and apply-once policy.
- Enhance state-keep logic.
- Fix minor test bugs.
I have:
=> Fix: add design docs for ResourceTracker

e2e/addon/addon_test.go, pkg/addon/registry.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go, references/cli/addon-registry.go, references/cli/addon.go
1. cli support addon registry
2. apiServer addon/status return detail workflow info of app, where often contain serror info when workflow hang in `AppStatus`phase.
I have:
=> Feat: cli manage addon registry and apiserver addon status return app status info

Makefile, charts/vela-core/values.yaml
Set multi-cluster as enabled by default in kubevela chart.
NOTE: minimal chart still keep it disabled by default
I have:
=> Feat: set multicluster enabled by default

docs/apidoc/swagger.json, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/project.go, pkg/apiserver/rest/usecase/project_test.go, pkg/apiserver/rest/usecase/testdata/ui-schema.yaml, pkg/apiserver/rest/utils/bcode/namespace.go, pkg/oam/labels.go
support specified existing namespace while creating a project, but the namespace can not belong to other projects.
Fixes #2914
I have:
=> Feat: support specified existing namespace while creating a project

pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller_test.go, pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller_test.go, pkg/controller/utils/utils.go, pkg/cue/package_suit_test.go, pkg/cue/packages/package.go, references/appfile/dryrun/testdata/cd-myworker.yaml, references/appfile/dryrun/testdata/diff-apprevision.yaml, references/appfile/dryrun/testdata/td-myingress.yaml
Fixes #
I have:
Disable package discover from kubernetes open api.
Alternative solution: [issues 2924](https://github.com/oam-dev/kubevela/issues/2924)
=> Fix:  deprecate CRD discovery for CUE import in Definition to prevent memory leak and OOM crash

charts/vela-core/templates/defwithtemplate/deploy2env.yaml, pkg/stdlib/pkgs/multicluster.cue, pkg/stdlib/pkgs/oam.cue, pkg/workflow/providers/oam/apply.go, vela-templates/definitions/internal/workflowstep/deploy2env.cue
Previous deploy2env will deploy resources one by one. Only when the last resource is healthy will the next resource be applied. This will cost lots of time for some heavy applications with lots of components such as addons.
It would be better to support `DependOn` in deploy2env but it is not very easy currently. This PR provides an alternative feature which allows resources to be deploy together at first and then health check, which means resources in one deploy2env step can be deployed without waiting each others.
I have:
=> Feat: support parallel apply in deploy2env

pkg/addon/addon.go, pkg/addon/addon_suite_test.go, pkg/addon/addon_test.go, pkg/addon/helper.go, pkg/addon/suite_test.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go, references/cli/addon.go
This pr have done such things：
1.  application's name of addon in 1.2 is addon-{addonName}, but in 1.1 is just {addonName}, we cannot let user delete old app and enable addon again, so insert compatibility code.
2. algin the addon status of  apiserver and cli  
3. addon suspend status
4. enable addon will continue app workflow if workflow is suspending
I have:
=> Feat: addon compatibility code for 1.1

pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/helper.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go
Return all domains and the IPs from all clusters. And
provider the way to visit the console of observability
Fixes #
I have:
=> Fix: implement addons/observability/status API

pkg/stdlib/op.cue, pkg/workflow/providers/workspace/workspace.go, pkg/workflow/providers/workspace/workspace_test.go
=> Fix: message invalid in action `op.#ConditionalWait` and `op.#Break`

pkg/utils/common/common.go, pkg/utils/common/common_test.go, references/cli/utils.go
Support port forwarding service of Addon Observability in
multiple clusters
Fixes #
I have:
=> Fix: vela port-forward supports Addon Observability

pkg/addon/addon.go
If enable a not exist addon will panic.
Fixes #
I have:
=> Fix: panic bug of addon enable

pkg/addon/addon.go
When getting addon from multiple registries, registries from second will be omitted. Fix this by return a typed error so caller can judge the situation.
Fixes https://github.com/oam-dev/kubevela/issues/2992
I have:
=> Fix: return reasonable error make multi-registry work

charts/vela-core/templates/addon_registry.yaml, pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/source.go, pkg/addon/type.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go, pkg/apiserver/rest/webservice/addon.go, references/cli/addon.go
Add registry-name in addon list
/api/v1/addons/ add registryName field 
```json
"addons": [
{
"name": "fluxcd",
"version": "1.0.0",
"description": "Extended workload to do continuous and progressive delivery",
"icon": "https://raw.githubusercontent.com/fluxcd/flux/master/docs/_files/weave-flux.png",
"url": "https://fluxcd.io",
"tags": [
"extended_workload",
"gitops"
],
"deployTo": {
"runtime_cluster": true,
"disableControlPlane": false,
"runtimeCluster": false
},
"needNamespace": [
"flux-system"
],
"invisible": false,
"registryName": "KubeVela"
},
```
Cli :
Fixes #
I have:
=> Fix: add registryName into addon list

pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/helper.go
Use Grafana service's external IP to visit the dashboard and
remove the prameter domain
Fixes #
I have:
=> Fix: change Grafana service type and remove domain parameter

pkg/apiserver/rest/rest_server.go, pkg/apiserver/rest/utils/http.go
log format:
```
{"level":"info","ts":1640599745.817394,"caller":"rest/rest_server.go:223","msg":"","clientIP":"127.0.0.1","path":"/api/v1/applications","method":"GET","status":200,"time":"2.393168736s","responseSize":1358}
```
I have:
=> Feat: add request logging for the api server

test/e2e-test/definition_revision_test.go, test/e2e-test/helm_app_test.go
Previous Helm Chart type is deprecated and replaced by newer implementation. Old test has the following problem:
- While dispatching helm chart component and apply patch trait to it, the deployment created by fluxcd can be relatively slow.
- Workflow has backoff wait but when the deployment is not created, error is returned, so backoff has a maximum time at 10. Therefore, after about 1 minute, if the deployment has not been created, the application will enter suspending status and will not retry anymore.
- In this case, the patch trait cannot work so e2e-test will fail.
Since this feature is not going to be supported and deprecated, the e2e-test can be pending for now.
If we would like to support this feature and re-enable this e2e-test, we …
=> Fix: pending deprecated test

pkg/multicluster/errors.go, pkg/multicluster/errors_test.go, pkg/resourcekeeper/cache.go, pkg/resourcekeeper/gc.go
During GC, ignore ClusterNotExists error. This is usually caused by some incorrect operation on cluster (such as directly removing cluster secret instead of using `vela cluster detach`, which will bypass the usage check) 
Notice that ClusterDisconnect is not ignored since it could be caused by some temporarily network failure.
Fixes #2986 
I have:
=> Feat: gc process ignore cluster not exists

pkg/apiserver/rest/usecase/velaql.go, pkg/stdlib/pkgs/query.cue, pkg/stdlib/ql.cue, pkg/velaql/providers/query/handler.go, pkg/velaql/providers/query/handler_test.go, pkg/velaql/suite_test.go, pkg/velaql/view.go, pkg/workflow/tasks/discover.go, test/e2e-apiserver-test/testdata/collect-logs.yaml, test/e2e-apiserver-test/velaql_test.go
Support stream logs for apiserver to query pod.
```bash
curl http://127.0.0.1:8000/api/v1/query?velaql=collect-logs{cluster=local,namespace=default,pod=example-pod,container=main-container}.status
```
```json
{
"info": {
"fromDate": "2021-12-28T06:26:20Z",
"toDate": "2021-12-28T08:15:47Z"
},
"logs": "hello-world\n"
}
```
`/api/v1/query?velaql=collect-logs{cluster=local,namespace=default,pod=example-pod,container=main-container,tailLines=10}.status`
`/api/v1/query?velaql=collect-logs{cluster=local,namespace=default,pod=example-pod,container=main-container,limitBytes=100}.status`
`/api/v1/query?velaql=collect-logs{cluster=local,namespace=default,pod=example-pod,container=main-container,timestamps=true}.status` …
=> Feat: support logs for velaql

docs/examples/workflow/source-to-image/step-definition.yaml, pkg/stdlib/pkgs/task.cue
we found that the cue type "op.#Task" couldn't work properly when we used it to create "source to image" workflow step definition. we fixed all bugs and make little changes and some enhancements, such as following:
1) allow to override the default base images since generally the production environment couldn't pull the images from the outside repositories.
2) add additional feature to bind the secrets into the step image container.
Fixes #
I have:
we have tested the changes with the "source to image" case, and can work properly now.
=> Fix: op.#Task couldn't work, debug task.cue and fix bugs

pkg/addon/addon.go, pkg/addon/addon_test.go
When there is no clusters, users use cli to enable observability,
we use workflow `apply-application-in-parallel` to enable the addon.
This workflow will skip health check and the addon won't become ready.
Fixes #
I have:
=> Fix: don't skip health check for observability in single cluster

pkg/utils/common/common_test.go
When we fix error logs in the definition controller in https://github.com/oam-dev/kubevela/pull/2063 The code works as expected. However, the error case is not actually tested. 
In short, we use `LookupDef` to get `cue.Value` and then generate `cue.ast`.
When using cue.format package to print `cue.ast`, we'll get a bad case for old code. Notice the unexpected `close` after if clause.
```cue
close({
x?: string
if x != "" close({ // this "close" makes it impossible to turn it back to cue.Value
y: string
})
})
```
But in the unit test, it's not tested. In another word, we can pass the test even we roll back the code.
This is how we do In the unit test, following `cue.ast` will be generated which is valid.
```cue
close({
x?: string
})
```
Fixes # …
=> Fix: error case is not tested when generate api schema

references/cli/addon.go
We should check error when client not initialized, and report the error reason.
Before:
After:
I have:
=> Fix: check error when client not created

apis/types/capability.go, hack/references/generate.go, pkg/controller/utils/capability.go, pkg/controller/utils/capability_test.go, pkg/utils/common/common.go, pkg/utils/common/common_test.go, references/plugins/cluster.go, references/plugins/reference_test.go, references/plugins/references.go
When the configuration of a Terraform Typed ComponentDefinition is in
remote Git, generate the properties for it. And generated outputs for
all Terraform ComponentDefinition
Fixes #
I have:
=> Fix: Generate doc for Terraform typed ComponentDefinition

apis/types/types.go, pkg/stdlib/pkgs/query.cue, pkg/utils/strings.go, pkg/velaql/providers/query/collector.go, pkg/velaql/providers/query/handler.go, pkg/velaql/providers/query/handler_test.go
Generate access endpoint information for the application. By reading Ingress and Service resources. Support common component type and helm component.
I have:
/cc @wangyikewxgm
=> Feat: support query service endpoints by velaQL

pkg/addon/addon_test.go, pkg/addon/error.go, test/e2e-apiserver-test/addon_test.go
duplicate here https://github.com/oam-dev/kubevela/pull/2993
Add test for this feature
Fixes #
I have:
=> Feat: add test for registry name in addon response

docs/examples/terraform/cloud-resource-provision-and-consume/application-aws-s3.yaml, pkg/appfile/appfile.go, pkg/appfile/appfile_test.go
Fixed the issue "The error message is not correct when AWS provider is not available"
Fix #3046
Fixes #
I have:
=> Fix: when a provider is set in ComponentDefinition, it should look for the provider

contribute/developer-guide.md
If the version of cue binary is less than v0.3.0, like v0.2.0, `make reviewable`
will fail due to issue: "make: *** [fmt] Error 1". As `make reviewable` is a
required step for code contribution, add this prerequiste in the doc.
Fixes #
I have:
=> Fix: add cue binary requirement in Development doc

hack/references/generate.go, pkg/controller/utils/capability.go, pkg/controller/utils/capability_test.go, references/cli/def.go, references/cli/def_test.go, references/plugins/cluster.go, references/plugins/reference_test.go, references/plugins/references.go
Generated kubevela.io docs for Terraform typed ComponentDefinition
with `vela def gen-doc xxx` cli.
Fixes #
I have:
=> Fix: generate docs for Terraform ComponentDefinition

references/cli/common.go, references/cli/def.go, references/cli/def_test.go
Support generate Terraform typed ComponentDefinition by `vela def init`
Fixes #
I have:
=> Fix: generate Terraform ComponentDefinition by vela cli

pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/webhook.go, pkg/apiserver/rest/usecase/webhook_test.go
add DockerHub webhook trigger: #3029 
change webhook response data struct to interface{} because [dockerhub webhook](https://docs.docker.com/docker-hub/webhooks/#validate-a-webhook-callback) should response standard data structure to show webhook call status in dockerhub web, and continue dockerhub webhook chain
=> Feat: add DockerHub webhook trigger 

pkg/appfile/appfile.go, pkg/controller/core.oam.dev/v1alpha2/application/generator.go, test/e2e-test/rollout_trait_test.go
cue template health check skipStandard workload and fix rollout e2e-test diverge
Fixes #
I have:
=> Fix: cue template health check skipStandard workload and fix test diverge

charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml, cmd/core/main.go, design/api/vela-controller-params-reference.md, pkg/controller/common/context.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
The default 1h re-sync time is a bit long for state-keep. In community version, users can experience the state-keep feature within 5 min now.
I have:
=> Feat: reset re-sync time

pkg/apiserver/model/system_info.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/system_info.go, pkg/apiserver/rest/webservice/system_info.go, pkg/apiserver/rest/webservice/webservice.go, test/e2e-apiserver-test/system_info_test.go
1. `get` userInfoCollection will return
```json
{
"userID": "n9qpmg2wtkcbj4cc",
"enableCollection": true
}
```
first `get` request will generate a UserID by random
2. post request `enable/disable`  will enable or disable user-Info-collection
3. write e2e-test
Fixes #
I have:
=> Feat: system information collection logic in apiserver

.github/workflows/release.yml
Fix release github action failed. 
I have:
=> Fix: use personel token of vela-bot instead of github token for homebrew update

.github/workflows/registry.yml
fix acr image have no vela-version
Fixes #
I have:
=> Fix: acr image no version

pkg/addon/reader_github.go
=> Fix:  file under the path of github addon registry is not ignored

pkg/addon/addon.go, pkg/addon/addon_test.go
…adata information
ignore vela-system, which is specified in needNamespace for addon metadata information.
Fixes #3108 
I have:
=> Fix: Vela is crashed, when disabling addon, which needs namespace vela-system

pkg/controller/standard.oam.dev/v1alpha1/rollout/handler.go
Fix rollout workload namespace not aligned with rollout. In EnvBinding, workload could be relocated at a namespace different from the initial one. Rollout controller should follow this redirection. 
Solve #3105 
I have:
=> Fix: rollout workload namespace not aligned with rollout

pkg/apiserver/model/application.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/webhook.go, pkg/apiserver/rest/usecase/webhook_test.go
add JFrog webhook trigger: #3029
jfrog webhook payload have no create time, image url and private/public fileds, use imageURL field in request header to mark image url, if not set request header in jfrog webhook configuration, just use `reponame/imagename:tag` to update application image field
=> Feat: add JFrog webhook trigger

docs/examples/envbinding/envpatch-with-wild-match.yaml, pkg/policy/envbinding/patch.go, pkg/policy/envbinding/patch_test.go, pkg/stdlib/pkgs/multicluster.cue
Add support for wild match in env patch.
1. Now EnvPatch could patch target component without specifying its type.
2. EnvPatch will patch all components with the specified type if the component name in EnvPatch is unset.
3. EnvPatch will patch all components if the component name and type in EnvPatch are neither set.
Example
```yaml
metadata:
name: example-app
namespace: default
spec:
components:
- name: podinfo
properties:
image: stefanprodan/podinfo
traits:
- type: scaler
properties:
replicas: 1
- name: hello-world
properties:
image: crccheck/hello-world
traits:
- type: scaler
properties:
replicas: 1
- name: nginx
type: worker
properties:
image: nginx …
```
=> Feat: support wild match for env patch

pkg/controller/core.oam.dev/v1alpha2/application/revision.go, pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
Fixes #2991 
When I fixed the problem, I found that there are some dependencies between ApplicationRevision and Workflow, I think these should be two independent modules
=> Fix: fix revision will change when add new trait with skiprevisionaffect to application

charts/vela-core/templates/admission-webhooks/job-patch/job-createSecret.yaml, charts/vela-core/templates/admission-webhooks/job-patch/job-patchWebhook.yaml, charts/vela-core/templates/cluster-gateway.yaml
add imagePullSecrets for helm templates to support private docker registry
Fixes #3121 
I have:
=> Fix: add imagePullSecrets for helm templates  to support private docker registry

references/cli/common.go, references/cli/def.go, references/cli/def_test.go, references/cli/test-data/redis.tf
Besides generating a Terraform ComponentDefinition from a remote git repo,
support generate one from local HCL file
Fixes #
I have:
=> Fix: support generate Terraform ComponentDefinition from local HCL file

references/cli/up.go, references/cli/up_test.go
Currently, CLI applies application to `default` namespace when there is no explicit namespace in application spec, even if the namespace flag is set.
This commit fixes issue by overriding the namespace if the namespace flag is set.
I have:
- ~Q. How can I add a `backport` label?~
```sh
export APP_SPEC_URL=https://raw.githubusercontent.com/oam-dev/kubevela/947455adb998426d56139f128b3a9cd7100e1d35/docs/examples/vela.yaml
vela up -f "${APP_SPEC_URL}"
vela up -f "${APP_SPEC_URL}" -n some-other-namespace
vela up -f "${APP_SPEC_URL}" -n some-other-namespace
```
I think overriding namespace in `NewUpCommand ` is better than extending `ApplyApplication` since it might be ambiguous  when taking it as a parameter. WDYT?
=> Fix: prioritize namespace flag for `vela up`

charts/vela-core/templates/defwithtemplate/gateway.yaml, charts/vela-minimal/templates/defwithtemplate/gateway.yaml, vela-templates/definitions/internal/trait/gateway.cue
[`kubernetes.io/ingress.class` annotation is deprecated](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) in favor of `.spec.ingressClassName`. However, there is no way to set it through the gateway trait for now.
This commit extends the gateway trait by adding `classInSpec` to parameter. Forcing the use of `.spec.ingressClassName` makes sense, but some ingress controllers (including old versions) may not recognize this field. Therefore, set default value of `classInSpec` to `false` for backward compatibility.
I have:
- https://github.com/oam-dev/kubevela.io/pull/474
```yaml
metadata:
spec:
components:
- name: express-server
properties:
image: …
```
=> Feat: extend gateway trait to set class in spec

references/cli/def.go, references/cli/def_test.go
If the provider is not provider, append the providerRef section in
the generated ComponentDefinition
Fixes #
I have:
=> Fix: add providerRef in generated ComponentDefinition

pkg/controller/utils/capability.go, pkg/controller/utils/capability_test.go, references/plugins/references.go
If Terraform modules/resources are stored in remote git repos, get
variables from file `varialbes.tf`, or from `main.tf`.
Fixes #
I have:
=> Fix: retrieve Terraform variables from variables.tf

references/cli/addon.go, references/cli/addon_test.go
fix vela addnon enable cannot support '='
Fixes #
I have:
=> Fix: vela addnon enable cannot support '='

pkg/appfile/validate.go
1. fix the typo
2. add context parameters into the error message
Signed-off-by: zeed-w-beez <zeed.w.zhao@gmail.com>
I have:
=> Fix: add context parameters into the error message

charts/vela-core/templates/addon_registry.yaml, charts/vela-core/templates/test/test-application.yaml
Use value in Addon Registry CM and the Test Application
Some vela-core helm chart templates did not use the value `systemDefinitionNamespace`. This leads to issues when using a different namespace than vela-system. I search all charts for those hardcoded references and make them configurable via the value.
I didn't create an Issue for this yet. Should I? Seems like a really minor change.
I have:
Did `helm template vela-test . --set=systemDefinitionNamespace=sys-kubevela | grep vela-system` see that no vela-system namespace is used anymore and a `helm lint`
=> Fix: Use systemDefinitionNamespace core Helm Chart

pkg/controller/utils/capability_test.go
Add another unit test when the configuration of Terraform locates
in a subpath of a git remote repository
Fixes #
I have:
=> Fix: add unit test for getting Terraform Configuration from remote git

cmd/core/main.go, pkg/controller/core.oam.dev/oamruntime_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, pkg/oam/labels.go
The purpose is to realize the grayscale upgrade scheme based on the application. You can choose  the controller with a specific version  to handle your application. 
For example, the application as follow require that the version of the controller to handle must be `v1.2.0`. If the controller with version  not equal to `v1.2.0`,  it will ignore the application.
```
metadata:
annotations:
app.oam.dev/controller-version-require: v1.2.0
```
I have:
Notice:
1. The controller must be upgraded to a version that includes this pr. Only after that, the grayscale release of the controller should be performed.
2. When there are multiple versions of the controller in the cluster, make sure that only one version of the controller has the command line …
=> Feat: application support controller requirement

Dockerfile, Dockerfile.apiserver, Dockerfile.e2e
https://nvd.nist.gov/vuln/detail/CVE-2021-38297 in go version 1.16.4
https://nvd.nist.gov/vuln/detail/CVE-2021-29923 in go version 1.16.4
https://security-tracker.debian.org/tracker/CVE-2022-23990 in expat package
https://security-tracker.debian.org/tracker/CVE-2022-23852 in expat package 
Fixes #
I have:
=> Feat: the golang version upgrade to 1.7

pkg/controller/core.oam.dev/v1alpha2/application/revision.go, pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go, pkg/oam/labels.go
Currently, when Definition changes, Revision in Application will be renewed when reconcile is triggered (like restart of controller or StateKeep) even if Application itself not change.
This PR let Revision in Application not renewed by default. User can add label "app.oam.dev/autoUpdate" to Application to fallback to previous behavior.
Fixes #3168 
I have:
=> Fix: disable cochange for apprev when def changes

pkg/addon/addon.go, references/cli/addon.go
A definition defined by CUE cannot be created because the namespace is empty.
I have:
=> Fix: the definition namespace is empty

charts/vela-core/templates/defwithtemplate/rollout.yaml, charts/vela-minimal/templates/defwithtemplate/rollout.yaml, pkg/velaql/providers/query/collector.go, vela-templates/definitions/internal/trait/rollout.cue
For component with rollout triat, the workload is Rollout. We will collector pod by label `app.oam.dev/component`.
It exists as a norm.
I have:
=> Fix: can not collector pod list with rollout trait

references/cli/def.go
Add cli support for provider baidu and gcp.
Fixes #
I have:
=> Fix: add cli support for provider gcp and baidu

pkg/controller/core.oam.dev/v1alpha2/application/revision.go
Fix the bugs: when user open performance optimization options(DisableAllApplicationRevision), it will lead to panic
Fixes #
I have:
=> Fix: fix panic when user disable create apprevision

references/plugins/references.go
If one column of a table contianers multiple line of a json
struct, it will break the table.
Fixes #
I have:
=> Fix: properties table of cloud resource doc is broken

go.mod, pkg/velaql/providers/query/handler.go, pkg/velaql/providers/query/handler_test.go, pkg/velaql/providers/query/suite_test.go, pkg/velaql/providers/query/testdata/virtual_service.yaml
add seldon virtual service support in endpoints
```bash
vela status simple-example --endpoint
+---------+-------------------------------------+---------------------------------------------------+
| CLUSTER |      REF(KIND/NAMESPACE/NAME)       |                     ENDPOINT                      |
+---------+-------------------------------------+---------------------------------------------------+
|         | VirtualService/default/demo-serving | tcp://1.1.1.1:80/seldon/default/demo-serving/ |
|         | Service/default/jupyter             | tcp://1.1.1.1:8888                           |
+---------+-------------------------------------+---------------------------------------------------+
```
I have:
=> Feat: add seldon virtual service support in endpoints

pkg/apiserver/rest/usecase/addon.go
Fixes #3274 
If addon argument secret exists, return the arguments.
if not exist, return 404
Current logic is 
```
if err != nil && !errors2.IsNotFound(err) {
return nil, bcode.ErrAddonSecretGet
} else if errors2.IsNotFound(err) {
res.Args = make(map[string]string, len(sec.Data))
for k, v := range sec.Data {
res.Args[k] = string(v)
}
}
```
It does not return "res.Args",when secret exists.
So update it to be 
```
if err != nil && !errors2.IsNotFound(err) {
return nil, bcode.ErrAddonSecretGet
} else if errors2.IsNotFound(err) {
return nil, bcode.ErrAddonSecretNotExist
} else {
res.Args = make(map[string]string, len(sec.Data))
for k, v := range sec.Data {
res.Args[k] = string(v)
}
}
```
I have:
=> Fix: vela status api can not return customized arguments of addon

pkg/controller/utils/capability_test.go
The UT `TestGetOpenAPISchemaFromTerraformComponentDefinition` won't
succeed 100%. The required variables in the generated isn't in the expected
order all the time.
Fixes #
I have:
=> Fix: not steady unit test

apis/types/types.go, charts/vela-core/templates/addon/fluxcd-def.yaml, charts/vela-core/templates/addon/fluxcd.yaml, charts/vela-core/templates/addon_registry.yaml, charts/vela-core/values.yaml, e2e/addon/addon_test.go, e2e/addon/mock/utils/utils.go, e2e/cli.go, pkg/addon/addon.go, pkg/addon/addon_test.go, references/cmd/cli/main.go
1. helm install add parameter `-enableFluxcdAddon=true` to enable fluxcd addon by default. eg:
```
helm install --create-namespace -n test-vela kubevela charts/vela-core/ --set multicluster.enabled=true --set systemDefinitionNamespace=test-vela  --wait
```
2. vela addon support user-defined KubeVela install namespace. eg: 
```
DEFAULT_VELA_NS=test-vela vela addon list
```
Fixes #
I have:
=> Feat: vela can set default namespace and user can  enable fluxcd addon by default

cmd/core/main.go, pkg/utils/util/factory.go, pkg/utils/util/factory_test.go
Fixes #
Let versioned  controller uses a separate election locker in one cluster.
I have:
=> Fix: Let versioned  controller uses a separate election locker in one cluster.

charts/vela-core/templates/defwithtemplate/storage.yaml, charts/vela-minimal/templates/defwithtemplate/storage.yaml, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/application.go, pkg/apiserver/rest/usecase/definition.go, pkg/apiserver/rest/utils/ui_schema.go, vela-templates/definitions/internal/trait/storage.cue
* `immutable`  set the immutable is true, indicates that the parameter cannot be changed.
* `style` support customize the reactive width of the field form.
I have:
=> Feat: add style and immutable parameters for uischema

pkg/addon/addon.go, pkg/addon/addon_suite_test.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go
fix complicate args storage
eg: vela addon enable velaux imagePullSecrets={myreg,myreg2}
request `127.0.0.1:8000/api/v1/addons/velaux/status` will return 
```json
{
"name": "velaux",
"phase": "enabled",
"args": {
"imagePullSecrets": [
"myreg",
"myreg2"
]
},
}
```
Refer to ：https://github.com/oam-dev/velaux/issues/372
I have:
=> Fix: addon store&show complicated parameter  

references/cli/ls.go, references/cli/ls_test.go
FIx The order of status displayed by vela ls is not correct
Fixes #3279 
User write there Yaml and specify all the components in Application's
```
spec:
components:
```
Vela core reconcile these components and record there status in Application's
```
status:
services:
``` 
Since user may use "dependsOn" or "workflow" to customize the deployment order of components, the order of components in "spec.components" may be different from that in "status.services". This mismatch is the cause of ISSUE: #3279
I have:
=> Fix: The order of status displayed by vela ls is not correct

OWNERS_ALIASES
Wei has been playing a critical role for getting KubeVela to more developers and done several major consistent contribution to the community. Helping KubeVela onboarding to CNCF, tracking community's visibility and ensuring show up rate in series of CNCF KubeCon or related summits, assembling [KubeVela.io](http://kubevela.io/)(official doc) and VelaUX(UI dashboard) localization,  and keep hosting both Asia and Europe&America friendly biweekly community call in the past.
Community management is equally important as contributing code does. We shall encourage more efforts as this to help KubeVela community narrow the gap from us to more developers out there.
=> Feat: Nominee Wei as a maintainer

pkg/apiserver/model/application.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/application.go, pkg/apiserver/rest/usecase/application_test.go, pkg/apiserver/rest/usecase/envbinding.go, pkg/apiserver/rest/usecase/testdata/ui-schema.yaml, pkg/apiserver/rest/usecase/workflow_model.go, pkg/apiserver/rest/utils/bcode/001_application.go, pkg/apiserver/rest/webservice/application.go, test/e2e-apiserver-test/application_test.go
1. add an API for delete component;
2. support creating traits in create component API.
3. add `main` param for the component.
I have:
=> Feat: add api for delete component

charts/vela-core/templates/defwithtemplate/webservice.yaml, charts/vela-core/templates/defwithtemplate/worker.yaml, charts/vela-minimal/templates/defwithtemplate/webservice.yaml, charts/vela-minimal/templates/defwithtemplate/worker.yaml, vela-templates/definitions/internal/component/webservice.cue, vela-templates/definitions/internal/component/worker.cue
Signed-off-by: kingram <kingram@163.com>
Fix the inaccurate judgment of ready status
Fixes https://github.com/oam-dev/kubevela/issues/3311
I have:
=> Fix: Fix the inaccurate judgment of ready status 

pkg/apiserver/rest/usecase/definition.go, pkg/apiserver/rest/usecase/definition_test.go
Fixes #3344 
Before:
The default value of "sort" is 100
After:
Set fixed value for every parameter
I have:
=> Fix: Position of  parameter  is always changing on addon's details page.

pkg/multicluster/proxy.go
Currently, multicluster round trippers are modifying request directly.
However, [golang documentation](https://pkg.go.dev/net/http#RoundTripper) says `RoundTrip` should not modify the request.
> RoundTrip should not modify the request, except for consuming and closing the Request's Body.
> RoundTrip may read fields of the request in a separate goroutine.
> Callers should not mutate or reuse the request until the Response's Body has been closed.
This commit fixes round trippers to clone the request before the modification.
I have:
I referred following links:
- [golang-nuts / Correct use of http.RoundTripper](https://groups.google.com/g/golang-nuts/c/-j6p12SSpXI)
- [client-go round trippers](https://github.com/kubernetes/client-go/blob/35bf219cc60981cdf318b711e2630cc05e0a83e5/transport/round …
=> Fix: clone request if round tripper modifies it

pkg/addon/addon.go
Fix vela cli  addon bug in windows env. The root cause is misused of `filepath.join` func.
In linux  the separator is "/" but in windows is "\". The result won't match the url path. 
Fixes #3144 
I have:
=> Fix: windows vela cli addon bug

go.mod, go.sum
Fixes [OCI Manifest Type Confusion Issue](https://github.com/oam-dev/kubevela/security/dependabot/3).
I have:
=> Fix: upgrade dependency to fix alerts

apis/core.oam.dev/common/types.go, apis/core.oam.dev/common/zz_generated.deepcopy.go, charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml, charts/vela-core/crds/core.oam.dev_applications.yaml, charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml, charts/vela-minimal/crds/core.oam.dev_applications.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml, legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
ResourceTracker field has been deprecated in #2849, but remains for v1.2. This PR completely removes it for v1.3.
I have:
=> Fix: remove deprecated rt field in app status

.github/workflows/go.yml, Makefile, charts/vela-core/README.md, charts/vela-core/templates/kubevela-controller.yaml, charts/vela-core/values.yaml, charts/vela-minimal/README.md, charts/vela-minimal/templates/kubevela-controller.yaml, charts/vela-minimal/values.yaml, cmd/core/main.go, design/vela-core/workflow_policy.md, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, pkg/workflow/tasks/custom/task.go, pkg/workflow/tasks/custom/task_test.go, pkg/workflow/workflow.go, pkg/workflow/workflow_test.go
separate waiting and failed backoff time and make them configurable
I have:
/cc @Somefive @wonderflow @leejanee
=> Fix: separate waiting and failed backoff time and make them configurable

pkg/workflow/step/dependency_test.go, pkg/workflow/step/generator.go, pkg/workflow/step/types.go
The `deploy` WorkflowStep has the `auto` field which is not included in the spec. The strict unmarshal will trigger an error.
P.S. This is a follow-up for PR #3223.
I have:
=> Fix: auto deploy spec missing

pkg/resourcekeeper/dispatch.go, pkg/utils/errors/list.go, pkg/utils/parallel/parallel.go, pkg/utils/parallel/parallel_test.go, pkg/workflow/providers/oam/apply.go, pkg/workflow/providers/oam/apply_test.go
1. Rework parallel execution and use it in ApplyComponents and ResourceKeeper parallel dispatch.
2. This original apply components only lock the process of write back cue.Value. The read process of cue.Value should also be protected.
I have:
Add a unit test for apply 1000 components concurrently.
=> Fix: rework parallel execution for ApplyComponents and ResourceKeeper Dispatch

pkg/stdlib/pkgs/oam.cue, pkg/workflow/step/dependency_test.go, pkg/workflow/step/types.go, test/e2e-multicluster-test/multicluster_standalone_test.go, test/e2e-test/application_test.go
Minor fixes.
1. Support `deploy` workflow step specifying `parallelism` parameter.
2. Explicit cue declaration for namespace in `ApplyComponent`, `ApplyComponents` and `RenderComponent`.
I have:
=> Fix: add parallelism params for deploy step

pkg/multicluster/virtual_cluster.go, references/cli/cluster.go, test/e2e-multicluster-test/multicluster_test.go
Add two commands to help user manage cluster labels:
- vela cluster labels add example-cluster region=hangzhou,creator=kubevela
- vela cluster labels del example-cluster creator
I have:
There is no protection for modifying cluster labels if some applications are using corresponding clusterLabelSelector.
=> Feat: support vela cluster labels add/del to manage cluster labels

charts/vela-core/templates/velaql/applied-resources.yaml, pkg/addon/addon.go, pkg/stdlib/pkgs/query.cue, pkg/stdlib/ql.cue, pkg/velaql/providers/query/collector.go, pkg/velaql/providers/query/handler.go, pkg/velaql/providers/query/handler_test.go, pkg/velaql/providers/query/types/type.go, references/cli/addon.go, references/cli/status.go, references/cli/velaql.go, references/cli/velaql_test.go
1. new cue provider function `ql.#ListAppliedResources`, list applied resources of an application, they read from ResourceTracker.
2. new velaQL view  `service-applied-resources-view`.
3. support filter service endpoints by component name. 
I have:
=> Feat: support query applied resources by velaQL

apis/core.oam.dev/v1alpha1/policy_types.go, apis/types/multicluster.go, pkg/multicluster/cluster_management.go, pkg/multicluster/virtual_cluster.go, pkg/multicluster/virtual_cluster_test.go, pkg/workflow/providers/multicluster/multicluster.go, pkg/workflow/providers/multicluster/multicluster_test.go, test/e2e-multicluster-test/multicluster_test.go
1. Allow local cluster as VirtualCluster. Now user can use local cluster in topology policy like previous env-binding policy.
2. Allow specifying namespace in topology policy. Now user can use a different namespace other than the original application namespace like previous env-binding policy. Notice that this will only work when bootstrap parameter --allow-cross-namespace-resource is set.
I have:
Picked from #3409.
=> Feat: local virtual cluster + namespace in topology

charts/vela-core/templates/defwithtemplate/gateway.yaml, charts/vela-minimal/templates/defwithtemplate/gateway.yaml, docs/apidoc/swagger.json, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/application.go, vela-templates/definitions/internal/trait/gateway.cue
Add the component definition spec to the detail component response body, the client(such as UI) could get the suitable trait definitions by the workload type.
Ref  oam-dev/velaux#394
I have:
=> Feat: add component definition in the detail component response body

.github/workflows/issue-commands.yml
It seems that the [issue-commands](https://github.com/oam-dev/kubevela/actions/workflows/issue-commands.yml) workflow keeps failing.
This PR will fix the `issue-commands` workflow by bumping up the action version and replacing `npm install` with `npm ci` for reproducibility.
Refs: https://github.com/oam-dev/kubevela-github-actions/pull/11
I have:
I tested with my personal repository
- [Actions Log](https://github.com/devholic/actions-test/runs/5557335137?check_suite_focus=true)
- [Workflow](https://github.com/devholic/actions-test/blob/d6c7771449b03075e93a51ae23e48c8fd1e4dd98/.github/workflows/issue.yaml)
This PR should be merged after https://github.com/oam-dev/kubevela-github-actions/pull/11 released.
=> Chore: fix `issue-commands` workflow

apis/types/types.go, docs/apidoc/swagger.json, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/definition.go, pkg/apiserver/rest/usecase/definition_test.go
* Add query policy definitions support.
* The query definitions API returns the spec.
Ref: oam-dev/velaux#395
I have:
=> Feat: support query the policy definitions

docs/apidoc/swagger.json, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/helm.go, pkg/apiserver/rest/usecase/helm_test.go, pkg/apiserver/rest/webservice/helm.go, pkg/apiserver/rest/webservice/webservice.go, pkg/utils/helm/helm_helper.go, pkg/utils/helm/helm_helper_test.go
helm apiserver webservice(list chart, list version, extract helm values)
the result ：
1. access the `/api/v1/helm/charts?repoUrl=https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core`
result is :
```json
[
"oam-runtime",
"vela-core",
"vela-core-legacy",
"vela-minimal",
"vela-rollout"
]
```
2. access the `/api/v1/helm/oam-runtime/versions?repoUrl=https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core`
result is :
```json
[
{
"name": "oam-runtime",
"version": "1.2.4",
"description": "A Helm chart for oam-runtime aligns with OAM spec v0.2",
"apiVersion": "v2",
"appVersion": "1.2.4",
"type": "application",
"urls": [
"https://kubevelacharts.oss-cn-hangzhou.aliyuncs.com/core/oam-runtime-1.2.4.tgz"
],
"created": "2022-03-08T10:00:11.180129339Z",
"digest": …
```
=> Feat(apiserver):  helm apiserver webservice (list chart, list version, extract helm values)

references/cli/def.go
Signed-off-by: Nicola115 <2225992901@qq.com>
enable provider elastic
Fixes #
I have:
=> Fix: enable provider elastic

charts/vela-core/templates/defwithtemplate/storage.yaml, charts/vela-minimal/templates/defwithtemplate/storage.yaml, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, vela-templates/definitions/internal/trait/storage.cue
Signed-off-by: maxiangbo <maxiangboo@cmbchina.com>
Fixes #3300.
Trait env, storage and webservice/worker properties env can be used at the same time.
Fixes #
I have:
=> Fix: trait env and storage conflict

charts/vela-core/templates/defwithtemplate/annotations.yaml, charts/vela-core/templates/defwithtemplate/labels.yaml, charts/vela-minimal/templates/defwithtemplate/annotations.yaml, charts/vela-minimal/templates/defwithtemplate/labels.yaml, docs/examples/traits/annotations/example.yaml, docs/examples/traits/json-patch/example.yaml, docs/examples/traits/labels/example.yaml, e2e/plugin/plugin_test.go, test/e2e-test/trait_test.go, vela-templates/definitions/internal/trait/annotations.cue, vela-templates/definitions/internal/trait/labels.cue
1. Allow `labels` and `annotations` traits to override & delete existing keys. Perviously, keys can only be added.
2. Rework example for `json-patch`. Override the whole metadata is confusing and should not be a recommended action.
I have:
=> Feat: enhance labels & annotations trait

charts/vela-core/templates/defwithtemplate/storage.yaml, charts/vela-minimal/templates/defwithtemplate/storage.yaml, pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go, vela-templates/definitions/internal/trait/storage.cue
Signed-off-by: maxiangbo maxiangboo@cmbchina.com
Support the mountPath parameter of trait-storage-secret is optional.
by this feature, we can valueFrom secret in container env, without mounting the secret to the container at the same time.
I have:
=> Feat: support the mountPath of trait-storage-secret is optional

pkg/apiserver/rest/usecase/definition.go, pkg/apiserver/rest/utils/ui_schema.go
The Conditions are used to set conditions for rendering the form. such as: 
```
- jsonKey: url
label: Repo URL
uiType: HelmRepoSelect
description: Please input or select the helm or git repo address.
sort: 2
validate:
required: true
pattern: ^(http|git).*$
- jsonKey: chart
uiType: HelmChartSelect
sort: 3
label: Chart
description: Please select the chart or input the chart path.
conditions: 
- jsonKey: url
op: "!="
value: ""
- jsonKey: version
uiType: HelmChartVersionSelect
sort: 4
label: Version
validate:
required: true
defaultValue: ""
conditions: 
- jsonKey: repoType
value: "helm"
- jsonKey: chart
op: "!="
value: ""
- jsonKey: url
op: "!="
value: ""
```
The select chart form will not be rendered firstly, after the `url` form input value, …
=> Feat: add the conditions for ui schema spec

pkg/apiserver/rest/usecase/helm.go, pkg/apiserver/rest/utils/bcode/013_repository.go, pkg/apiserver/rest/webservice/helm.go, pkg/utils/helm/helm_helper.go, pkg/utils/helm/helm_helper_test.go, references/cli/cli.go
optimize helm repository logic put cache lower layer and return bcode when error
Fixes #
I have:
=> Fix:  optimize helm repository logic put cache lower layer and return bcode when error

pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/helper.go, pkg/addon/testdata/test-disable-addon/definitions/compDef.yaml, pkg/addon/testdata/test-disable-addon/definitions/traitDef.cue, pkg/addon/testdata/test-disable-addon/metadata.yaml, pkg/addon/utils.go, pkg/addon/utils_test.go, pkg/apiserver/rest/usecase/addon.go, pkg/apiserver/rest/webservice/addon.go, references/cli/addon.go, references/cli/uninstall.go, references/cli/uninstall_test.go
This pr done these things:
1. parse 'created x-defs' in addon-app's annotation。such as
```yaml
metadata:
annotations:
addon.oam.dev/traitDefinitions: '["rollout"]'
addon.oam.dev/componentDefinitions: '["webservice"]'
....
```
3. check all applications whether using this addon while disabling.
4. for lagacy addon which don't have these annotation, so fetch them from alive registry.
5. give user a way to force disable addon and ignore the check
Fixes #3415 
I have:
=> Feat: check if an addon is been used while disabling.

pkg/addon/utils.go, pkg/addon/utils_test.go, pkg/apiserver/rest/webservice/addon.go
fix when disable an addon with empty force parameter bugs.
Fixes #
I have:
=> Fix: disable addon check  bugs

OWNERS_ALIASES
Signed-off-by: BinaryHB0916 <davidduan0916@gmail.com>
Daniel@[dhiguero](https://github.com/dhiguero)  has been consistently devoting his effort to help OAM Spec evolve and very active at the community call.
He was already a maintainer in OAM Spec repo based on serveral major contribtuions that made, such as [New application entity (v0.3.0)](https://github.com/oam-dev/spec/pull/447/files).
OAM/KubeVela is becoming pratical and clear for developers who needs a easily and sufficient application delivery platform or ecosystem. OAM Spec will serve the abstraction model layer of KubeVela and the latter tests what really developers need in the real world.
Based on the community membership updated recently, the goverance model of OAM/KubeVela community should be perceived universally for all the …
=> Chore: Nominate Daniel as a Maintainer

apis/types/multicluster.go, docs/apidoc/swagger.json, pkg/addon/addon.go, pkg/addon/addon_suite_test.go, pkg/addon/addon_test.go, pkg/addon/suite_test.go, pkg/addon/type.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/webservice/addon.go, references/cli/addon.go, references/cli/addon_test.go
* Install addon by:
```
vela addon enable <addon-name> --clusters={local,cluster1,cluster2}
```
* Upgrade addon by:
```
vela addon upgrade <addon-name> --clusters={local,cluster1,cluster2}
```
Also add an api for addon install.
request body:
```
{
"args": {},
"clusters": ["clustername1","clusternam2",..]
}
```
I have:
=> Feat: support specify clusters in addon installation

pkg/apiserver/clients/kubeclient.go, pkg/multicluster/errors.go, pkg/multicluster/utils.go
How to fix it?
1. api-server try to create multicluster k8s client
2. if create fails and error is "failed to wait cluster gateway service " , roll back to create singlecluster client
```
│ I0323 09:51:17.916606       1 utils.go:128] waiting for cluster gateway service: ClusterGateway APIService v1alpha1.cluster.core.oam.dev is not found
│ I0323 09:51:22.921861       1 utils.go:128] waiting for cluster gateway service: ClusterGateway APIService v1alpha1.cluster.core.oam.dev is not found
│ I0323 09:51:27.892016       1 utils.go:128] waiting for cluster gateway service: ClusterGateway APIService v1alpha1.cluster.core.oam.dev is not found
│ I0323 09:51:32.899635       1 utils.go:128] waiting for cluster gateway service: ClusterGateway …
```
=> Fix: api-server fail to start, when multi-cluster is disabled

charts/vela-core/templates/defwithtemplate/task.yaml, charts/vela-core/templates/defwithtemplate/webservice.yaml, charts/vela-core/templates/defwithtemplate/worker.yaml, charts/vela-minimal/templates/defwithtemplate/task.yaml, charts/vela-minimal/templates/defwithtemplate/webservice.yaml, charts/vela-minimal/templates/defwithtemplate/worker.yaml, vela-templates/definitions/internal/component/task.cue, vela-templates/definitions/internal/component/webservice.cue, vela-templates/definitions/internal/component/worker.cue
This PR add health check and custom the status of ComponentDefinition task.
The PR also simplified the `healthPolicy` and `customStatus` of webservice and worker.
Fixes https://github.com/oam-dev/kubevela/issues/3474
I have:
=> Feat: add health check for componentdefinition task

pkg/appfile/dryrun/diff.go, pkg/appfile/dryrun/diff_test.go, pkg/appfile/dryrun/testdata/diff-input-app-with-externals.yaml, pkg/appfile/dryrun/testdata/livediff-demo-deploy.yaml, pkg/appfile/dryrun/testdata/wd-ref-objects.yaml, pkg/appfile/parser.go, test/e2e-multicluster-test/multicluster_standalone_test.go, test/e2e-multicluster-test/testdata/app/standalone/app-with-publish-version-busybox.yaml, test/e2e-multicluster-test/testdata/app/standalone/deployment-busybox.yaml
`vela live-diff` command now can show the changes in the referred objects.
I have:
This PR should be accepted after #3446.
=> Feat: support ref-objects in live-diff

hack/references/generate.go, references/cli/common.go, references/cli/def.go, references/plugins/reference_test.go, references/plugins/references.go
…rseLocalFile
Signed-off-by: Nicola115 <2225992901@qq.com>
1. add readFrom instead of namespace to pass either namespace or localFilePath to `GenerateRefeenceDocs`. 
2. set ref.DefinitionName as fileName if the args[0] is a filePath. 
3. change yaml.Unmarsh in ParseLocalFile to converting yaml to json using k8s pkg first.
Fixes #
1. using local filepath as generated markdown filename. 
4. failed to unmarshal parts of yaml data into ComponentDefinitions due to lack of yaml tags.  
5. wrong unit tests. 
I have:
1. pass TestParseLocalFile. 
2. I build the local vela and test `vela def doc-gen <localFilePath>` command.
=> Fix: fix bugs in vela def doc-gen from local file

charts/vela-core/templates/defwithtemplate/ref-objects.yaml, charts/vela-minimal/templates/defwithtemplate/ref-objects.yaml, vela-templates/definitions/internal/component/ref-objects.cue
Enhance ref-objects typed component by adding healthPolicy and message. If the main workload in the ref-objects typed component is Deployment, the application will wait and show the replica number of the dispatched deployment.
I have:
=> Fix: enhance ref object to support health check for deployment

docs/apidoc/swagger.json, pkg/addon/helper.go, pkg/apiserver/datastore/kubeapi/kubeapi.go, pkg/apiserver/datastore/kubeapi/migrate.go, pkg/apiserver/datastore/kubeapi/migrate_test.go, pkg/apiserver/rest/apis/v1/types.go, pkg/apiserver/rest/usecase/addon.go, pkg/apiserver/rest/webservice/addon.go, pkg/apiserver/rest/webservice/webservice.go
1. fix migrate data duplicate in list API , change migrate key to "db.oam.dev/migrated", so the clean up command changed to:
```
kubectl -n kubevela delete cm -l db.oam.dev/migrated=ok
```
2. add cluster info in addon status
```
GET  /addons/{addonName}/status
{
"clusters":{
"cluster-name1":{},
"cluster-name2":{}
},
"allClusters": [{ "name": "cluster-name1", "alias":"my-clustername"},{"name":"cluster-name2","alias":"cluster-name2"}]
}
```
I have:
=> Fix: fix migrate data duplicate in list API and add cluster info in addon status

pkg/addon/addon.go, pkg/addon/addon_test.go, pkg/addon/testdata/example/metadata.yaml, pkg/addon/testdata/example/resources/configmap.cue
When building the addon, we will get metadata info from context. such as:
```
output: {
type: "webservice"
properties: {
if parameter["repo"] == _|_ {
image: "oamdev/velaux:" + context.metadata.version
}
...
}
...
}
```
I have:
=> Feat: support with metadata as context render cue file in the addon

e2e/addon/addon_test.go, references/cli/addon.go, references/cli/addon_test.go
Fix:  cli addon multicluster bug
Fixes #
I have:
=> Fix:  cli addon multicluster bug

pkg/workflow/providers/multicluster/multicluster.go, pkg/workflow/providers/multicluster/multicluster_test.go
When namespace in topology policy is empty, do not directly override the original resources' namespace with the application's namespace. This is useful for addon applications. 
I have:
=> Fix: topology use original resource namespace when not specify

references/cli/addon.go, references/cli/addon_test.go
1. list addon put installedVersion as the first one and avoid too many versions cause print info  too long.
2. addon status more info
Fixes #
I have:
=> Fix: optimize the user-experience  of addon

pkg/apiserver/rest/webservice/config.go
Added an empty struct in the API of config deletion
Fixes #
I have:
=> Fix: add response struct to config deletion api

references/plugins/references.go
… def doc-gen
Signed-off-by: Nicola115 <2225992901@qq.com>
add sorting for properties, outputs, writeSecretRefParameters in vela def doc-gen command
https://github.com/oam-dev/kubevela/issues/3536
Fixes #
I have:
build locally and test for existing componentDefinition files.
=> Feat: add sorting for properties, outputs, writeSecretRefParameters in vela def doc-gen command

pkg/utils/common/common.go, pkg/utils/common/common_test.go
Fix this case: run `vela logs` without `--name`, all resources are filtered and can not print logs.
cc @Somefive 
Fixes #
I have:
=> Fix: vela logs without specified resource name

makefiles/e2e.mk, pkg/apiserver/rest/webservice/addon.go, test/e2e-apiserver-test/addon_test.go, test/e2e-apiserver-test/suite_test.go
add e2e apiserver test for addon
Fixes #
I have:
=> Fix: add e2e apiserver test for addon

apis/types/types.go, docs/apidoc/swagger.json, pkg/apiserver/rest/usecase/project.go, pkg/apiserver/rest/usecase/project_test.go, pkg/apiserver/rest/usecase/rbac.go, pkg/apiserver/rest/webservice/project.go
When creating a target,  list configs by the config type and the project.
Fixes #
I have:
=> Feat: add api of listing configs for project when creating a target
